package hooks

import (
	"context"
	"strings"
	"testing"
)

func commentQualityDiff(path, src string, added ...int) *StagedDiff {
	lines := make([]AddedLine, 0, len(added))
	for _, line := range added {
		lines = append(lines, AddedLine{New: line})
	}
	return &StagedDiff{
		ctx: context.Background(), StagedPaths: []string{path}, AddedByFile: map[string][]AddedLine{path: lines},
		fileCache: map[string]fileEntry{path: {data: []byte(src), exists: true}}, candidates: make(map[string]candidateNote),
	}
}

func TestCommentQualityFlagsNarrationButExemptsDocumentation(t *testing.T) {
	src := `package sample

// Exported explains the public contract.
func Exported() {}

func local() {
	// This function loops through the items.
	for range []int{1} {}
}
`
	d := commentQualityDiff("sample.go", src, 3, 7)
	findings, err := gateCommentQuality(d)
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 1 || findings[0].Line != 7 {
		t.Fatalf("findings = %#v", findings)
	}
	if n, _, ok := d.Candidates(commentQualityGate); !ok || n != 1 {
		t.Fatalf("candidates = %d, %v", n, ok)
	}
}

func TestCommentQualityFlagsOnlyConspicuouslyLongImplementationBlocks(t *testing.T) {
	long := strings.Repeat("explanation ", 45)
	src := "package sample\n\nfunc local() {\n// " + strings.ReplaceAll(long, "explanation explanation explanation explanation explanation explanation explanation explanation ", "explanation explanation explanation explanation explanation explanation explanation explanation\n// ") + "\n}\n"
	d := commentQualityDiff("sample.go", src, 4)
	findings, err := gateCommentQuality(d)
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 1 || !strings.Contains(findings[0].Detail, "long implementation") {
		t.Fatalf("findings = %#v", findings)
	}
}

func TestCommentQualityExemptsGeneratedAndDirectiveComments(t *testing.T) {
	generated := commentQualityDiff("generated.go", "// Code generated by test. DO NOT EDIT.\npackage sample\n", 1)
	if findings, err := gateCommentQuality(generated); err != nil || len(findings) != 0 {
		t.Fatalf("generated: %#v, %v", findings, err)
	}

	directive := commentQualityDiff("sample.go", "package sample\n\n//go:noinline\nfunc local() {}\n", 3)
	if findings, err := gateCommentQuality(directive); err != nil || len(findings) != 0 {
		t.Fatalf("directive: %#v, %v", findings, err)
	}
	if n, _, ok := directive.Candidates(commentQualityGate); !ok || n != 0 {
		t.Fatalf("candidates = %d, %v", n, ok)
	}
}

func TestCommentQualityIgnoresTopLevelLicenseAndRationale(t *testing.T) {
	src := `// Copyright 2026 Example
// Licensed under the Apache License, Version 2.0.
package sample

// This function accepts an empty value because older clients omit the field.
func Exported() {}

func local() {
	// Keep this allocation outside the lock to avoid extending the critical section.
	_ = make([]byte, 1)
}
`
	d := commentQualityDiff("sample.go", src, 1, 5, 9)
	findings, err := gateCommentQuality(d)
	if err != nil || len(findings) != 0 {
		t.Fatalf("findings = %#v, err = %v", findings, err)
	}
	if n, _, ok := d.Candidates(commentQualityGate); !ok || n != 1 {
		t.Fatalf("candidates = %d, %v", n, ok)
	}
}

func TestCommentQualityPreservesURLAndBuildConstraints(t *testing.T) {
	src := `//go:build linux

package sample

func local() {
	// Keep the URL intact because https://example.test/protocol#fragment is the compatibility authority.
	_ = 1
}
`
	d := commentQualityDiff("sample.go", src, 1, 6)
	findings, err := gateCommentQuality(d)
	if err != nil || len(findings) != 0 {
		t.Fatalf("findings = %#v, err = %v", findings, err)
	}
	if n, _, ok := d.Candidates(commentQualityGate); !ok || n != 1 {
		t.Fatalf("candidates = %d, %v", n, ok)
	}
}

func TestCommentQualityExampleFixtureAndEmptyDomain(t *testing.T) {
	example := commentQualityDiff("example_test.go", `package sample

func Example_local() {
	// This function loops through the items.
	for range []int{1} {}
}
`, 4)
	findings, err := gateCommentQuality(example)
	if err != nil || len(findings) != 0 {
		t.Fatalf("example findings = %#v, err = %v", findings, err)
	}

	empty := commentQualityDiff("sample.go", "package sample\n\nfunc local() {}\n", 3)
	findings, err = gateCommentQuality(empty)
	if err != nil || len(findings) != 0 {
		t.Fatalf("empty findings = %#v, err = %v", findings, err)
	}
	if n, _, ok := empty.Candidates(commentQualityGate); !ok || n != 0 {
		t.Fatalf("empty candidates = %d, %v", n, ok)
	}
}

func TestCommentQualityFlagsTautologicalDocComments(t *testing.T) {
	src := `package sample

// Foo defines the foo.
func Foo() {}

// Bar specifies Bar.
type Bar struct{}

// ReasonSupported indicates full support for the metadata envelope.
const ReasonSupported = "supported"
`
	d := commentQualityDiff("sample.go", src, 3, 6, 9)
	findings, err := gateCommentQuality(d)
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 2 {
		t.Fatalf("expected 2 tautological findings, got %d: %#v", len(findings), findings)
	}
	if !strings.Contains(findings[0].Detail, "Foo") || findings[0].Line != 3 {
		t.Errorf("expected finding on Foo at line 3, got %#v", findings[0])
	}
	if !strings.Contains(findings[1].Detail, "Bar") || findings[1].Line != 6 {
		t.Errorf("expected finding on Bar at line 6, got %#v", findings[1])
	}
}
