// Code generated by trajectory.GenerateGoRuntimeSDK. DO NOT EDIT.
package fakclient

import (
	"encoding/json"
	"time"
)

type RuntimeEventKind string

const (
	RuntimeEventSchema                             = "fak-runtime-event/1"
	RuntimeEventWireSchema                         = "fak-runtime-event-wire/1"
	RuntimeKindTurnStarted        RuntimeEventKind = "turn_started"
	RuntimeKindToolProposed       RuntimeEventKind = "tool_proposed"
	RuntimeKindToolVerdict        RuntimeEventKind = "tool_verdict"
	RuntimeKindToolResultAdmitted RuntimeEventKind = "tool_result_admitted"
	RuntimeKindContextChanged     RuntimeEventKind = "context_changed"
	RuntimeKindCostDebited        RuntimeEventKind = "cost_debited"
	RuntimeKindTerminalWitness    RuntimeEventKind = "terminal_witness"
	RuntimeKindTurnTerminal       RuntimeEventKind = "turn_terminal"
	RuntimeKindError              RuntimeEventKind = "error"
)

type RuntimeSource struct {
	Component string `json:"component"`
	Instance  string `json:"instance"`
	Runtime   string `json:"runtime"`
}
type RuntimeEvent struct {
	Schema    string           `json:"schema"`
	EventID   string           `json:"event_id"`
	SessionID string           `json:"session_id"`
	TurnID    string           `json:"turn_id"`
	TraceID   string           `json:"trace_id"`
	Sequence  uint64           `json:"sequence"`
	Timestamp time.Time        `json:"timestamp"`
	Kind      RuntimeEventKind `json:"kind"`
	Source    RuntimeSource    `json:"source"`
	Payload   json.RawMessage  `json:"payload"`
}
type RuntimeAdmission struct {
	Screened bool   `json:"screened"`
	Taint    string `json:"taint"`
	Screen   string `json:"screen"`
}
type RuntimeWireEvent struct {
	Schema    string           `json:"schema"`
	Event     RuntimeEvent     `json:"event"`
	Admission RuntimeAdmission `json:"admission"`
}
