package workerworktree

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

// RecoveryRefPrefix is the private namespace that makes isolated-land candidate
// commits durable across process crashes and visible to operators. These refs are
// local by default; remote durability remains the wipref checkpoint layer's job.
const RecoveryRefPrefix = "refs/fak/worker-land/"

const recoveryReflogMessage = "fak worker land candidate"

// RecoveryEntry is one named off-branch land candidate and its relation to
// the current trunk tip.
type RecoveryEntry struct {
	Ref      string `json:"ref"`
	SHA      string `json:"sha"`
	Worktree string `json:"worktree"`
	State    string `json:"state"`  // LANDED or RECOVERABLE
	Action   string `json:"action"` // operator-checkable next step
}

// RecoveryRef deterministically names candidateSHA by the worker worktree that
// authored it. A SHA suffix preserves every candidate generated by CAS retries.
func RecoveryRef(wtPath, candidateSHA string) (string, error) {
	sha := strings.TrimSpace(candidateSHA)
	if len(sha) < 7 || !isRefObjectToken(sha) {
		return "", fmt.Errorf("invalid candidate object id %q", sha)
	}
	name := recoveryName(filepath.Base(filepath.Clean(wtPath)))
	if name == "" || name == "." {
		return "", fmt.Errorf("invalid worktree identity %q", wtPath)
	}
	return RecoveryRefPrefix + name + "/" + sha, nil
}

func recoveryName(s string) string {
	var b strings.Builder
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' || r == '_' || r == '.' {
			b.WriteRune(r)
		} else {
			b.WriteByte('-')
		}
	}
	return strings.Trim(b.String(), ".-")
}

func isRefObjectToken(s string) bool {
	for _, r := range s {
		if !((r >= '0' && r <= '9') || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')) {
			return false
		}
	}
	return true
}

// AnchorRecoveryEntry gives a commit-tree result a named, reflogged root
// before any attempt to move trunk. A failure is terminal: landing without its
// recovery witness would reopen the crash-loss window this guard closes.
func AnchorRecoveryEntry(root, wtPath, candidateSHA string, git GitRunner) (string, error) {
	ref, err := RecoveryRef(wtPath, candidateSHA)
	if err != nil {
		return "", err
	}
	rc, out := run(git, root, []string{"update-ref", "--create-reflog", "-m", recoveryReflogMessage, ref, strings.TrimSpace(candidateSHA)})
	if rc != 0 {
		return ref, fmt.Errorf("could not anchor recovery ref %s (git error): %s", ref, strings.TrimSpace(out))
	}
	return ref, nil
}

// RecoveryEntries inventories every durable worker-land candidate. Git's
// reachability relation, not a session ledger, decides whether it is landed.
func RecoveryEntries(root string, git GitRunner) ([]RecoveryEntry, error) {
	rc, out := run(git, root, []string{"for-each-ref", "--format=%(refname)%00%(objectname)", RecoveryRefPrefix})
	if rc != 0 {
		return nil, fmt.Errorf("could not list worker-land recovery refs: %s", strings.TrimSpace(out))
	}
	items := []RecoveryEntry{}
	for _, line := range strings.Split(strings.TrimSpace(out), "\n") {
		if strings.TrimSpace(line) == "" {
			continue
		}
		parts := strings.SplitN(line, "\x00", 2)
		if len(parts) != 2 || !strings.HasPrefix(parts[0], RecoveryRefPrefix) {
			return nil, fmt.Errorf("malformed worker-land recovery ref row %q", line)
		}
		ref, sha := parts[0], strings.TrimSpace(parts[1])
		rest := strings.TrimPrefix(ref, RecoveryRefPrefix)
		wt := strings.SplitN(rest, "/", 2)[0]
		item := RecoveryEntry{Ref: ref, SHA: sha, Worktree: wt, State: "RECOVERABLE", Action: "inspect with git show " + ref + "; re-run worktree worker land or cherry-pick " + ref}
		if ancRC, _ := run(git, root, []string{"merge-base", "--is-ancestor", sha, "HEAD"}); ancRC == 0 {
			item.State = "LANDED"
			item.Action = "safe to clean with fak worktree worker recover --cleanup " + ref
		}
		items = append(items, item)
	}
	sort.Slice(items, func(i, j int) bool { return items[i].Ref < items[j].Ref })
	return items, nil
}

// DeleteRecoveryRef deletes a recovery ref only when its candidate is already
// reachable from HEAD. force is the explicit disaster-recovery escape hatch.
func DeleteRecoveryRef(root, ref string, force bool, git GitRunner) error {
	if !strings.HasPrefix(ref, RecoveryRefPrefix) || strings.Contains(ref, "..") {
		return fmt.Errorf("ref is outside %s", RecoveryRefPrefix)
	}
	rc, sha := run(git, root, []string{"rev-parse", "--verify", ref})
	if rc != 0 || strings.TrimSpace(sha) == "" {
		return fmt.Errorf("recovery ref not found: %s", ref)
	}
	sha = strings.TrimSpace(sha)
	if !force {
		if ancRC, _ := run(git, root, []string{"merge-base", "--is-ancestor", sha, "HEAD"}); ancRC != 0 {
			return fmt.Errorf("ref %s is not landed in HEAD; refusing cleanup without --force", ref)
		}
	}
	if delRC, out := run(git, root, []string{"update-ref", "-d", ref, sha}); delRC != 0 {
		return fmt.Errorf("could not delete recovery ref %s: %s", ref, strings.TrimSpace(out))
	}
	return nil
}
