package generalizationdebt

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

func TestScanClassifiesSpecificityAndAcceptedDebt(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "internal/a/specific.go", `package a
// fak:generalization-debt accepted_temporary rationale="migration bridge" owner="runtime" exit_gate="remove after registry ships"
func OpenAIBackend() { println("anthropic") }
func GeminiOnly() {}
func llamaCPPOnly() {}
`)
	writeFixture(t, root, "internal/a/bad.go", `package a
// fak:generalization-debt accepted_temporary rationale="" owner="runtime" exit_gate="remove someday"
func BedrockOnly() {}
`)

	report, err := Scan(root)
	if err != nil {
		t.Fatal(err)
	}
	if report.Schema != Schema {
		t.Fatalf("schema=%q", report.Schema)
	}
	if report.Totals != (Totals{Findings: 4, DebtPoints: 40, AccidentalUnaccepted: 3, AcceptedTemporary: 1}) {
		t.Fatalf("totals=%+v", report.Totals)
	}
	bySubject := findingsBySubject(report.Findings)
	assertFinding(t, bySubject["GeminiOnly"], "model_specific", DispositionAccidental, InterestCritical, "compounding", 10)
	assertFinding(t, bySubject["llamaCPPOnly"], "backend_specific", DispositionAccidental, InterestHigh, "accelerating", 8)
	assertFinding(t, bySubject["BedrockOnly"], "provider_specific", DispositionAccidental, InterestCritical, "compounding", 10)

	accepted := bySubject["OpenAIBackend"]
	assertFinding(t, accepted, "provider_specific", DispositionAcceptedTemporary, InterestCritical, "compounding", 12)
	if accepted.Accepted == nil || accepted.Accepted.Rationale != "migration bridge" || accepted.Accepted.Owner != "runtime" || accepted.Accepted.ExitGate != "remove after registry ships" {
		t.Fatalf("accepted metadata=%+v", accepted.Accepted)
	}
	if !reflect.DeepEqual(accepted.Interest.Drivers, []string{"blast_radius", "explicit_retirement_gate", "implementation_specificity", "unsupported_variant_count"}) {
		t.Fatalf("drivers=%v", accepted.Interest.Drivers)
	}
}

func TestGenericAbstractionsScoreZeroWithoutLaunderingSpecificCode(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "generic.go", `package p
type Backend interface{ Run() }
var OpenAIRegistry = map[string]Backend{}
func RegisterOpenAI() {}
func OpenAIConcrete() {
	// Registry migration is planned, but this is still singular today.
	registry := "future"
	_ = registry
}
`)

	report, err := Scan(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Findings) != 1 || report.Findings[0].Subject != "OpenAIConcrete" {
		t.Fatalf("findings=%+v", report.Findings)
	}
	assertFinding(t, report.Findings[0], "provider_specific", DispositionAccidental, InterestCritical, "compounding", 10)
}

func TestScanExcludesNonProductionAndHistoricalQwen36Paths(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "internal/a/live.go", "package a\nfunc OpenAILive(){}\n// Qwen3.6 is mentioned as history; do not hide this declaration.\n")
	writeFixture(t, root, "internal/a/x_test.go", "package a\nfunc OpenAITest(){}\n")
	writeFixture(t, root, "internal/a/generated.go", "// Code generated by x. DO NOT EDIT.\npackage a\nfunc OpenAIGenerated(){}\n")
	writeFixture(t, root, "internal/a/testdata/x.go", "package testdata\nfunc OpenAIFixture(){}\n")
	writeFixture(t, root, "examples/x.go", "package examples\nfunc OpenAIExample(){}\n")
	writeFixture(t, root, "docs/x.go", "package docs\nfunc OpenAIDoc(){}\n")
	writeFixture(t, root, "experiments/qwen36/probe.go", "package probe\nfunc OpenAIHistorical(){}\n")
	writeFixture(t, root, "_scratch/broken.go", "package broken\nfunc OpenAIBroken(\n")
	writeFixture(t, root, "README.md", "OpenAI")

	report, err := Scan(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Findings) != 1 || report.Findings[0].Subject != "OpenAILive" {
		t.Fatalf("findings=%+v", report.Findings)
	}
}

func TestScanJSONAndOrderingAreDeterministic(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "z.go", "package p\nfunc VLLMOnly(){}\n")
	writeFixture(t, root, "a.go", "package p\nfunc ClaudeOnly(){}\n")

	first, err := Scan(root)
	if err != nil {
		t.Fatal(err)
	}
	second, err := Scan(root)
	if err != nil {
		t.Fatal(err)
	}
	firstJSON, _ := json.Marshal(first)
	secondJSON, _ := json.Marshal(second)
	if string(firstJSON) != string(secondJSON) {
		t.Fatalf("JSON differs:\n%s\n%s", firstJSON, secondJSON)
	}
	if first.Findings[0].Path != "a.go" || first.Findings[1].Path != "z.go" {
		t.Fatalf("ordering=%+v", first.Findings)
	}
}

func writeFixture(t *testing.T, root, path, body string) {
	t.Helper()
	full := filepath.Join(root, filepath.FromSlash(path))
	if err := os.MkdirAll(filepath.Dir(full), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(body), 0644); err != nil {
		t.Fatal(err)
	}
}

func findingsBySubject(findings []Finding) map[string]Finding {
	out := make(map[string]Finding, len(findings))
	for _, finding := range findings {
		out[finding.Subject] = finding
	}
	return out
}

func assertFinding(t *testing.T, finding Finding, kind string, disposition Disposition, band InterestBand, rate string, points int) {
	t.Helper()
	if finding.Subject == "" || finding.Kind != kind || finding.Disposition != disposition || finding.Interest.Band != band || finding.Interest.Rate != rate || finding.DebtPoints != points {
		t.Fatalf("finding=%+v; want kind=%s disposition=%s interest=%s/%s points=%d", finding, kind, disposition, band, rate, points)
	}
}
