package harnessinit

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const (
	ContractVersion   = "v1alpha1"
	DefaultFAKVersion = "v0.43.1-0.20260814184635-613a82b762e2"
	generatorID       = "fak harness init/v1"
	generatedMarker   = "Code generated by fak harness init/v1; DO NOT EDIT."
)

var modulePattern = regexp.MustCompile(`^[A-Za-z0-9._~/-]+$`)

type Options struct {
	Dir        string
	Module     string
	FAKVersion string
}

type Result struct {
	Directory       string   `json:"directory"`
	Module          string   `json:"module"`
	FAKVersion      string   `json:"fak_version"`
	ContractVersion string   `json:"contract_version"`
	Created         []string `json:"created"`
	Updated         []string `json:"updated,omitempty"`
	Preserved       []string `json:"preserved,omitempty"`
}

type manifest struct {
	Schema          string            `json:"schema"`
	Generator       string            `json:"generator"`
	FAKModule       string            `json:"fak_module"`
	FAKVersion      string            `json:"fak_version"`
	ContractVersion string            `json:"contract_version"`
	Ownership       map[string]string `json:"ownership"`
	Build           string            `json:"build"`
	Run             string            `json:"run"`
	Upgrade         string            `json:"upgrade"`
}

type fileSpec struct {
	path      string
	body      string
	generated bool
}

func Init(opts Options) (Result, error) {
	if opts.Dir == "" {
		return Result{}, errors.New("--dir is required")
	}
	if opts.Module == "" || !modulePattern.MatchString(opts.Module) || strings.HasPrefix(opts.Module, "/") {
		return Result{}, fmt.Errorf("invalid --module %q", opts.Module)
	}
	if opts.FAKVersion == "" {
		opts.FAKVersion = DefaultFAKVersion
	}
	root, err := filepath.Abs(opts.Dir)
	if err != nil {
		return Result{}, err
	}
	if err := os.MkdirAll(root, 0o755); err != nil {
		return Result{}, err
	}

	files, err := render(opts.Module, opts.FAKVersion)
	if err != nil {
		return Result{}, err
	}
	result := Result{Directory: root, Module: opts.Module, FAKVersion: opts.FAKVersion, ContractVersion: ContractVersion}
	priorManifest, priorManifestErr := os.ReadFile(filepath.Join(root, "harness.lock.json"))
	goSumOwned := priorManifestErr == nil && bytes.Contains(priorManifest, []byte(`"generator": "`+generatorID+`"`)) && bytes.Contains(priorManifest, []byte(`"go.sum": "generated"`))
	for _, f := range files {
		path := filepath.Join(root, filepath.FromSlash(f.path))
		old, readErr := os.ReadFile(path)
		switch {
		case readErr == nil && !f.generated:
			result.Preserved = append(result.Preserved, f.path)
			continue
		case readErr == nil && f.generated && !bytes.Contains(old, []byte(generatedMarker)) && f.path != "harness.lock.json" && f.path != "go.sum":
			return Result{}, fmt.Errorf("refusing to overwrite user-owned file %s", f.path)
		case readErr == nil && f.path == "go.sum" && !bytes.Equal(old, []byte(f.body)) && !goSumOwned:
			return Result{}, fmt.Errorf("refusing to overwrite unrecognized generated file %s", f.path)
		case readErr == nil && f.path == "harness.lock.json" && !bytes.Contains(old, []byte(`"generator": "`+generatorID+`"`)):
			return Result{}, fmt.Errorf("refusing to overwrite unrecognized manifest %s", f.path)
		case readErr != nil && !errors.Is(readErr, os.ErrNotExist):
			return Result{}, readErr
		}
		if readErr == nil && bytes.Equal(old, []byte(f.body)) {
			result.Preserved = append(result.Preserved, f.path)
			continue
		}
		if err := writeAtomic(path, []byte(f.body)); err != nil {
			return Result{}, err
		}
		if readErr == nil {
			result.Updated = append(result.Updated, f.path)
		} else {
			result.Created = append(result.Created, f.path)
		}
	}
	sort.Strings(result.Created)
	sort.Strings(result.Updated)
	sort.Strings(result.Preserved)
	return result, nil
}

func writeAtomic(path string, body []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp := path + ".fak-init-tmp"
	if err := os.WriteFile(tmp, body, 0o644); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}

func render(module, version string) ([]fileSpec, error) {
	m := manifest{
		Schema: "fak-harness-product/v1", Generator: generatorID,
		FAKModule: "github.com/anthony-chaudhary/fak", FAKVersion: version, ContractVersion: ContractVersion,
		Ownership: map[string]string{"go.mod": "generated", "go.sum": "generated", "cmd/product/main.go": "generated", "generated/runtime.go": "generated", "product/config.go": "user", "harness.lock.json": "generated", "README.md": "user"},
		Build:     "go build -o product-bin ./cmd/product", Run: "go run ./cmd/product --selfcheck", Upgrade: "fak harness init --dir . --module " + module + " --fak-version " + version,
	}
	mb, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return nil, err
	}
	return []fileSpec{
		{"go.mod", fmt.Sprintf("// %s\nmodule %s\n\ngo 1.26\n\nrequire github.com/anthony-chaudhary/fak %s\n", generatedMarker, module, version), true},
		{"go.sum", fmt.Sprintf("github.com/anthony-chaudhary/fak %s h1:tDlanAfpwQOgGgtMIjsif7YUryFFTnydYPHJk69Ydow=\ngithub.com/anthony-chaudhary/fak %s/go.mod h1:n6KmWHdq9ufGPlRGo8n6xIBrsOw9YuGi+lAFWINC5SI=\n", version, version), true},
		{"cmd/product/main.go", fmt.Sprintf(`// %s
// fak-contract: %s; fak-module: github.com/anthony-chaudhary/fak@%s
package main

import (
 "context"
 "flag"
 "fmt"
 "os"

 runtime "%s/generated"
)

func main() {
 selfcheck := flag.Bool("selfcheck", false, "run one deterministic offline turn")
 productLock := flag.String("product-lock", "", "verified fak product lock")
 flag.Parse()
 if !*selfcheck { fmt.Fprintln(os.Stderr, "use --selfcheck"); os.Exit(2) }
 if err := runtime.Selfcheck(context.Background(), os.Stdout, *productLock); err != nil { fmt.Fprintln(os.Stderr, err); os.Exit(1) }
}
`, generatedMarker, ContractVersion, version, module), true},
		{"generated/runtime.go", fmt.Sprintf(`// %s
// fak-contract: %s; fak-module: github.com/anthony-chaudhary/fak@%s
package generated

import (
 "context"
 "crypto/sha256"
 "encoding/hex"
 "encoding/json"
 "fmt"
 "io"
 "os"
 "sort"
 "strings"

 "github.com/anthony-chaudhary/fak/pkg/harnesskit"
 "%s/product"
)

type event struct { Type string `+"`json:\"type\"`"+`; Turn string `+"`json:\"turn\"`"+`; Detail string `+"`json:\"detail,omitempty\"`"+` }
type lockedComponent struct { ID string `+"`json:\"id\"`"+`; Version string `+"`json:\"version\"`"+`; Digest string `+"`json:\"digest\"`"+`; Source string `+"`json:\"source\"`"+`; Reason string `+"`json:\"reason,omitempty\"`"+`; Provider string `+"`json:\"provider,omitempty\"`"+`; Provides []string `+"`json:\"provides,omitempty\"`"+` }
type lockedAsset struct { Kind string `+"`json:\"kind\"`"+`; ID string `+"`json:\"id\"`"+`; Value string `+"`json:\"value,omitempty\"`"+`; Ref string `+"`json:\"ref,omitempty\"`"+`; Boundary string `+"`json:\"boundary,omitempty\"`"+`; Grants []string `+"`json:\"grants,omitempty\"`"+`; Denies []string `+"`json:\"denies,omitempty\"`"+`; Source string `+"`json:\"source\"`"+`; Locked bool `+"`json:\"locked,omitempty\"`"+`; Mandatory bool `+"`json:\"mandatory,omitempty\"`"+` }
type productLock struct { Schema string `+"`json:\"schema\"`"+`; ID string `+"`json:\"id\"`"+`; Environment json.RawMessage `+"`json:\"environment\"`"+`; Budget json.RawMessage `+"`json:\"budget\"`"+`; Components []lockedComponent `+"`json:\"components\"`"+`; Assets []lockedAsset `+"`json:\"assets\"`"+`; AssetTrace json.RawMessage `+"`json:\"asset_trace\"`"+`; Decisions json.RawMessage `+"`json:\"decisions\"`"+` }
type launchReceipt struct { Schema string `+"`json:\"schema\"`"+`; LockID string `+"`json:\"lock_id\"`"+`; ProductID string `+"`json:\"product_id\"`"+`; Profile string `+"`json:\"profile\"`"+`; Layers []string `+"`json:\"layers\"`"+`; Assets []string `+"`json:\"assets\"`"+`; Components []string `+"`json:\"components\"`"+` }

func loadLock(path string) (productLock, error) {
 raw, err := os.ReadFile(path); if err != nil { return productLock{}, err }
 var lock productLock; dec := json.NewDecoder(strings.NewReader(string(raw))); dec.DisallowUnknownFields(); if err := dec.Decode(&lock); err != nil { return productLock{}, err }
 if lock.Schema != "fak.harness-product-lock/v1alpha1" || lock.ID == "" || len(lock.Components) == 0 { return productLock{}, fmt.Errorf("invalid product lock") }
 want := lock.ID; lock.ID = ""; canonical, err := json.Marshal(lock); if err != nil { return productLock{}, err }; sum := sha256.Sum256(canonical); got := "sha256:" + hex.EncodeToString(sum[:]); if got != want { return productLock{}, fmt.Errorf("product lock digest mismatch") }; lock.ID = want
 for _, component := range lock.Components { if component.ID == "" || component.Version == "" || component.Source == "" || !strings.HasPrefix(component.Digest, "sha256:") { return productLock{}, fmt.Errorf("invalid locked component") } }
 for _, asset := range lock.Assets { if asset.Kind == "" || asset.ID == "" || asset.Source == "" || (asset.Kind == "secret" && asset.Ref == "") { return productLock{}, fmt.Errorf("invalid locked asset") } }
 return lock, nil
}
func (lock productLock) project(productID string) (harnesskit.Profile, launchReceipt, string) {
 seen := map[string]bool{}; layers := []string{}; assets := []string{}; instructions := []string{}
 for _, asset := range lock.Assets { if !seen[asset.Source] { seen[asset.Source] = true; layers = append(layers, asset.Source) }; assets = append(assets, asset.Kind+"/"+asset.ID+"@"+asset.Source); if asset.Kind == "instruction" && asset.Value != "" { instructions = append(instructions, asset.Value) } }
 profileID := "locked"; for _, layer := range layers { if layer == "legal" || layer == "coding" || layer == "integrated" { profileID = layer; break } }; capabilities := make([]harnesskit.Capability, 0, len(layers)); for _, layer := range layers { capabilities = append(capabilities, harnesskit.Capability("layer:"+layer)) }
 components := []string{}; for _, component := range lock.Components { components = append(components, component.ID+"@"+component.Version+"#"+component.Digest) }; sort.Strings(assets); sort.Strings(components); sort.Strings(instructions)
 return harnesskit.Profile{ID: profileID, Capabilities: capabilities}, launchReceipt{Schema:"fak.harness-launch-receipt/v1alpha1", LockID:lock.ID, ProductID:productID, Profile:profileID, Layers:layers, Assets:assets, Components:components}, strings.Join(instructions,"\n")
}


func Selfcheck(ctx context.Context, out io.Writer, lockPath string) error {
 select { case <-ctx.Done(): return ctx.Err(); default: }
 profile := harnesskit.Profile{ID: product.Profile}
 var lock productLock
 var receipt launchReceipt
 instructions := ""
 if lockPath != "" {
  var err error
  lock, err = loadLock(lockPath)
  if err != nil { return err }
  profile, receipt, instructions = lock.project(product.ID)
 }
 p, err := harnesskit.New(product.ID, product.Version).WithProfile(profile).Build()
 if err != nil { return err }
 if p.Spec().ID != product.ID { return fmt.Errorf("product identity mismatch") }
 emit := func(kind, detail string) error { return json.NewEncoder(out).Encode(event{Type: kind, Turn: "offline-1", Detail: detail}) }
 if lockPath != "" {
  rawReceipt, err := json.Marshal(receipt); if err != nil { return err }
  if err := emit("harness.locked", string(rawReceipt)); err != nil { return err }
 }
 if err := emit("turn.started", "offline deterministic model"); err != nil { return err }
 reply := product.OfflineReply("prove the external harness works")
 if instructions != "" { reply = profile.ID + " | " + instructions + " | " + reply }
 if err := emit("model.response", reply); err != nil { return err }
 if err := emit("tool.requested", "record_selfcheck"); err != nil { return err }
 if err := emit("tool.completed", "record_selfcheck:ok"); err != nil { return err }
 return emit("turn.completed", "ok")
}
`, generatedMarker, ContractVersion, version, module), true},
		{"product/config.go", `// Package product is user-owned product configuration. fak harness init never overwrites this file.
package product

const (
 ID = "example-product"
 Version = "0.1.0"
 Profile = "offline-selfcheck"
)

func OfflineReply(prompt string) string { return "offline reply: " + prompt }
`, false},
		{"harness.lock.json", string(mb) + "\n", true},
		{"README.md", fmt.Sprintf(`# External fak harness product

Generated by **%s** against public contract **%s** and pinned module **github.com/anthony-chaudhary/fak@%s**.

- Build: `+"`go build -o product-bin ./cmd/product`"+`
- Run the stock offline turn: `+"`go run ./cmd/product --selfcheck`"+`
- Run a verified contextual product: `+"`go run ./cmd/product --selfcheck --product-lock product.lock.json`"+`
- Upgrade generated files: `+"`fak harness init --dir . --module %s --fak-version %s`"+`
- Ownership: `+"`product/config.go`"+` is user-owned and is never overwritten. Files marked `+"`Code generated`"+` plus `+"`harness.lock.json`"+` are generator-owned.
`, generatorID, ContractVersion, version, module, version), false},
	}, nil
}
