package policy

// Obfuscation-corpus containment REPORT: capability floor vs regex approval
// (issue #2919, part of program #2908 — Hermes-evidence security-gap survey).
//
// #2843 (redteam_deobfuscation_capfloor_conformance_test.go) already shipped the
// three executable pieces #2919 asks for: the obfuscation CORPUS (redTeamCorpus),
// a FAK-FLOOR ARM (adjudicator DEFAULT_DENY on an ungranted exec capability), and
// a REGEX-EMULATION ARM (a raw danger pattern that misses the obfuscated forms).
// What #2843 did NOT produce is #2919's fourth acceptance element: a single
// RENDERED REPORT that puts both arms head-to-head and states, as one artifact,
// that the floor's containment is independent of encoding while the regexes are
// not. This file is that report — it REUSES #2843's shipped corpus and floor (no
// duplicate corpus), runs both arms over every case, and renders a markdown table
// + summary to a golden artifact (testdata/redteam_floor_report.md).
//
// The golden is not decoration: the report is regenerated from the LIVE
// adjudicator and the LIVE corpus on every run and compared byte-for-byte, so it
// cannot rot into a lie. If the capability floor ever started admitting Bash, the
// "contained" column would change and this test would fail — the report stays
// true by construction, not by a stale hand-written claim.
//
// Regenerate the golden after an intentional change with:
//
//	FAK_UPDATE_GOLDEN=1 go test ./internal/policy -run TestRedTeamFloorReport
//
// Scope note (the #2919 confusion risk): the regex arm is a deliberately SMALL,
// representative subset of approval.py's action-targeting DANGEROUS_PATTERNS, not
// a re-implementation of its 2,921 lines. It targets the dangerous ACTIONS the
// corpus hides (destructive rm, fetch-pipe-to-shell), because that is what a fair
// comparison measures: containment of the underlying capability, not whether one
// exact string is on a block-list.

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/anthony-chaudhary/fak/internal/abi"
	"github.com/anthony-chaudhary/fak/internal/adjudicator"
)

// regexArmPattern is one representative approval.py-style DANGEROUS_PATTERN run
// WITHOUT a de-obfuscation normalizer — the honest baseline for "what a regex
// approval layer catches before it has grown a rule for this particular
// encoding." Each targets a dangerous ACTION the corpus reconstructs at runtime.
type regexArmPattern struct {
	name string
	re   *regexp.Regexp
}

// regexArm mirrors the shape of approval.py's action patterns: a destructive
// recursive delete and a fetch-piped-to-shell remote exec. These are exactly the
// actions redTeamCorpus hides; the point of the report is that every obfuscation
// class defeats them (the action text is encoded), yet the capability floor
// contains all of them because it never reads the command string at all.
var regexArm = []regexArmPattern{
	{"destructive-rm", regexp.MustCompile(`rm\s+-[rf]{2,}`)},
	{"fetch-pipe-to-shell", regexp.MustCompile(`(?:curl|wget)\b[^\n]*https?://[^\n|]*\|\s*(?:sh|bash)`)},
}

// regexArmCatches reports whether ANY regex-arm pattern matches the raw command
// string, and the name of the first that does (for the report cell).
func regexArmCatches(command string) (caught bool, by string) {
	for _, p := range regexArm {
		if p.re.MatchString(command) {
			return true, p.name
		}
	}
	return false, ""
}

// mdCell renders a command string safe for a single markdown table cell: Go-quoted
// so ANSI/control bytes surface as escapes (deterministic across platforms) and
// fullwidth runes stay readable, with the column-breaking pipe escaped.
func mdCell(s string) string {
	return strings.ReplaceAll(fmt.Sprintf("%q", s), "|", `\|`)
}

// renderRedTeamFloorReport runs BOTH arms over the shipped #2843 corpus against the
// LIVE capability floor and returns the rendered markdown report. It is the single
// source of truth for the golden artifact; the test below both writes it (update
// mode) and verifies it (default mode).
func renderRedTeamFloorReport(t *testing.T) string {
	t.Helper()
	a := adjudicator.New(capabilityFloor())
	ctx := t.Context()

	var b strings.Builder
	b.WriteString("# Obfuscation-corpus containment: capability floor vs regex approval (#2919)\n\n")
	b.WriteString("Generated by `internal/policy` `TestRedTeamFloorReport` — do not hand-edit; it is\n")
	b.WriteString("regenerated from the live adjudicator and the #2843 obfuscation corpus and\n")
	b.WriteString("golden-checked, so a drift means the floor's behavior changed, not the prose.\n\n")
	b.WriteString("Two arms decide the same corpus of Hermes `approval.py` obfuscation classes:\n\n")
	b.WriteString("- **Floor arm** — fak's capability floor (`adjudicator` on a default-deny\n")
	b.WriteString("  allow-list that never grants an exec/shell tool). It decides on TOOL\n")
	b.WriteString("  IDENTITY and never inspects the command string, so the deny is `DEFAULT_DENY`\n")
	b.WriteString("  no matter how the payload is spelled.\n")
	b.WriteString("- **Regex-emulation arm** — a representative subset of action-targeting\n")
	b.WriteString("  `DANGEROUS_PATTERNS` run WITHOUT a de-obfuscation normalizer:\n")
	for _, p := range regexArm {
		fmt.Fprintf(&b, "  - `%s`: `%s`\n", p.name, p.re.String())
	}
	b.WriteString("\n")

	b.WriteString("| # | Obfuscation | Hidden action | Floor arm (capability) | Regex-emulation arm |\n")
	b.WriteString("|---|---|---|---|---|\n")

	var floorContained, regexCaught int
	for i, tc := range redTeamCorpus {
		v := a.Adjudicate(ctx, bashCall(t, tc.command))
		contained := v.Kind == abi.VerdictDeny
		if contained {
			floorContained++
		}
		floorCell := fmt.Sprintf("%s · %s", verdictWord(v.Kind), abi.ReasonName(v.Reason))
		if contained {
			floorCell += " — contained"
		} else {
			floorCell += " — ADMITTED"
		}

		caught, by := regexArmCatches(tc.command)
		regexCell := "BYPASSED"
		if caught {
			regexCaught++
			regexCell = fmt.Sprintf("caught by `%s`", by)
		}

		fmt.Fprintf(&b, "| %d | %s | `%s` | %s | %s |\n",
			i+1, tc.name, strings.ReplaceAll(tc.hides, "|", `\|`), floorCell, regexCell)
	}

	total := len(redTeamCorpus)
	b.WriteString("\n## Result\n\n")
	fmt.Fprintf(&b, "- **Floor arm: %d/%d contained** — every obfuscation class is denied with\n", floorContained, total)
	b.WriteString("  `DEFAULT_DENY` (the missing Bash capability), so containment is\n")
	b.WriteString("  **spelling-invariant**: the deciding factor is the absent capability, never\n")
	b.WriteString("  the bytes, and no new regex is needed for any encoding.\n")
	fmt.Fprintf(&b, "- **Regex-emulation arm: %d/%d caught, %d/%d BYPASSED** — the action text is\n",
		regexCaught, total, total-regexCaught, total)
	b.WriteString("  encoded (base64/xxd/tr/openssl), whitespace-split (`${IFS}`), NFKC-foldable\n")
	b.WriteString("  (fullwidth), or ANSI-split, so an un-normalized action pattern misses it. The\n")
	b.WriteString("  one caught case is the heredoc, where the action text is visible — the honest\n")
	b.WriteString("  control that the arm is not vacuously blind.\n\n")
	b.WriteString("Containment is independent of encoding for the floor and dependent on it for the\n")
	b.WriteString("regexes: that gap is exactly why `approval.py` must carry a de-obfuscation\n")
	b.WriteString("normalizer (`_normalize_command_for_detection`) and grow a rule per encoding,\n")
	b.WriteString("and why fak needs neither the ~90 patterns nor the normalizer.\n")
	return b.String()
}

// verdictWord renders a verdict kind as the short word the report uses.
func verdictWord(k abi.VerdictKind) string {
	if k == abi.VerdictDeny {
		return "DENY"
	}
	return fmt.Sprintf("ADMIT(%d)", k)
}

// goldenReportPath is the committed report artifact #2919's acceptance names.
func goldenReportPath() string {
	return filepath.Join("testdata", "redteam_floor_report.md")
}

// TestRedTeamFloorReport is the #2919 witness: it renders the head-to-head report
// from the live floor + the #2843 corpus, asserts the two load-bearing claims
// (floor contains every case; the regex arm is bypassed by at least one variant),
// and golden-checks the rendered artifact so the committed report can never drift
// from the floor's real behavior.
func TestRedTeamFloorReport(t *testing.T) {
	got := renderRedTeamFloorReport(t)

	// The report's headline claims, asserted directly so a green test == a true
	// report (not just a matching file).
	a := adjudicator.New(capabilityFloor())
	ctx := t.Context()
	bypassedAny := false
	for _, tc := range redTeamCorpus {
		v := a.Adjudicate(ctx, bashCall(t, tc.command))
		if v.Kind != abi.VerdictDeny || v.Reason != abi.ReasonDefaultDeny {
			t.Fatalf("floor arm: case %q rendered as contained but Adjudicate gave Kind=%v Reason=%s — the report would be a lie",
				tc.name, v.Kind, abi.ReasonName(v.Reason))
		}
		if caught, _ := regexArmCatches(tc.command); !caught {
			bypassedAny = true
		}
	}
	if !bypassedAny {
		t.Fatal("regex-emulation arm caught every case — the #2919 comparison requires at least one obfuscation variant to bypass the regexes")
	}

	if os.Getenv("FAK_UPDATE_GOLDEN") != "" {
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatalf("mkdir testdata: %v", err)
		}
		if err := os.WriteFile(goldenReportPath(), []byte(got), 0o644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		t.Logf("updated golden report %s", goldenReportPath())
		return
	}

	want, err := os.ReadFile(goldenReportPath())
	if err != nil {
		t.Fatalf("read golden report %s: %v (regenerate with FAK_UPDATE_GOLDEN=1)", goldenReportPath(), err)
	}
	wantStr := strings.ReplaceAll(string(want), "\r\n", "\n")
	gotStr := strings.ReplaceAll(got, "\r\n", "\n")
	if gotStr != wantStr {
		t.Fatalf("rendered report drifted from committed golden %s — the floor's behavior or the corpus changed; regenerate with FAK_UPDATE_GOLDEN=1 and review the diff",
			goldenReportPath())
	}
}
