package orphanscan

import (
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"testing"
)

// writeGo drops one .go file into dir.
func writeGo(t *testing.T, dir, name, src string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(src), 0o644); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
}

// scanNames scans dir and returns the flagged orphan names, sorted.
func scanNames(t *testing.T, dir string) []string {
	t.Helper()
	orphans, err := ScanDir(dir, "")
	if err != nil {
		t.Fatalf("ScanDir: %v", err)
	}
	var names []string
	for _, o := range orphans {
		names = append(names, o.Name)
	}
	sort.Strings(names)
	return names
}

// TestFlagsOrphanNotWired is the core case: an unexported top-level func with no call
// site is flagged; a sibling that IS called from exported code is not. This is the
// "panel builder written but never added to the registry" shape.
func TestFlagsOrphanNotWired(t *testing.T) {
	dir := t.TempDir()
	writeGo(t, dir, "panels.go", `package fixture

// orphanBuilder was authored but never added to the registry.
func orphanBuilder() int { return 1 }

// wiredBuilder is in the registry.
func wiredBuilder() int { return 2 }

// Registry is exported API and references only the wired builder.
func Registry() []int { return []int{wiredBuilder()} }
`)
	got := scanNames(t, dir)
	want := []string{"orphanBuilder"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("orphans = %v, want %v", got, want)
	}
}

// TestSkipsExportedMainInitBlank: exported funcs (API), main, init, and the blank func
// are never candidates even with no visible reference.
func TestSkipsExportedMainInitBlank(t *testing.T) {
	dir := t.TempDir()
	writeGo(t, dir, "main.go", `package main

func main()      {}
func init()      {}
func _()         {}
func Exported()  {}
func alsoUnused() {}
`)
	got := scanNames(t, dir)
	want := []string{"alsoUnused"} // only the plain unexported one is an orphan
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("orphans = %v, want %v", got, want)
	}
}

// TestTestFileReferenceCountsAsUse: a helper referenced only from a _test.go file is
// NOT an orphan — a test-only helper is wired, just wired by the tests.
func TestTestFileReferenceCountsAsUse(t *testing.T) {
	dir := t.TempDir()
	writeGo(t, dir, "helper.go", `package fixture

func onlyTestUses() int { return 9 }
`)
	writeGo(t, dir, "helper_test.go", `package fixture

// Exercise is exported so it is not itself a candidate; it wires onlyTestUses.
func Exercise() { _ = onlyTestUses() }
`)
	if got := scanNames(t, dir); len(got) != 0 {
		t.Fatalf("orphans = %v, want none (test-referenced helper is wired)", got)
	}
}

// TestKeepDirectiveSuppresses: //orphanscan:keep on the func's doc comment is the
// visible escape hatch for a func wired in a way the syntactic scan cannot see.
func TestKeepDirectiveSuppresses(t *testing.T) {
	dir := t.TempDir()
	writeGo(t, dir, "reflected.go", `package fixture

//orphanscan:keep dispatched by name through a reflection table
func keptOrphan() {}
`)
	if got := scanNames(t, dir); len(got) != 0 {
		t.Fatalf("orphans = %v, want none (keep directive suppresses)", got)
	}
}

// TestGeneratedFileNotFlagged: a func in a `Code generated ... DO NOT EDIT.` file is
// owned by its generator, not by this gate.
func TestGeneratedFileNotFlagged(t *testing.T) {
	dir := t.TempDir()
	writeGo(t, dir, "zz_generated.go", `// Code generated by stringer. DO NOT EDIT.

package fixture

func genOrphan() {}
`)
	if got := scanNames(t, dir); len(got) != 0 {
		t.Fatalf("orphans = %v, want none (generated file)", got)
	}
}

// TestLinknameSuppresses: a func wired via //go:linkname has no in-package reference by
// design and must not be flagged.
func TestLinknameSuppresses(t *testing.T) {
	dir := t.TempDir()
	writeGo(t, dir, "link.go", `package fixture

import _ "unsafe"

//go:linkname secretImpl example.com/other.secretImpl
func secretImpl() {}
`)
	if got := scanNames(t, dir); len(got) != 0 {
		t.Fatalf("orphans = %v, want none (go:linkname wires it)", got)
	}
}

// TestMethodNotFlagged: a receiver method may satisfy an interface and be dispatched
// dynamically, so methods are out of scope even when their name is unreferenced.
func TestMethodNotFlagged(t *testing.T) {
	dir := t.TempDir()
	writeGo(t, dir, "method.go", `package fixture

type T struct{}

func (t T) unusedMethod() {}

func Use() { _ = T{} }
`)
	if got := scanNames(t, dir); len(got) != 0 {
		t.Fatalf("orphans = %v, want none (methods are out of scope)", got)
	}
}

// TestRecursiveSelfCallNotFlagged documents the deliberate conservative false negative:
// a func that only references itself counts as used, so a purely-recursive but
// externally-dead func is NOT flagged. Precision over recall — we never cry wolf.
func TestRecursiveSelfCallNotFlagged(t *testing.T) {
	dir := t.TempDir()
	writeGo(t, dir, "recur.go", `package fixture

func recur(n int) int {
	if n <= 0 {
		return 0
	}
	return recur(n - 1)
}
`)
	if got := scanNames(t, dir); len(got) != 0 {
		t.Fatalf("orphans = %v, want none (self-reference is conservatively a use)", got)
	}
}

// TestRelPrefixAndUnparseableFile: relPrefix is applied to File, and a file that will
// not parse is skipped rather than failing the scan.
func TestRelPrefixAndUnparseableFile(t *testing.T) {
	dir := t.TempDir()
	writeGo(t, dir, "good.go", `package fixture

func lonely() {}
`)
	writeGo(t, dir, "broken.go", "package fixture\n\nfunc (((( syntax error\n")
	orphans, err := ScanDir(dir, "internal/fixture")
	if err != nil {
		t.Fatalf("ScanDir: %v", err)
	}
	if len(orphans) != 1 || orphans[0].Name != "lonely" {
		t.Fatalf("orphans = %+v, want one 'lonely'", orphans)
	}
	if orphans[0].File != "internal/fixture/good.go" {
		t.Errorf("File = %q, want internal/fixture/good.go", orphans[0].File)
	}
	if orphans[0].Line != 3 {
		t.Errorf("Line = %d, want 3", orphans[0].Line)
	}
}

func TestOrphanString(t *testing.T) {
	o := Orphan{Name: "guardAblationPanel", File: "cmd/fak/info_panels.go", Line: 42}
	want := "cmd/fak/info_panels.go:42: func guardAblationPanel is defined but never referenced in its package (ORPHAN_FUNC)"
	if got := o.String(); got != want {
		t.Errorf("String() = %q, want %q", got, want)
	}
}

// dogfoodPkgs are the live packages the gate judges. Deliberately a short, named list
// rather than the whole tree: this gate's job is to stop NEW orphans in the packages
// that have already been triaged against the allowlist, and widening the scan to
// packages nobody has baselined would red the trunk with pre-existing debt.
var dogfoodPkgs = []string{"cmd/fak", "internal/gateway"}

// TestDogfoodRealRepo is the gate (#3167). It runs the scanner over the live packages
// and FAILS on any orphan that the checked-in allowlist and the //orphanscan:keep
// directive do not account for — so a newly orphaned func reds the tree instead of
// being logged and ignored, which is what the log-only predecessor did.
//
// It stays a ratchet, not a cliff: known debt is pinned in keep_allowlist.txt with a
// per-entry reason, so only a NEW orphan can fail. Two deliberate degradations keep it
// from crying wolf on a shared tree with in-flight siblings — a package that is absent
// is skipped, and a package with a file the scan could not parse is skipped too, since
// that file may hold the only call site of a func that would otherwise look orphaned.
// A stale allowlist entry is reported but never fails: pruning it is the fix landing,
// and a peer who wires a func should not red the tree for fixing something.
func TestDogfoodRealRepo(t *testing.T) {
	keep, err := KeepAllowlist()
	if err != nil {
		t.Fatalf("KeepAllowlist: %v", err) // the gate cannot judge without its own input
	}
	root := repoRoot(t)

	var scanned []string
	var found []Orphan
	for _, rel := range dogfoodPkgs {
		dir := filepath.Join(root, filepath.FromSlash(rel))
		if _, statErr := os.Stat(dir); statErr != nil {
			t.Logf("%s: absent, not judged", rel)
			continue
		}
		rep, scanErr := ScanDirReport(dir, rel)
		if scanErr != nil {
			t.Errorf("%s: scan error: %v", rel, scanErr)
			continue
		}
		if len(rep.Unparsed) > 0 {
			// An unparseable neighbour contributes no references, so a live func can
			// look orphaned. Decline to judge this package rather than fail on it.
			t.Logf("%s: NOT judged — %d file(s) did not parse (an in-flight sibling): %v",
				rel, len(rep.Unparsed), rep.Unparsed)
			continue
		}
		scanned = append(scanned, rel)
		found = append(found, rep.Orphans...)
		t.Logf("%s: %d orphan-func candidate(s)", rel, len(rep.Orphans))
		for _, o := range rep.Orphans {
			t.Logf("  %s", o)
		}
	}
	if len(scanned) == 0 {
		t.Skip("no dogfood package could be judged this run")
	}

	unexpected, unused := Gate(scanned, found, keep)
	for _, o := range unexpected {
		t.Errorf("new orphan func: %s\n\t%s", o, SuppressionHint(o))
	}
	for _, k := range unused {
		// Advisory only — this fires when someone FIXED an orphan.
		t.Logf("allowlist entry %q is no longer an orphan; prune its line from "+
			"internal/orphanscan/keep_allowlist.txt", k.Key())
	}
}

// repoRoot walks up from the test's working directory to the module root (the dir with
// go.mod).
func repoRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatalf("no go.mod above %s", dir)
		}
		dir = parent
	}
}
