package perfscout

import "time"

// ModelFamily identifies which of the target next-gen flash families a repo serves.
type ModelFamily string

const (
	FamilyQwenFlash ModelFamily = "qwen_flash"
	FamilyGLMFlash  ModelFamily = "glm_flash"
	FamilyDual      ModelFamily = "dual_family"
	FamilyUnknown   ModelFamily = "unknown"
)

// EvidenceGrade indicates the degree of verified empirical evidence in the repo.
type EvidenceGrade string

const (
	GradeMeasured   EvidenceGrade = "MEASURED"   // Concrete tok/s, latency numbers, or benchmark tables published
	GradeKernel     EvidenceGrade = "KERNEL"     // Custom kernels, patches, or low-level runtime engine modifications
	GradeRecipe     EvidenceGrade = "RECIPE"     // Deterministic reproducible recipe, container, or configuration
	GradeEvaluation EvidenceGrade = "EVALUATION" // Evals, quality vs speed trade-offs, or agentic benchmarks
	GradeWrapper    EvidenceGrade = "WRAPPER"    // Higher-level wrapper, harness, or adapter
)

// GitHubRawRepo represents the JSON schema returned by gh search repos.
type GitHubRawRepo struct {
	FullName        string `json:"fullName"`
	Description     string `json:"description"`
	URL             string `json:"url"`
	StargazersCount int    `json:"stargazersCount"`
	UpdatedAt       string `json:"updatedAt"`
	PushedAt        string `json:"pushedAt"`
	CreatedAt       string `json:"createdAt"`
	Language        string `json:"language"`
	Size            int    `json:"size"`
}

// ScoredRepo represents a candidate repository analyzed and scored for performance claims.
type ScoredRepo struct {
	FullName          string        `json:"full_name"`
	Description       string        `json:"description"`
	URL               string        `json:"url"`
	StargazersCount   int           `json:"stargazers_count"`
	UpdatedAt         time.Time     `json:"updated_at"`
	PushedAt          time.Time     `json:"pushed_at"`
	CreatedAt         time.Time     `json:"created_at"`
	Language          string        `json:"language"`
	ModelFamily       ModelFamily   `json:"model_family"`
	TargetModel       string        `json:"target_model"`
	HardwareTarget    string        `json:"hardware_target"`
	ServingEngine     string        `json:"serving_engine"`
	Quantization      string        `json:"quantization"`
	PerformanceProof  string        `json:"performance_proof"`
	SpecialMechanisms []string      `json:"special_mechanisms"`
	EvidenceGrade     EvidenceGrade `json:"evidence_grade"`
	PerformanceScore  int           `json:"performance_score"`
	UnpopularIndie    bool          `json:"unpopular_indie"`
	FreshnessDays     int           `json:"freshness_days"`
	CohortID          int           `json:"cohort_id,omitempty"`
}

// SearchOptions configures the performance scout execution.
type SearchOptions struct {
	MaxStars      int         // Upper bound for stars (unpopular indie filter)
	MinScore      int         // Minimum performance score to include
	MaxAgeDays    int         // Maximum age since update in days
	FamilyFilter  ModelFamily // Filter for specific family ("" or FamilyUnknown means all)
	LimitPerQuery int         // Limit per query to fetch from GitHub
	Queries       []string    // Override default queries if non-empty
	FixturePath   string      // Offline fixture path
	CohortCount   int         // Number of cohorts to split results into for subagents
	Now           time.Time   // Anchor time for freshness calculations
}

// InventoryReport is the complete output generated by the scout.
type InventoryReport struct {
	GeneratedAt   time.Time            `json:"generated_at"`
	QueriesWalked []string             `json:"queries_walked"`
	TotalFetched  int                  `json:"total_fetched"`
	TotalScored   int                  `json:"total_scored"`
	RetainedCount int                  `json:"retained_count"`
	QwenCount     int                  `json:"qwen_count"`
	GLMCount      int                  `json:"glm_count"`
	DualCount     int                  `json:"dual_count"`
	SearchErrors  []string             `json:"search_errors,omitempty"`
	Cohorts       map[int][]ScoredRepo `json:"cohorts,omitempty"`
	Repositories  []ScoredRepo         `json:"repositories"`
}
