package model

import (
	"context"
	"errors"
	"fmt"
)

// speculative_contract.go — seam-first capability contract isolating speculative
// draft proposers from core KV cache and attention buffers (#10937).
//
// The core architectural invariant:
// Draft proposers (n-gram lookahead, speculative heads, co-resident small models,
// or external endpoints) own their internal draft state and receive only committed token
// IDs. They NEVER touch, borrow, or hold references to core KV cache buffers, attention
// projections, or device state.
//
// Verification is mediated entirely through DraftVerifier (e.g. SessionDraftVerifier wrapping
// Session.VerifyForward), which evaluates linear or tree proposals in a single batched/masked
// forward pass and manages all KV admission, rollback, and correction/bonus token selection.

// DraftProposer is the capability contract for speculative candidate proposers.
// Proposers own their internal state and generate draft candidate sequences
// or trees strictly from committed token history, without direct access to core
// KV cache or attention buffers.
type DraftProposer interface {
	// Propose generates candidate tokens given committed context.
	// Proposer owns its internal draft state and does not touch core KV buffers directly.
	Propose(ctx context.Context, committed []int, maxDraft int) (DraftProposal, error)
}

// DraftProposal encapsulates speculative candidate tokens generated by a DraftProposer.
type DraftProposal struct {
	Tokens   []int          // linear candidate sequence
	Tree     *CandidateTree // optional branch/tree candidates
	Mask     [][]bool       // causal mask for tree attention if Tree != nil
	Metadata map[string]any // proposer provenance, confidence, etc.
}

// CandidateTree represents a tree topology of speculative token candidates.
type CandidateTree struct {
	Nodes []CandidateNode
}

// CandidateNode is a single candidate token node within a CandidateTree.
type CandidateNode struct {
	Token    int
	Parent   int   // index in Nodes, -1 for root
	Children []int // indices in Nodes
	Depth    int
}

// DraftVerifier evaluates proposed candidate tokens against the target model in a single forward pass.
type DraftVerifier interface {
	// Verify evaluates proposed candidate tokens against the target model in a single forward pass.
	Verify(ctx context.Context, committed []int, proposal DraftProposal) (VerificationResult, error)
}

// VerificationResult contains the outcome of a single speculative verification pass.
type VerificationResult struct {
	AcceptedTokens  []int
	CorrectionToken int
	NumAccepted     int
	RollbackKVCount int
	TargetLogits    [][]float32
	// LastAcceptedLogits identifies the final accepted tree node's logits when
	// accepted nodes are not contiguous in TargetLogits panel order.
	LastAcceptedLogits []float32
}

// DeriveMask computes the N x N causal attention mask for the candidate tree.
// mask[j][i] is true iff node i is an ancestor of node j (including self).
func (t *CandidateTree) DeriveMask() ([][]bool, error) {
	if t == nil || len(t.Nodes) == 0 {
		return nil, errors.New("model: candidate tree has no nodes")
	}
	n := len(t.Nodes)
	mask := make([][]bool, n)
	for j := 0; j < n; j++ {
		mask[j] = make([]bool, n)
		mask[j][j] = true
		curr := t.Nodes[j].Parent
		visited := make(map[int]bool)
		visited[j] = true
		for curr != -1 {
			if curr < 0 || curr >= n {
				return nil, fmt.Errorf("model: node %d has invalid parent %d (tree size %d)", j, curr, n)
			}
			if visited[curr] {
				return nil, fmt.Errorf("model: cycle detected in candidate tree at node %d", curr)
			}
			visited[curr] = true
			mask[j][curr] = true
			curr = t.Nodes[curr].Parent
		}
	}
	return mask, nil
}

// Tokens returns the slice of token IDs for all nodes in the tree in index order.
func (t *CandidateTree) Tokens() []int {
	if t == nil || len(t.Nodes) == 0 {
		return nil
	}
	tokens := make([]int, len(t.Nodes))
	for i, node := range t.Nodes {
		tokens[i] = node.Token
	}
	return tokens
}

// BuildCandidateTreeFromBranches constructs a CandidateTree trie from candidate token branches.
// Shared prefix tokens across branches are deduplicated into common ancestor nodes.
func BuildCandidateTreeFromBranches(branches [][]int) (*CandidateTree, error) {
	tree := &CandidateTree{Nodes: make([]CandidateNode, 0)}
	for _, branch := range branches {
		if len(branch) == 0 {
			continue
		}
		currParent := -1
		depth := 0
		for _, tok := range branch {
			matchIdx := -1
			if currParent == -1 {
				for i, node := range tree.Nodes {
					if node.Parent == -1 && node.Token == tok {
						matchIdx = i
						break
					}
				}
			} else {
				for _, childIdx := range tree.Nodes[currParent].Children {
					if childIdx >= 0 && childIdx < len(tree.Nodes) && tree.Nodes[childIdx].Token == tok {
						matchIdx = childIdx
						break
					}
				}
			}

			if matchIdx != -1 {
				currParent = matchIdx
				depth++
			} else {
				newIdx := len(tree.Nodes)
				newNode := CandidateNode{
					Token:    tok,
					Parent:   currParent,
					Children: nil,
					Depth:    depth,
				}
				tree.Nodes = append(tree.Nodes, newNode)
				if currParent != -1 {
					tree.Nodes[currParent].Children = append(tree.Nodes[currParent].Children, newIdx)
				}
				currParent = newIdx
				depth++
			}
		}
	}
	if len(tree.Nodes) == 0 {
		return nil, errors.New("model: cannot build candidate tree from empty branches")
	}
	return tree, nil
}

// NewTreeProposal constructs a DraftProposal from a CandidateTree, automatically deriving its causal mask.
func NewTreeProposal(tree *CandidateTree, metadata map[string]any) (DraftProposal, error) {
	if tree == nil || len(tree.Nodes) == 0 {
		return DraftProposal{}, errors.New("model: cannot create proposal from empty candidate tree")
	}
	mask, err := tree.DeriveMask()
	if err != nil {
		return DraftProposal{}, err
	}
	tokens := tree.Tokens()
	return DraftProposal{
		Tokens:   tokens,
		Tree:     tree,
		Mask:     mask,
		Metadata: metadata,
	}, nil
}

// NewLinearProposal constructs a DraftProposal for a linear sequence of candidate tokens.
func NewLinearProposal(tokens []int, metadata map[string]any) DraftProposal {
	return DraftProposal{
		Tokens:   append([]int(nil), tokens...),
		Metadata: metadata,
	}
}

// NgramDraftProposer adapts an NgramDrafter to the DraftProposer interface.
// It generates speculative candidate proposals strictly from token history with no weights,
// session, or KV cache access.
type NgramDraftProposer struct {
	drafter     NgramDrafter
	treeMode    bool
	maxBranches int
}

// NewNgramDraftProposer constructs a DraftProposer backed by an NgramDrafter.
func NewNgramDraftProposer(drafter NgramDrafter) *NgramDraftProposer {
	return &NgramDraftProposer{drafter: drafter}
}

// WithTree configures the proposer to emit CandidateTree proposals using NgramDrafter.DraftTree.
func (p *NgramDraftProposer) WithTree(maxBranches int) *NgramDraftProposer {
	return &NgramDraftProposer{
		drafter:     p.drafter,
		treeMode:    true,
		maxBranches: maxBranches,
	}
}

// Drafter returns a copy of the underlying NgramDrafter configuration.
func (p *NgramDraftProposer) Drafter() NgramDrafter {
	return p.drafter
}

// Propose generates candidate tokens given committed context without touching KV cache.
func (p *NgramDraftProposer) Propose(ctx context.Context, committed []int, maxDraft int) (DraftProposal, error) {
	if err := ctx.Err(); err != nil {
		return DraftProposal{}, err
	}
	d := p.drafter
	if maxDraft > 0 {
		d.MaxDraft = maxDraft
	}

	metadata := map[string]any{
		"proposer":  "ngram",
		"min_match": d.MinMatch,
		"max_match": d.MaxMatch,
		"max_draft": d.MaxDraft,
	}

	if p.treeMode {
		dt := d.DraftTree(committed, p.maxBranches)
		if dt == nil || len(dt.Branches) == 0 {
			return DraftProposal{
				Tokens:   nil,
				Metadata: metadata,
			}, nil
		}
		tree, err := BuildCandidateTreeFromBranches(dt.Branches)
		if err != nil {
			return DraftProposal{}, fmt.Errorf("model: build candidate tree from ngram: %w", err)
		}
		metadata["match_count"] = dt.MatchCount
		metadata["match_length"] = dt.MatchLength
		return NewTreeProposal(tree, metadata)
	}

	tokens := d.Draft(committed)
	return NewLinearProposal(tokens, metadata), nil
}

// SessionDraftVerifier adapts a model.Session and its VerifyForward engine to DraftVerifier.
// It owns the target verification forward pass, KV rollback, and bonus/correction token selection.
type SessionDraftVerifier struct {
	session      *Session
	lastLogits   []float32
	mockCacheLen int

	// Optional injection hooks for testing without full weights or hardware
	verifyFn  func(ids []int, pos []int, allow func(q, k int) bool) [][]float32
	stepFn    func(tok int) []float32
	prefillFn func(tokens []int) []float32
	evictFn   func(from, n int) int
}

// NewSessionDraftVerifier creates a DraftVerifier backed by a live Session.
func NewSessionDraftVerifier(s *Session) *SessionDraftVerifier {
	return &SessionDraftVerifier{session: s}
}

// NewMockSessionVerifier creates a SessionDraftVerifier with injected verification functions.
func NewMockSessionVerifier(
	lastLogits []float32,
	verifyFn func(ids []int, pos []int, allow func(q, k int) bool) [][]float32,
	stepFn func(tok int) []float32,
	evictFn func(from, n int) int,
) *SessionDraftVerifier {
	return &SessionDraftVerifier{
		lastLogits: append([]float32(nil), lastLogits...),
		verifyFn:   verifyFn,
		stepFn:     stepFn,
		evictFn:    evictFn,
	}
}

// Session returns the underlying Session, or nil if using mock functions.
func (v *SessionDraftVerifier) Session() *Session {
	return v.session
}

// LastLogits returns the current boundary logits.
func (v *SessionDraftVerifier) LastLogits() []float32 {
	return v.lastLogits
}

// SetLastLogits sets the boundary logits before the first verification round.
func (v *SessionDraftVerifier) SetLastLogits(logits []float32) {
	v.lastLogits = append([]float32(nil), logits...)
}

func (v *SessionDraftVerifier) cacheLen() int {
	if v.session != nil && v.session.Cache != nil {
		return v.session.Cache.Len()
	}
	return v.mockCacheLen
}

func (v *SessionDraftVerifier) runPrefill(tokens []int) []float32 {
	if v.prefillFn != nil {
		v.mockCacheLen = len(tokens)
		return v.prefillFn(tokens)
	}
	if v.session != nil {
		return v.session.Prefill(tokens)
	}
	v.mockCacheLen = len(tokens)
	return nil
}

func (v *SessionDraftVerifier) runStep(tok int) []float32 {
	if v.stepFn != nil {
		v.mockCacheLen++
		return v.stepFn(tok)
	}
	if v.session != nil {
		return v.session.Step(tok)
	}
	v.mockCacheLen++
	return nil
}

func (v *SessionDraftVerifier) runVerify(ids []int, pos []int, allow func(q, k int) bool) [][]float32 {
	if v.verifyFn != nil {
		v.mockCacheLen += len(ids)
		return v.verifyFn(ids, pos, allow)
	}
	if v.session != nil {
		return v.session.VerifyForward(ids, pos, allow)
	}
	return nil
}

func (v *SessionDraftVerifier) runEvict(from, n int) int {
	if v.evictFn != nil {
		v.mockCacheLen -= n
		if v.mockCacheLen < 0 {
			v.mockCacheLen = 0
		}
		return v.evictFn(from, n)
	}
	if v.session != nil {
		return v.session.evictKV(from, n)
	}
	v.mockCacheLen -= n
	if v.mockCacheLen < 0 {
		v.mockCacheLen = 0
	}
	return n
}

// Verify evaluates proposed candidate tokens against the target model in a single forward pass.
func (v *SessionDraftVerifier) Verify(ctx context.Context, committed []int, proposal DraftProposal) (VerificationResult, error) {
	if err := ctx.Err(); err != nil {
		return VerificationResult{}, err
	}
	if v == nil || (v.session == nil && v.verifyFn == nil && len(v.lastLogits) == 0) {
		return VerificationResult{}, errors.New("model: draft verifier has no session or verify function")
	}
	if len(committed) == 0 {
		return VerificationResult{}, errors.New("model: committed context cannot be empty")
	}

	// Synchronize session KV cache with committed context if needed.
	if v.session != nil {
		cLen := v.session.Cache.Len()
		if cLen == 0 {
			v.lastLogits = v.runPrefill(committed)
		} else if cLen < len(committed) {
			for _, tok := range committed[cLen:] {
				v.lastLogits = v.runStep(tok)
			}
		} else if cLen > len(committed) {
			v.session.evictKV(len(committed), cLen-len(committed))
		}

		if len(v.lastLogits) == 0 && len(committed) > 0 {
			v.session.evictKV(len(committed)-1, 1)
			v.lastLogits = v.session.Step(committed[len(committed)-1])
		}
	} else {
		// Mock session mode: retain boundary lastLogits if already provided
		if len(v.lastLogits) == 0 {
			if v.prefillFn != nil {
				v.lastLogits = v.runPrefill(committed)
			} else if v.stepFn != nil && len(committed) > 0 {
				v.lastLogits = v.runStep(committed[len(committed)-1])
			}
		}
		if v.mockCacheLen == 0 {
			v.mockCacheLen = len(committed)
		}
	}

	if len(v.lastLogits) == 0 {
		return VerificationResult{}, errors.New("model: failed to obtain target boundary logits")
	}

	if proposal.Tree != nil && len(proposal.Tree.Nodes) > 0 {
		return v.verifyTree(proposal)
	}
	return v.verifyLinear(proposal)
}

func (v *SessionDraftVerifier) verifyLinear(proposal DraftProposal) (VerificationResult, error) {
	draft := proposal.Tokens
	if len(draft) == 0 {
		correction := argmaxF32(v.lastLogits)
		return VerificationResult{
			AcceptedTokens:  nil,
			CorrectionToken: correction,
			NumAccepted:     0,
			RollbackKVCount: 0,
			TargetLogits:    nil,
		}, nil
	}

	tBase := v.cacheLen()
	rows := v.runVerify(draft, nil, nil)
	if len(rows) != len(draft) {
		return VerificationResult{}, fmt.Errorf("model: verify forward returned %d rows for %d draft tokens", len(rows), len(draft))
	}

	targetArgmax := make([]int, len(draft)+1)
	targetArgmax[0] = argmaxF32(v.lastLogits)
	for i, row := range rows {
		if len(row) == 0 {
			return VerificationResult{}, fmt.Errorf("model: empty logits row at draft position %d", i)
		}
		targetArgmax[i+1] = argmaxF32(row)
	}

	accepted := 0
	for accepted < len(draft) && draft[accepted] == targetArgmax[accepted] {
		accepted++
	}

	correctionToken := targetArgmax[accepted]
	rollbackCount := len(draft) - accepted
	if rollbackCount > 0 {
		v.runEvict(tBase+accepted, rollbackCount)
	}

	if accepted > 0 {
		v.lastLogits = rows[accepted-1]
	}

	var acceptedTokens []int
	if accepted > 0 {
		acceptedTokens = append([]int(nil), draft[:accepted]...)
	}

	return VerificationResult{
		AcceptedTokens:  acceptedTokens,
		CorrectionToken: correctionToken,
		NumAccepted:     accepted,
		RollbackKVCount: rollbackCount,
		TargetLogits:    rows,
	}, nil
}

func (v *SessionDraftVerifier) verifyTree(proposal DraftProposal) (VerificationResult, error) {
	tree := proposal.Tree
	N := len(tree.Nodes)
	ids := proposal.Tokens
	if len(ids) != N {
		ids = tree.Tokens()
	}

	tBase := v.cacheLen()
	pos := make([]int, N)
	for i, node := range tree.Nodes {
		pos[i] = tBase + node.Depth
	}

	mask := proposal.Mask
	if mask == nil || len(mask) != N {
		var err error
		mask, err = tree.DeriveMask()
		if err != nil {
			return VerificationResult{}, fmt.Errorf("model: derive tree causal mask: %w", err)
		}
	}

	allow := func(q, k int) bool {
		if q >= 0 && q < len(mask) && k >= 0 && k < len(mask[q]) {
			return mask[q][k]
		}
		return false
	}

	rows := v.runVerify(ids, pos, allow)
	if len(rows) != N {
		return VerificationResult{}, fmt.Errorf("model: verify forward returned %d rows for %d tree nodes", len(rows), N)
	}

	rootExpected := argmaxF32(v.lastLogits)
	matchRoot := -1
	for i, node := range tree.Nodes {
		if node.Parent == -1 && node.Token == rootExpected {
			matchRoot = i
			break
		}
	}

	if matchRoot == -1 {
		v.runEvict(tBase, N)
		return VerificationResult{
			AcceptedTokens:  nil,
			CorrectionToken: rootExpected,
			NumAccepted:     0,
			RollbackKVCount: N,
			TargetLogits:    rows,
		}, nil
	}

	acceptedIndices := []int{matchRoot}
	cur := matchRoot
	pred := argmaxF32(rows[cur])
	for {
		nextChild := -1
		for _, childIdx := range tree.Nodes[cur].Children {
			if childIdx >= 0 && childIdx < N && tree.Nodes[childIdx].Token == pred {
				nextChild = childIdx
				break
			}
		}
		if nextChild == -1 {
			break
		}
		acceptedIndices = append(acceptedIndices, nextChild)
		cur = nextChild
		pred = argmaxF32(rows[cur])
	}

	acceptedTokens := make([]int, len(acceptedIndices))
	for i, idx := range acceptedIndices {
		acceptedTokens[i] = tree.Nodes[idx].Token
	}

	v.runEvict(tBase, N)
	for _, tok := range acceptedTokens {
		v.runStep(tok)
	}
	if len(acceptedIndices) > 0 {
		v.lastLogits = rows[cur]
	}

	return VerificationResult{
		AcceptedTokens:  acceptedTokens,
		CorrectionToken: pred,
		NumAccepted:     len(acceptedTokens),
		RollbackKVCount: N - len(acceptedTokens),
		TargetLogits:    rows,
	}, nil
}

// MockDraftProposer provides a mock implementation of DraftProposer for testing.
type MockDraftProposer struct {
	ProposeFunc func(ctx context.Context, committed []int, maxDraft int) (DraftProposal, error)
	Calls       [][]int
}

// Propose records the call and invokes ProposeFunc if provided.
func (m *MockDraftProposer) Propose(ctx context.Context, committed []int, maxDraft int) (DraftProposal, error) {
	m.Calls = append(m.Calls, append([]int(nil), committed...))
	if m.ProposeFunc != nil {
		return m.ProposeFunc(ctx, committed, maxDraft)
	}
	return DraftProposal{}, nil
}

// MockDraftVerifier provides a mock implementation of DraftVerifier for testing.
type MockDraftVerifier struct {
	VerifyFunc func(ctx context.Context, committed []int, proposal DraftProposal) (VerificationResult, error)
	Calls      []DraftProposal
}

// Verify records the proposal and invokes VerifyFunc if provided.
func (m *MockDraftVerifier) Verify(ctx context.Context, committed []int, proposal DraftProposal) (VerificationResult, error) {
	m.Calls = append(m.Calls, proposal)
	if m.VerifyFunc != nil {
		return m.VerifyFunc(ctx, committed, proposal)
	}
	return VerificationResult{}, nil
}
