package model

// v41_compress_index_test.go - the pinned-vector arm for the UNMASKED (no
// source-candidate) top-k row selection of the DeepSeek V4.1 lightning indexer
// (fak#13168).
//
// Why this file exists. The sibling arm in v41_compress_index_ref_test.go
// exercises V41SelectIndexRows only through a candidate MASK: its selection
// controls all pass a non-nil mask and use topK=1, so the unmasked branch
// (candidates == nil), the topK-shorter-than-visible branch, and the
// tie-break branch could all be broken and the suite would still be green. This
// file closes that hole with a dedicated pinned vector for the unmasked arm,
// generated by an independent transcription of the reference selection
// equation.
//
// Resolved semantics (full note:
// testdata/v41_oracle/SELECTION_REFERENCE_PROVENANCE.md). With no source mask,
// the final top-k is SCORE-RANKED over the causal-visible positions:
//
//	1. a position is causal-visible iff position < compressLen;
//	2. EVERY logits position is ranked, with masked-out and causal-invisible
//	   positions ranked as -Inf so they sink to the tail of the descending-score
//	   sort;
//	3. among visible positions, an exact score tie keeps the LOWER position;
//	4. the top min(topK, len(logits)) are kept and re-sorted by position
//	   ascending, then shifted by offset;
//	5. the -1 slots are NOT a fixed end-pad. The result is re-sorted by
//	   position, so a -1 occupies the position-order slot of whichever selection
//	   was causal-invisible or masked-out. -Inf ranking sends invisible
//	   positions to the tail of the SCORE sort, so they leave the kept set only
//	   after the visible ones: a -1 lands after the visible rows when the
//	   invisible positions are the higher indices (e.g. the unmasked
//	   [11 12 13 14 15 -1]), and before them when the invisible positions are
//	   the lower indices (e.g. the masked [-1 -1 22]).
//
// This is the definition the pinned reference equations encode and the one
// production V41SelectIndexRows implements. It is NOT a "latest-window" /
// positional selection. An expectation that the unmasked arm should return a
// contiguous run of the highest indices (e.g. [11 12 13 14 15 16] at
// compressLen=5, offset=11) is impossible by construction: the int32 row
// encoding is bounded by offset+(compressLen-1) = 15, and any position at or
// beyond compressLen is causal-invisible. The fixture records the score-ranked
// semantics, plus the disproven positional reading as an explicit
// discrimination witness, so a future reader cannot re-drift.

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

const (
	v41SelectionRefPath   = "testdata/v41_oracle/selection_reference.json"
	v41SelectionRefSchema = "fak-v41-oracle-selection-reference/1"
	v41SelectionRefRung   = "HAND-DERIVED-FROM-REFERENCE-EQUATIONS"
)

// v41SelectionRefCase is one pinned-vector case: the exact arguments to
// V41SelectIndexRows, the rows an independent execution of the reference
// selection equation produces for them, and the rows the disproven positional
// reading would produce.
type v41SelectionRefCase struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Arm         string    `json:"arm"`
	Logits      []float32 `json:"logits"`
	CompressLen int       `json:"compress_len"`
	TopK        int       `json:"top_k"`
	Offset      int       `json:"offset"`
	// Candidates is the optional source-candidate mask. It is a pointer so JSON
	// null (the unmasked arm under test) is distinguishable from an all-false
	// mask.
	Candidates *[]bool `json:"candidates"`
	Rows       []int32 `json:"rows"`
	NaiveRows  []int32 `json:"naive_positional_rows"`
}

// v41SelectionRefFixture is the checked-in pinned-vector fixture for the
// selection arm.
type v41SelectionRefFixture struct {
	Schema    string                `json:"schema"`
	Rung      string                `json:"rung"`
	Revision  string                `json:"revision"`
	Semantics string                `json:"semantics"`
	Cases     []v41SelectionRefCase `json:"cases"`
}

// v41SelectionRefRowsExec executes the reference final row selection from the
// equation text, reusing nothing from production. It is the independent
// transcription the fixture bytes are generated from, so a correlated mis-read
// of the equation shared with the production port cannot pass silently.
func v41SelectionRefRowsExec(logits []float32, compressLen, topK, offset int, candidates []bool) []int32 {
	type ranked struct {
		pos     int
		score   float64
		visible bool
	}
	rows := make([]ranked, 0, len(logits))
	for t := 0; t < len(logits); t++ {
		vis := t < compressLen && (candidates == nil || candidates[t])
		score := float64(logits[t])
		if !vis {
			score = math.Inf(-1)
		}
		rows = append(rows, ranked{pos: t, score: score, visible: vis})
	}
	// Descending score; an exact tie keeps the LOWER position first.
	for i := 1; i < len(rows); i++ {
		for j := i; j > 0; j-- {
			better := rows[j].score > rows[j-1].score ||
				(rows[j].score == rows[j-1].score && rows[j].pos < rows[j-1].pos)
			if !better {
				break
			}
			rows[j], rows[j-1] = rows[j-1], rows[j]
		}
	}
	keep := topK
	if keep > len(rows) {
		keep = len(rows)
	}
	rows = rows[:keep]
	// Return the chosen rows in position order.
	for i := 1; i < len(rows); i++ {
		for j := i; j > 0 && rows[j].pos < rows[j-1].pos; j-- {
			rows[j], rows[j-1] = rows[j-1], rows[j]
		}
	}
	out := make([]int32, 0, keep)
	for _, r := range rows {
		if !r.visible {
			out = append(out, -1)
			continue
		}
		out = append(out, int32(r.pos+offset))
	}
	return out
}

// v41SelectionRefNaiveRows is the DISPROVEN positional/latest-window reading:
// take the top-k highest indices and return them as a contiguous run, padding
// with -1 when the window underflows. It is carried in the fixture only as an
// explicit non-vacuity witness: at least one case must DIFFER from it, which is
// what proves the vector constrains the selection rule rather than restating an
// arithmetic identity.
func v41SelectionRefNaiveRows(compressLen, topK, offset int) []int32 {
	out := make([]int32, 0, topK)
	start := compressLen - topK
	if start < 0 {
		start = 0
	}
	for i := 0; i < topK; i++ {
		pos := start + i
		if pos >= compressLen {
			out = append(out, -1)
			continue
		}
		out = append(out, int32(pos+offset))
	}
	return out
}

func v41SelectionRefMask(c v41SelectionRefCase) []bool {
	if c.Candidates == nil {
		return nil
	}
	return *c.Candidates
}

// TestV41SelectionReferenceVector pins production V41SelectIndexRows against a
// fixture whose expected rows were produced by executing the reference
// selection equation independently. The score-ranked cases and the control keep
// the arm non-vacuous: their expected rows differ from the disproven positional
// run, so a positional implementation fails here.
func TestV41SelectionReferenceVector(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join(v41SelectionRefPath))
	if err != nil {
		t.Fatalf("read selection reference fixture: %v", err)
	}
	var want v41SelectionRefFixture
	if err := json.Unmarshal(raw, &want); err != nil {
		t.Fatalf("decode selection reference fixture: %v", err)
	}
	if want.Schema != v41SelectionRefSchema {
		t.Fatalf("fixture schema %q, want %q", want.Schema, v41SelectionRefSchema)
	}
	if want.Rung != v41SelectionRefRung {
		t.Fatalf("fixture rung %q, want %q", want.Rung, v41SelectionRefRung)
	}
	if want.Revision != v41OracleRevision {
		t.Fatalf("fixture revision %q, want pinned %q", want.Revision, v41OracleRevision)
	}
	if len(want.Cases) < 3 {
		t.Fatalf("fixture carries %d cases, want >= 3 (unmasked, tie, control)", len(want.Cases))
	}

	// Re-execute the independent transcription: the checked-in bytes must be
	// exactly what the pinned equation produces now. This makes a stale or
	// hand-edited fixture a failure rather than a silently-relaxed assertion.
	for _, c := range want.Cases {
		got := v41SelectionRefRowsExec(c.Logits, c.CompressLen, c.TopK, c.Offset, v41SelectionRefMask(c))
		if !v41RefRowsEqual(got, c.Rows) {
			t.Fatalf("case %q: fixture rows %v are stale; the reference equation now yields %v",
				c.Name, c.Rows, got)
		}
		naive := v41SelectionRefNaiveRows(c.CompressLen, c.TopK, c.Offset)
		if !v41RefRowsEqual(naive, c.NaiveRows) {
			t.Fatalf("case %q: recorded positional rows %v are stale, want %v",
				c.Name, c.NaiveRows, naive)
		}
	}

	// Non-vacuity: at least two cases must have expected rows that DIFFER from
	// the disproven positional run, or the vector would not discriminate the two
	// candidate definitions at all.
	discriminating := 0
	for _, c := range want.Cases {
		if !v41RefRowsEqual(c.Rows, c.NaiveRows) {
			discriminating++
		}
	}
	if discriminating < 2 {
		t.Fatalf("only %d cases disagree with the positional run; the vector is vacuous", discriminating)
	}

	for _, c := range want.Cases {
		c := c
		t.Run(c.Name, func(t *testing.T) {
			rows, err := V41SelectIndexRows(c.Logits, c.CompressLen, c.TopK, c.Offset, v41SelectionRefMask(c))
			if err != nil {
				t.Fatalf("V41SelectIndexRows: %v", err)
			}
			if !reflect.DeepEqual(rows, c.Rows) {
				t.Fatalf("rows = %v, want fixture %v", rows, c.Rows)
			}
		})
	}

	// The unmasked arm must be exercised at all: a fixture that only carried
	// masked cases would leave the branch under test uncovered. At least one
	// unmasked case must ALSO discriminate the score-ranked rule from the
	// disproven positional run, or the vector would pin an arithmetic identity
	// instead of the selection rule.
	t.Run("unmasked_arm_is_covered_and_non_vacuous", func(t *testing.T) {
		unmasked, unmaskedDiscriminating := 0, 0
		for _, c := range want.Cases {
			if c.Candidates != nil {
				continue
			}
			unmasked++
			rows, err := V41SelectIndexRows(c.Logits, c.CompressLen, c.TopK, c.Offset, nil)
			if err != nil {
				t.Fatal(err)
			}
			if !reflect.DeepEqual(rows, c.Rows) {
				t.Fatalf("case %q unmasked rows = %v, want %v", c.Name, rows, c.Rows)
			}
			if !v41RefRowsEqual(rows, c.NaiveRows) {
				unmaskedDiscriminating++
			}
		}
		if unmasked < 2 {
			t.Fatalf("fixture carries %d unmasked cases, want >= 2", unmasked)
		}
		if unmaskedDiscriminating == 0 {
			t.Fatal("no unmasked case disagrees with the positional run; the vector is vacuous")
		}
	})

	// The masked arm's expected rows must also be independently derived, not
	// read back from production: assert the cached mask path agrees with the
	// reference transcription for every masked case.
	t.Run("masked_arm_matches_reference_transcription", func(t *testing.T) {
		masked := 0
		for _, c := range want.Cases {
			if c.Candidates == nil {
				continue
			}
			masked++
			rows, err := V41SelectIndexRows(c.Logits, c.CompressLen, c.TopK, c.Offset, *c.Candidates)
			if err != nil {
				t.Fatal(err)
			}
			ref := v41SelectionRefRowsExec(c.Logits, c.CompressLen, c.TopK, c.Offset, *c.Candidates)
			if !reflect.DeepEqual(rows, ref) {
				t.Fatalf("case %q masked rows = %v, reference transcription %v", c.Name, rows, ref)
			}
		}
		if masked < 1 {
			t.Fatal("fixture carries no masked case")
		}
	})

	// A -1 slot is not a fixed end-pad: it occupies the position-order slot of
	// the invisible selection. At least one case must place a -1 BEFORE a visible
	// row, which a fixed end-pad implementation cannot do.
	t.Run("negative_one_pad_placement_is_not_a_fixed_end_pad", func(t *testing.T) {
		padBefore := 0
		for _, c := range want.Cases {
			seenVisible := false
			for _, r := range c.Rows {
				if r == -1 && !seenVisible {
					padBefore++
					break
				}
				if r != -1 {
					seenVisible = true
				}
			}
		}
		if padBefore == 0 {
			t.Fatal("no case places a -1 before a visible row; a fixed end-pad implementation would pass")
		}
	})
}
