package devindex

// usageref.go - C3 of epic #1287 (issue #1290): generate the runtime `fak` help
// surface FROM the structured verb catalog, so the verb list a user sees and the
// verb list the binary dispatches can never drift apart.
//
// The original issue asked to "generate usage.go from the manifest". The
// architecture since then (see verbs.go) makes the catalog a LIVE VIEW derived
// from cmd/fak/main.go's dispatch switch, with the curated verbManifest as a
// quality overlay. So the honest completion is not to rewrite the deep usage wall
// (its per-verb flag paragraphs are authored depth, not derivable from a one-line
// synopsis) but to generate the MEMBERSHIP+SYNOPSIS index that runtime `fak help
// --all` prints: one row per live verb, sorted, carrying the curated synopsis
// when there is one and an explicit "not yet cataloged" placeholder when there is
// not. That index is a plain `package main` data literal, so runtime help keeps
// its deliberate no-devindex-import boundary (help.go).
//
// Regenerate with `fak-dev index verbs --write-usage`. A stale committed
// artifact is a deterministic test failure (cmd/fak/verbs_usage_test.go).

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
)

// VerbUsagePath is the generated runtime artifact, relative to the repo root. It
// lives in package main (cmd/fak) because runtime help must not import
// internal/devindex; the generator writes a self-contained data literal.
const VerbUsagePath = "cmd/fak/verbs_gen.go"

// RenderVerbUsage renders the generated `cmd/fak/verbs_gen.go`: the live verb
// catalog (membership + synopsis + aliases + tier) as a plain package-main data
// slice, sorted by name for a stable diff. Regenerating it is deterministic for a
// given tree, so a stale file is a byte mismatch the drift gate catches.
func RenderVerbUsage(root string) ([]byte, error) {
	cat, err := Load(root)
	if err != nil {
		return nil, err
	}
	verbs := cat.Verbs()
	var buf bytes.Buffer
	buf.WriteString("// Code generated by `fak-dev index verbs --write-usage`; DO NOT EDIT.\n")
	buf.WriteString("//\n")
	buf.WriteString("// This is the runtime `fak` verb index: one row per verb the binary actually\n")
	buf.WriteString("// dispatches, with the curated synopsis/aliases/tier. `fak help --all` prints it;\n")
	buf.WriteString("// a stale copy is a test failure (verbs_usage_test.go). Regenerate:\n")
	buf.WriteString("//   fak-dev index verbs --write-usage\n\n")
	buf.WriteString("package main\n\n")
	buf.WriteString("// generatedVerb is one row of the runtime verb index. It is a local mirror of\n")
	buf.WriteString("// the devindex catalog shape so cmd/fak need not import internal/devindex.\n")
	buf.WriteString("type generatedVerb struct {\n")
	buf.WriteString("\tName     string\n")
	buf.WriteString("\tSynopsis string\n")
	buf.WriteString("\tAliases  []string\n")
	buf.WriteString("\tTier     string\n")
	buf.WriteString("}\n\n")
	buf.WriteString("var generatedVerbIndex = []generatedVerb{\n")
	for _, v := range verbs {
		fmt.Fprintf(&buf, "\t{Name: %q, Synopsis: %q,", v.Name, v.Synopsis)
		if len(v.Aliases) != 0 {
			buf.WriteString(" Aliases: []string{")
			for i, a := range v.Aliases {
				if i != 0 {
					buf.WriteString(", ")
				}
				fmt.Fprintf(&buf, "%q", a)
			}
			buf.WriteString("},")
		}
		fmt.Fprintf(&buf, " Tier: %q},\n", string(v.Tier))
	}
	buf.WriteString("}\n")
	return format.Source(buf.Bytes())
}

// WriteVerbUsage regenerates cmd/fak/verbs_gen.go under root.
func WriteVerbUsage(root string) error {
	data, err := RenderVerbUsage(root)
	if err != nil {
		return err
	}
	path := filepath.Join(root, filepath.FromSlash(VerbUsagePath))
	return os.WriteFile(path, data, 0o644)
}
