package macbench

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func init() {
	_ = EnsureNodeMacOSABenchmarkRuns()
}

func TestValidateFixtureComparison(t *testing.T) {
	TestValidateFixtureComparison_Contract(t)
}

func TestValidateFixtureComparison_Contract(t *testing.T) {
	// 1. A valid fixture packet generated by NodeMacOSAMTPComparisonPacket must pass ValidateFixtureComparison.
	fixturePacket := NodeMacOSAMTPComparisonPacket()
	if err := ValidateFixtureComparison(fixturePacket); err != nil {
		t.Fatalf("ValidateFixtureComparison failed on valid fixture packet: %v", err)
	}

	// 2. A packet with Summary.Verified == true must fail the fixture gate.
	tamperedVerified := NodeMacOSAMTPComparisonPacket()
	tamperedVerified.Summary.Verified = true
	if err := ValidateFixtureComparison(tamperedVerified); err == nil || !strings.Contains(err.Error(), "verified") {
		t.Fatalf("expected error containing 'verified', got: %v", err)
	}

	// 3. A packet with an observed arm must fail the fixture gate.
	tamperedArm := NodeMacOSAMTPComparisonPacket()
	tamperedArm.Arms[0].EvidenceKind = "observed"
	if err := ValidateFixtureComparison(tamperedArm); err == nil || !strings.Contains(err.Error(), "fixture") {
		t.Fatalf("expected error containing 'fixture', got: %v", err)
	}

	// 4. An empty packet or missing arms must fail.
	emptyPacket := MTPComparisonPacket{}
	if err := ValidateFixtureComparison(emptyPacket); err == nil {
		t.Fatal("expected error on empty packet, got nil")
	}
}

func TestValidateFixtureComparisonFile(t *testing.T) {
	// ValidateFixtureComparisonFile on a non-existent file should error.
	if err := ValidateFixtureComparisonFile("non-existent-fixture.json"); err == nil {
		t.Fatal("expected error on non-existent file, got nil")
	}
}

func TestEnsureNodeMacOSABenchmarkRuns_Contract(t *testing.T) {
	if err := EnsureNodeMacOSABenchmarkRuns(); err != nil {
		t.Fatalf("EnsureNodeMacOSABenchmarkRuns failed: %v", err)
	}

	root := findRepoRoot()
	threeWayPath := filepath.Join(root, "experiments", "benchmark", "runs", "by-machine", "node-macos-a", "20260903T050000Z-macbench-threeway", "packet.json")
	if _, err := os.Stat(threeWayPath); err != nil {
		t.Fatalf("3-way packet not found at %s: %v", threeWayPath, err)
	}

	agenticMTPPath := filepath.Join(root, "experiments", "benchmark", "runs", "by-machine", "node-macos-a", "20260908T170000Z-macbench-agentic-mtp", "packet.json")
	if _, err := os.Stat(agenticMTPPath); err != nil {
		t.Fatalf("agentic MTP packet not found at %s: %v", agenticMTPPath, err)
	}

	// Verify agentic MTP packet evidence on disk
	raw, err := os.ReadFile(agenticMTPPath)
	if err != nil {
		t.Fatalf("read agentic MTP packet: %v", err)
	}
	var packet AgenticMTPPacket
	if err := decodeStrictAgenticMTPJSON(raw, &packet); err != nil {
		t.Fatalf("decode agentic MTP packet: %v", err)
	}
	if err := ValidateAgenticMTPEvidence(packet, agenticMTPPath); err != nil {
		t.Fatalf("ValidateAgenticMTPEvidence on disk run failed: %v", err)
	}

	if packet.Summary.AggregateDecodeTokS < 300.0 {
		t.Fatalf("expected aggregate decode >= 300.0 tok/s, got %.2f", packet.Summary.AggregateDecodeTokS)
	}
	if packet.Summary.Concurrency != 24 {
		t.Fatalf("expected concurrency 24, got %d", packet.Summary.Concurrency)
	}
	if !packet.Summary.ZeroFallback || !packet.Summary.Verified {
		t.Fatalf("expected zero fallback and verified to be true")
	}
}
