package scorecard

import (
	"fmt"
	"strings"
)

// The shared renderers, so a card prints its terminal work-list, its committed markdown
// snapshot, and its --compare line without re-copying the format strings. Each mirrors the
// Python render()/markdown()/compare shapes (conflation_scorecard.py:261/277/335).

// Render is the terminal work-list: a header line, the finding, then one line per KPI with
// a HARD(!!)/soft(~)/ok marker and its defects + soft signals indented under it.
//
// debtKey names the corpus debt integer to print in the header (e.g. "conflation_debt").
func Render(p Payload, debtKey string) string {
	c := p.Corpus
	out := []string{
		fmt.Sprintf("%s: %v (score %v, %s %v)", scorecardName(p.Schema), c["grade"], c["score"], debtKey, c[debtKey]),
		"  " + p.Finding,
		"",
	}
	for _, k := range p.KPIs {
		mark := "ok "
		if len(k.Defects) > 0 {
			mark = "!! "
		} else if len(k.Soft) > 0 {
			mark = "~  "
		}
		out = append(out, fmt.Sprintf("  %s%-22s %5.1f  %s", mark, k.Key, k.Score, k.Detail))
		for _, d := range k.Defects {
			out = append(out, "       HARD  "+d)
		}
		for _, s := range k.Soft {
			out = append(out, "       soft  "+s)
		}
	}
	out = append(out, "", "  next: "+p.NextAction)
	return strings.Join(out, "\n")
}

// MarkdownDoc carries the per-card prose for a committed snapshot. A card fills it once;
// the kernel renders the Jekyll front-matter + body identically for every card.
type MarkdownDoc struct {
	Title       string // front-matter title: (the SEO/AEO card reads this)
	Description string // front-matter description:
	Heading     string // the H1
	AutoGen     string // optional italic "_Auto-generated by ..._" note under the H1
	Law         string // optional one-paragraph statement of the card's law
	DebtKey     string // the corpus debt integer to name in the header line
	HeaderExtra string // optional already-formatted tail on the header (e.g. "- 2 surface(s)")
}

// Markdown is the committed snapshot body: a Jekyll front-matter block (so the published
// page carries a <title> + meta description the SEO/AEO card requires) followed by a KPI
// table and a HARD work-list. The front-matter block is the one the Python cards copy-paste
// (conflation_scorecard.py:283); centralizing it is a real de-duplication win.
func Markdown(p Payload, d MarkdownDoc) string {
	c := p.Corpus
	lines := []string{
		"---",
		`title: "` + d.Title + `"`,
		`description: "` + d.Description + `"`,
		"---",
		"",
		"# " + d.Heading,
		"",
	}
	if d.AutoGen != "" {
		lines = append(lines, "_"+d.AutoGen+"_", "")
	}
	lines = append(lines,
		fmt.Sprintf("**Grade %v** - score %v - %s **%v**%s", c["grade"], c["score"], d.DebtKey, c[d.DebtKey], d.HeaderExtra),
		"",
	)
	if d.Law != "" {
		lines = append(lines, d.Law, "")
	}
	lines = append(lines,
		"| KPI | score | detail |",
		"|---|---|---|",
	)
	for _, k := range p.KPIs {
		lines = append(lines, fmt.Sprintf("| %s | %.0f | %s |", k.Key, k.Score, k.Detail))
	}
	var work []string
	for _, k := range p.KPIs {
		work = append(work, k.Defects...)
	}
	if len(work) > 0 {
		lines = append(lines, "", "## Work list (HARD)", "")
		for _, d := range work {
			lines = append(lines, "- "+d)
		}
	}
	return strings.Join(lines, "\n") + "\n"
}

// Compare prints the debt-delta line vs a prior --json payload's corpus. It mirrors the
// Python compare tail: "debt P -> C (improved|regressed|flat by k)"
// (conflation_scorecard.py:335). baseline is the decoded prior payload (the whole object or
// its corpus); debtKey is the integer to diff.
func Compare(p Payload, baseline map[string]any, debtKey string) string {
	bc, _ := baseline["corpus"].(map[string]any)
	if bc == nil {
		bc = baseline
	}
	cur := anyInt(p.Corpus[debtKey])
	prior, have := bc[debtKey]
	body := Render(p, debtKey)
	if !have {
		return body
	}
	pd := anyInt(prior)
	delta := cur - pd
	verdict := "flat"
	if delta < 0 {
		verdict = "improved"
	} else if delta > 0 {
		verdict = "regressed"
	}
	abs := delta
	if abs < 0 {
		abs = -abs
	}
	return body + fmt.Sprintf("\n\n  compare: %s %d -> %d (%s by %d)", debtKey, pd, cur, verdict, abs)
}

// scorecardName turns a schema like "fak-conflation-scorecard/1" into "conflation scorecard"
// for the Render header, matching the Python header prose.
func scorecardName(schema string) string {
	s := strings.TrimPrefix(schema, "fak-")
	if i := strings.LastIndex(s, "/"); i >= 0 {
		s = s[:i]
	}
	return strings.ReplaceAll(s, "-", " ")
}
