package workflowaudit

import (
	"fmt"
	"sort"
	"strings"
)

// The committed audit report doc and its generated-block markers. The block between the
// markers is rendered deterministically from a Report by Block(); --write-doc splices it
// in place and --check-doc reds the trunk when it drifts from the live workflows.
const (
	// DocRel is the committed report path, repo-relative (slash form).
	DocRel = "docs/ci/workflow-branch-audit.md"
	// Begin and End bound the generated block inside DocRel.
	Begin = "<!-- BEGIN workflow-branch-audit (generated by `fak workflow-audit --write-doc`; do not hand-edit) -->"
	End   = "<!-- END workflow-branch-audit -->"
)

const docLegend = "Generated from `.github/workflows/*.yml` and classified by `internal/workflowaudit` against the " +
	"branch-role contract in `dos.toml [branch_roles]` (read via `internal/branchrole`) -- not hand-typed. Every " +
	"branch and tag reference in every workflow is folded onto one closed class so the dev/main front-door " +
	"migration (#1697/#1701) has a checkable map of what each branch filter is FOR. The distribution is WITNESSED " +
	"from the tree, never self-reported. A development-path reference that names no configured role and is not an " +
	"intentional allowlisted legacy/compat arm renders as `unclassified` -- and reds " +
	"`go test ./internal/workflowaudit` (the regression gate). Regenerate with `fak workflow-audit --write-doc`.\n\n"

// Block renders the generated audit block (markers inclusive) deterministically from rep.
// The per-class distribution and the per-file reference table change as a diff when a
// workflow's branch filters change, so the committed doc tracks the front-door contract.
func Block(rep Report) string {
	var b strings.Builder
	b.WriteString(Begin)
	b.WriteString("\n\n")

	verdict := "ALL CLASSIFIED"
	if !rep.Clean() {
		verdict = fmt.Sprintf("%d UNCLASSIFIED", len(rep.Unclassified))
	}
	fmt.Fprintf(&b, "**Verdict: %s** -- %d reference(s) across %d workflow file(s); roles: development=%s release=%s source=%s front-door=%s\n\n",
		verdict, len(rep.Refs), rep.Files,
		dashIfEmpty(rep.Roles.DevelopmentBranch), dashIfEmpty(rep.Roles.ReleaseBranch),
		dashIfEmpty(rep.Roles.ReleaseSource), dashIfEmpty(rep.Roles.PublicFrontDoor))
	b.WriteString(docLegend)

	// Class distribution, one row per class in stable render order so an absent class is
	// an explicit 0, not a gap.
	b.WriteString("| Class | Meaning | References |\n|---|---|---|\n")
	for _, c := range renderOrder {
		fmt.Fprintf(&b, "| %s | %s | %d |\n", c, classMeaning(c), rep.ByClass[c])
	}
	b.WriteString("\n")

	// The full per-reference table, already sorted by (file, line) in Audit.
	b.WriteString("| Workflow | Line | Kind | Ref | Class |\n|---|---|---|---|---|\n")
	for _, r := range rep.Refs {
		fmt.Fprintf(&b, "| %s | %d | %s | `%s` | %s |\n", r.File, r.Line, r.Kind, r.Raw, r.Class)
	}
	b.WriteString("\n")

	// The unclassified call-out: empty renders an explicit clean line.
	if len(rep.Unclassified) > 0 {
		b.WriteString("Unclassified development-path references (the gate fails on these):\n\n")
		refs := append([]Ref(nil), rep.Unclassified...)
		sort.SliceStable(refs, func(i, j int) bool {
			if refs[i].File != refs[j].File {
				return refs[i].File < refs[j].File
			}
			return refs[i].Line < refs[j].Line
		})
		for _, r := range refs {
			fmt.Fprintf(&b, "- `%s:%d` %s `%s`\n", r.File, r.Line, r.Kind, r.Raw)
		}
		b.WriteString("\n")
	} else {
		b.WriteString("Unclassified development-path references: none -- every reference is a configured role, a tag, or an intentional allowlisted legacy arm.\n\n")
	}

	b.WriteString(End)
	return b.String()
}

func classMeaning(c RefClass) string {
	switch c {
	case ClassDevelopment:
		return "push/PR branch filter on a configured development branch"
	case ClassReleaseFrontDoor:
		return "if-gate that runs a job only on the release / public front-door branch"
	case ClassTag:
		return "tags: filter -- the tag-driven release surface"
	case ClassLegacy:
		return "intentional compat / hidden-baseline reference (allowlisted)"
	case ClassUnclassified:
		return "development-path ref matching no role and not allowlisted -- gate fails"
	default:
		return string(c)
	}
}

func dashIfEmpty(s string) string {
	if strings.TrimSpace(s) == "" {
		return "-"
	}
	return s
}

// Extract returns the generated block (markers inclusive) embedded in doc, or ("", false)
// when the two markers are not both present in order.
func Extract(doc string) (string, bool) {
	i := strings.Index(doc, Begin)
	if i < 0 {
		return "", false
	}
	j := strings.Index(doc[i:], End)
	if j < 0 {
		return "", false
	}
	return doc[i : i+j+len(End)], true
}

// Splice replaces the block between the markers in doc with a freshly rendered Block(rep)
// and returns the new doc. It errors when the markers are absent so the generator never
// guesses where to write.
func Splice(doc string, rep Report) (string, error) {
	i := strings.Index(doc, Begin)
	if i < 0 {
		return "", fmt.Errorf("begin marker not found: %s", Begin)
	}
	j := strings.Index(doc[i:], End)
	if j < 0 {
		return "", fmt.Errorf("end marker not found after begin marker: %s", End)
	}
	end := i + j + len(End)
	return doc[:i] + Block(rep) + doc[end:], nil
}

// Fresh reports whether the committed doc's embedded block equals the live Block(rep).
func Fresh(doc string, rep Report) bool {
	got, ok := Extract(doc)
	return ok && got == Block(rep)
}

// Scaffold is the full doc a first --write-doc writes when DocRel does not yet exist: a
// titled header, a one-line orientation, and an empty marker pair Splice then fills.
func Scaffold() string {
	var b strings.Builder
	b.WriteString("# Workflow branch-role audit\n\n")
	b.WriteString("The durable, freshness-checked classification of every git-branch and tag reference in\n")
	b.WriteString("`.github/workflows/*.yml`, folded against the branch-role contract in `dos.toml [branch_roles]`.\n")
	b.WriteString("It is the checkable map for the dev/main front-door migration (#1697/#1701): development gates,\n")
	b.WriteString("release/front-door gates, tag-driven release, and intentional legacy arms are each labeled, and a\n")
	b.WriteString("newly-introduced unclassified development-path reference reds the trunk. Generated by\n")
	b.WriteString("`internal/workflowaudit`; regenerate with `fak workflow-audit --write-doc` and gate it with\n")
	b.WriteString("`--check-doc`. The block between the markers is generated -- do not hand-edit it.\n\n")
	b.WriteString(Begin)
	b.WriteString("\n")
	b.WriteString(End)
	b.WriteString("\n")
	return b.String()
}
