package main

// antipatternscore.go wires the `fak antipattern-scorecard` verb over internal/antipattern:
// the UNIFYING anti-pattern debt card. It folds three previously-siloed loss detectors --
// post-hoc REDUNDANT_REWORK (two landed commits that redid the same unit of work),
// UNWIRED_PKG (a code-complete package imported by nothing), and ORPHAN_FUNC (an unexported
// func referenced nowhere) -- into ONE antipattern_debt integer and one worst-first work
// list. It answers the higher-abstraction question the operator asked: which recent units of
// work failed to convert into global, user-useful progress -- because they were redone, or
// because they landed wired to nothing.
//
// The tree scans (unwired/orphan) run inside internal/antipattern.Build; the git-history read
// for the redundant-rework window stays HERE (exec is a CLI concern), bounded by --commits and
// degrading to "no rework findings" when git is unavailable.

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"strings"

	"github.com/anthony-chaudhary/fak/internal/antipattern"
	"github.com/anthony-chaudhary/fak/pkg/scorecard"
)

func cmdAntipatternScorecard(argv []string) {
	os.Exit(runAntipatternScorecard(os.Stdout, os.Stderr, argv))
}

func runAntipatternScorecard(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak antipattern-scorecard", flag.ContinueOnError)
	fs.SetOutput(stderr)
	workspace := fs.String("workspace", "", "workspace root (default: repo root)")
	commitsN := fs.Int("commits", 200, "size of the recent-commit window scanned for redundant rework (0 disables)")
	asJSON := fs.Bool("json", false, "emit control-pane JSON")
	asMarkdown := fs.Bool("markdown", false, "emit the committed snapshot body")
	comparePath := fs.String("compare", "", "compare against a prior --json payload")
	if !parseFlags(fs, argv) {
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "fak antipattern-scorecard: unexpected argument %q\n", fs.Arg(0))
		return 2
	}
	if *commitsN < 0 {
		fmt.Fprintln(stderr, "fak antipattern-scorecard: --commits must be >= 0")
		return 2
	}
	root := *workspace
	if root == "" {
		root = repoRoot()
	}

	// The recent-commit window feeds the post-hoc repetition detector. A git failure (not a
	// repo, git absent) is not fatal: the card just carries no REDUNDANT_REWORK findings and
	// still reports the tree-derived lost-work classes.
	commits := readRecentCommits(root, *commitsN)

	payload := antipattern.Build(root, commits)

	return emitScorecard(stdout, stderr, "fak antipattern-scorecard", antipattern.DebtKey, payload,
		*comparePath, *asJSON, *asMarkdown, scorecard.MarkdownDoc{
			Title: "fak antipattern scorecard - the unified work-loss stick",
			Description: "fak's deterministic anti-pattern scorecard: work that did not convert into global, " +
				"user-useful progress -- redone (REDUNDANT_REWORK) or landed wired to nothing (UNWIRED_PKG, " +
				"ORPHAN_FUNC) -- folded from three previously-siloed detectors into one antipattern_debt count.",
			Heading: "Anti-pattern / work-loss scorecard",
			AutoGen: "Auto-generated by `fak antipattern-scorecard --markdown`. Do not hand-edit; re-run the tool.",
			Law: "The law: work is conserved -- every unit of work either converts into global, user-useful " +
				"progress or is named as debt. A commit that redid shipped work, a package wired to nothing, and " +
				"a func referenced nowhere are all locally-done-but-globally-useless, and each is one tracked finding.",
			DebtKey: antipattern.DebtKey,
			HeaderExtra: fmt.Sprintf(" - %v commit(s) scanned - rework=%v unwired=%v orphan=%v",
				payload.Corpus["commits_scanned"], payload.Corpus["redundant_rework"],
				payload.Corpus["unwired_pkg"], payload.Corpus["orphan_func"]),
		})
}

// readRecentCommits shells out to `git log` for the last n non-merge commits at root and
// parses each into an antipattern.Commit (short sha, subject, touched files). It returns nil
// on any git error or when n<=0 -- the caller treats an empty window as "no rework signal",
// never an error. The format uses SOH (\x01) as a per-commit record marker and US (\x1f) as
// the sha/subject separator so subjects containing colons or parentheses parse cleanly.
func readRecentCommits(root string, n int) []antipattern.Commit {
	if n <= 0 {
		return nil
	}
	cmd := exec.Command("git", "-C", root, "log", "--no-merges",
		fmt.Sprintf("-n%d", n), "--name-only", "--format=format:%x01%h%x1f%s")
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = io.Discard
	if err := cmd.Run(); err != nil {
		return nil
	}
	return parseGitLog(out.Bytes())
}

// parseGitLog turns the SOH-delimited `git log --name-only` stream into commits. Each record
// starts with \x01, then "<sha>\x1f<subject>" on the first line, then the touched files one
// per line until the next record. It is pure over the byte stream (unit-testable without git).
func parseGitLog(b []byte) []antipattern.Commit {
	var commits []antipattern.Commit
	records := strings.Split(string(b), "\x01")
	for _, rec := range records {
		rec = strings.TrimLeft(rec, "\r\n")
		if rec == "" {
			continue
		}
		sc := bufio.NewScanner(strings.NewReader(rec))
		sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
		if !sc.Scan() {
			continue
		}
		header := sc.Text()
		sep := strings.IndexByte(header, '\x1f')
		if sep < 0 {
			continue
		}
		c := antipattern.Commit{SHA: strings.TrimSpace(header[:sep]), Subject: header[sep+1:]}
		for sc.Scan() {
			line := strings.TrimSpace(sc.Text())
			if line != "" {
				c.Files = append(c.Files, line)
			}
		}
		if c.SHA != "" {
			commits = append(commits, c)
		}
	}
	return commits
}
