package main

// brittlenessscore.go wires the `fak brittleness-scorecard` verb over
// internal/brittleness: the DETECTOR-AND-CAPTURE card for seams that "got lucky".
// It folds two git-history detectors -- RECURRING_FIX (a file re-fixed by two or more
// fix/revert commits: the earlier fix did not hold) and REVERTED_LANDING (a landing
// later reverted) -- plus an optional capture bridge from a fresh flaky-rerun verdict
// (FLAKY_RETRY_PASS via --flaky) into one severity-weighted brittleness_pressure trend
// and a worst-first work list.
//
// Every finding rides as a SOFT signal, never debt: a history-window observation is not
// HARD, in-tree-mendable debt (you cannot un-ship a landed commit), so the card gates on
// nothing -- it reports a trend, it does not red a peer's `make ci`.
//
// The git-history read (exec is a CLI concern) stays HERE, bounded by --commits and
// degrading to "no history findings" when git is unavailable. The pure fold lives in
// internal/brittleness.

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"strings"

	"github.com/anthony-chaudhary/fak/internal/brittleness"
	"github.com/anthony-chaudhary/fak/pkg/scorecard"
)

func cmdBrittlenessScorecard(argv []string) {
	os.Exit(runBrittlenessScorecard(os.Stdout, os.Stderr, argv))
}

func runBrittlenessScorecard(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak brittleness-scorecard", flag.ContinueOnError)
	fs.SetOutput(stderr)
	workspace := fs.String("workspace", "", "workspace root (default: repo root)")
	commitsN := fs.Int("commits", 200, "size of the recent-commit window scanned for recurring fixes and reverts (0 disables)")
	flaky := fs.String("flaky", "", "comma-separated packages a fresh same-tree rerun exonerated as flaky; folded in as FLAKY_RETRY_PASS (the capture-when-fresh bridge)")
	since := fs.String("since", "", "freshness stamp recorded on --flaky findings (default: the current short HEAD sha -- the tree that flaked)")
	asJSON := fs.Bool("json", false, "emit control-pane JSON")
	asMarkdown := fs.Bool("markdown", false, "emit the committed snapshot body")
	comparePath := fs.String("compare", "", "compare against a prior --json payload")
	if !parseFlags(fs, argv) {
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "fak brittleness-scorecard: unexpected argument %q\n", fs.Arg(0))
		return 2
	}
	if *commitsN < 0 {
		fmt.Fprintln(stderr, "fak brittleness-scorecard: --commits must be >= 0")
		return 2
	}
	root := *workspace
	if root == "" {
		root = repoRoot()
	}

	// The recent-commit window feeds the git-history detectors. A git failure (not a repo,
	// git absent) is not fatal: the card just carries no history findings.
	commits := readCommitWindowForBrittleness(root, *commitsN)
	findings := brittleness.DetectFromCommits(commits)

	// The capture-when-fresh bridge: a caller that just saw `fak affected` exonerate packages
	// as flaky pipes them in here, stamped with the tree they flaked on, so the transient
	// verdict becomes a durable, ranked brittleness seam instead of being re-derived later.
	if flakyPkgs := splitCSV(*flaky); len(flakyPkgs) > 0 {
		stamp := strings.TrimSpace(*since)
		if stamp == "" {
			stamp = currentHeadSha(root)
		}
		findings = append(findings, brittleness.FromFlakyPackages(flakyPkgs, stamp)...)
	}

	payload := brittleness.Fold(findings)

	return emitScorecard(stdout, stderr, "fak brittleness-scorecard", brittleness.DebtKey, payload,
		*comparePath, *asJSON, *asMarkdown, scorecard.MarkdownDoc{
			Title: "fak brittleness scorecard - seams that got lucky",
			Description: "fak's deterministic brittleness detector-and-capture: outcomes that worked but only " +
				"by timing or chance, and the regressions they throw -- a test that passed only on rerun " +
				"(FLAKY_RETRY_PASS), a file re-fixed because the earlier fix did not hold (RECURRING_FIX), a " +
				"landing that had to be undone (REVERTED_LANDING) -- captured while the seam is fresh and ranked " +
				"worst-first by severity-weighted recurrence (brittleness_pressure).",
			Heading: "Brittleness scorecard",
			AutoGen: "Auto-generated by `fak brittleness-scorecard --markdown`. Do not hand-edit; re-run the tool.",
			Law: "The law: a green that was luck is not a green. Every seam that only passed by chance, or that " +
				"keeps regressing, is captured at its freshest moment -- with the evidence that proves it -- so no " +
				"later agent has to re-derive it. History-window findings are SOFT (a landed commit cannot be " +
				"un-shipped), so the card trends brittleness_pressure rather than gating.",
			DebtKey: brittleness.DebtKey,
			HeaderExtra: fmt.Sprintf(" - %d commit(s) scanned - pressure=%v seams=%v (flaky=%v recurring-fix=%v reverted=%v)",
				len(commits), payload.Corpus[brittleness.PressureKey], payload.Corpus["seams_observed"],
				payload.Corpus["flaky_retry_pass"], payload.Corpus["recurring_fix"], payload.Corpus["reverted_landing"]),
		})
}

// currentHeadSha returns the short HEAD sha at root, or "" on any git error -- the
// freshness stamp for --flaky findings when the caller did not supply --since.
func currentHeadSha(root string) string {
	cmd := exec.Command("git", "-C", root, "rev-parse", "--short", "HEAD")
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = io.Discard
	if err := cmd.Run(); err != nil {
		return ""
	}
	return strings.TrimSpace(out.String())
}

// readCommitWindowForBrittleness shells out to `git log` for the last n non-merge commits
// at root and parses each into a brittleness.Commit (short sha, subject, touched files). It
// returns nil on any git error or when n<=0 -- the caller treats an empty window as "no
// history signal", never an error. Deliberately its own reader (not antipattern's) so this
// verb depends only on internal/brittleness and stays green in a clean checkout. The format
// uses SOH (\x01) as a per-commit record marker and US (\x1f) as the sha/subject separator
// so subjects containing colons or parentheses parse cleanly.
func readCommitWindowForBrittleness(root string, n int) []brittleness.Commit {
	if n <= 0 {
		return nil
	}
	cmd := exec.Command("git", "-C", root, "log", "--no-merges",
		fmt.Sprintf("-n%d", n), "--name-only", "--format=format:%x01%h%x1f%s")
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = io.Discard
	if err := cmd.Run(); err != nil {
		return nil
	}
	return parseBrittlenessGitLog(out.Bytes())
}

// parseBrittlenessGitLog turns the SOH-delimited `git log --name-only` stream into commits.
// Each record starts with \x01, then "<sha>\x1f<subject>" on the first line, then the touched
// files one per line until the next record. Pure over the byte stream (unit-testable without git).
func parseBrittlenessGitLog(b []byte) []brittleness.Commit {
	var commits []brittleness.Commit
	for _, rec := range strings.Split(string(b), "\x01") {
		rec = strings.TrimLeft(rec, "\r\n")
		if rec == "" {
			continue
		}
		sc := bufio.NewScanner(strings.NewReader(rec))
		sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
		if !sc.Scan() {
			continue
		}
		header := sc.Text()
		sep := strings.IndexByte(header, '\x1f')
		if sep < 0 {
			continue
		}
		c := brittleness.Commit{SHA: strings.TrimSpace(header[:sep]), Subject: header[sep+1:]}
		for sc.Scan() {
			if line := strings.TrimSpace(sc.Text()); line != "" {
				c.Files = append(c.Files, line)
			}
		}
		if c.SHA != "" {
			commits = append(commits, c)
		}
	}
	return commits
}
