package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"time"

	"github.com/anthony-chaudhary/fak/internal/cachevalueledger"
	"github.com/anthony-chaudhary/fak/internal/cachevaluereport"
	"github.com/anthony-chaudhary/fak/internal/gatewayusageledger"
	"github.com/anthony-chaudhary/fak/pkg/scorecard"
)

// cmdCacheHealthScore is `fak score cache-health` (issue #3643, epic #3569): the single fleet
// cache-health number + worst-first worklist, folded ALONGSIDE the D1/D2/D3 cache-VALUE aspects.
//
// It RE-USES the existing weekly cache-health digest (#3646) component metrics rather than
// re-deriving them: it folds the durable Track-1 cache-value ledger and the gateway-usage ledger
// into that digest, then maps this-week's posture adoption, realized reuse, shed effectiveness,
// and upgrade-fired rate into one 0..1 cache-health headline. Missing/empty ledgers fold to the
// honest INSUFFICIENT card (cache_health 1.0, empty worklist) rather than failing.
//
// The fifth family the scorecard folds -- witnessed/observed (gross/net) agreement -- is left
// absent here because those shares live on the D1/D2/D3 cache-VALUE surface, not the weekly
// cache-health digest; the fold already supports it (CacheHealthFacts.WitnessedObservedAgreement),
// so wiring it is a thin follow-up when a two-track gross/net source is available at this CLI.
func cmdCacheHealthScore(argv []string) {
	os.Exit(runCacheHealthScore(os.Stdout, os.Stderr, argv))
}

func runCacheHealthScore(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak score cache-health", flag.ContinueOnError)
	fs.SetOutput(stderr)
	ledger := fs.String("ledger", cachevalueledger.DefaultLedgerRel, "Track-1 WITNESSED kernel ledger (docs/nightrun/cache-value.jsonl)")
	usageLedger := fs.String("usage-ledger", gatewayusageledger.DefaultLedgerRel, "gateway usage ledger for posture/shed/refusal counters (.fak/nightrun/gateway-usage.jsonl)")
	since := fs.String("since", "", "fold only rows on or after this date (YYYY-MM-DD)")
	asJSON := fs.Bool("json", false, "emit control-pane JSON")
	asMarkdown := fs.Bool("markdown", false, "emit the committed snapshot body")
	comparePath := fs.String("compare", "", "compare against a prior --json payload")
	if !parseFlags(fs, argv) {
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "fak score cache-health: unexpected argument %q\n", fs.Arg(0))
		return 2
	}
	if *since != "" {
		if _, err := time.Parse("2006-01-02", *since); err != nil {
			fmt.Fprintf(stderr, "fak score cache-health: --since must be YYYY-MM-DD: %v\n", err)
			return 2
		}
	}

	track1 := filterTrack1Since(cachevalueledger.ReadLedgerFile(*ledger), *since)
	usage := filterGatewayUsageSince(gatewayusageledger.ReadLedgerFile(*usageLedger), *since)
	digest := cachevaluereport.FoldWeeklyDigest(track1, usage, time.Now())
	payload := scorecard.ComposeCacheHealth(cacheHealthFactsFromWindow(digest.ThisWeek))

	return emitScorecard(stdout, stderr, "fak score cache-health", scorecard.CacheHealthDebtKey, payload,
		*comparePath, *asJSON, *asMarkdown, scorecard.MarkdownDoc{
			Title: "fak cache-health scorecard - one fleet cache-health number",
			Description: "fak's single 0..1 fleet cache-health number: managed-cache posture, realized reuse, shed " +
				"effectiveness, witnessed/observed agreement, and the upgrade-fired rate folded into one headline " +
				"with a worst-first component worklist a human reads at a glance and a gate ratchets on.",
			Heading: "Fleet cache-health scorecard",
			AutoGen: "Auto-generated by `fak score cache-health --markdown`. Do not hand-edit; re-run the tool.",
			Law: "The law: the cache families fold into ONE 0..1 cache-health number with a worst-first worklist; a " +
				"family below the pass line is debt, retired by raising the real component (reuse the existing metric), " +
				"never by weakening the floor.",
			DebtKey: scorecard.CacheHealthDebtKey,
			HeaderExtra: fmt.Sprintf(" - %v/%v families with evidence - cache_health %v",
				payload.Corpus["components_present"], payload.Corpus["components_total"], payload.Corpus["cache_health"]),
		})
}

// cacheHealthFactsFromWindow maps a weekly cache-health digest window (#3646) into the fold's
// CacheHealthFacts, re-using each family's already-derived metric. Nil-able ratios pass their
// "no evidence" (nil) through unchanged so an absent family is excluded, never scored as zero.
func cacheHealthFactsFromWindow(w cachevaluereport.WeeklyWindow) scorecard.CacheHealthFacts {
	return scorecard.CacheHealthFacts{
		ManagedCachePosture: scorecard.PostureHealth(w.PostureAdoptionPct),
		ReuseRatio:          w.ReuseRatio,
		ShedEffectiveness:   scorecard.ShedEffectivenessHealth(w.CompactionFired, w.CompactionBailed),
		UpgradeFiredRate:    scorecard.UpgradeFiredHealth(w.TTLUpgrades, w.TTLRefusals),
		// WitnessedObservedAgreement stays nil: the gross/net shares live on the D1/D2/D3
		// cache-VALUE surface, not this weekly digest. The fold supports it when supplied.
	}
}
