package main

// checkpointscore.go wires two verbs over internal/checkpointscore:
//
//   fak checkpoint-scorecard     -- the score: which long-running process subsystems persist
//                                   durable, resumable WIP state (crash_recovery) and expose a
//                                   witnessed status surface (status)? Probes each subsystem's
//                                   own source, folds an unbounded checkpoint_debt integer, and
//                                   emits the standard --json/--markdown/--compare control-pane.
//   fak checkpoint-debt-dispatch -- the fan-out: one deduped issue/record per (subsystem, axis)
//                                   gap, routed to a general-purpose sink (--sink stdout|localdb|
//                                   github). Dry-run by default; --live commits.
//
// Together they answer "which unbounded processes can't survive or report a mid-task crash":
// the score names every gap, the dispatcher fans the work out to a sink without anyone holding
// the backlog in their head.

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/anthony-chaudhary/fak/internal/checkpointscore"
	"github.com/anthony-chaudhary/fak/internal/findingsink"
	"github.com/anthony-chaudhary/fak/pkg/scorecard"
)

func cmdCheckpointScorecard(argv []string) {
	os.Exit(runCheckpointScorecard(os.Stdout, os.Stderr, argv))
}

func runCheckpointScorecard(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak checkpoint-scorecard", flag.ContinueOnError)
	fs.SetOutput(stderr)
	workspace := fs.String("workspace", "", "workspace root (default: repo root)")
	asJSON := fs.Bool("json", false, "emit control-pane JSON")
	asMarkdown := fs.Bool("markdown", false, "emit the committed snapshot body")
	comparePath := fs.String("compare", "", "compare against a prior --json payload")
	if !parseFlags(fs, argv) {
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "fak checkpoint-scorecard: unexpected argument %q\n", fs.Arg(0))
		return 2
	}
	root := *workspace
	if root == "" {
		root = repoRoot()
	}
	payload := checkpointscore.Build(root)

	return emitScorecard(stdout, stderr, "fak checkpoint-scorecard", checkpointscore.DebtKey, payload,
		*comparePath, *asJSON, *asMarkdown, scorecard.MarkdownDoc{
			Title: "fak checkpoint scorecard - can the long-running processes survive a crash",
			Description: "fak's deterministic WIP-checkpoint scorecard: every long-running process subsystem " +
				"probed for whether it persists durable, resumable work-in-progress state (crash_recovery) " +
				"and exposes a witnessed status surface (status), plus the still-unbuilt unified worker " +
				"checkpoint - folded into an unbounded checkpoint_debt count.",
			Heading: "WIP-checkpoint readiness scorecard",
			AutoGen: "Auto-generated by `fak checkpoint-scorecard --markdown`. Do not hand-edit; re-run the tool.",
			Law: "The law: a long-running process must persist durable, resumable WIP state so a mid-task " +
				"crash loses no work, and expose a witnessed status a peer can read without tailing its logs. " +
				"A process that runs unbounded with neither is a silent liability.",
			DebtKey: checkpointscore.DebtKey,
			HeaderExtra: fmt.Sprintf(" - %v subsystem(s) - %v recovery-ready - %v status-ready - %v planned open",
				payload.Corpus["subsystems"], payload.Corpus["recovery_ready"],
				payload.Corpus["status_ready"], payload.Corpus["planned_open"]),
		})
}

func cmdCheckpointDebtDispatch(argv []string) {
	os.Exit(runCheckpointDebtDispatch(os.Stdout, os.Stderr, argv))
}

func runCheckpointDebtDispatch(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak checkpoint-debt-dispatch", flag.ContinueOnError)
	fs.SetOutput(stderr)
	project := addDogfoodProjectFlags(fs)
	workspace := fs.String("workspace", "", "workspace root (default: repo root)")
	capN := fs.Int("cap", 10, "maximum gaps to fan out in one run")
	sinkName := fs.String("sink", "stdout", "finding sink: stdout | localdb | github")
	repo := fs.String("repo", "", "owner/repo for the github sink; default is the current repo")
	limit := fs.Int("limit", 300, "existing-issue scan limit for the live github sink")
	live := fs.Bool("live", false, "commit to the sink (localdb: write the ledger; github: create/update issues)")
	asJSON := fs.Bool("json", false, "emit machine-readable sink report")
	var labels stringList
	fs.Var(&labels, "label", "label to add to newly-created github issues; repeatable")
	if !parseFlags(fs, argv) {
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "fak checkpoint-debt-dispatch: unexpected argument %q\n", fs.Arg(0))
		return 2
	}
	if *capN < 0 {
		fmt.Fprintln(stderr, "fak checkpoint-debt-dispatch: --cap must be >= 0")
		return 2
	}
	root := *workspace
	if root == "" {
		root = repoRoot()
	} else if abs, err := filepath.Abs(root); err == nil {
		root = abs
	}

	sink, err := selectSink(*sinkName, stdout)
	if err != nil {
		fmt.Fprintf(stderr, "fak checkpoint-debt-dispatch: %v\n", err)
		return 2
	}

	gaps := checkpointscore.Gaps(root)
	if *capN >= 0 && len(gaps) > *capN {
		gaps = gaps[:*capN]
	}
	items := checkpointscore.ActionItems(gaps, "fak checkpoint-scorecard --json")
	findings := findingsink.FromActionItems(items)

	rep, err := sink.Emit(findings, findingsink.EmitOptions{
		Live:           *live,
		Repo:           *repo,
		Cap:            *capN,
		Dir:            root,
		Labels:         []string(labels),
		Evidence:       "fak checkpoint-scorecard --json",
		Limit:          *limit,
		ParentBaseline: project.baseline(), CompletionStandard: *project.standard, TargetEnvelope: *project.target, WitnessedEnvelope: *project.witnessed,
	})
	if err != nil {
		fmt.Fprintf(stderr, "fak checkpoint-debt-dispatch: %v\n", err)
		return 1
	}

	exit := 0
	for _, row := range rep.Rows {
		if !row.OK {
			exit = 1
		}
	}

	if *asJSON {
		if err := writeIndentedJSON(stdout, rep); err != nil {
			fmt.Fprintf(stderr, "fak checkpoint-debt-dispatch: encode json: %v\n", err)
			return 1
		}
		return exit
	}
	renderSinkReport(stdout, rep)
	return exit
}

// selectSink resolves the --sink flag to a findingsink.Sink.
func selectSink(name string, stdout io.Writer) (findingsink.Sink, error) {
	switch name {
	case "", "stdout":
		return findingsink.StdoutSink{W: stdout}, nil
	case "localdb":
		return findingsink.LocalDBSink{}, nil
	case "github", "gh":
		return findingsink.GitHubSink{}, nil
	default:
		return nil, fmt.Errorf("unknown --sink %q (want stdout|localdb|github)", name)
	}
}

func renderSinkReport(w io.Writer, rep findingsink.Report) {
	fmt.Fprintf(w, "sink=%s mode=%s planned=%d created=%d updated=%d skipped=%d\n",
		rep.Sink, rep.Mode, rep.Planned, rep.Created, rep.Updated, rep.Skipped)
	for _, row := range rep.Rows {
		status := "ok"
		if !row.OK {
			status = "FAIL"
		}
		line := fmt.Sprintf("  %-6s %-40s %s", row.Action, row.Key, status)
		if row.Ref != "" {
			line += " " + row.Ref
		}
		if row.Detail != "" {
			line += " " + row.Detail
		}
		fmt.Fprintln(w, line)
	}
}
