package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/anthony-chaudhary/fak/internal/conflationscore"
	"github.com/anthony-chaudhary/fak/pkg/scorecard"
)

func cmdConflationScorecard(argv []string) {
	os.Exit(runConflationScorecard(os.Stdout, os.Stderr, argv))
}

func runConflationScorecard(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak conflation-scorecard", flag.ContinueOnError)
	fs.SetOutput(stderr)
	workspace := fs.String("workspace", "", "workspace root (default: repo root)")
	asJSON := fs.Bool("json", false, "emit control-pane JSON")
	asMarkdown := fs.Bool("markdown", false, "emit the committed snapshot body")
	comparePath := fs.String("compare", "", "compare against a prior --json payload")
	if err := fs.Parse(argv); err != nil {
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "fak conflation-scorecard: unexpected argument %q\n", fs.Arg(0))
		return 2
	}
	root := *workspace
	if root == "" {
		root = repoRoot()
	}
	payload := conflationscore.Build(root)

	if *comparePath != "" {
		base, ok := readCompareBase(stderr, "fak conflation-scorecard", *comparePath)
		if !ok {
			return 2
		}
		fmt.Fprintln(stdout, scorecard.Compare(payload, base, conflationscore.DebtKey))
		return okExit(payload.OK)
	}
	if *asJSON {
		if err := writeIndentedJSON(stdout, payload); err != nil {
			fmt.Fprintf(stderr, "fak conflation-scorecard: encode json: %v\n", err)
			return 1
		}
		return okExit(payload.OK)
	}
	if *asMarkdown {
		fmt.Fprint(stdout, scorecard.Markdown(payload, scorecard.MarkdownDoc{
			Title: "fak conflation scorecard - the provenance-honesty stick",
			Description: "fak's deterministic conflation scorecard: does every number and status fak reports " +
				"label its provenance - WITNESSED (a fact fak authored) vs OBSERVED (a value relayed " +
				"from an external party) - folded into a conflation-debt count.",
			Heading: "Conflation / provenance-honesty scorecard",
			AutoGen: "Auto-generated by `fak conflation-scorecard --markdown`. Do not hand-edit; re-run the tool.",
			Law: "The law: every reported number/status labels its provenance -- WITNESSED (a fact fak " +
				"authored) vs OBSERVED (a value fak relays from an external party) -- and a bad OBSERVED " +
				"value is never blamed on a fak action unless a witnessed signal proves the fault is fak's.",
			DebtKey: conflationscore.DebtKey,
			HeaderExtra: fmt.Sprintf(" - %v reporting surface(s) - %v external-value string(s)",
				payload.Corpus["surfaces"], payload.Corpus["external_values_seen"]),
		}))
		return 0
	}
	fmt.Fprintln(stdout, scorecard.Render(payload, conflationscore.DebtKey))
	return okExit(payload.OK)
}

func okExit(ok bool) int {
	if ok {
		return 0
	}
	return 1
}

// readCompareBase reads and JSON-parses a prior --compare scorecard payload into a
// generic map, emitting the shared read/parse error messages under prefix (e.g.
// "fak conflation-scorecard") and returning ok=false on failure (callers return 2).
// It is the shared --compare loader behind the conflation/dogfood/guard-rsi scorecards.
func readCompareBase(stderr io.Writer, prefix, path string) (map[string]any, bool) {
	b, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintf(stderr, "%s: read --compare: %v\n", prefix, err)
		return nil, false
	}
	var base map[string]any
	if err := json.Unmarshal(b, &base); err != nil {
		fmt.Fprintf(stderr, "%s: parse --compare: %v\n", prefix, err)
		return nil, false
	}
	return base, true
}
