package main

// defaultvaluescore.go wires internal/defaultvaluescore into `fak score default-value`.
//
// The scorecard is epic #1089's RECURRING GUARD against the "shipped not-fully-enabled"
// failure class: a cost/cache/context VALUE lever that is implemented, tested, and working
// but ships default-OFF (or an exit line that folds vacuous kernel.Counters on the Decide
// proxy, or a score surface that headlines a modeled number as measured). The package was
// built, tested, and architest-tiered but never given a CLI verb -- so the guard it defines
// never actually ran on any default path. This verb turns it on: it emits the standard
// --json/--markdown/--compare control-pane surface so a cadence (and the control pane) can
// pin default_value_debt against silent regrowth, exactly as its CleanFloor=0 promises.

import (
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/anthony-chaudhary/fak/internal/defaultvaluescore"
	"github.com/anthony-chaudhary/fak/pkg/scorecard"
)

func cmdDefaultValueScorecard(argv []string) {
	os.Exit(runDefaultValueScorecard(os.Stdout, os.Stderr, argv))
}

func runDefaultValueScorecard(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak score default-value", flag.ContinueOnError)
	fs.SetOutput(stderr)
	workspace := fs.String("workspace", "", "workspace root (default: repo root)")
	asJSON := fs.Bool("json", false, "emit control-pane JSON")
	asMarkdown := fs.Bool("markdown", false, "emit the committed snapshot body")
	comparePath := fs.String("compare", "", "compare against a prior --json payload")
	if !parseFlags(fs, argv) {
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "fak score default-value: unexpected argument %q\n", fs.Arg(0))
		return 2
	}
	root := *workspace
	if root == "" {
		root = repoRoot()
	}
	payload := defaultvaluescore.Build(root)

	return emitScorecard(stdout, stderr, "fak score default-value", defaultvaluescore.DebtKey, payload,
		*comparePath, *asJSON, *asMarkdown, scorecard.MarkdownDoc{
			Title: "fak default-value scorecard - is every value lever actually enabled where it ships",
			Description: "fak's deterministic agentic default-window monitor: a cost/cache/context VALUE " +
				"lever that is implemented, tested, and working but ships default-OFF without a current reviewed gate " +
				"creates omission harm; an unsafe default creates exposure harm. Also flags an exit line that folds vacuous " +
				"kernel.Counters on the Decide proxy, and a score surface that headlines a modeled number as " +
				"measured. Folded into a default-value-debt count.",
			Heading: "Default-value scorecard",
			AutoGen: "Auto-generated by `fak score default-value --markdown`. Do not hand-edit; re-run the tool.",
			Law:     "The law: keep every value lever inside the reviewed agentic default window -- default-ON when benefit outweighs bounded harm, or default-OFF only with a reason and review date -- so neither unsafe exposure nor stale opt-in friction silently harms users.",
			DebtKey: defaultvaluescore.DebtKey,
			HeaderExtra: fmt.Sprintf(" - %v value-flag(s) seen - %v off - %v flag surface(s) - %v score surface(s)",
				payload.Corpus["value_flags_seen"], payload.Corpus["value_flags_off"],
				payload.Corpus["flag_surfaces"], payload.Corpus["score_surfaces"]) +
				fmt.Sprintf(" - %v reviewed opt-in gate(s) - next review %v",
					payload.Corpus["reviewed_opt_in_flags"], payload.Corpus["next_default_review"]),
		})
}
