package main

import (
	"context"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"strings"
	"time"

	"github.com/anthony-chaudhary/fak/internal/issuehygiene"
	"github.com/anthony-chaudhary/fak/pkg/scorecard"
)

// cmdIssueHygieneScorecard is the `fak score issue-hygiene` entry. It grades how
// well the DEFAULT GitHub issue surface is created and tagged -- class/priority
// coverage, worker-ready body sections, near-dup avoidance, epic decomposition --
// folded into one issue_hygiene_debt integer (see internal/issuehygiene). It is
// the SCORED half of "make issue creation and tagging scored": a producer fans
// issues into `gh issue create` ungated, this measures the resulting backlog.
//
// Source: the live open backlog via `gh issue list` by default (this is a
// live-backlog card, like `fak maturity`'s issue bridge). --fixture <path> reads
// a committed snapshot instead, so the pure core (issuehygiene.Score) is graded
// offline and deterministically in tests. The gh fetch lives HERE in the
// integrator shell; the internal leaf stays pure.
func cmdIssueHygieneScorecard(argv []string) {
	os.Exit(runIssueHygieneScorecard(os.Stdout, os.Stderr, argv))
}

func runIssueHygieneScorecard(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak score issue-hygiene", flag.ContinueOnError)
	fs.SetOutput(stderr)
	workspace := fs.String("workspace", "", "workspace root (default: repo root)")
	asJSON := fs.Bool("json", false, "emit control-pane JSON")
	asMarkdown := fs.Bool("markdown", false, "emit the committed snapshot body")
	comparePath := fs.String("compare", "", "compare against a prior --json payload")
	fixture := fs.String("fixture", "", "grade a committed `gh issue list --json ...` snapshot file instead of the live backlog (deterministic)")
	limit := fs.Int("limit", 500, "max open issues to fetch from gh (live mode)")
	nowUnix := fs.Int64("now-unix", 0, "reference clock (epoch seconds) for the soft staleness axis; 0 = wall clock")
	repo := fs.String("repo", "", "gh --repo OWNER/REPO (default: the current repo)")
	if !parseFlags(fs, argv) {
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "fak score issue-hygiene: unexpected argument %q\n", fs.Arg(0))
		return 2
	}
	root := *workspace
	if root == "" {
		root = repoRoot()
	}

	var raw []byte
	var err error
	if *fixture != "" {
		raw, err = os.ReadFile(*fixture)
		if err != nil {
			fmt.Fprintf(stderr, "fak score issue-hygiene: read --fixture: %v\n", err)
			return 2
		}
	} else {
		raw, err = fetchIssueHygieneBacklog(*repo, *limit)
		if err != nil {
			fmt.Fprintf(stderr, "fak score issue-hygiene: %v\n", err)
			fmt.Fprintln(stderr, "  (need `gh` authenticated to the repo, or pass --fixture <snapshot.json>)")
			return 1
		}
	}

	issues, err := issuehygiene.Parse(raw)
	if err != nil {
		fmt.Fprintf(stderr, "fak score issue-hygiene: %v\n", err)
		return 2
	}

	now := *nowUnix
	if now == 0 {
		now = time.Now().Unix()
	}
	payload := issuehygiene.Score(issues, issuehygiene.Reference{NowUnix: now})
	payload.Workspace = root

	return emitScorecard(stdout, stderr, "fak score issue-hygiene", issuehygiene.DebtKey, payload,
		*comparePath, *asJSON, *asMarkdown, scorecard.MarkdownDoc{
			Title: "fak issue-hygiene scorecard - the pickup-readiness stick",
			Description: "fak's issue-hygiene scorecard: is every dispatchable GitHub issue born pickup-ready - " +
				"class + priority tagged, its body carrying the worker-ready sections a fresh agent needs, " +
				"and not a duplicate of work already filed - folded into an issue_hygiene_debt count.",
			Heading: "Issue-hygiene / pickup-readiness scorecard",
			AutoGen: "Auto-generated by `fak score issue-hygiene --markdown`. Do not hand-edit; re-run the tool.",
			Law: "The law: every dispatchable issue carries a class:* label (findable in the dev-leaves / infra / " +
				"front-door views), a priority/P? label (rankable for pickup), the worker-ready body sections, " +
				"and is not a near-duplicate of an earlier open issue -- so the next pickup is one obvious, ready choice.",
			DebtKey: issuehygiene.DebtKey,
			HeaderExtra: fmt.Sprintf(" - %v open, %v dispatchable, %v pickup-ready (%v%%)",
				payload.Corpus["open_issues"], payload.Corpus["dispatchable"],
				payload.Corpus["pickup_ready"], payload.Corpus["pickup_ready_pct"]),
		})
}

// fetchIssueHygieneBacklog reads the live open backlog via gh with the label,
// assignee and timestamp fields the scorecard grades. 60s timeout mirrors the
// other gh helpers so a stalled network call or auth prompt cannot hang.
func fetchIssueHygieneBacklog(repo string, limit int) ([]byte, error) {
	if limit <= 0 {
		limit = 500
	}
	args := []string{"issue", "list", "--state", "open", "--limit", fmt.Sprint(limit),
		"--json", "number,title,body,labels,assignees,state,createdAt,updatedAt"}
	if repo != "" {
		args = append(args, "--repo", repo)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "gh", args...)
	configureDispatchHelperCommand(cmd)
	b, err := cmd.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("gh %s: %w (%s)", strings.Join(args, " "), err, strings.TrimSpace(string(b)))
	}
	return b, nil
}
