package main

import (
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/anthony-chaudhary/fak/internal/memvaluescore"
	"github.com/anthony-chaudhary/fak/pkg/scorecard"
)

// cmdMemoryValueScorecard is the shell for `fak memory-value-scorecard`. The
// main.go dispatch case is intentionally NOT wired in this change — main.go is
// carrying unrelated in-flight work and a shared-tree pathspec commit would
// sweep it (the peer-sweep-commit fence). The one-line `case
// "memory-value-scorecard": cmdMemoryValueScorecard(os.Args[2:])` lands when
// that lane clears; until then the card runs through its package tests.
func cmdMemoryValueScorecard(argv []string) {
	os.Exit(runMemoryValueScorecard(os.Stdout, os.Stderr, argv))
}

var _ = cmdMemoryValueScorecard // parked: referenced by the main.go case once the cmd lane clears

func runMemoryValueScorecard(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak memory-value-scorecard", flag.ContinueOnError)
	fs.SetOutput(stderr)
	workspace := fs.String("workspace", "", "workspace root (default: repo root)")
	store := fs.String("store", "", "memory store dir (default: <root>/"+memvaluescore.DefaultStoreRel+")")
	ledger := fs.String("ledger", "", "recall-events ledger (default: <root>/"+memvaluescore.DefaultLedgerRel+")")
	asJSON := fs.Bool("json", false, "emit control-pane JSON")
	asMarkdown := fs.Bool("markdown", false, "emit the committed snapshot body")
	comparePath := fs.String("compare", "", "compare against a prior --json payload")
	if !parseFlags(fs, argv) {
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "fak memory-value-scorecard: unexpected argument %q\n", fs.Arg(0))
		return 2
	}
	root := *workspace
	if root == "" {
		root = repoRoot()
	}
	storeDir := *store
	if storeDir == "" {
		storeDir = root + "/" + memvaluescore.DefaultStoreRel
	}
	ledgerPath := *ledger
	if ledgerPath == "" {
		ledgerPath = root + "/" + memvaluescore.DefaultLedgerRel
	}
	payload := memvaluescore.BuildWith(ctx(), storeDir, ledgerPath, nil)

	return emitScorecard(stdout, stderr, "fak memory-value-scorecard", memvaluescore.DebtKey, payload,
		*comparePath, *asJSON, *asMarkdown, scorecard.MarkdownDoc{
			Title: "fak memory-value scorecard - the unbounded memory P&L",
			Description: "fak's deterministic memory-value scorecard: the unbounded value frontier " +
				"(witnessed recall events from the ledger), the unbounded rot pressure over the " +
				"committed memory mirror, and the hard structural debt the ratchet holds.",
			Heading: "Memory-value scorecard",
			AutoGen: "Auto-generated by `fak memory-value-scorecard --markdown`. Do not hand-edit; re-run the tool.",
			Law: "The law: the frontier moves only on WITNESSED recall events (never store size), " +
				"rot that external drift can create is pressure not debt, and only " +
				"mechanically-mendable structural defects gate.",
			DebtKey: memvaluescore.DebtKey,
			HeaderExtra: fmt.Sprintf(" - frontier %v - rot pressure %v",
				payload.Corpus["memory_value_frontier"], payload.Corpus["memory_rot_pressure"]),
		})
}
