package main

// negframescore.go wires the `fak score negframe` verb over internal/negframe: the
// negation-lexicon / reframe card. It scores agent-steer prose (AGENTS.md, CLAUDE.md, the
// skills by default, or explicit paths) for negatively-framed directives and, where a
// mechanical reframe is unambiguous, hands back the positive rewrite.
//
// Surfaces, all over the one card:
//   - default / --json / --markdown / --compare: the shared control-pane scorecard (emitScorecard).
//   - --per-doc: a per-document breakdown of the findings (the "per-doc" view #3540 asks for).
//   - --suggest: the review-diff view -- every mechanical negative with its positive reframe,
//     the shape a maintainer applies by hand (#3543).
//   - --since <ref>: the diff-scoped ratchet -- only negatives a change INTRODUCED vs the git
//     ref, exit 1 when any new mechanical reframe-able negative appears (the CI gate, #3545).
//
// The git reads for --since live HERE (exec is a CLI concern), degrading to "the file is new"
// when a path is absent in the ref and to a clean pass when git is unavailable.

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/anthony-chaudhary/fak/internal/negframe"
	"github.com/anthony-chaudhary/fak/internal/windowgate"
	"github.com/anthony-chaudhary/fak/pkg/scorecard"
)

func cmdNegframeScore(argv []string) { os.Exit(runNegframeScore(os.Stdout, os.Stderr, argv)) }

// runNegframeScore scores agent-steer prose for negative framing. Exit codes: 0 clean (no
// mechanical debt / no new negatives under --since), 1 debt/new-negatives present, 2 usage/IO.
func runNegframeScore(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak score negframe", flag.ContinueOnError)
	fs.SetOutput(stderr)
	workspace := fs.String("workspace", "", "workspace root (default: repo root)")
	asJSON := fs.Bool("json", false, "emit control-pane JSON")
	asMarkdown := fs.Bool("markdown", false, "emit the committed snapshot body")
	perDoc := fs.Bool("per-doc", false, "emit a per-document finding breakdown")
	suggest := fs.Bool("suggest", false, "emit review-diff reframe suggestions for mechanical negatives")
	since := fs.String("since", "", "diff-scoped ratchet: report only negatives introduced vs this git ref (exit 1 if any new mechanical negative)")
	comparePath := fs.String("compare", "", "compare against a prior --json payload")
	if !parseFlags(fs, argv) {
		return 2
	}
	root := *workspace
	if root == "" {
		root = repoRoot()
	}
	// Positional args, when present, override the default steer-prose corpus with explicit paths.
	paths := append([]string(nil), fs.Args()...)

	switch {
	case *since != "":
		return emitNegframeSince(stdout, stderr, root, *since, paths)
	case *suggest:
		return emitNegframeSuggest(stdout, root, paths)
	case *perDoc:
		return emitNegframePerDoc(stdout, stderr, root, paths, *asJSON)
	}

	payload := negframe.Build(root, paths)
	return emitScorecard(stdout, stderr, "fak score negframe", negframe.DebtKey, payload,
		*comparePath, *asJSON, *asMarkdown, scorecard.MarkdownDoc{
			Title: "fak negframe scorecard - the lead-with-the-affordance stick",
			Description: "fak's deterministic negation-framing scorecard: does agent-steer prose lead with " +
				"the action to take instead of the one to avoid -- mechanical negatives (\"don't forget to X\" " +
				"-> \"remember to X\") folded into a negframe-debt count with the positive reframe attached.",
			Heading: "Negation-framing / reframe scorecard",
			AutoGen: "Auto-generated by `fak score negframe --markdown`. Do not hand-edit; re-run the tool.",
			Law: "The law: steer prose leads with the affordance. A directive framed as a prohibition makes " +
				"the reader invert a negative to find the action; where that inversion is mechanical, the card " +
				"names the positive rewrite and counts it as debt until applied.",
			DebtKey: negframe.DebtKey,
			HeaderExtra: fmt.Sprintf(" - %v document(s) - %v mechanical / %v judgement",
				payload.Corpus["documents"], payload.Corpus["mechanical_debt"], payload.Corpus["judgement_soft"]),
		})
}

// emitNegframePerDoc prints (or JSON-encodes) the per-document finding breakdown.
func emitNegframePerDoc(stdout, stderr io.Writer, root string, paths []string, asJSON bool) int {
	if len(paths) == 0 {
		paths = negframe.ResolveTargets(root)
	}
	type docView struct {
		Path       string             `json:"path"`
		Mechanical int                `json:"mechanical"`
		Judgement  int                `json:"judgement"`
		Findings   []negframe.Finding `json:"findings"`
	}
	var docs []docView
	for _, rel := range paths {
		text := scorecard.SafeRead(filepath.Join(root, filepath.FromSlash(rel)))
		d := negframe.ScoreDoc(rel, text)
		docs = append(docs, docView{Path: rel, Mechanical: d.Mechanical, Judgement: d.Judgement, Findings: d.Findings})
	}
	if asJSON {
		return encodeJSONOrFail(stdout, stderr, docs, "fak score negframe")
	}
	total := 0
	for _, d := range docs {
		fmt.Fprintf(stdout, "%s -- %d mechanical, %d judgement\n", d.Path, d.Mechanical, d.Judgement)
		for _, f := range d.Findings {
			total++
			if f.Mechanical() {
				fmt.Fprintf(stdout, "  L%d [%s] %s\n     reframe: %s\n", f.Line, f.Category, f.Text, f.Suggest)
			} else {
				fmt.Fprintf(stdout, "  L%d [%s] %s\n     hint: %s\n", f.Line, f.Category, f.Text, f.Hint)
			}
		}
	}
	if total == 0 {
		fmt.Fprintln(stdout, "no negatively-framed directives found")
	}
	return 0
}

// emitNegframeSuggest prints the review-diff view: every mechanical negative with its positive
// reframe, grouped by document. This is the maintainer-facing "apply these" list (#3543).
func emitNegframeSuggest(stdout io.Writer, root string, paths []string) int {
	findings := negframe.AllFindings(root, paths)
	n := 0
	var lastPath string
	for _, f := range findings {
		if !f.Mechanical() {
			continue
		}
		if f.Path != lastPath {
			fmt.Fprintf(stdout, "\n%s:\n", f.Path)
			lastPath = f.Path
		}
		n++
		fmt.Fprintf(stdout, "  L%d [%s]\n    - %s\n    + %s\n", f.Line, f.Category, f.Text, f.Suggest)
	}
	if n == 0 {
		fmt.Fprintln(stdout, "no mechanical reframe suggestions -- steer prose already leads with the affordance")
		return 0
	}
	fmt.Fprintf(stdout, "\n%d mechanical reframe suggestion(s)\n", n)
	return 0
}

// emitNegframeSince is the diff-scoped ratchet: for each target path, it diffs the working copy
// against the file's content at the git ref and reports only the mechanical negatives the change
// INTRODUCED. Exit 1 when any new negative appears (the CI gate); a clean diff or an unavailable
// git both pass (0). A file absent in the ref is treated as fully new (before == "").
func emitNegframeSince(stdout, stderr io.Writer, root, ref string, paths []string) int {
	if len(paths) == 0 {
		paths = negframe.ResolveTargets(root)
	}
	var newFindings []negframe.Finding
	for _, rel := range paths {
		after := scorecard.SafeRead(filepath.Join(root, filepath.FromSlash(rel)))
		before := gitShow(root, ref, rel)
		newFindings = append(newFindings, negframe.NewFindings(rel, before, after)...)
	}
	if len(newFindings) == 0 {
		fmt.Fprintf(stdout, "negframe ratchet: no new mechanical negatives since %s\n", ref)
		return 0
	}
	fmt.Fprintf(stdout, "negframe ratchet: %d new mechanical negative(s) since %s -- reframe before landing:\n", len(newFindings), ref)
	for _, f := range newFindings {
		fmt.Fprintf(stdout, "  %s:%d [%s] %s\n     reframe: %s\n", f.Path, f.Line, f.Category, f.Text, f.Suggest)
	}
	return 1
}

// gitShow returns the content of rel at ref (`git show <ref>:<path>`), or "" when the path did
// not exist in that ref or git is unavailable -- both mean "no prior baseline", so the ratchet
// treats the whole current file as new content to scan.
func gitShow(root, ref, rel string) string {
	spec := ref + ":" + filepath.ToSlash(rel)
	cmd := exec.Command("git", "-C", root, "show", spec)
	windowgate.ConfigureBackgroundCommand(cmd)
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = io.Discard
	if err := cmd.Run(); err != nil {
		return ""
	}
	return strings.ReplaceAll(out.String(), "\r\n", "\n")
}
