package main

// fak operator heaviness -- the operator-heaviness / steering-effort scorecard. It grades the
// surface an operator DRIVES (the dispatch table, the front-door flag set, the refusal vocabulary,
// the doc-map discoverability of the steering surfaces), distinct from the steerability index,
// which grades the SHAPE of the package graph. The headline is heaviness_pressure (an unbounded
// "how far over the comfortable lines" integer, not a 0-100 grade); heaviness_debt is the HARD gate.

import (
	"flag"
	"fmt"
	"io"

	"github.com/anthony-chaudhary/fak/internal/heavinessscore"
	"github.com/anthony-chaudhary/fak/pkg/scorecard"
)

func runOperatorHeaviness(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak operator heaviness", flag.ContinueOnError)
	fs.SetOutput(stderr)
	workspace := fs.String("workspace", "", "workspace root (default: repo root)")
	asJSON := fs.Bool("json", false, "emit control-pane JSON")
	asMarkdown := fs.Bool("markdown", false, "emit the committed snapshot body")
	comparePath := fs.String("compare", "", "compare against a prior --json payload")
	if err := fs.Parse(argv); err != nil {
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "fak operator heaviness: unexpected argument %q\n", fs.Arg(0))
		return 2
	}
	root := *workspace
	if root == "" {
		root = repoRoot()
	}
	payload := heavinessscore.Build(root)

	return emitScorecard(stdout, stderr, "fak operator heaviness", heavinessscore.DebtKey, payload,
		*comparePath, *asJSON, *asMarkdown, scorecard.MarkdownDoc{
			Title: "fak operator-heaviness scorecard - how heavy the repo feels to drive",
			Description: "fak's deterministic operator-heaviness scorecard: how heavy the repo feels to an " +
				"operator who DRIVES it - the verb-surface size, the front-door flag burden, the refusal " +
				"vocabulary, and whether the doc map makes the steering surfaces discoverable - folded into " +
				"a continual heaviness_pressure integer plus a heaviness_debt hard gate.",
			Heading: "Operator-heaviness / steering-effort scorecard",
			AutoGen: "Auto-generated by `fak operator heaviness --markdown`. Do not hand-edit; re-run the tool.",
			Law: "The law: keep the OPERATOR surface flat as the repo grows. heaviness_pressure sums how far " +
				"over the comfortable lines the surface sits (verbs, front-door flags, refusal reasons, " +
				"meta-verb share); a clean pass holds it flat, and a real consolidation drives it down. The " +
				"only HARD debt is a steering surface the doc map hides or a missing in-product appeal channel.",
			DebtKey: heavinessscore.DebtKey,
			HeaderExtra: fmt.Sprintf(" - pressure %v - %v verbs - %v front-door flags - %v refusal reasons",
				payload.Corpus["heaviness_pressure"], payload.Corpus["verbs"],
				payload.Corpus["front_door_flags"], payload.Corpus["refusal_reasons"]),
		})
}
