package main

// propagationscore.go wires two verbs over internal/propagationscore:
//
//   fak propagation-scorecard       -- the score: how far has each proven scorecard convention
//                                      (the shared kernel, --compare, --markdown, ...) fanned out
//                                      across the family? Emits the standard --json/--markdown/
//                                      --compare control-pane surface, so it dogfoods the very
//                                      conventions it measures.
//   fak propagation-debt-dispatch   -- the fan-out: one deduped, scoped GitHub issue per HARD
//                                      un-propagated gap, via the internal/dogfoodissues backlog
//                                      bridge. Dry-run by default; --live files and dedups.
//
// Together they are the "10 auto-created tickets beat the operator remembering" spine: the score
// names every place an improvement stalled, and the dispatcher fans the work out without anyone
// holding it in their head.

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/anthony-chaudhary/fak/internal/dogfoodissues"
	"github.com/anthony-chaudhary/fak/internal/propagationscore"
	"github.com/anthony-chaudhary/fak/pkg/scorecard"
)

func cmdPropagationScorecard(argv []string) {
	os.Exit(runPropagationScorecard(os.Stdout, os.Stderr, argv))
}

func runPropagationScorecard(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak propagation-scorecard", flag.ContinueOnError)
	fs.SetOutput(stderr)
	workspace := fs.String("workspace", "", "workspace root (default: repo root)")
	asJSON := fs.Bool("json", false, "emit control-pane JSON")
	asMarkdown := fs.Bool("markdown", false, "emit the committed snapshot body")
	comparePath := fs.String("compare", "", "compare against a prior --json payload")
	if err := fs.Parse(argv); err != nil {
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "fak propagation-scorecard: unexpected argument %q\n", fs.Arg(0))
		return 2
	}
	root := *workspace
	if root == "" {
		root = repoRoot()
	}
	payload := propagationscore.Build(root)

	return emitScorecard(stdout, stderr, "fak propagation-scorecard", propagationscore.DebtKey, payload,
		*comparePath, *asJSON, *asMarkdown, scorecard.MarkdownDoc{
			Title: "fak propagation scorecard - does a proven scorecard improvement fan out to every sibling",
			Description: "fak's deterministic convention-propagation scorecard: when a scoring concept is " +
				"improved in one card (the shared pkg/scorecard kernel, --compare, --markdown), has it " +
				"fanned out to the whole scorecard family? Folded into a propagation-debt count.",
			Heading: "Convention-propagation scorecard",
			AutoGen: "Auto-generated by `fak propagation-scorecard --markdown`. Do not hand-edit; re-run the tool.",
			Law: "The law: a scoring concept proven across the scorecard family must fan out to every " +
				"sibling -- a declared standard immediately, an emerging convention once it clears the " +
				"propagation quorum -- so no improvement stalls and the operator never has to remember to extend it.",
			DebtKey: propagationscore.DebtKey,
			HeaderExtra: fmt.Sprintf(" - %v family card(s) - %v convention(s) - %v open fan-out gap(s)",
				payload.Corpus["members"], payload.Corpus["conventions"], payload.Corpus["fanout_gaps"]),
		})
}

func cmdPropagationDebtDispatch(argv []string) {
	os.Exit(runPropagationDebtDispatch(os.Stdout, os.Stderr, argv))
}

func runPropagationDebtDispatch(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak propagation-debt-dispatch", flag.ContinueOnError)
	fs.SetOutput(stderr)
	workspace := fs.String("workspace", "", "workspace root (default: repo root)")
	capN := fs.Int("cap", 10, "maximum gaps to fan out into issues in one run")
	repo := fs.String("repo", "", "owner/repo for gh; default is the current repo")
	limit := fs.Int("limit", 300, "existing-issue scan limit for live/fetch modes")
	existingJSON := fs.String("existing-json", "", "fixture list of existing gh issues for dry-run dedup tests")
	fetchExisting := fs.Bool("fetch-existing", false, "dry-run but query gh to dedup against existing issue bodies")
	live := fs.Bool("live", false, "create/update GitHub issues with gh")
	asJSON := fs.Bool("json", false, "emit machine-readable plan/result")
	var labels stringList
	fs.Var(&labels, "label", "label to add to newly-created issues; repeatable")
	if err := fs.Parse(argv); err != nil {
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "fak propagation-debt-dispatch: unexpected argument %q\n", fs.Arg(0))
		return 2
	}
	if *capN < 0 {
		fmt.Fprintln(stderr, "fak propagation-debt-dispatch: --cap must be >= 0")
		return 2
	}
	root := *workspace
	if root == "" {
		root = repoRoot()
	} else if abs, err := filepath.Abs(root); err == nil {
		root = abs
	}

	gaps := propagationscore.Gaps(root)
	// Cap bounds how many gaps are turned into issues in one run (creates + updates), so a first
	// live run can't open a flood; dedup makes re-runs converge on the same set.
	if *capN >= 0 && len(gaps) > *capN {
		gaps = gaps[:*capN]
	}
	items := propagationscore.ActionItems(gaps, "fak propagation-scorecard --json")

	var existing []dogfoodissues.Issue
	switch {
	case *existingJSON != "":
		b, err := os.ReadFile(*existingJSON)
		if err != nil {
			fmt.Fprintf(stderr, "fak propagation-debt-dispatch: %v\n", err)
			return 2
		}
		if err := json.Unmarshal(b, &existing); err != nil {
			fmt.Fprintf(stderr, "fak propagation-debt-dispatch: --existing-json must be a JSON list: %v\n", err)
			return 2
		}
	case *live || *fetchExisting:
		var err error
		existing, err = dogfoodissues.FetchExistingIssues(*repo, *limit)
		if err != nil {
			fmt.Fprintf(stderr, "fak propagation-debt-dispatch: %v\n", err)
			return 2
		}
	}

	plan, skipped := dogfoodissues.BuildPlanWithOptions(items, existing, dogfoodissues.BuildOptions{
		Live:          *live,
		DedupeChecked: *existingJSON != "" || *fetchExisting || *live,
		DedupeCap:     *capN,
	})

	mode := "dry-run"
	if *live {
		mode = "live"
	}
	result := dogfoodissues.Result{
		Schema:  dogfoodissues.Schema,
		Mode:    mode,
		Report:  "fak propagation-scorecard --json",
		Planned: plan,
		Synced:  []dogfoodissues.SyncRow{},
		Skipped: skipped,
	}

	exit := 0
	if *live && len(plan) > 0 {
		result.Synced = dogfoodissues.Sync(plan, *repo, []string(labels), nil)
		for _, row := range result.Synced {
			if !row.OK {
				exit = 1
			}
		}
	}

	if *asJSON {
		if err := writeIndentedJSON(stdout, result); err != nil {
			fmt.Fprintf(stderr, "fak propagation-debt-dispatch: encode json: %v\n", err)
			return 1
		}
	} else {
		fmt.Fprintln(stdout, dogfoodissues.Render(result))
	}
	return exit
}
