package main

import (
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/anthony-chaudhary/fak/internal/supportmaturityscore"
	"github.com/anthony-chaudhary/fak/pkg/scorecard"
)

func cmdSupportMaturityScorecard(argv []string) {
	os.Exit(runSupportMaturityScorecard(os.Stdout, os.Stderr, argv))
}

func runSupportMaturityScorecard(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak support-maturity-scorecard", flag.ContinueOnError)
	fs.SetOutput(stderr)
	asJSON := fs.Bool("json", false, "emit control-pane JSON")
	asMarkdown := fs.Bool("markdown", false, "emit scorecard markdown")
	comparePath := fs.String("compare", "", "compare against a prior --json payload")
	if err := fs.Parse(argv); err != nil {
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "fak support-maturity-scorecard: unexpected argument %q\n", fs.Arg(0))
		return 2
	}

	payload := supportmaturityscore.Build()
	if *comparePath != "" {
		base, ok := readCompareBase(stderr, "fak support-maturity-scorecard", *comparePath)
		if !ok {
			return 2
		}
		fmt.Fprintln(stdout, scorecard.Compare(payload, base, supportmaturityscore.DebtKey))
		return okExit(payload.OK)
	}
	if *asJSON {
		if err := writeIndentedJSON(stdout, payload); err != nil {
			fmt.Fprintf(stderr, "fak support-maturity-scorecard: encode json: %v\n", err)
			return 1
		}
		return okExit(payload.OK)
	}
	if *asMarkdown {
		fmt.Fprint(stdout, scorecard.Markdown(payload, scorecard.MarkdownDoc{
			Title:       "fak support-maturity scorecard",
			Description: "fak's deterministic support-maturity scorecard folds the generated model x backend coverage matrix into support_maturity_debt, coverage percentage, and an A-F grade.",
			Heading:     "Support-maturity scorecard",
			AutoGen:     "Auto-generated by `fak support-maturity-scorecard --markdown`. Do not hand-edit; re-run the tool.",
			Law:         "A cell is fully mature only when the generated coverage matrix marks it SUPPORTED; proof-path-only, fenced, and undefined cells remain honest but incomplete support.",
			DebtKey:     supportmaturityscore.DebtKey,
			HeaderExtra: fmt.Sprintf(" - %v/%v cells supported", payload.Corpus["supported"], payload.Corpus["cells"]),
		}))
		return 0
	}
	fmt.Fprintln(stdout, scorecard.Render(payload, supportmaturityscore.DebtKey))
	return okExit(payload.OK)
}
