package main

import (
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/anthony-chaudhary/fak/internal/scdiff"
	"github.com/anthony-chaudhary/fak/internal/uiquality"
)

func cmdUIQualityScore(argv []string) { os.Exit(runUIQualityScore(os.Stdout, os.Stderr, argv)) }

// runUIQualityScore grades fak's terminal UI/UX surface (the `fak console` panes,
// the `fak info` overlay, the `fak guard --split` launcher) on mechanical KPIs and
// emits the control-pane payload the unified scorecard folds. Read-only: it reads
// the git-tracked render sources and writes nothing.
func runUIQualityScore(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak ui-quality-scorecard", flag.ContinueOnError)
	fs.SetOutput(stderr)
	workspace := fs.String("workspace", "", "workspace root (default: repo root)")
	asJSON := fs.Bool("json", false, "emit control-pane JSON")
	asMarkdown := fs.Bool("markdown", false, "emit scorecard markdown (the committed snapshot body)")
	comparePath := fs.String("compare", "", "compare against a prior --json payload and prove the debt moved")
	since := fs.String("since", "", "shift-left skip-gate: when no render source changed vs this git ref, report \"unchanged\" without rescanning (else full rescan)")
	if !parseFlags(fs, argv) {
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "fak ui-quality-scorecard: unexpected argument %q\n", fs.Arg(0))
		return 2
	}
	root := *workspace
	if root == "" {
		root = repoRoot()
	}
	// --since is the at-origin skip-gate. The UI-quality KPIs are HOLISTIC over the
	// render set (they ask "does dispWidthTUI exist anywhere", "are all panes width-
	// consistent"), so a partial scan of only the changed files would report a wrong
	// debt. The correct incremental move is therefore all-or-nothing: if none of the
	// card's corpus is in the diff, the debt cannot have moved -> skip; otherwise fall
	// through to a full, correct rescan.
	if *since != "" {
		if done, code := uiQualitySinceSkip(stdout, stderr, root, *since, *asJSON); done {
			return code
		}
	}
	payload := uiquality.Build(uiquality.Options{Root: root})

	return emitScorecard(stdout, stderr, "fak ui-quality-scorecard", uiquality.DebtKey, payload,
		*comparePath, *asJSON, *asMarkdown, standardScorecardDoc(
			"fak UI quality scorecard - terminal render quality",
			"fak's deterministic UI quality scorecard: does the terminal surface render correctly, legibly, and cleanly across the guard and console panes.",
			"UI quality scorecard",
			"Auto-generated by `fak ui-quality-scorecard --markdown`. Do not hand-edit; re-run the tool.",
			"The law: the operator-facing terminal surface must render correct bytes, fit its width budget, explain its terms, and degrade cleanly outside a TTY.",
			uiquality.DebtKey, fmt.Sprintf(" - %v render file(s)", payload.Corpus["render_files"])))
}

// uiQualitySinceSkip implements the --since skip-gate. It returns done=true (with an
// exit code) when it fully handled the run by reporting "unchanged" — i.e. none of
// the card's render corpus appears in the diff against `ref`, so the debt provably
// cannot have moved. It returns done=false to signal "fall through to a full
// rescan": either the corpus WAS touched, or the diff could not be computed (an
// unresolvable ref / git failure), in which case a full scan is the safe choice —
// silently reporting "unchanged" off a failed diff would be a false clean.
func uiQualitySinceSkip(stdout, stderr io.Writer, root, ref string, asJSON bool) (done bool, code int) {
	changed, err := scdiff.ChangedPaths(root, ref)
	if err != nil {
		fmt.Fprintf(stderr, "fak ui-quality-scorecard: --since %s diff failed (%v); rescanning fully\n", ref, err)
		return false, 0
	}
	touched := scdiff.Intersect(uiquality.Corpus(), changed)
	if len(touched) > 0 {
		fmt.Fprintf(stderr, "fak ui-quality-scorecard: %d render source(s) changed since %s; rescanning\n", len(touched), ref)
		return false, 0
	}
	if asJSON {
		_ = writeIndentedJSON(stdout, map[string]any{
			"schema":           uiquality.Schema,
			"ok":               true,
			"incremental_skip": true,
			"since":            ref,
			"changed_corpus":   0,
			"finding":          "unchanged since " + ref + ": no render source in the changed set",
		})
		return true, 0
	}
	fmt.Fprintf(stdout, "fak ui-quality-scorecard: unchanged since %s (no render source in the changed set)\n", ref)
	return true, 0
}
