package main

import (
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/anthony-chaudhary/fak/internal/uiquality"
	"github.com/anthony-chaudhary/fak/pkg/scorecard"
)

func cmdUIQualityScore(argv []string) { os.Exit(runUIQualityScore(os.Stdout, os.Stderr, argv)) }

// runUIQualityScore grades fak's terminal UI/UX surface (the `fak console` panes,
// the `fak info` overlay, the `fak guard --split` launcher) on mechanical KPIs and
// emits the control-pane payload the unified scorecard folds. Read-only: it reads
// the git-tracked render sources and writes nothing.
func runUIQualityScore(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak ui-quality-scorecard", flag.ContinueOnError)
	fs.SetOutput(stderr)
	workspace := fs.String("workspace", "", "workspace root (default: repo root)")
	asJSON := fs.Bool("json", false, "emit control-pane JSON")
	asMarkdown := fs.Bool("markdown", false, "emit scorecard markdown (the committed snapshot body)")
	comparePath := fs.String("compare", "", "compare against a prior --json payload and prove the debt moved")
	if err := fs.Parse(argv); err != nil {
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "fak ui-quality-scorecard: unexpected argument %q\n", fs.Arg(0))
		return 2
	}
	root := *workspace
	if root == "" {
		root = repoRoot()
	}
	payload := uiquality.Build(uiquality.Options{Root: root})

	return emitScorecard(stdout, stderr, "fak ui-quality-scorecard", uiquality.DebtKey, payload,
		*comparePath, *asJSON, *asMarkdown, scorecard.MarkdownDoc{
			Title:       "fak UI quality scorecard - terminal render quality",
			Description: "fak's deterministic UI quality scorecard: does the terminal surface render correctly, legibly, and cleanly across the guard and console panes.",
			Heading:     "UI quality scorecard",
			AutoGen:     "Auto-generated by `fak ui-quality-scorecard --markdown`. Do not hand-edit; re-run the tool.",
			Law:         "The law: the operator-facing terminal surface must render correct bytes, fit its width budget, explain its terms, and degrade cleanly outside a TTY.",
			DebtKey:     uiquality.DebtKey,
			HeaderExtra: fmt.Sprintf(" - %v render file(s)", payload.Corpus["render_files"]),
		})
}
