package main

// unwiredscore.go wires two verbs over internal/unwiredscore:
//
//   fak unwired-scorecard       -- the score: which code-complete internal packages are wired
//                                  into a default path, and which are orphaned (imported by no
//                                  .go file in the module)? Emits the standard --json/--markdown/
//                                  --compare control-pane surface, folding an unbounded
//                                  unwired_debt integer.
//   fak unwired-debt-dispatch   -- the fan-out: one deduped, scoped GitHub issue per orphaned
//                                  package, via the internal/dogfoodissues backlog bridge.
//                                  Dry-run by default; --live files and dedups.
//
// Together they answer "code complete but not wired into the default path": the score names
// every package that stalled at code-complete, and the dispatcher fans the wire-or-retire work
// out without anyone holding the backlog in their head.

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/anthony-chaudhary/fak/internal/dogfoodissues"
	"github.com/anthony-chaudhary/fak/internal/unwiredscore"
	"github.com/anthony-chaudhary/fak/pkg/scorecard"
)

func cmdUnwiredScorecard(argv []string) {
	os.Exit(runUnwiredScorecard(os.Stdout, os.Stderr, argv))
}

func runUnwiredScorecard(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak unwired-scorecard", flag.ContinueOnError)
	fs.SetOutput(stderr)
	workspace := fs.String("workspace", "", "workspace root (default: repo root)")
	asJSON := fs.Bool("json", false, "emit control-pane JSON")
	asMarkdown := fs.Bool("markdown", false, "emit the committed snapshot body")
	comparePath := fs.String("compare", "", "compare against a prior --json payload")
	if !parseFlags(fs, argv) {
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "fak unwired-scorecard: unexpected argument %q\n", fs.Arg(0))
		return 2
	}
	root := *workspace
	if root == "" {
		root = repoRoot()
	}
	payload := unwiredscore.Build(root)

	return emitScorecard(stdout, stderr, "fak unwired-scorecard", unwiredscore.DebtKey, payload,
		*comparePath, *asJSON, *asMarkdown, scorecard.MarkdownDoc{
			Title: "fak unwired scorecard - which code-complete packages are wired to nothing",
			Description: "fak's deterministic unwired-code scorecard: every internal Go package that declares real " +
				"API but whose import path is referenced by no .go file in the module - code complete, wired into " +
				"no default path - folded into an unwired_debt count.",
			Heading: "Unwired-code scorecard",
			AutoGen: "Auto-generated by `fak unwired-scorecard --markdown`. Do not hand-edit; re-run the tool.",
			Law: "The law: a package that is code complete but imported by nothing delivers zero durable value - " +
				"it must be wired into a default path (a verb, the request-path closure, a benchmark) or retired, " +
				"never left to rot silently because a dead package breaks no build.",
			DebtKey: unwiredscore.DebtKey,
			HeaderExtra: fmt.Sprintf(" - %v candidate package(s) - %v orphaned - %v allow-listed",
				payload.Corpus["candidates"], payload.Corpus["unwired"], payload.Corpus["allowlisted"]),
		})
}

func cmdUnwiredDebtDispatch(argv []string) {
	os.Exit(runUnwiredDebtDispatch(os.Stdout, os.Stderr, argv))
}

func runUnwiredDebtDispatch(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak unwired-debt-dispatch", flag.ContinueOnError)
	fs.SetOutput(stderr)
	project := addDogfoodProjectFlags(fs)
	workspace := fs.String("workspace", "", "workspace root (default: repo root)")
	capN := fs.Int("cap", 10, "maximum orphaned packages to fan out into issues in one run")
	repo := fs.String("repo", "", "owner/repo for gh; default is the current repo")
	limit := fs.Int("limit", 300, "existing-issue scan limit for live/fetch modes")
	existingJSON := fs.String("existing-json", "", "fixture list of existing gh issues for dry-run dedup tests")
	fetchExisting := fs.Bool("fetch-existing", false, "dry-run but query gh to dedup against existing issue bodies")
	live := fs.Bool("live", false, "create/update GitHub issues with gh")
	asJSON := fs.Bool("json", false, "emit machine-readable plan/result")
	var labels stringList
	fs.Var(&labels, "label", "label to add to newly-created issues; repeatable")
	if !parseFlags(fs, argv) {
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "fak unwired-debt-dispatch: unexpected argument %q\n", fs.Arg(0))
		return 2
	}
	if *capN < 0 {
		fmt.Fprintln(stderr, "fak unwired-debt-dispatch: --cap must be >= 0")
		return 2
	}
	root := *workspace
	if root == "" {
		root = repoRoot()
	} else if abs, err := filepath.Abs(root); err == nil {
		root = abs
	}

	gaps := unwiredscore.Gaps(root)
	// Cap bounds how many orphans are turned into issues in one run (creates + updates), so a
	// first live run over a large backlog can't open a flood; dedup makes re-runs converge.
	if *capN >= 0 && len(gaps) > *capN {
		gaps = gaps[:*capN]
	}
	items := unwiredscore.ActionItems(gaps, "fak unwired-scorecard --json")

	var existing []dogfoodissues.Issue
	switch {
	case *existingJSON != "":
		b, err := os.ReadFile(*existingJSON)
		if err != nil {
			fmt.Fprintf(stderr, "fak unwired-debt-dispatch: %v\n", err)
			return 2
		}
		if err := json.Unmarshal(b, &existing); err != nil {
			fmt.Fprintf(stderr, "fak unwired-debt-dispatch: --existing-json must be a JSON list: %v\n", err)
			return 2
		}
	case *live || *fetchExisting:
		var err error
		existing, err = dogfoodissues.FetchExistingIssues(*repo, *limit)
		if err != nil {
			fmt.Fprintf(stderr, "fak unwired-debt-dispatch: %v\n", err)
			return 2
		}
	}

	buildOpt := dogfoodissues.BuildOptions{
		Live:           *live,
		DedupeChecked:  *existingJSON != "" || *fetchExisting || *live,
		DedupeCap:      *capN,
		ParentIssue:    *project.parent,
		ParentBaseline: project.baseline(), CompletionStandard: *project.standard, TargetEnvelope: *project.target, WitnessedEnvelope: *project.witnessed,
	}
	plan, skipped := dogfoodissues.BuildPlanWithOptions(items, existing, buildOpt)
	cohort := dogfoodissues.CohortPlan(items, buildOpt)

	mode := "dry-run"
	if *live {
		mode = "live"
	}
	result := dogfoodissues.Result{
		Schema:  dogfoodissues.Schema,
		Mode:    mode,
		Report:  "fak unwired-scorecard --json",
		Planned: plan,
		Synced:  []dogfoodissues.SyncRow{},
		Skipped: skipped,
		Cohort:  &cohort,
	}

	exit := 0
	if *live && len(plan) > 0 {
		result.Synced = dogfoodissues.Sync(plan, *repo, []string(labels), nil)
		for _, row := range result.Synced {
			if !row.OK {
				exit = 1
			}
		}
	}

	if code := emitJSONOrPrintln(stdout, stderr, "fak unwired-debt-dispatch", *asJSON, result, dogfoodissues.Render(result)); code != 0 {
		return code
	}
	return exit
}
