package studyadjacency

import (
	"bytes"
	"fmt"
	"io"
	"sort"
	"strings"
)

const generatedHeader = "<!-- Generated by fak study-adjacency render; DO NOT EDIT. -->"

// RenderMarkdown validates and renders a stable human summary. Collection
// ordering in the input is intentionally ignored.
func RenderMarkdown(manifest Manifest) ([]byte, error) {
	var output bytes.Buffer
	if err := WriteMarkdown(&output, manifest); err != nil {
		return nil, err
	}
	return output.Bytes(), nil
}

// WriteMarkdown writes the deterministic human summary to w.
func WriteMarkdown(w io.Writer, manifest Manifest) error {
	if err := Validate(manifest); err != nil {
		return err
	}

	var output strings.Builder
	fmt.Fprintln(&output, "---")
	fmt.Fprintf(&output, "title: %q\n", manifest.Title)
	fmt.Fprintf(&output, "description: %q\n", manifest.Scope.BoundedMeaning)
	fmt.Fprintln(&output, "---")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, generatedHeader)
	fmt.Fprintf(&output, "# %s\n\n", markdownText(manifest.Title))
	fmt.Fprintf(&output, "- **Schema:** `%s`\n", markdownCode(manifest.Schema))
	fmt.Fprintf(&output, "- **Manifest ID:** `%s`\n", markdownCode(manifest.ID))
	fmt.Fprintf(&output, "- **Bounded meaning:** %s\n\n", markdownText(manifest.Scope.BoundedMeaning))

	fmt.Fprintln(&output, "## Anchor corpus")
	fmt.Fprintln(&output)
	fmt.Fprintf(&output, "- **Repository:** `%s`\n", markdownCode(manifest.Anchor.Repository.String()))
	fmt.Fprintf(&output, "- **Revision:** `%s`\n", markdownCode(manifest.Anchor.Pin.Revision))
	fmt.Fprintf(&output, "- **Cutoff:** `%s`\n", markdownCode(manifest.Anchor.Pin.Cutoff))
	fmt.Fprintf(&output, "- **Observed:** `%s`\n", markdownCode(manifest.Anchor.Pin.ObservedAt))
	fmt.Fprintf(&output, "- **Normalized records:** %d\n", manifest.Anchor.NormalizedRecords)
	fmt.Fprintf(&output, "- **SHA-256:** `%s`\n", markdownCode(manifest.Anchor.SHA256))
	if strings.TrimSpace(manifest.Anchor.Notes) != "" {
		fmt.Fprintf(&output, "- **Notes:** %s\n", markdownText(manifest.Anchor.Notes))
	}
	fmt.Fprintln(&output)

	fmt.Fprintln(&output, "## Scope criteria")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "### Include")
	for _, criterion := range sortedStrings(manifest.Scope.InclusionCriteria) {
		fmt.Fprintf(&output, "- %s\n", markdownText(criterion))
	}
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "### Exclude")
	for _, criterion := range sortedStrings(manifest.Scope.ExclusionCriteria) {
		fmt.Fprintf(&output, "- %s\n", markdownText(criterion))
	}
	fmt.Fprintln(&output)

	declared := append([]Repository(nil), manifest.DeclaredRepositories...)
	sort.Slice(declared, func(i, j int) bool { return repositoryKey(declared[i]) < repositoryKey(declared[j]) })
	fmt.Fprintf(&output, "## Declared set (%d)\n\n", len(declared))
	for _, repository := range declared {
		fmt.Fprintf(&output, "- `%s`\n", markdownCode(repository.String()))
	}
	fmt.Fprintln(&output)

	members := append([]Member(nil), manifest.Members...)
	sort.Slice(members, func(i, j int) bool {
		return repositoryKey(members[i].Repository) < repositoryKey(members[j].Repository)
	})
	fmt.Fprintf(&output, "## Processed members (%d/%d)\n\n", len(members), len(declared))
	for _, member := range members {
		renderMember(&output, member)
	}

	_, err := io.WriteString(w, output.String())
	return err
}

func renderMember(output *strings.Builder, member Member) {
	fmt.Fprintf(output, "### %s (`%s`)\n\n", markdownText(member.Name), markdownCode(member.Repository.String()))
	fmt.Fprintf(output, "- **Revision:** `%s`\n", markdownCode(member.Pin.Revision))
	fmt.Fprintf(output, "- **Cutoff:** `%s`\n", markdownCode(member.Pin.Cutoff))
	fmt.Fprintf(output, "- **Observed:** `%s`\n", markdownCode(member.Pin.ObservedAt))
	fmt.Fprintf(output, "- **Processed:** yes\n")
	fmt.Fprintf(output, "- **Include because:** %s\n", markdownText(member.InclusionRationale))
	fmt.Fprintf(output, "- **Decision relation:** %s\n", markdownText(member.DecisionRelation))
	fmt.Fprintf(output, "- **Freshness:** %s\n", markdownText(member.FreshnessNotes))
	fmt.Fprintf(output, "- **Partials:** %s\n\n", markdownText(member.PartialNotes))

	receipts := append([]SourceClassReceipt(nil), member.SourceClassReceipts...)
	sort.Slice(receipts, func(i, j int) bool {
		return strings.ToLower(receipts[i].Class) < strings.ToLower(receipts[j].Class)
	})
	fmt.Fprintln(output, "#### Source-class receipts")
	fmt.Fprintln(output)
	fmt.Fprintln(output, "| Class | Status | Terminal receipt | Notes |")
	fmt.Fprintln(output, "|---|---|---|---|")
	for _, receipt := range receipts {
		terminal := "—"
		if strings.TrimSpace(receipt.TerminalReceipt) != "" {
			terminal = "`" + markdownCode(receipt.TerminalReceipt) + "`"
		}
		fmt.Fprintf(output, "| %s | `%s` | %s | %s |\n", markdownTable(receipt.Class), markdownCode(string(receipt.Status)), terminal, markdownTable(receipt.Notes))
	}
	fmt.Fprintln(output)

	candidates := append([]Candidate(nil), member.Candidates...)
	sort.Slice(candidates, func(i, j int) bool {
		return strings.ToLower(candidates[i].ID) < strings.ToLower(candidates[j].ID)
	})
	fmt.Fprintf(output, "#### Candidates (%d)\n\n", len(candidates))
	if len(candidates) == 0 {
		fmt.Fprintln(output, "No imported candidates.")
		fmt.Fprintln(output)
		return
	}
	fmt.Fprintln(output, "| ID | Candidate | Repository links | vLLM mechanism | Frontier-changing contrast | Rationale |")
	fmt.Fprintln(output, "|---|---|---|---|---|---|")
	for _, candidate := range candidates {
		links := append([]Repository(nil), candidate.RepositoryLinks...)
		sort.Slice(links, func(i, j int) bool { return repositoryKey(links[i]) < repositoryKey(links[j]) })
		linkText := make([]string, 0, len(links))
		for _, repository := range links {
			linkText = append(linkText, "`"+markdownCode(repository.String())+"`")
		}
		fmt.Fprintf(output, "| `%s` | %s | %s | %s | %s | %s |\n",
			markdownCode(candidate.ID),
			markdownTable(candidate.Title),
			strings.Join(linkText, "<br>"),
			markdownTable(emptyDash(candidate.VLLMMechanismLink)),
			markdownTable(emptyDash(candidate.FrontierChangingContrast)),
			markdownTable(candidate.Rationale),
		)
	}
	fmt.Fprintln(output)
}

func sortedStrings(values []string) []string {
	result := append([]string(nil), values...)
	sort.Slice(result, func(i, j int) bool { return strings.ToLower(result[i]) < strings.ToLower(result[j]) })
	return result
}

func markdownText(value string) string {
	value = strings.ReplaceAll(value, "\\", "\\\\")
	value = strings.ReplaceAll(value, "\r\n", "<br>")
	value = strings.ReplaceAll(value, "\n", "<br>")
	return strings.ReplaceAll(value, "|", "\\|")
}

func markdownTable(value string) string { return markdownText(value) }

func markdownCode(value string) string {
	return strings.ReplaceAll(value, "`", "\\`")
}

func emptyDash(value string) string {
	if strings.TrimSpace(value) == "" {
		return "—"
	}
	return value
}
