// Package milestonedoc renders the project's milestone CLIMB snapshot into a
// freshness-checked, committed markdown block, the milestone-shaped sibling of
// internal/supportmaturityscore's MatrixBlock (#1441, child of epic #1436).
//
// The contract mirrors the established --write-doc / --check-doc seam:
//
//   - WriteDoc splices Block() between two markers in docs/milestones/STATUS.md, so
//     the durable milestone state is a reviewable doc — not only an ephemeral Slack
//     card.
//   - CheckDoc reds (advisory) when the committed block drifts from the live fold,
//     the same freshness fence the support-maturity matrix rides.
//
// Only the CLIMB dimension is embedded. The fold logic stays in
// internal/milestonereport (read-only import here): Block() lowers the live
// covmatrix.Grid() onto the M0–M7 ladder via milestonereport.InterpretMaturity, so
// the committed block regenerates deterministically from in-process state and a stale
// cell becomes a failing gate, never a silent prose drift. The ROADMAP dimension is
// deliberately excluded from the committed block: it is read live from `gh` and is
// non-deterministic, so it can never be byte-stable across commits — it remains the
// Slack card's and the JSONL ledger's job. The block is ASCII-only so the committed
// bytes are byte-identical on every platform (no em-dash / middot to mojibake on a
// Windows checkout).
package milestonedoc

import (
	"fmt"
	"strings"

	"github.com/anthony-chaudhary/fak/internal/covmatrix"
	"github.com/anthony-chaudhary/fak/internal/milestonereport"
	"github.com/anthony-chaudhary/fak/internal/supportmaturity"
)

const (
	// Begin and End bound the generated block inside docs/milestones/STATUS.md. The
	// freshness check extracts the bytes between them and compares against Block().
	Begin = "<!-- BEGIN milestone-climb (generated by `fak milestone status-doc --write-doc`; do not hand-edit) -->"
	End   = "<!-- END milestone-climb -->"
)

// legend is the prose under the header line: one paragraph defining the climb and the
// ladder so the generated table reads on its own. ASCII-only, like the rest of the block.
const legend = "Generated from `internal/covmatrix` (the kernel's own model x backend grid) and " +
	"folded by `internal/milestonereport` (the CLIMB dimension) -- not hand-typed. Each cell's rung " +
	"is lowered from the live grid onto the closed M0-M7 support-maturity ladder; the distribution " +
	"below is WITNESSED, never self-reported, so the climb cannot be inflated. A cell is MATURED once " +
	"it reaches M4Correct (correctness witnessed by a CI-runnable oracle); cells below it are honest " +
	"positions on the ladder but still support-maturity debt. The epic ROADMAP dimension is read live " +
	"from `gh` and is non-deterministic, so it is NOT embedded here -- it rides the Slack card and the " +
	"durable JSONL trend ledger (`docs/milestones/history.jsonl`).\n\n"

// Block renders the generated milestone-climb block (markers inclusive),
// deterministically from covmatrix.Grid() folded by milestonereport.InterpretMaturity.
// The per-rung distribution and the worst-cell list change as a diff when a model or
// backend's support rung changes, so the committed doc tracks the climb.
func Block() string {
	m := milestonereport.InterpretMaturity(covmatrix.Grid())

	var b strings.Builder
	b.WriteString(Begin)
	b.WriteString("\n\n")
	fmt.Fprintf(&b, "**Climb %s** -- %d/%d cell(s) matured (M4+) -- progress **%.1f%%** across %d (model family x backend) cell(s)\n\n",
		dashIfEmpty(m.Highest), m.Matured, m.Cells, m.ProgressPct, m.Cells)
	b.WriteString(legend)

	// The ladder distribution as a stable table, one row per rung in ladder order so
	// an absent rung renders as 0, not a gap.
	b.WriteString("| Rung | Meaning | Cells |\n|---|---|---|\n")
	for _, r := range supportmaturity.Rungs {
		id := r.String()
		fmt.Fprintf(&b, "| %s | %s | %d |\n", id, r.Label(), m.Dist[id])
	}
	b.WriteString("\n")

	// The render-only worst list: the lowest-rung cells dragging the climb, in the
	// report's own deterministic order. Empty (all matured) renders an explicit line.
	if len(m.Worst) > 0 {
		b.WriteString("Lowest cells (dragging the climb): " + strings.Join(m.Worst, ", ") + "\n\n")
	} else {
		b.WriteString("Lowest cells (dragging the climb): none -- every cell is matured (M4+)\n\n")
	}
	b.WriteString(End)
	return b.String()
}

// Extract returns the generated block (markers inclusive) embedded in doc, or
// ("", false) when the two markers are not both present in order. The freshness check
// compares this against Block().
func Extract(doc string) (string, bool) {
	i := strings.Index(doc, Begin)
	if i < 0 {
		return "", false
	}
	j := strings.Index(doc[i:], End)
	if j < 0 {
		return "", false
	}
	return doc[i : i+j+len(End)], true
}

// Splice replaces the block between the markers in doc with a freshly generated
// Block() and returns the new doc. It errors when the markers are absent so the
// generator never guesses where to write.
func Splice(doc string) (string, error) {
	i := strings.Index(doc, Begin)
	if i < 0 {
		return "", fmt.Errorf("begin marker not found: %s", Begin)
	}
	j := strings.Index(doc[i:], End)
	if j < 0 {
		return "", fmt.Errorf("end marker not found after begin marker: %s", End)
	}
	end := i + j + len(End)
	return doc[:i] + Block() + doc[end:], nil
}

// Fresh reports whether the committed doc's embedded block equals the live Block().
// It is the pure predicate behind --check-doc: false when the markers are missing or
// the committed block drifted from the live fold.
func Fresh(doc string) bool {
	got, ok := Extract(doc)
	return ok && got == Block()
}

// Scaffold is the full STATUS.md a first `--write-doc` writes when the doc does not
// yet exist: a titled header, a one-line orientation, and an empty marker pair Splice
// then fills. Deterministic and ASCII-only so the first committed bytes are stable.
func Scaffold() string {
	// The marker pair starts adjacent; Splice fills Block() between them on the same
	// write, so the scaffold is never committed empty.
	var b strings.Builder
	b.WriteString("# Milestone status\n\n")
	b.WriteString("The durable, freshness-checked snapshot of the project's maturity CLIMB -- the model x backend\n")
	b.WriteString("grid's distribution across the closed M0-M7 support-maturity ladder. Generated from\n")
	b.WriteString("`internal/covmatrix` + `internal/milestonereport`; regenerate with\n")
	b.WriteString("`fak milestone status-doc --write-doc` and gate it with `--check-doc`. The block between the\n")
	b.WriteString("markers is generated -- do not hand-edit it.\n\n")
	b.WriteString(Begin)
	b.WriteString("\n")
	b.WriteString(End)
	b.WriteString("\n")
	return b.String()
}

func dashIfEmpty(s string) string {
	if strings.TrimSpace(s) == "" {
		return "-"
	}
	return s
}
