// Package supportmaturityscore grades the covmatrix support rungs as a scorecard.
//
// growth_debt is intentionally narrow: only silently undefined cells are hard debt.
// This card is stricter. It answers "how much of the declared model x backend grid is
// actually mature support?" A SUPPORTED cell is mature; PROOF-PATH-ONLY, FENCED, and
// UNDEFINED cells are honest positions on the ladder, but still support-maturity debt.
package supportmaturityscore

import (
	"fmt"
	"strings"

	"github.com/anthony-chaudhary/fak/internal/covmatrix"
	"github.com/anthony-chaudhary/fak/pkg/scorecard"
)

const (
	// Schema is the control-pane schema id for this scorecard.
	Schema = "fak-support-maturity-scorecard/1"
	// DebtKey is the headline integer the control pane folds.
	DebtKey = "support_maturity_debt"
)

// Build folds the live coverage matrix into a support-maturity scorecard payload.
func Build() scorecard.Payload {
	cells := covmatrix.Grid()
	counts := countBy(cells)
	supported := counts[covmatrix.Supported]
	total := len(cells)

	var defects []string
	for _, c := range cells {
		if c.Support == covmatrix.Supported {
			continue
		}
		defects = append(defects, fmt.Sprintf("%s x %s is %s", c.Family, c.Backend, c.Support))
	}

	kpi := scorecard.KPI{
		Key:     "supported_cell_coverage",
		Group:   "maturity",
		Score:   pct(supported, total),
		Detail:  fmt.Sprintf("%d/%d model x backend cells are SUPPORTED", supported, total),
		Defects: defects,
	}

	return scorecard.Fold(Schema, []scorecard.KPI{kpi}, DebtKey, nil, scorecard.Messages{
		Finding: fmt.Sprintf("%d model x backend cell(s) below the SUPPORTED maturity rung",
			len(defects)),
		FindingClean:    fmt.Sprintf("all %d model x backend cells are SUPPORTED", total),
		NextAction:      "retire support-maturity debt by moving proof-path/fenced/undefined cells to SUPPORTED with a CI witness",
		NextActionClean: "hold the line: re-run the support-maturity scorecard on every model/backend change",
		ExtraCorpus: map[string]any{
			"families":             len(covmatrix.Families),
			"backends":             len(covmatrix.Backends),
			"cells":                total,
			"supported":            supported,
			"proof_path_only":      counts[covmatrix.ProofPathOnly],
			"fenced":               counts[covmatrix.Fenced],
			"undefined":            counts[covmatrix.Undefined],
			"support_coverage_pct": scorecard.Round1(pct(supported, total)),
		},
	})
}

func countBy(cells []covmatrix.Cell) map[covmatrix.Support]int {
	m := map[covmatrix.Support]int{}
	for _, c := range cells {
		m[c.Support]++
	}
	return m
}

func pct(n, total int) float64 {
	if total == 0 {
		return 100
	}
	return 100 * float64(n) / float64(total)
}

// The generated support-maturity matrix view embedded in docs/HARDWARE-MATRIX.md (#1255,
// E6 of epic #1243). The matrix cells are GENERATED from the same covmatrix.Grid() the
// scorecard folds, never hand-typed: `fak support-maturity-scorecard --write-doc` splices
// MatrixBlock() between the two markers, and --check-doc (plus the cmd/fak freshness test)
// reds the trunk when a committed cell drifts from the live grid. That is the "view of the
// instrument, kept honest by the same freshness check as the other scorecards" the epic
// asks for: a stale cell becomes a failing gate, not a silent prose drift.
const (
	// MatrixBegin and MatrixEnd bound the generated block inside docs/HARDWARE-MATRIX.md.
	MatrixBegin = "<!-- BEGIN support-maturity-matrix (generated by `fak support-maturity-scorecard --write-doc`; do not hand-edit) -->"
	MatrixEnd   = "<!-- END support-maturity-matrix -->"
)

// matrixLegend is the prose under the header line; one paragraph defining each rung so the
// generated table reads on its own. ASCII-only, like the rest of the block.
const matrixLegend = "Generated from `internal/covmatrix` (the kernel's own model x backend grid) and " +
	"folded by `internal/supportmaturityscore` -- not hand-typed. Each cell is the support rung " +
	"of one (model family x backend): SUPPORTED (runs with a CI witness on this path), " +
	"PROOF-PATH-ONLY (runs on the cpu scalar path, no CI numeric oracle), FENCED (the accelerated " +
	"path refuses honestly rather than diverge), UNDEFINED (a silently-reachable wrong result -- " +
	"the debt this view exists to catch).\n\n"

// MatrixBlock renders the generated support-maturity matrix block (markers inclusive),
// deterministically from covmatrix.Grid() + the folded scorecard. Columns are derived from
// covmatrix.Backends and rows from Grid()'s deterministic family order, so adding a backend
// or family changes the doc as a diff. The block is ASCII-only so the committed bytes are
// byte-identical on every platform (no em-dash / middot to mojibake on a Windows checkout).
func MatrixBlock() string {
	p := Build()
	c := p.Corpus
	cells := covmatrix.Grid()
	backends := covmatrix.Backends

	byFamily := map[string]map[string]string{}
	topo := map[string]string{}
	var familyOrder []string
	for _, cell := range cells {
		if _, ok := byFamily[cell.Family]; !ok {
			byFamily[cell.Family] = map[string]string{}
			topo[cell.Family] = cell.Topology
			familyOrder = append(familyOrder, cell.Family)
		}
		byFamily[cell.Family][cell.Backend] = string(cell.Support)
	}

	var b strings.Builder
	b.WriteString(MatrixBegin)
	b.WriteString("\n\n")
	fmt.Fprintf(&b, "**Grade %v** - score %v - support_maturity_debt **%v** - %v/%v model x backend cells SUPPORTED\n\n",
		c["grade"], c["score"], c[DebtKey], c["supported"], c["cells"])
	b.WriteString(matrixLegend)

	b.WriteString("| Model family | Topology |")
	for _, bk := range backends {
		b.WriteString(" " + bk + " |")
	}
	b.WriteString("\n|---|---|")
	for range backends {
		b.WriteString("---|")
	}
	b.WriteString("\n")
	for _, fam := range familyOrder {
		row := byFamily[fam]
		fmt.Fprintf(&b, "| %s | %s |", fam, topo[fam])
		for _, bk := range backends {
			b.WriteString(" " + row[bk] + " |")
		}
		b.WriteString("\n")
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "Counts: %v SUPPORTED, %v PROOF-PATH-ONLY, %v FENCED, %v UNDEFINED across %v cells (%v families x %v backends).\n\n",
		c["supported"], c["proof_path_only"], c["fenced"], c["undefined"], c["cells"], c["families"], c["backends"])
	b.WriteString(MatrixEnd)
	return b.String()
}

// ExtractMatrixBlock returns the generated block (markers inclusive) embedded in doc, or
// ("", false) when the two markers are not both present in order. The freshness check
// compares this against MatrixBlock().
func ExtractMatrixBlock(doc string) (string, bool) {
	i := strings.Index(doc, MatrixBegin)
	if i < 0 {
		return "", false
	}
	j := strings.Index(doc[i:], MatrixEnd)
	if j < 0 {
		return "", false
	}
	return doc[i : i+j+len(MatrixEnd)], true
}

// SpliceMatrixBlock replaces the block between the markers in doc with a freshly generated
// MatrixBlock() and returns the new doc. It errors when the markers are absent so the
// generator never guesses where to write.
func SpliceMatrixBlock(doc string) (string, error) {
	i := strings.Index(doc, MatrixBegin)
	if i < 0 {
		return "", fmt.Errorf("begin marker not found: %s", MatrixBegin)
	}
	j := strings.Index(doc[i:], MatrixEnd)
	if j < 0 {
		return "", fmt.Errorf("end marker not found after begin marker: %s", MatrixEnd)
	}
	end := i + j + len(MatrixEnd)
	return doc[:i] + MatrixBlock() + doc[end:], nil
}
