package ctxplan

import (
	"strconv"
	"strings"
)

// objective.go — issue #1583: the OBJECTIVE PIN, the runtime continuity contract for the
// user's ACTIVE GOAL across a hidden restart (a ctxplan replan, a session reset, a
// session migration). Session budgets, reset carryover (sessionreset.BuildSeed), and the
// planned view (ctxplan.Plan/Forecast) already exist; the page-fault protocol (pagefault.go,
// #1587) already makes a missing SPAN produce exactly one closed-vocabulary decision instead
// of silent omission. What was missing is the analogous contract for the single span that
// matters most: the standing objective a long-running session is granted once and must not
// lose, drop, or silently rewrite while it re-arms context underneath the user.
//
// THE MODEL. An ObjectivePin is a stable, addressable span: PinID never changes for the
// life of the objective (it is assigned once, at first pin, and threaded through every
// replan/reset); Digest is a content address over the pin's identity-relevant fields, so
// "the pin was preserved" is a checkable equality (ReconcileObjective), not a narrative
// claim. A replan or reset is free to change EVERYTHING else about the resident view — it
// must not change the pin's PinID or Digest without producing a visible, typed outcome.
//
// RELATIONSHIP TO pagefault.go. This file reuses #1587's closed-vocabulary-decision shape
// wholesale: ObjectiveOutcome mirrors PageFaultOutcome (an exhaustive, closed set — no
// "no decision" state), ReconcileObjective mirrors DecidePageFault (a pure function of
// (before, after, policy) with no clock/randomness), and ObjectiveLog mirrors PageFaultLog
// (append-only, Replay-checkable, Explain-able). Where pagefault.go decides what to do about
// a MISSING span, this file decides what to do about a DRIFTED pin — but the "exactly one
// closed-vocabulary outcome, never silent" discipline is identical, so a caller already
// familiar with the page-fault protocol reads this one for free.
//
// DETERMINISM. ReconcileObjective is pure: no clock, no randomness, no I/O. The same
// (before, after, policy) always yields the same ObjectiveDecision, so a decision is
// REPLAYABLE — ObjectiveLog.Replay recomputes every logged decision from its persisted
// (before, after, policy) triple and reports any entry whose recomputed outcome no longer
// matches the stored one (DIVERGED), mirroring PageFaultLog.Replay's divergence detection.
//
// PERSISTED STATE. ObjectivePin itself is the durable record (mirroring dormancy.Stamp's
// "plain fields that survive a JSON round-trip and a process restart" discipline: no
// monotonic clock reading, no in-memory-only handle — PinID/Digest/Text are all plain
// strings). ObjectiveLog is the append-only ledger of (before, after, decision) transitions
// a host records across every replan/reset, giving the "deterministic runtime object with
// persisted state, typed transitions, and replayable witnesses" the issue asks for.

// ObjectivePin is the user's active objective represented as a stable, addressable span.
// PinID is the identity that must survive every replan and reset unchanged (assigned once,
// at NewObjectivePin, and carried forward by every later pin derived from it); Digest is a
// content address over the fields that define WHAT the objective is, so two pins with the
// same PinID can still be compared for content drift (an accidental rewrite of the text
// under a preserved identity, which is exactly as dangerous as losing the pin outright).
//
// A pin is deliberately NOT a Span: it is not a candidate for the resident-view knapsack
// (Optimize never scores it, Candidates never lists it) — it is out-of-band structural
// state the planner and the reset both consult, the same way a system/developer pin sits
// outside the knapsack in the Layout's base area. SourceSpanID optionally names the Span
// (if any) the objective was extracted from, so a caller that also runs the pin through the
// resident-view planner can cross-reference the two without this package importing Layout.
type ObjectivePin struct {
	// PinID is the stable identity of this objective — assigned once and never
	// regenerated by a replan/reset. Two pins with the same PinID are claims about the
	// SAME objective; ReconcileObjective compares their Digest to check whether the
	// claim held.
	PinID string `json:"pin_id"`
	// Text is the objective statement itself — the SAFE, human-readable span content
	// (mirrors Span.Descriptor: extractive text, never sealed bytes).
	Text string `json:"text"`
	// Digest is the canonical content address (Digest(), sha256 hex) over PinID+Text —
	// the identity+content fingerprint a replan/reset must reproduce unchanged for the
	// pin to count as PRESERVED. Computed by NewObjectivePin / Rehash, never hand-set,
	// so a caller cannot construct a pin whose Digest lies about its Text.
	Digest string `json:"digest"`
	// Step is the ordinal position (mirrors Span.Step) the objective was pinned at —
	// carried for audit ordering only; it does not participate in the Digest.
	Step int `json:"step,omitempty"`
	// SourceSpanID optionally names the Span this objective was extracted from (e.g. the
	// first durable user line sessionreset.taskDistill already identifies), for a caller
	// that wants to cross-reference the pin against the resident-view store.
	SourceSpanID string `json:"source_span_id,omitempty"`
}

// digestFields renders the identity+content fields of a pin into the canonical byte
// sequence Digest hashes — PinID and Text only, so Step/SourceSpanID (pure audit metadata)
// can change without moving the digest, and so hashing is a pure function of exactly the
// fields ReconcileObjective treats as "what the objective is."
func digestFields(pinID, text string) []byte {
	// A NUL separator prevents a PinID/Text boundary ambiguity (the same discipline
	// plancache.go's field-writer uses) — "ab"+"c" and "a"+"bc" must not collide.
	return []byte(pinID + "\x00" + text)
}

// NewObjectivePin constructs a fresh, freestanding objective pin: pinID is assigned by the
// caller (a caller minting the FIRST pin for a session typically uses a fresh id; a caller
// deriving a successor pin across a replan/reset reuses the PRIOR PinID so identity is
// preserved by construction — see Rehash for the content-changed case). The Digest is
// always computed here, never accepted as input, so a pin's Digest can never disagree with
// its own Text.
func NewObjectivePin(pinID, text string, step int) ObjectivePin {
	p := ObjectivePin{PinID: strings.TrimSpace(pinID), Text: strings.TrimSpace(text), Step: step}
	p.Digest = Digest(digestFields(p.PinID, p.Text))
	return p
}

// Rehash returns a copy of p with its Digest recomputed from its current PinID/Text. It is
// the escape hatch for a caller that legitimately edits Text (e.g. the user restates the
// objective) and wants a NEW, self-consistent Digest under the SAME PinID — as opposed to
// ReconcileObjective, which treats any Text change under an unchanged PinID as drift to be
// caught, not silently absorbed. A host that intentionally revises the objective calls
// Rehash and then re-pins explicitly; it never happens implicitly inside this package.
func (p ObjectivePin) Rehash() ObjectivePin {
	p.Digest = Digest(digestFields(p.PinID, p.Text))
	return p
}

// Verify reports whether p's stored Digest actually matches a fresh hash of its own
// PinID+Text — the tamper/corruption check for a pin that arrived over the wire or was
// loaded from persisted state, mirroring the fail-closed posture ValidPageFaultOutcome
// applies to a deserialized PageFaultOutcome. A pin failing Verify must never be trusted as
// "preserved" by ReconcileObjective — see reconcileObjectiveState's corrupt-input handling.
func (p ObjectivePin) Verify() bool {
	return p.Digest == Digest(digestFields(p.PinID, p.Text))
}

// IsZero reports whether p is the unset pin (never pinned) — the "no active objective yet"
// state, distinct from a pin with empty Text but a real PinID.
func (p ObjectivePin) IsZero() bool { return p.PinID == "" && p.Digest == "" }

// ObjectiveOutcome is the CLOSED vocabulary of dispositions for an objective-pin
// reconciliation across a replan/reset — the decision a caller makes the instant a
// before/after pin PAIR is compared. Exactly one outcome is produced per reconciliation;
// there is no "no decision" state, which is what keeps a dropped or silently rewritten pin
// from ever passing through unnoticed. Mirrors PageFaultOutcome's shape one-for-one.
type ObjectiveOutcome string

const (
	// ObjectivePreserved: the pin's PinID and Digest are IDENTICAL before and after —
	// the objective survived the replan/reset byte-for-byte. The common, silent-success
	// case: no refusal, no query, carryover simply worked.
	ObjectivePreserved ObjectiveOutcome = "preserved"
	// ObjectiveEstablished: there was no prior pin (before is zero) and the after pin is
	// well-formed — the FIRST pin of a session, not a carryover at all. Distinguished
	// from ObjectivePreserved so a caller/log can tell "this is turn one" from "this
	// survived a reset," which matters for an audit trying to reconstruct history.
	ObjectiveEstablished ObjectiveOutcome = "established"
	// ObjectiveDropped: there WAS a prior pin and the after pin is zero (or carries a
	// different PinID with no reconciling link) — a reset silently lost the objective.
	// This is the failure #1583 exists to make impossible-by-construction: a caller
	// hitting this outcome MUST surface a visible refusal/query, never proceed as if
	// nothing happened.
	ObjectiveDropped ObjectiveOutcome = "dropped"
	// ObjectiveDrifted: the PinID matches (same claimed identity) but the Digest does
	// NOT — the objective's content was silently rewritten under a preserved identity.
	// This is the subtler failure: an identity-preserving carryover that paraphrased or
	// truncated the objective is just as dangerous as dropping it, because a caller
	// trusting PinID equality alone would never notice.
	ObjectiveDrifted ObjectiveOutcome = "drifted"
	// ObjectiveQueryUser: the reconciler cannot determine whether the after pin is a
	// faithful carryover of the before pin (e.g. the after pin fails Verify — its Digest
	// does not match its own content, so it is corrupt/tampered input, not a trustworthy
	// claim either way). Ask rather than assume; mirrors PageFaultQueryUser's posture
	// for a live-but-not-safely-reconstructable span.
	ObjectiveQueryUser ObjectiveOutcome = "query_user"
)

// validObjectiveOutcomes is the membership set ReconcileObjective always produces one
// member of — used by tests and by any caller (de)serializing a persisted decision to fail
// closed on a corrupt/foreign value rather than silently accept it.
var validObjectiveOutcomes = map[ObjectiveOutcome]bool{
	ObjectivePreserved:   true,
	ObjectiveEstablished: true,
	ObjectiveDropped:     true,
	ObjectiveDrifted:     true,
	ObjectiveQueryUser:   true,
}

// ValidObjectiveOutcome reports whether o is a member of the closed vocabulary.
func ValidObjectiveOutcome(o ObjectiveOutcome) bool { return validObjectiveOutcomes[o] }

func (o ObjectiveOutcome) String() string {
	if ValidObjectiveOutcome(o) {
		return string(o)
	}
	if o == "" {
		return "(unset)"
	}
	return "unknown(" + string(o) + ")"
}

// Refusal reports whether this outcome is a REFUSAL — a disposition a caller must surface
// to the user rather than silently continue past. ObjectiveDropped and ObjectiveDrifted are
// both refusals (a reset that cannot preserve the pin must say so); ObjectiveQueryUser is
// also refusal-shaped (it blocks silent continuation) even though it is a question rather
// than a hard deny. ObjectivePreserved and ObjectiveEstablished are not.
func (o ObjectiveOutcome) Refusal() bool {
	switch o {
	case ObjectiveDropped, ObjectiveDrifted, ObjectiveQueryUser:
		return true
	default:
		return false
	}
}

// ObjectiveDecision is the typed transition ReconcileObjective produces: the outcome, the
// reason it was chosen (an operator-readable EXPLAIN, mirroring PageFaultDecision.Reason),
// and the before/after pins it was computed from (echoed back so a decision is
// self-describing and a persisted log entry needs no side join).
type ObjectiveDecision struct {
	PinID   string           `json:"pin_id,omitempty"`
	Step    int              `json:"step,omitempty"`
	Outcome ObjectiveOutcome `json:"outcome"`
	Reason  string           `json:"reason"`
	Before  ObjectivePin     `json:"before"`
	After   ObjectivePin     `json:"after"`
}

// ReconcileObjective is the deterministic decision function: given the pin state BEFORE a
// replan/reset and the pin state AFTER, it returns EXACTLY ONE closed-vocabulary outcome —
// never a silent no-decision. It is pure (no clock, no randomness, no I/O), so the same
// (before, after) pair always reproduces the same decision, which is what makes a persisted
// ObjectiveLog replayable (mirrors DecidePageFault's determinism contract).
//
// Decision order (first match wins, most safety-critical first):
//
//  1. before is zero AND after is zero -> ObjectivePreserved. Nothing was ever pinned and
//     still isn't; trivially "preserved" (there is nothing to lose). Distinguished from
//     ObjectiveEstablished by after also being zero.
//  2. before is zero AND after is well-formed -> ObjectiveEstablished. The first pin of a
//     session — not a carryover, a fresh grant.
//  3. before is well-formed AND after is zero -> ObjectiveDropped. A reset silently lost
//     the objective; this is the exact silent-omission failure #1583 closes. Refusal.
//  4. after fails Verify (its Digest does not match its own PinID+Text) -> ObjectiveQueryUser.
//     The after pin is corrupt/tampered input — untrustworthy in either direction, so ask
//     rather than assume it is a faithful carryover OR a genuine drift.
//  5. before.PinID != after.PinID -> ObjectiveDropped. The reset re-pinned a DIFFERENT
//     objective under a fresh identity without ever producing a reconciling link back to
//     the original — from the original pin's point of view it was dropped, not renamed.
//  6. before.PinID == after.PinID AND before.Digest == after.Digest -> ObjectivePreserved.
//     The exact byte-for-byte survival case.
//  7. before.PinID == after.PinID AND before.Digest != after.Digest -> ObjectiveDrifted.
//     Same claimed identity, different content — a silent rewrite under a preserved id.
//     Refusal.
func ReconcileObjective(before, after ObjectivePin) ObjectiveDecision {
	out := ObjectiveDecision{Before: before, After: after}
	if after.PinID != "" {
		out.PinID = after.PinID
		out.Step = after.Step
	} else {
		out.PinID = before.PinID
		out.Step = before.Step
	}

	switch {
	case before.IsZero() && after.IsZero():
		out.Outcome = ObjectivePreserved
		out.Reason = "no objective pinned before or after: nothing to carry over"
	case before.IsZero() && !after.IsZero():
		out.Outcome = ObjectiveEstablished
		out.Reason = "no prior pin: this is the first objective pin, not a carryover"
	case !before.IsZero() && after.IsZero():
		out.Outcome = ObjectiveDropped
		out.Reason = "prior pin existed but no pin survived the reset: silently dropped"
	case !after.Verify():
		out.Outcome = ObjectiveQueryUser
		out.Reason = "carried-over pin fails its own digest check: corrupt or tampered, cannot trust either way"
	case before.PinID != after.PinID:
		out.Outcome = ObjectiveDropped
		out.Reason = "carried-over pin has a different identity with no reconciling link: original pin dropped"
	case before.Digest == after.Digest:
		out.Outcome = ObjectivePreserved
		out.Reason = "pin identity and content are byte-identical before and after"
	default:
		out.Outcome = ObjectiveDrifted
		out.Reason = "pin identity preserved but content digest changed: silently rewritten"
	}
	return out
}

// ObjectiveLog is the append-only, replayable ledger of objective reconciliations — the
// PERSISTED-STATE half of the runtime continuity contract. Entries are kept in occurrence
// order; Replay recomputes every entry's decision from its stored (before, after) pair and
// reports any DIVERGED entry, so a caller can tell "was this decision reproduced" from real
// evidence instead of trusting the stored Decision field blindly. The zero value is a usable
// empty log. Mirrors PageFaultLog one-for-one.
type ObjectiveLog struct {
	entries []ObjectiveLogEntry
}

// ObjectiveLogEntry pairs one logged (before, after) reconciliation with the decision
// computed for it, so the log is self-contained: replaying it needs no external state.
type ObjectiveLogEntry struct {
	Before   ObjectivePin      `json:"before"`
	After    ObjectivePin      `json:"after"`
	Decision ObjectiveDecision `json:"decision"`
}

// Append reconciles (before, after), records the (before, after, decision) as the next
// entry, and returns the decision — the one call sites need to both persist the transition
// and act on it. It never mutates a prior entry: ObjectiveLog is append-only, matching the
// audit posture the rest of ctxplan uses (Elision/Selection/PageFaultLog records are never
// edited in place, only added to).
func (l *ObjectiveLog) Append(before, after ObjectivePin) ObjectiveDecision {
	d := ReconcileObjective(before, after)
	l.entries = append(l.entries, ObjectiveLogEntry{Before: before, After: after, Decision: d})
	return d
}

// Entries returns a defensive copy of the logged entries in occurrence order.
func (l *ObjectiveLog) Entries() []ObjectiveLogEntry {
	return append([]ObjectiveLogEntry(nil), l.entries...)
}

// Latest returns the most recently logged AFTER pin — the pin a caller should treat as
// "currently active" — and whether the log has any entries at all. A caller starting a new
// replan/reset uses this as the BEFORE pin of its next Append call, chaining reconciliations
// across an arbitrary number of resets.
func (l *ObjectiveLog) Latest() (ObjectivePin, bool) {
	if len(l.entries) == 0 {
		return ObjectivePin{}, false
	}
	return l.entries[len(l.entries)-1].After, true
}

// ObjectiveReplayVerdict is the outcome of replaying one logged entry: whether recomputing
// ReconcileObjective from the stored (before, after) pair reproduces the stored decision.
type ObjectiveReplayVerdict struct {
	PinID      string           `json:"pin_id,omitempty"`
	Stored     ObjectiveOutcome `json:"stored"`
	Recomputed ObjectiveOutcome `json:"recomputed"`
	Diverged   bool             `json:"diverged"`
}

// Replay recomputes ReconcileObjective for every logged entry from its own stored
// (Before, After) and compares the result against the stored Decision. A log built from
// pure inputs always replays with zero diverged entries — that is the replayability witness
// this type exists to make checkable (mirrors PageFaultLog.Replay). A non-empty diverged
// result means either the log was tampered with or ReconcileObjective's logic changed
// incompatibly since the entry was recorded.
func (l *ObjectiveLog) Replay() (verdicts []ObjectiveReplayVerdict, allMatch bool) {
	allMatch = true
	for _, e := range l.entries {
		got := ReconcileObjective(e.Before, e.After)
		v := ObjectiveReplayVerdict{
			PinID:      e.Decision.PinID,
			Stored:     e.Decision.Outcome,
			Recomputed: got.Outcome,
			Diverged:   got.Outcome != e.Decision.Outcome,
		}
		if v.Diverged {
			allMatch = false
		}
		verdicts = append(verdicts, v)
	}
	return verdicts, allMatch
}

// ObjectiveSummary folds the log into outcome counts — the O(1) health signal a debug
// surface prints instead of walking every entry (mirrors PageFaultSummary's role).
type ObjectiveSummary struct {
	Preserved   int `json:"preserved"`
	Established int `json:"established"`
	Dropped     int `json:"dropped"`
	Drifted     int `json:"drifted"`
	QueryUser   int `json:"query_user"`
}

// Summary computes the outcome-class counts over every logged entry.
func (l *ObjectiveLog) Summary() ObjectiveSummary {
	var s ObjectiveSummary
	for _, e := range l.entries {
		switch e.Decision.Outcome {
		case ObjectivePreserved:
			s.Preserved++
		case ObjectiveEstablished:
			s.Established++
		case ObjectiveDropped:
			s.Dropped++
		case ObjectiveDrifted:
			s.Drifted++
		case ObjectiveQueryUser:
			s.QueryUser++
		}
	}
	return s
}

// Clean reports whether the log contains ZERO refusal-shaped outcomes (Dropped, Drifted,
// QueryUser) — the O(1) gate the issue's "done condition" reduces to: a session whose
// ObjectiveLog is Clean never had its objective pin silently dropped or rewritten.
func (s ObjectiveSummary) Clean() bool {
	return s.Dropped == 0 && s.Drifted == 0 && s.QueryUser == 0
}

// Explain renders the log as an operator-readable report, in the PageFaultLog.Explain /
// Plan.Explain style: one line per decision plus the outcome-count footer.
func (l *ObjectiveLog) Explain() string {
	var b strings.Builder
	s := l.Summary()
	b.WriteString("ctxplan objective-pin log: " + strconv.Itoa(len(l.entries)) + " reconciliation(s)\n")
	for _, e := range l.entries {
		b.WriteString("  [step ")
		b.WriteString(strconv.Itoa(e.Decision.Step))
		b.WriteString("] ")
		b.WriteString(e.Decision.PinID)
		b.WriteString(" -> ")
		b.WriteString(string(e.Decision.Outcome))
		b.WriteString(": ")
		b.WriteString(e.Decision.Reason)
		b.WriteString("\n")
	}
	b.WriteString("  totals: preserved=" + strconv.Itoa(s.Preserved) +
		" established=" + strconv.Itoa(s.Established) +
		" dropped=" + strconv.Itoa(s.Dropped) +
		" drifted=" + strconv.Itoa(s.Drifted) +
		" query_user=" + strconv.Itoa(s.QueryUser) +
		" clean=" + strconv.FormatBool(s.Clean()) + "\n")
	return b.String()
}
