package compute

import "testing"

// zzscaffbuildgolden_arch_test.go — GENERATED by `fak backend scaffold zzscaffbuildgolden`. Host-tractable witnesses
// for the zzscaffbuildgolden device taxonomy: every assertion here is hardware-independent, so this
// file is green on any host right after generation, before any device code exists.

func TestZzscaffbuildgoldenArchLookupKnown(t *testing.T) {
	for _, a := range KnownZzscaffbuildgoldenArches() {
		got, ok := LookupZzscaffbuildgoldenArch(a.Target)
		if !ok {
			t.Fatalf("LookupZzscaffbuildgoldenArch(%q): not found, want supported", a.Target)
		}
		if got.Target != a.Target {
			t.Errorf("Target = %q, want %q", got.Target, a.Target)
		}
		for _, al := range a.aliases {
			if _, ok := LookupZzscaffbuildgoldenArch(al); !ok {
				t.Errorf("alias %q for %q did not resolve", al, a.Target)
			}
		}
	}
}

// TestZzscaffbuildgoldenArchNormalizationRejectsUnsupported pins the fail-closed contract: an
// unrecognized device string must never resolve to a target.
func TestZzscaffbuildgoldenArchNormalizationRejectsUnsupported(t *testing.T) {
	for _, in := range []string{"", "not-a-real-device", "unknown-gen99"} {
		if got, ok := ZzscaffbuildgoldenToken(in); ok {
			t.Errorf("ZzscaffbuildgoldenToken(%q) = (%q,true), want unsupported", in, got)
		}
	}
}

// TestZzscaffbuildgoldenArchTokenRoundTrips checks the canonical token normalizes to itself and that
// case noise on a known alias still resolves.
func TestZzscaffbuildgoldenArchTokenRoundTrips(t *testing.T) {
	arches := KnownZzscaffbuildgoldenArches()
	if len(arches) == 0 {
		t.Fatal("KnownZzscaffbuildgoldenArches() returned no rows; the seed row was removed without a replacement")
	}
	first := arches[0]
	if tok, ok := ZzscaffbuildgoldenToken(first.Target); !ok || tok != first.Target {
		t.Errorf("ZzscaffbuildgoldenToken(%q) = (%q,%v), want (%q,true)", first.Target, tok, ok, first.Target)
	}
}
