//go:build custom

// zzscaffbuildgolden_backend.go — GENERATED by `fak backend scaffold zzscaffbuildgolden --lane custom` (issue #1685).
// This is the cgo registration stub for the zzscaffbuildgolden backend: it registers an Approx
// backend named "custom" into the EXISTING compute.Register/Pick seam, unchanged — adding a
// backend is a registration, never a forward-loop edit, exactly as cuda.go/vulkan.go/
// metal.go do. TODO: every op body below panics with "not implemented"; replace each
// with a call into your vendor's device library (see cuda.go / vulkan.go for the cgo
// wrapper shape, or metal.go for a from-scratch Go+ObjC example). Until then this file
// only compiles under -tags custom; the default `go build ./...` excludes it entirely.

package compute

func init() {
	// TODO: probe for a reachable device here; return without registering if none is
	// found, so a binary built with -tags custom on a host with no device still falls back
	// to cpu-ref (the Reference Default), exactly as metal.go's init does when MPS is
	// unavailable.
	Register(&zzscaffbuildgoldenBackend{name: "custom", tier: "TODO"})
}

// ZzscaffbuildgoldenBackend implements compute.Backend. It is an Approx backend (never Reference —
// RequireReference must stay false for every device backend; see compute.go's
// CorrectnessClass doc).
type zzscaffbuildgoldenBackend struct {
	name string
	tier string
}

func (c *zzscaffbuildgoldenBackend) Name() string            { return c.name }
func (c *zzscaffbuildgoldenBackend) Tier() string            { return c.tier }
func (c *zzscaffbuildgoldenBackend) Class() CorrectnessClass { return Approx }
func (c *zzscaffbuildgoldenBackend) Caps() Caps              { return Caps{} } // TODO: advertise this device's real capabilities

func (c *zzscaffbuildgoldenBackend) Upload(t Tensor, as Dtype) Tensor {
	panic("compute: zzscaffbuildgolden.Upload not implemented (scaffold TODO)")
}
func (c *zzscaffbuildgoldenBackend) Host(t Tensor) ([]float32, bool) {
	panic("compute: zzscaffbuildgolden.Host not implemented (scaffold TODO)")
}
func (c *zzscaffbuildgoldenBackend) Read(t Tensor) []float32 {
	panic("compute: zzscaffbuildgolden.Read not implemented (scaffold TODO)")
}
func (c *zzscaffbuildgoldenBackend) Free(t Tensor) {
	panic("compute: zzscaffbuildgolden.Free not implemented (scaffold TODO)")
}
func (c *zzscaffbuildgoldenBackend) NewKV(cfg KVConfig) KVStore {
	panic("compute: zzscaffbuildgolden.NewKV not implemented (scaffold TODO)")
}
func (c *zzscaffbuildgoldenBackend) MatMul(w, x Tensor) Tensor {
	panic("compute: zzscaffbuildgolden.MatMul not implemented (scaffold TODO)")
}
func (c *zzscaffbuildgoldenBackend) BatchedMatMul(w, X Tensor, P int) Tensor {
	panic("compute: zzscaffbuildgolden.BatchedMatMul not implemented (scaffold TODO)")
}
func (c *zzscaffbuildgoldenBackend) RMSNorm(x, weight Tensor, eps float32) Tensor {
	panic("compute: zzscaffbuildgolden.RMSNorm not implemented (scaffold TODO)")
}
func (c *zzscaffbuildgoldenBackend) RoPE(x Tensor, pos, nHeads, headDim int, theta float64) Tensor {
	panic("compute: zzscaffbuildgolden.RoPE not implemented (scaffold TODO)")
}
func (c *zzscaffbuildgoldenBackend) SwiGLU(gate, up Tensor) Tensor {
	panic("compute: zzscaffbuildgolden.SwiGLU not implemented (scaffold TODO)")
}
func (c *zzscaffbuildgoldenBackend) AddInPlace(dst, src Tensor) {
	panic("compute: zzscaffbuildgolden.AddInPlace not implemented (scaffold TODO)")
}
func (c *zzscaffbuildgoldenBackend) AddBias(dst, bias Tensor) {
	panic("compute: zzscaffbuildgolden.AddBias not implemented (scaffold TODO)")
}
func (c *zzscaffbuildgoldenBackend) Attention(q Tensor, kv KVStore, layer int, causal bool, grp int, scale float32) Tensor {
	panic("compute: zzscaffbuildgolden.Attention not implemented (scaffold TODO)")
}
func (c *zzscaffbuildgoldenBackend) Argmax(logits Tensor) int {
	panic("compute: zzscaffbuildgolden.Argmax not implemented (scaffold TODO)")
}
