package compute

// zzscaffbuildgolden_arch.go — GENERATED by `fak backend scaffold zzscaffbuildgolden --lane custom` (issue #1685).
// This is the always-compiled, hardware-independent half of the zzscaffbuildgolden backend: the
// device/arch taxonomy a CUSTOM build needs BEFORE any kernel runs. It has no build tag and
// is unit-witnessed on any host — the same split ROCM-C002-NOTES.md / TPU-C004-NOTES.md /
// OPENVINO-C006-NOTES.md use (ship the exact, host-tractable part; defer the device run).
// EDIT THIS: replace the single seed row in zzscaffbuildgoldenArches with your real device lineup, and
// extend ZzscaffbuildgoldenFamily with your actual generations.

// ZzscaffbuildgoldenFamily is a zzscaffbuildgolden device generation fak can target.
type ZzscaffbuildgoldenFamily uint8

const (
	// ZzscaffbuildgoldenUnknown is the zero value: a device string fak has no target for.
	ZzscaffbuildgoldenUnknown ZzscaffbuildgoldenFamily = iota
	// ZzscaffbuildgoldenGen1 is the seed generation row — RENAME to your first real device family.
	ZzscaffbuildgoldenGen1
)

// String returns the short generation label.
func (f ZzscaffbuildgoldenFamily) String() string {
	switch f {
	case ZzscaffbuildgoldenGen1:
		return "gen1"
	default:
		return "unknown"
	}
}

// ZzscaffbuildgoldenArch is one supported zzscaffbuildgolden compile target: its canonical target token, its family,
// the device-native compute dtype, and a representative product.
type ZzscaffbuildgoldenArch struct {
	Target      string      // canonical target token, e.g. "zzscaffbuildgolden-gen1"
	Family      ZzscaffbuildgoldenFamily // generation
	NativeDtype Dtype       // device-native compute tier
	Examples    string      // representative product(s)
	aliases     []string    // device-reported spellings (already normalized) that resolve here
}

// zzscaffbuildgoldenArches is the supported-target table, declared once. EDIT THIS: one seed row —
// add every real device your backend targets.
var zzscaffbuildgoldenArches = []ZzscaffbuildgoldenArch{
	{Target: "zzscaffbuildgolden-gen1", Family: ZzscaffbuildgoldenGen1, NativeDtype: F32, Examples: "TODO: representative product", aliases: []string{"zzscaffbuildgoldengen1"}},
}

// zzscaffbuildgoldenByKey indexes the table by the canonical target token AND every alias (all
// normalized) for O(1) lookup of a noisy device-reported string.
var zzscaffbuildgoldenByKey = func() map[string]ZzscaffbuildgoldenArch {
	m := make(map[string]ZzscaffbuildgoldenArch, len(zzscaffbuildgoldenArches)*2)
	for _, a := range zzscaffbuildgoldenArches {
		m[normalizeZzscaffbuildgolden(a.Target)] = a
		for _, al := range a.aliases {
			m[normalizeZzscaffbuildgolden(al)] = a
		}
	}
	return m
}()

// normalizeZzscaffbuildgolden canonicalizes a device-reported string to a compact lowercase key: it
// lowercases and strips whitespace/separators. It does not invent a target: an
// unrecognized key is returned for Lookup to reject (fail closed). EDIT THIS if your
// device reports noisier strings (case, suffixes, instance ordinals — see
// rocm_arch.go's normalizeGFX or openvino_arch.go's normalizeOVDevice for patterns).
func normalizeZzscaffbuildgolden(s string) string {
	out := make([]byte, 0, len(s))
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch c {
		case ' ', '\t', '\n', '\r', '-', '_', '.':
			continue
		}
		if c >= 'A' && c <= 'Z' {
			c += 'a' - 'A'
		}
		out = append(out, c)
	}
	return string(out)
}

// LookupZzscaffbuildgoldenArch resolves a device-reported string (any case, separators) to its
// supported target, or (zero, false) if fak has no target for it. This is the
// fail-closed admission a build/runtime path uses so an unknown device is never
// silently compiled for the wrong target.
func LookupZzscaffbuildgoldenArch(name string) (ZzscaffbuildgoldenArch, bool) {
	a, ok := zzscaffbuildgoldenByKey[normalizeZzscaffbuildgolden(name)]
	return a, ok
}

// ZzscaffbuildgoldenToken returns the canonical target token for a device-reported string, or
// ("", false) if unsupported. The deferred build/registration path feeds this to the
// vendor toolchain; a `--backend zzscaffbuildgolden --device <token>` selector accepts the same token.
func ZzscaffbuildgoldenToken(name string) (string, bool) {
	a, ok := LookupZzscaffbuildgoldenArch(name)
	if !ok {
		return "", false
	}
	return a.Target, true
}

// KnownZzscaffbuildgoldenArches returns the supported-target table in declared order. A `fak`
// diagnostic or the backend's build script enumerates it to print exactly which
// zzscaffbuildgolden devices this build of fak targets.
func KnownZzscaffbuildgoldenArches() []ZzscaffbuildgoldenArch {
	out := make([]ZzscaffbuildgoldenArch, len(zzscaffbuildgoldenArches))
	copy(out, zzscaffbuildgoldenArches)
	return out
}
