#!/usr/bin/env bash
# gcp-realmodel-note.sh — drop a discoverable "this is the long-lived demo host"
# note onto fak-realmodel (or any persistent serve box you DON'T want reaped). It
# does NOT install the idle reaper — fak-realmodel is left up by design — it just
# leaves a breadcrumb on the box so whoever lands there next knows what it is and
# how to refresh the served model / demo endpoint.
#
# Why: fak-realmodel is the cheap, always-on L4 demo/serve box. Unlike the A100
# serve nodes it has no idle gardener; the risk is the opposite — that someone
# finds an un-labeled VM and either tears it down or has no idea how to update what
# it serves. This note answers "what is this and how do I update the demos here?"
# right on the box. The repo-side counterpart lives in docs/run-the-demos.md.
#
# It writes /opt/fak/DEMO-HOST.md on the VM. Idempotent — re-running overwrites it.
# The note carries NO secret (no project id, no key) — purely operational.
#
# PLAN BY DEFAULT. --apply writes it over IAP. Usage:
#   ./gcp-realmodel-note.sh                                  # PLAN: print the note + steps
#   ./gcp-realmodel-note.sh --apply                          # write it onto fak-realmodel
#   VM_NAME=fak-realmodel GCP_ZONE=us-central1-a ./gcp-realmodel-note.sh --apply
#
# Knobs (env):
#   VM_NAME    instance to annotate   (default fak-realmodel)
#   GCP_ZONE   its zone               (default us-central1-a)
#   GCP_PROJECT  gcloud project       (default: active gcloud project)
set -euo pipefail

VM_NAME="${VM_NAME:-fak-realmodel}"
GCP_ZONE="${GCP_ZONE:-us-central1-a}"
PROJECT="${GCP_PROJECT:-}"
PROJ_FLAG=""; [ -n "$PROJECT" ] && PROJ_FLAG="--project $PROJECT"

MODE="plan"
case "${1:-}" in
  --apply)   MODE="apply" ;;
  --plan|"") MODE="plan" ;;
  --help|-h) sed -n '2,30p' "$0"; exit 0 ;;
  *) echo "unknown arg: $1 (see --help)" >&2; exit 2 ;;
esac

log() { printf '\033[36m[realmodel-note]\033[0m %s\n' "$*" >&2; }
die() { printf '\033[31m[realmodel-note] %s\033[0m\n' "$*" >&2; exit 1; }

# The note. No secrets — operational only.
render_note() {
  cat <<'NOTE'
# fak-realmodel — the long-lived demo / serve host (DO NOT idle-reap)

This VM is the **persistent fak demo and serve box** (a single NVIDIA L4, sm_89,
~23 GB), serving GLM/SmolLM-class models from fak's OWN in-kernel forward
(`fak serve --backend cuda`) behind `/v1/messages` + `/v1/chat/completions`.

Unlike the A100 serve nodes (fak-glm-serve / fak-qwen-serve), this box has **no
idle gardener** — it is meant to stay up so the live demos keep working. Please do
not install the idle reaper here and do not tear it down without checking first.

## How to update what this box serves (refresh the demos here)

1. Pull the latest fak:
       cd /opt/fak && sudo git pull --ff-only
2. Rebuild if the kernel changed (CUDA build):
       cd /opt/fak && make build-cuda   # or: go build -tags cuda ./cmd/fak
3. Restart the serve unit so it picks up the new binary / model:
       systemctl list-units --type=service | grep -iE 'serve|fak'   # find the unit
       sudo systemctl restart <that-unit>                            # e.g. glm52serve
4. Confirm it came back:
       curl -fsS http://127.0.0.1:8000/healthz && echo OK
       curl -fsS http://127.0.0.1:8000/metrics | grep inference_requests_total

The served port and unit name depend on how it was launched (see the serve script
under /opt/fak/tools/ and `journalctl -u <unit> -e`).

## Repo-side docs

- docs/run-the-demos.md   — how the demos are built and run (and how to refresh this box)
- docs/demos.html         — the live demo gallery this box backs

Generated by scripts/gcp-realmodel-note.sh.
NOTE
}

echo "# Would write /opt/fak/DEMO-HOST.md on: $VM_NAME (zone $GCP_ZONE)"
echo "# --- note contents ---"
render_note
echo "# --- remote write step ---"
echo "render_note | gcloud compute ssh $VM_NAME --zone $GCP_ZONE --tunnel-through-iap $PROJ_FLAG -- 'sudo tee /opt/fak/DEMO-HOST.md >/dev/null'"

if [ "$MODE" = "plan" ]; then
  echo; log "PLAN only. Re-run with --apply to write the note onto $VM_NAME."
  exit 0
fi

command -v gcloud >/dev/null || die "gcloud not found — install the Cloud SDK"
log "writing /opt/fak/DEMO-HOST.md onto $VM_NAME over IAP…"
render_note | gcloud compute ssh "$VM_NAME" --zone "$GCP_ZONE" --tunnel-through-iap $PROJ_FLAG \
  -- 'sudo install -d -m 0755 /opt/fak && sudo tee /opt/fak/DEMO-HOST.md >/dev/null && echo "DEMO-HOST.md written:" && ls -l /opt/fak/DEMO-HOST.md'
log "done. The box now self-documents as the demo host."
