package gateway

import "github.com/anthony-chaudhary/fak/internal/agent"

// Which side served a turn, and why the gateway has to say so.
//
// The whole point of running models on our own hardware is that most of the tokens
// stop being bought. Nothing in fak could state that fraction about its OWN serving
// path: the dual planner decides the side per request, serves the turn, and the
// decision dies with the call frame — computed and discarded a line apart, while the
// durable usage row kept the volume and lost the attribution. This is the thin
// vocabulary that carries the decision as far as the observation.

// servingLocality is the closed vocabulary for who generated one served turn.
type servingLocality uint8

const (
	// localityUnknown: the side could not be resolved. It is the ZERO VALUE on
	// purpose — every path that has not been taught to classify reports unknown by
	// default rather than a plausible guess, and unknown volume is counted in
	// neither group. It shrinks the classified coverage, which is a visible,
	// self-correcting failure; a guess is an invisible one.
	localityUnknown servingLocality = iota
	// localityLocal: generated in-kernel on hardware we host — the tokens that were
	// not bought.
	localityLocal
	// localityVendor: generated by a third-party API upstream.
	localityVendor
)

// servedLocality resolves which side served a turn that named reqModel.
//
// Under a dual planner the side is a property of the REQUEST, so the answer comes
// from the planner's own routing predicate rather than from a copy of its rules —
// there is exactly one definition of "this id decodes in-kernel", and asking it is
// what keeps the metric honest if the local id set changes. An empty model id routes
// to the proxy there (the documented default side), so an omitted model field is
// reported as vendor, matching what actually served it.
//
// Every other deployment has a constant side that selectChatPlanner already
// resolved. A planner wired in directly (tests, or a host that bypassed the
// selector) leaves servedSide at its zero value and reports unknown, which is the
// direction that under-claims self-hosting rather than over-claiming it.
func (s *Server) servedLocality(reqModel string) servingLocality {
	if s == nil {
		return localityUnknown
	}
	if dp, ok := s.planner.(*DualPlanner); ok {
		if dp.RoutesLocal(reqModel) {
			return localityLocal
		}
		return localityVendor
	}
	return s.servedSide
}

// servedLocalityOf resolves the side for a turn described by its per-request sampling
// opts — the buffered path, which holds the opts rather than a bare model id.
//
// It folds them the same way DualPlanner.pick does, and for the same reason: pick
// chose the side from sp.Model, so classifying from any other input (the response's
// reported model, the gateway's configured default) risks disagreeing with the
// planner that actually served the turn. Same input, same predicate, same answer.
func (s *Server) servedLocalityOf(opts []agent.SampleOpt) servingLocality {
	var sp agent.SampleParams
	for _, o := range opts {
		if o != nil {
			o(&sp)
		}
	}
	return s.servedLocality(sp.Model)
}
