package livecodebench

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strconv"
)

// CacheKeyInput is the identity of one generation request: the exact inputs that,
// if unchanged, make a prior completion safe to reuse instead of re-spending
// tokens. It mirrors the lcb_runner `--use_cache` contract (#2108): the cache key
// includes model + prompt + n + temperature + release, so a re-run with the same
// knobs reuses the cached completion and a run that changes ANY of them misses and
// regenerates. Nothing else is part of the identity — two runs that differ only in
// where the artifact is written share a key.
type CacheKeyInput struct {
	Model       string  // model identity the completion was generated by
	Prompt      string  // the fully-rendered prompt sent to the model
	N           int     // samples requested per problem
	Temperature float64 // sampling temperature
	Release     string  // LCB dataset release the problem is pinned to
}

// CacheKey is the deterministic content address of a generation request. It is a
// SHA-256 over a canonical, length-prefixed encoding of every identity field, so
// the boundary between fields cannot be forged: a model "a" + prompt "bc" can
// never collide with a model "ab" + prompt "c". The temperature is encoded with
// full float precision (strconv 'g', -1) so 0.2 and 0.20000001 are distinct keys.
// Same inputs -> same key on every host and every run; that stability is what lets
// a re-run recognize a cached completion.
func (in CacheKeyInput) CacheKey() string {
	h := sha256.New()
	field := func(label, v string) {
		// label + length-prefix each field so no concatenation of values can
		// masquerade as a different field split.
		fmt.Fprintf(h, "%s:%d:%s;", label, len(v), v)
	}
	field("model", in.Model)
	field("prompt", in.Prompt)
	field("n", strconv.Itoa(in.N))
	field("temperature", strconv.FormatFloat(in.Temperature, 'g', -1, 64))
	field("release", in.Release)
	return "lcbgen_" + hex.EncodeToString(h.Sum(nil))
}

// PendingWork is the `--continue-existing` resume filter: given the full ordered
// list of problem ids a run must cover and the set already completed by a prior
// (possibly interrupted) run, it returns the ids still to do, in the original
// order and with no duplicates. An interrupted run resumed with the same work list
// therefore never re-generates a problem it already finished. Duplicate ids in
// `all` collapse to their first occurrence, so a malformed work list cannot cause
// the same problem to be scored twice.
func PendingWork(all []string, done map[string]bool) []string {
	pending := make([]string, 0, len(all))
	seen := make(map[string]bool, len(all))
	for _, id := range all {
		if done[id] || seen[id] {
			continue
		}
		seen[id] = true
		pending = append(pending, id)
	}
	return pending
}

// CacheStats is honest cache-hit accounting (#2108): it counts only genuine cache
// lookups, so the surfaced hit rate can never be a vanity number. A "hit" is a
// completion actually reused; a "miss" is a lookup that had to regenerate. Work
// that was never looked up (e.g. a problem outside the run) is not counted at all
// — it can neither inflate nor deflate the rate.
type CacheStats struct {
	Hits   int `json:"hits"`
	Misses int `json:"misses"`
}

// Hit records a reused completion.
func (s *CacheStats) Hit() { s.Hits++ }

// Miss records a lookup that had to regenerate.
func (s *CacheStats) Miss() { s.Misses++ }

// Lookups is the denominator the rate is honest against: only requests actually
// checked against the cache.
func (s CacheStats) Lookups() int { return s.Hits + s.Misses }

// HitRate is Hits/Lookups in [0,1]. With zero lookups it is 0, never an
// undefined-as-100% flourish: a run that reused nothing reports a 0% hit rate, not
// a vacuous perfect one.
func (s CacheStats) HitRate() float64 {
	n := s.Lookups()
	if n == 0 {
		return 0
	}
	return float64(s.Hits) / float64(n)
}

// Summary renders the accounting as absolute counts first, with the rate stated
// against the lookup count so the reader can always see the denominator behind it.
func (s CacheStats) Summary() string {
	return fmt.Sprintf("cache: %d hit(s), %d miss(es), %.1f%% of %d lookup(s)",
		s.Hits, s.Misses, s.HitRate()*100, s.Lookups())
}
