package disambiguation

import (
	"bytes"
	"cmp"
	"fmt"
	"slices"
	"strings"
	"unicode"
)

const GeneratedDocsSchemaVersion = "fak-disambiguation-docs/1"

// DocPage is one deterministic documentation artifact rendered from the
// canonical terminology index.
type DocPage struct {
	Path    string
	Content []byte
}

// RenderPublicDocs renders the human-readable projection of the same records
// used by GeneratePublicIndex and the query commands.
func RenderPublicDocs() ([]DocPage, error) { return RenderDocs(publicEntries) }

// RenderDocs renders canonical-term pages without introducing a second source
// of terminology truth.
func RenderDocs(entries []Entry) ([]DocPage, error) {
	canonical, err := canonicalEntries(entries)
	if err != nil {
		return nil, err
	}
	return []DocPage{
		{Path: "canonical-terms.md", Content: renderCanonicalTerms(canonical)},
		{Path: "contrast-index.md", Content: renderContrastIndex(canonical)},
	}, nil
}

func renderCanonicalTerms(entries []Entry) []byte {
	var out bytes.Buffer
	fmt.Fprintln(&out, "# Canonical terminology")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "> Generated by `fak disambiguation docs`; do not edit by hand. Each definition below is queryable through the public CLI.")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "| Canonical term | Scope | Definition | Query |")
	fmt.Fprintln(&out, "|---|---|---|---|")
	for _, entry := range entries {
		anchor := entryAnchor(entry)
		fmt.Fprintf(&out, "| [%s](#%s) | `%s:%s` | %s | `%s` |\n",
			escapeCell(entry.Identity.CanonicalTerm), anchor, escapeCode(entry.Scope.Kind), escapeCode(entry.Scope.Value),
			escapeCell(entry.Definition), escapeCell(queryCommand(entry, entries)))
	}
	for _, entry := range entries {
		fmt.Fprintln(&out)
		fmt.Fprintf(&out, "<a id=\"%s\"></a>\n", entryAnchor(entry))
		fmt.Fprintf(&out, "## %s — `%s:%s`\n\n", entry.Identity.CanonicalTerm, entry.Scope.Kind, entry.Scope.Value)
		fmt.Fprintf(&out, "%s\n\n", entry.Definition)
		fmt.Fprintf(&out, "- **Query:** `%s`\n", queryCommand(entry, entries))
		fmt.Fprintf(&out, "- **Owner:** leaf `%s`, lane `%s`\n", entry.Owner.Leaf, entry.Owner.Lane)
		fmt.Fprintf(&out, "- **Lifecycle:** `%s`, rollout `%s`\n", entry.Lifecycle.Class, entry.Lifecycle.Rollout)
		if len(entry.Identity.Aliases) > 0 {
			fmt.Fprintf(&out, "- **Aliases:** `%s`\n", strings.Join(entry.Identity.Aliases, "`, `"))
		}
		if len(entry.Sources) > 0 {
			fmt.Fprintln(&out, "- **Sources:**")
			for _, source := range entry.Sources {
				fmt.Fprintf(&out, "  - `%s` — `%s` at `%s`\n", source.Locator, source.Kind, source.Revision)
			}
		}
		if len(entry.Contrasts) > 0 {
			fmt.Fprintln(&out, "- **Do not conflate with:**")
			for _, contrast := range entry.Contrasts {
				fmt.Fprintf(&out, "  - [%s](contrast-index.md#%s) — %s\n", contrast.CanonicalTerm, termAnchor(contrast.CanonicalTerm), contrast.Explanation)
			}
		}
	}
	return out.Bytes()
}

func renderContrastIndex(entries []Entry) []byte {
	byTerm := make(map[string][]Entry)
	for _, entry := range entries {
		byTerm[entry.Identity.CanonicalTerm] = append(byTerm[entry.Identity.CanonicalTerm], entry)
	}
	terms := make([]string, 0, len(byTerm))
	for term := range byTerm {
		terms = append(terms, term)
	}
	slices.Sort(terms)

	var out bytes.Buffer
	fmt.Fprintln(&out, "# Terminology contrast index")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "> Generated by `fak disambiguation docs`; do not edit by hand. Follow a term to its canonical, queryable identity.")
	for _, term := range terms {
		var contrasts []struct{ target, explanation string }
		for _, entry := range byTerm[term] {
			for _, contrast := range entry.Contrasts {
				contrasts = append(contrasts, struct{ target, explanation string }{contrast.CanonicalTerm, contrast.Explanation})
			}
		}
		if len(contrasts) == 0 {
			continue
		}
		slices.SortFunc(contrasts, func(a, b struct{ target, explanation string }) int {
			if order := cmp.Compare(a.target, b.target); order != 0 {
				return order
			}
			return cmp.Compare(a.explanation, b.explanation)
		})
		fmt.Fprintln(&out)
		fmt.Fprintf(&out, "<a id=\"%s\"></a>\n", termAnchor(term))
		fmt.Fprintf(&out, "## %s\n\n", term)
		for _, entry := range byTerm[term] {
			fmt.Fprintf(&out, "- **Identity:** [%s — `%s:%s`](canonical-terms.md#%s); query with `%s`\n",
				term, entry.Scope.Kind, entry.Scope.Value, entryAnchor(entry), queryCommand(entry, entries))
		}
		fmt.Fprintln(&out, "- **Contrasts:**")
		for _, contrast := range contrasts {
			fmt.Fprintf(&out, "  - **%s:** %s\n", contrast.target, contrast.explanation)
		}
	}
	return out.Bytes()
}

func queryCommand(entry Entry, entries []Entry) string {
	count := 0
	for _, candidate := range entries {
		if candidate.Identity.CanonicalTerm == entry.Identity.CanonicalTerm {
			count++
		}
	}
	term := strings.ReplaceAll(entry.Identity.CanonicalTerm, `"`, `\"`)
	if count > 1 {
		return fmt.Sprintf(`fak disambiguation query --scope-kind %s --scope-value %s "%s"`, entry.Scope.Kind, entry.Scope.Value, term)
	}
	return fmt.Sprintf(`fak disambiguation query "%s"`, term)
}

func entryAnchor(entry Entry) string {
	return termAnchor(entry.Identity.CanonicalTerm + " " + entry.Scope.Kind + " " + entry.Scope.Value)
}
func termAnchor(value string) string {
	var out strings.Builder
	dash := false
	for _, r := range strings.ToLower(value) {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			out.WriteRune(r)
			dash = false
			continue
		}
		if !dash && out.Len() > 0 {
			out.WriteByte('-')
			dash = true
		}
	}
	return strings.Trim(out.String(), "-")
}
func escapeCell(value string) string {
	return strings.ReplaceAll(strings.ReplaceAll(value, "|", `\|`), "\n", " ")
}
func escapeCode(value string) string { return strings.ReplaceAll(value, "`", "") }
