package disambiguation

import (
	"bytes"
	"fmt"
	"path"
	"sort"
	"strings"
)

// DocPage is one deterministic public documentation artifact.
type DocPage struct {
	Path    string
	Content []byte
}

// RenderPublicDocs renders the committed public index through the same typed
// entries used by generation and query. It never re-parses source families.
func RenderPublicDocs() ([]DocPage, error) {
	return RenderDocs(publicEntries)
}

// RenderDocs renders aggregate compatibility pages, a browsable index, and one
// stable standalone page for every scoped identity.
func RenderDocs(entries []Entry) ([]DocPage, error) {
	ordered := cloneEntries(entries)
	sort.Slice(ordered, func(i, j int) bool { return compareIdentity(ordered[i].Identity, ordered[j].Identity) < 0 })

	var canonical bytes.Buffer
	writeFrontMatter(&canonical, "Canonical disambiguation terms", "Canonical scoped terminology for fak, with query commands, ownership, freshness, and nearest contrasts for each identity.")
	canonical.WriteString("# Canonical disambiguation terms\n\n")
	canonical.WriteString("> Generated by `fak disambiguation docs`; do not edit. Query identities with `fak disambiguation query`.\n\n")
	canonical.WriteString("## Index\n\n")
	for _, entry := range ordered {
		anchor := entryAnchor(entry)
		fmt.Fprintf(&canonical, "- [%s](#%s) — `%s`\n", entry.Identity.CanonicalTerm, anchor, scopeSelector(entry.Scope))
	}
	canonical.WriteString("\n")
	for _, entry := range ordered {
		renderCanonicalEntry(&canonical, entry)
	}

	var contrast bytes.Buffer
	writeFrontMatter(&contrast, "Disambiguation contrast index", "A scoped index of fak terms that are easy to conflate, with their nearest contrasts and exact identity query commands.")
	contrast.WriteString("# Disambiguation contrast index\n\n## Identity contrasts\n\n")
	contrast.WriteString("> Generated by `fak disambiguation docs`; do not edit. Each row links to the exact canonical identity.\n\n")
	contrast.WriteString("| canonical identity | scope | do not confuse with | query |\n")
	contrast.WriteString("|---|---|---|---|\n")
	for _, entry := range ordered {
		if len(entry.Contrasts) == 0 {
			continue
		}
		anchor := entryAnchor(entry)
		query := queryCommand(entry)
		fmt.Fprintf(&contrast, "| [%s](canonical-terms.md#%s) | `%s` | %s | `%s` |\n", escapeTable(entry.Identity.CanonicalTerm), anchor, escapeTable(scopeSelector(entry.Scope)), escapeTable(contrastSummary(entry.Contrasts)), escapeTable(query))
	}

	pages := []DocPage{
		{Path: "canonical-terms.md", Content: canonical.Bytes()},
		{Path: "contrast-index.md", Content: contrast.Bytes()},
	}

	var index bytes.Buffer
	writeFrontMatter(&index, "Disambiguation identity index", "Browse every scoped fak identity with its meaning, owner-backed scope, nearest contrast, and exact machine query command.")
	index.WriteString("# Disambiguation index\n\n## Scoped identities\n\n")
	index.WriteString("> Generated by `fak disambiguation docs`; do not edit. Each row links to one scoped machine-index identity.\n\n")
	index.WriteString("| canonical identity | scope | meaning | nearest contrast | query |\n")
	index.WriteString("|---|---|---|---|---|\n")
	for _, entry := range ordered {
		rel := path.Join("identities", entryAnchor(entry)+".md")
		nearestContrast := "—"
		if len(entry.Contrasts) > 0 {
			nearestContrast = contrastText(entry.Contrasts[0])
		}
		fmt.Fprintf(&index, "| [%s](%s) | `%s` | %s | %s | `%s` |\n", escapeTable(entry.Identity.CanonicalTerm), rel, escapeTable(scopeSelector(entry.Scope)), escapeTable(entry.Definition), escapeTable(nearestContrast), escapeTable(queryCommand(entry)))
	}
	pages = append(pages, DocPage{Path: "INDEX.md", Content: index.Bytes()})

	for _, entry := range ordered {
		var page bytes.Buffer
		renderIdentityPage(&page, entry)
		pages = append(pages, DocPage{Path: path.Join("identities", entryAnchor(entry)+".md"), Content: page.Bytes()})
	}
	if err := validateDocPages(pages); err != nil {
		return nil, err
	}
	return pages, nil
}

func validateDocPages(pages []DocPage) error {
	seen := make(map[string]struct{}, len(pages))
	for _, page := range pages {
		clean := path.Clean(page.Path)
		if clean != page.Path || clean == "." || strings.HasPrefix(clean, "../") || path.IsAbs(clean) {
			return fmt.Errorf("unsafe documentation path %q", page.Path)
		}
		if _, ok := seen[clean]; ok {
			return fmt.Errorf("duplicate documentation path %q", clean)
		}
		seen[clean] = struct{}{}
	}
	return nil
}

func writeFrontMatter(buf *bytes.Buffer, title, description string) {
	fmt.Fprintf(buf, "---\ntitle: %q\ndescription: %q\n---\n\n", title, description)
}

func renderIdentityPage(buf *bytes.Buffer, entry Entry) {
	title := fmt.Sprintf("%s - %s identity", entry.Identity.CanonicalTerm, scopeSelector(entry.Scope))
	description := fmt.Sprintf("%s Scope: %s. Includes its nearest contrasts, owner, lifecycle, freshness, and exact fak query command.", entry.Definition, scopeSelector(entry.Scope))
	writeFrontMatter(buf, title, description)
	fmt.Fprintf(buf, "# %s\n\n", entry.Identity.CanonicalTerm)
	fmt.Fprintf(buf, "**Meaning:** %s\n\n", entry.Definition)
	buf.WriteString("## Do not conflate with\n\n")
	for _, distinction := range entry.Contrasts {
		fmt.Fprintf(buf, "- **%s:** %s\n", distinction.CanonicalTerm, distinction.Explanation)
	}
	buf.WriteString("\n## Query this identity\n\n```console\n")
	fmt.Fprintf(buf, "$ %s\n", queryCommand(entry))
	buf.WriteString("```\n\n## Identity\n\n")
	fmt.Fprintf(buf, "- **Scope:** `%s`\n", scopeSelector(entry.Scope))
	if len(entry.Identity.Aliases) > 0 {
		fmt.Fprintf(buf, "- **Aliases:** %s\n", strings.Join(entry.Identity.Aliases, ", "))
	} else {
		buf.WriteString("- **Aliases:** none\n")
	}
	fmt.Fprintf(buf, "- **Owner:** `%s`\n", entry.Owner.Leaf+" / "+entry.Owner.Lane)
	fmt.Fprintf(buf, "- **Lifecycle:** `%s`\n", entry.Lifecycle.Class)
	fmt.Fprintf(buf, "- **Rollout:** `%s`\n", entry.Lifecycle.Rollout)
	buf.WriteString("\n## Freshness\n\n")
	fmt.Fprintf(buf, "- **Verdict:** `%s`\n", entry.Freshness.Verdict)
	fmt.Fprintf(buf, "- **Reason:** `%s`\n", entry.Freshness.ReasonCode)
	fmt.Fprintf(buf, "- **Checked at:** `%s`\n", entry.Freshness.CheckedAt)
	fmt.Fprintf(buf, "- **Probe:** `%s`\n", entry.Freshness.Probe)
	buf.WriteString("\n## Source witnesses\n\n")
	for _, source := range entry.Sources {
		fmt.Fprintf(buf, "- `%s` (%s, revision `%s`, checked `%s`; probe `%s`)", source.Locator, source.Kind, source.Revision, source.CheckedAt, source.Probe)
		buf.WriteString("\n")
	}
	buf.WriteString("\n[Back to the disambiguation index](../INDEX.md)\n")
}

func renderCanonicalEntry(buf *bytes.Buffer, entry Entry) {
	anchor := entryAnchor(entry)
	fmt.Fprintf(buf, "<a id=\"%s\"></a>\n", anchor)
	fmt.Fprintf(buf, "## %s\n\n", entry.Identity.CanonicalTerm)
	fmt.Fprintf(buf, "**Scope:** `%s`  \n", scopeSelector(entry.Scope))
	fmt.Fprintf(buf, "**Owner:** `%s`  \n", entry.Owner.Leaf+" / "+entry.Owner.Lane)
	fmt.Fprintf(buf, "**Status:** `%s` (lifecycle `%s`, rollout `%s`)  \n", entry.Freshness.Verdict, entry.Lifecycle.Class, entry.Lifecycle.Rollout)
	fmt.Fprintf(buf, "**Queryable identity:** `%s`\n\n", queryCommand(entry))
	fmt.Fprintf(buf, "%s\n\n", entry.Definition)
	if len(entry.Identity.Aliases) > 0 {
		fmt.Fprintf(buf, "**Aliases:** %s\n\n", strings.Join(entry.Identity.Aliases, ", "))
	}
	if len(entry.Contrasts) > 0 {
		buf.WriteString("**Do not confuse with:**\n")
		for _, item := range entry.Contrasts {
			fmt.Fprintf(buf, "- **%s:** %s\n", item.CanonicalTerm, item.Explanation)
		}
		buf.WriteString("\n")
	}
	if len(entry.Sources) > 0 {
		buf.WriteString("**Grounded by:**\n")
		for _, source := range entry.Sources {
			fmt.Fprintf(buf, "- `%s` (%s, revision `%s`, checked `%s`; probe `%s`)", source.Locator, source.Kind, source.Revision, source.CheckedAt, source.Probe)
			buf.WriteString("\n")
		}
		buf.WriteString("\n")
	}
}

func entryAnchor(entry Entry) string {
	raw := entry.Identity.CanonicalTerm + "-" + string(entry.Scope.Kind) + "-" + entry.Scope.Value
	var b strings.Builder
	lastDash := false
	for _, r := range strings.ToLower(raw) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			lastDash = false
			continue
		}
		if !lastDash && b.Len() > 0 {
			b.WriteByte('-')
			lastDash = true
		}
	}
	return strings.Trim(b.String(), "-")
}

func queryCommand(entry Entry) string {
	return fmt.Sprintf("fak disambiguation query %s --scope-kind %s --scope-value %s --json", shellQuote(entry.Identity.CanonicalTerm), shellQuote(entry.Scope.Kind), shellQuote(entry.Scope.Value))
}
func shellQuote(value string) string { return `"` + strings.ReplaceAll(value, `"`, `\"`) + `"` }
func escapeTable(value string) string {
	return strings.ReplaceAll(strings.ReplaceAll(value, "|", `\|`), "\n", " ")
}

func scopeSelector(scope Scope) string { return scope.Kind + ":" + scope.Value }
func contrastText(contrast Contrast) string {
	return contrast.CanonicalTerm + ": " + contrast.Explanation
}
func contrastSummary(contrasts []Contrast) string {
	items := make([]string, 0, len(contrasts))
	for _, contrast := range contrasts {
		items = append(items, contrastText(contrast))
	}
	return strings.Join(items, "; ")
}
func cloneEntries(entries []Entry) []Entry { return append([]Entry(nil), entries...) }
func compareIdentity(left, right Identity) int {
	if left.CanonicalTerm < right.CanonicalTerm {
		return -1
	}
	if left.CanonicalTerm > right.CanonicalTerm {
		return 1
	}
	return 0
}
