#!/usr/bin/env python3
"""Generate llms-full.txt from the curated llms.txt index.

`llms.txt` is the curated, link-rich map an LLM/answer-engine reads first.
`llms-full.txt` is its companion: the full text of every local document `llms.txt`
links to, inlined into one file so an answer engine can ingest the whole corpus in a
single fetch (per the https://llmstxt.org convention).

This keeps the two in sync: edit llms.txt, re-run this script. Read-only except for
writing llms-full.txt.

Run:  python tools/gen_llms_full.py
"""
from __future__ import annotations

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "llms.txt")
OUT = os.path.join(ROOT, "llms-full.txt")

LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")


def version() -> str:
    try:
        with open(os.path.join(ROOT, "VERSION"), encoding="utf-8") as f:
            return f.read().strip()
    except OSError:
        return "unknown"


def collect_targets(index_text: str):
    """Ordered, de-duplicated list of (title, relpath) for local .md links."""
    seen = set()
    out = []
    for title, target in LINK_RE.findall(index_text):
        # Skip external links and pure anchors.
        if target.startswith(("http://", "https://", "#", "mailto:")):
            continue
        relpath = target.split("#", 1)[0]
        if not relpath.endswith(".md"):
            continue
        abspath = os.path.normpath(os.path.join(ROOT, relpath))
        if not os.path.isfile(abspath):
            sys.stderr.write(f"warn: linked file not found, skipping: {relpath}\n")
            continue
        if relpath in seen:
            continue
        seen.add(relpath)
        out.append((title.strip(), relpath.replace("\\", "/")))
    return out


def main():
    with open(INDEX, encoding="utf-8") as f:
        index_text = f.read()

    targets = collect_targets(index_text)

    parts = []
    parts.append("# fak — the agent kernel: full documentation corpus")
    parts.append("")
    parts.append(
        "> This file inlines the full text of every document the curated `llms.txt` "
        "links to, for one-fetch ingestion by LLMs and answer engines. Generated by "
        "`tools/gen_llms_full.py` from `llms.txt` (the source of truth). "
        f"Project version: {version()}."
    )
    parts.append("")
    parts.append("## Index (start with the curated map)")
    parts.append("")
    parts.append(index_text.strip())
    parts.append("")
    parts.append("---")
    parts.append("")

    for title, relpath in targets:
        with open(os.path.join(ROOT, relpath), encoding="utf-8", errors="replace") as f:
            body = f.read().strip()
        parts.append(f"# {title}")
        parts.append("")
        parts.append(f"> Source: `{relpath}`")
        parts.append("")
        parts.append(body)
        parts.append("")
        parts.append("---")
        parts.append("")

    text = "\n".join(parts).rstrip() + "\n"
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)

    print(f"wrote {OUT}: {len(targets)} documents, {len(text):,} bytes")


if __name__ == "__main__":
    main()
