#!/usr/bin/env python3
"""Generate JSON-LD structured data for the docs site — the AEO heavy-hitter.

Answer engines (ChatGPT, Perplexity, Google AI Overviews) and rich-result crawlers
read JSON-LD to identify a project and cite it correctly. The fak docs site shipped
ZERO structured data; this generator emits it, re-derived from repo facts so it can
never drift from reality (the same discipline as `tools/gen_llms_full.py` and the
docs scorecard — no hand-entry):

  SITE-WIDE  -> injected between markers in docs/_includes/head-custom.html, so the
               cayman layout's head hook puts it on every page:
    SoftwareApplication   what the project IS (category, language, license, version)
    WebSite               the site identity (name, url, publisher, language)
    Organization          the publisher (logo, sameAs the GitHub repo)

  INDEX PAGE -> injected between markers in docs/index.md, where the visible page is
               the project documentation front door:
    BreadcrumbList        a truthful Home -> fak documentation trail

  FAQ-PAGE   -> injected between markers in docs/FAQ.md (FAQPage markup must live on
               the page whose visible Q&A it mirrors, per Google's guideline):
    FAQPage               every `## question` + its answer, from the live FAQ

Facts come from VERSION, docs/_config.yml (url/baseurl/description), and llms.txt.
The injected blocks are bounded by HTML-comment markers and rewritten in place, so
re-running is idempotent. IMPORTANT: the blocks are pure <script> JSON — never a
Liquid tag — so they are safe to inject into head-custom.html (a Liquid tag there
recurses the Pages build; see that file's header).

Run:  python tools/gen_structured_data.py            # write the blocks
      python tools/gen_structured_data.py --check     # CI: fail if out of date
"""
from __future__ import annotations

import argparse
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG = os.path.join(ROOT, "docs", "_config.yml")
LLMS = os.path.join(ROOT, "llms.txt")
FAQ = os.path.join(ROOT, "docs", "FAQ.md")
HEAD_INCLUDE = os.path.join(ROOT, "docs", "_includes", "head-custom.html")
INDEX_PAGE = os.path.join(ROOT, "docs", "index.md")
VERSION_FILE = os.path.join(ROOT, "VERSION")

UPDATES_FEED = os.path.join(ROOT, "docs", "marketing", "updates.json")

REPO_URL = "https://github.com/anthony-chaudhary/fak"
SITE_BEGIN = "<!-- STRUCTURED-DATA:BEGIN (generated by tools/gen_structured_data.py — do not edit by hand) -->"
SITE_END = "<!-- STRUCTURED-DATA:END -->"
# The recency block fenced into llms.txt from the marketing updates feed (docs/marketing/
# updates.json, written by `fak marketing aeo`). It fills the gap llms.txt has no "what's
# new" section, so an answer engine answering "what is the latest in fak" has a dated,
# sha-cited block to cite. The feed is GENERATED (Go, from witnessed ships); this injects it
# between markers so the hand-written body of llms.txt is never touched.
WHATSNEW_BEGIN = "<!-- WHATS-NEW:BEGIN (generated from docs/marketing/updates.json by `fak marketing aeo` — do not edit by hand) -->"
WHATSNEW_END = "<!-- WHATS-NEW:END -->"
FAQ_BEGIN = "<!-- FAQPAGE-JSONLD:BEGIN (generated by tools/gen_structured_data.py — do not edit by hand) -->"
FAQ_END = "<!-- FAQPAGE-JSONLD:END -->"
BREADCRUMB_BEGIN = "<!-- BREADCRUMB-JSONLD:BEGIN (generated by tools/gen_structured_data.py — do not edit by hand) -->"
BREADCRUMB_END = "<!-- BREADCRUMB-JSONLD:END -->"


def _read(path: str) -> str:
    try:
        with open(path, encoding="utf-8") as f:
            return f.read()
    except OSError:
        return ""


def version() -> str:
    return (_read(VERSION_FILE).strip() or "unknown")


def site_url() -> str:
    cfg = _read(CONFIG)
    url = re.search(r'^url:\s*"?([^"\n]+)', cfg, re.MULTILINE)
    base = re.search(r'^baseurl:\s*"?([^"\n]+)', cfg, re.MULTILINE)
    u = (url.group(1).strip() if url else "https://anthony-chaudhary.github.io").rstrip("/")
    b = (base.group(1).strip() if base else "/fak")
    return u + b


def site_description() -> str:
    cfg = _read(CONFIG)
    # The folded `description: >-` block in _config.yml.
    m = re.search(r"^description:\s*>-\s*\n((?:[ \t]+.*\n?)+)", cfg, re.MULTILINE)
    if m:
        return " ".join(line.strip() for line in m.group(1).splitlines() if line.strip())
    return ("Netra Fused Agent Kernel (`fak`): an in-process, default-deny permission "
            "gate for AI agents fused with an addressable, bit-exact KV cache, in Go.")


def social_image() -> str:
    cfg = _read(CONFIG)
    m = re.search(r'image:\s*"?([^"\n]+)', cfg)
    return m.group(1).strip() if m else (
        "https://raw.githubusercontent.com/anthony-chaudhary/fak/main/visuals/social-preview.png")


# ---------------------------------------------------------------------------
# FAQ extraction (-> FAQPage)
# ---------------------------------------------------------------------------

_MD_LINK = re.compile(r"\[([^\]]+)\]\([^)]+\)")
_MD_FENCE = re.compile(r"```.*?```", re.DOTALL)   # a fenced code block (multi-line)
_MD_BOLD = re.compile(r"\*\*([^*]+)\*\*")          # **bold**
_MD_EMPH = re.compile(r"(?<!\*)\*([^*]+)\*(?!\*)")  # *italic* (run AFTER whitespace-collapse)
# underscore emphasis only at word boundaries — never inside snake_case identifiers.
_MD_UND = re.compile(r"(?<![A-Za-z0-9_])_([^_]+)_(?![A-Za-z0-9_])")
_MD_CODE = re.compile(r"`([^`]+)`")                # `inline code`
# A leading markdown MARKER: a blockquote/heading run, a bullet, or an `N.` list
# number — each REQUIRES a trailing space, so a bare leading digit (e.g. "4x fewer
# tokens" after **bold** is stripped) is NEVER mistaken for a list marker. This is
# the bug the adversarial review caught: the old `^[>#\-\*\d\.]+` ate the "4" from
# "4x", silently corrupting the headline benchmark in the machine-readable answer.
_MD_LEAD = re.compile(r"^\s*(?:[>#]+|[-*+]|\d+\.)\s+", re.MULTILINE)


def _plain(text: str) -> str:
    """Flatten markdown answer prose to a clean plain-text JSON-LD answer string.

    Order matters:
      1. drop fenced code blocks (a flattened multi-line command reads as noise);
      2. strip leading list/quote/heading MARKERS while line starts still exist;
      3. collapse all whitespace to single spaces — this also JOINS emphasis that
         wraps across a source line break (`*same call\\npath*`), which a per-line
         regex could never match (the bug the review's artifact guard caught);
      4. only now strip inline markdown — bold BEFORE single-* emphasis so `**x**`
         is consumed before `*x*`, then underscore emphasis, then inline code.
    """
    text = _MD_FENCE.sub(" ", text)
    text = _MD_LEAD.sub("", text)
    text = re.sub(r"\s+", " ", text).strip()
    text = _MD_LINK.sub(r"\1", text)
    text = _MD_BOLD.sub(r"\1", text)
    text = _MD_EMPH.sub(r"\1", text)
    text = _MD_UND.sub(r"\1", text)
    text = _MD_CODE.sub(r"\1", text)
    return text.strip()


# Stray markdown markers that must NOT survive into a JSON-LD answer (the artifact
# guard the review asked for, so --check can catch a regression the drift check can't).
_ARTIFACT_RE = re.compile(r"\*|```|`{2,}|\]\(")


def faq_pairs(faq_md: str) -> list[tuple[str, str]]:
    """(question, answer-plain-text) for every `## …` section in FAQ.md.

    A heading that does not read as a question (no '?', and not a 'How/What/Why/…'
    lead) is skipped — keeps section dividers out of the FAQPage."""
    body = faq_md
    # Drop front matter if present.
    if body.startswith("---"):
        end = body.find("\n---", 3)
        if end != -1:
            body = body[end + 4:]
    parts = re.split(r"^##\s+(.+)$", body, flags=re.MULTILINE)
    # parts = [pre, q1, a1, q2, a2, ...]
    out: list[tuple[str, str]] = []
    for i in range(1, len(parts), 2):
        q = parts[i].strip()
        a_raw = parts[i + 1] if i + 1 < len(parts) else ""
        # Stop the answer at a horizontal rule if one separates sections.
        a_raw = re.split(r"^---\s*$", a_raw, flags=re.MULTILINE)[0]
        a = _plain(a_raw)
        is_question = q.endswith("?") or re.match(
            r"(?i)^(how|what|why|when|where|who|which|is|are|can|does|do|should|will)\b", q)
        if not is_question or len(a) < 20:
            continue
        # Trim absurdly long answers (answer engines want the gist).
        if len(a) > 1200:
            a = a[:1190].rsplit(" ", 1)[0] + " …"
        out.append((q, a))
    return out


# ---------------------------------------------------------------------------
# Schema builders
# ---------------------------------------------------------------------------

def build_site_schemas() -> list[dict]:
    url = site_url()
    desc = site_description()
    img = social_image()
    name = "Netra Fused Agent Kernel (`fak`)"
    publisher = {
        "@type": "Organization",
        "name": "Netra Systems",
        "url": url,
        "logo": img,
        "sameAs": [REPO_URL],
    }
    software = {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        "name": "Netra Fused Agent Kernel",
        "alternateName": ["fak", "Fused Agent Kernel", "agent tool firewall"],
        "description": desc,
        "applicationCategory": "DeveloperApplication",
        "applicationSubCategory": "SecurityApplication",
        "operatingSystem": "Linux, macOS, Windows",
        "programmingLanguage": "Go",
        "softwareVersion": version(),
        "license": "https://www.apache.org/licenses/LICENSE-2.0",
        "codeRepository": REPO_URL,
        "url": url,
        "image": img,
        "downloadUrl": REPO_URL,
        "author": {"@type": "Person", "name": "Anthony Chaudhary"},
        "publisher": publisher,
        "offers": {"@type": "Offer", "price": "0", "priceCurrency": "USD"},
        "keywords": ("agent kernel, agent tool firewall, AI agent security, prompt injection "
                     "defense, tool poisoning, capability security, default-deny permission gate, "
                     "KV cache, addressable KV cache, self-hosted LLM, LLM agent fleet, Go"),
    }
    website = {
        "@context": "https://schema.org",
        "@type": "WebSite",
        "name": name,
        "url": url,
        "description": desc,
        "inLanguage": "en",
        "publisher": publisher,
    }
    organization = {
        "@context": "https://schema.org",
        **publisher,
    }
    # NB: no global BreadcrumbList. A breadcrumb injected into EVERY page's <head>
    # would claim the same degenerate Home->Home trail everywhere (the review's nit);
    # a real breadcrumb is per-page hierarchy, which this site's flat docs root lacks.
    return [software, website, organization]


def build_faqpage(faq_md: str) -> dict | None:
    pairs = faq_pairs(faq_md)
    if not pairs:
        return None
    return {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {"@type": "Question", "name": q,
             "acceptedAnswer": {"@type": "Answer", "text": a}}
            for q, a in pairs
        ],
    }


def build_index_breadcrumb() -> dict:
    url = site_url()
    parent = url.rsplit("/", 1)[0] + "/" if "/" in url else url
    return {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {
                "@type": "ListItem",
                "position": 1,
                "name": "Home",
                "item": parent,
            },
            {
                "@type": "ListItem",
                "position": 2,
                "name": "fak documentation",
                "item": url + "/",
            },
        ],
    }


def faqpage_artifacts(faq_md: str) -> list[str]:
    """Answer texts that still carry raw markdown markers (*, ```, ``, ](). An
    empty list means the flattener produced clean prose — the guard the drift
    check ('--check') cannot provide on its own, since corruption baked into the
    generator is byte-stable against itself."""
    schema = build_faqpage(faq_md)
    if not schema:
        return []
    bad = []
    for q in schema["mainEntity"]:
        a = q["acceptedAnswer"]["text"]
        if _ARTIFACT_RE.search(a):
            bad.append(f"{q['name']!r}: {a[:80]}…")
    return bad


def _script(obj: dict) -> str:
    payload = json.dumps(obj, ensure_ascii=False, indent=2)
    return f'<script type="application/ld+json">\n{payload}\n</script>'


def render_site_block() -> str:
    blocks = "\n".join(_script(s) for s in build_site_schemas())
    return f"{SITE_BEGIN}\n{blocks}\n{SITE_END}"


def render_faq_block(faq_md: str) -> str | None:
    schema = build_faqpage(faq_md)
    if schema is None:
        return None
    return f"{FAQ_BEGIN}\n{_script(schema)}\n{FAQ_END}"


def render_breadcrumb_block() -> str:
    return f"{BREADCRUMB_BEGIN}\n{_script(build_index_breadcrumb())}\n{BREADCRUMB_END}"


# ---------------------------------------------------------------------------
# Idempotent in-place injection
# ---------------------------------------------------------------------------

def render_whatsnew_block(cap: int = 12) -> str:
    """Render the llms.txt "What's new" block from docs/marketing/updates.json.

    The feed is a schema.org ItemList of witnessed ships (written by `fak marketing aeo`);
    each item's `item.name` is the claim and `item.codeRepository` is the witnessing commit
    URL. We render a bounded, dated markdown list under a `## What's new` heading, every line
    citing its commit — the recency surface an answer engine quotes. Returns "" (the block is
    then omitted) when the feed is absent or empty, so a repo without the marketing loop wired
    simply has no What's-new section rather than a broken one."""
    raw = _read(UPDATES_FEED)
    if not raw.strip():
        return ""
    try:
        feed = json.loads(raw)
    except json.JSONDecodeError:
        return ""
    items = feed.get("itemListElement", [])
    if not items:
        return ""
    lines = [WHATSNEW_BEGIN, "", "## What's new", ""]
    for el in items[:cap]:
        it = el.get("item", {})
        name = (it.get("name") or "").strip()
        url = (it.get("codeRepository") or "").strip()
        date = (it.get("dateModified") or "").strip()
        if not name:
            continue
        sha = url.rsplit("/", 1)[-1] if url else ""
        stamp = f"**{date}** — " if date else ""
        cite = f" ([`{sha}`]({url}))" if url else ""
        lines.append(f"- {stamp}{name}{cite}")
    lines += ["", WHATSNEW_END]
    return "\n".join(lines)


def inject(text: str, begin: str, end: str, block: str, *, after_front_matter: bool) -> str:
    """Replace an existing BEGIN..END block, else insert a fresh one.

    For a markdown page (`after_front_matter`), a new block lands right after the
    `---` front-matter fence (so front matter stays line 1) — else after the H1,
    else at the top. For an HTML include it is appended."""
    pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    if pat.search(text):
        return pat.sub(lambda _m: block, text)
    if not after_front_matter:
        sep = "" if text.endswith("\n") or not text else "\n"
        return text + sep + block + "\n"
    # markdown: after front matter if present
    if text.startswith("---"):
        fm_end = text.find("\n---", 3)
        if fm_end != -1:
            cut = text.find("\n", fm_end + 1)
            cut = cut + 1 if cut != -1 else len(text)
            return text[:cut] + "\n" + block + "\n" + text[cut:]
    # else after the first H1
    m = re.search(r"^#\s+.*$", text, re.MULTILINE)
    if m:
        cut = m.end()
        nl = text.find("\n", cut)
        cut = nl + 1 if nl != -1 else len(text)
        return text[:cut] + "\n" + block + "\n" + text[cut:]
    return block + "\n\n" + text


def append_block(text: str, begin: str, end: str, block: str) -> str:
    """Replace an existing BEGIN..END block, but keep the generated block out of
    the first-screen prose by appending it to the document."""
    pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    body = pat.sub("", text).rstrip()
    sep = "\n\n" if body else ""
    return body + sep + block + "\n"


def _write(path: str, text: str) -> None:
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Generate JSON-LD structured data (read facts, write blocks).")
    ap.add_argument("--check", action="store_true", help="exit 1 if any block is out of date (CI)")
    args = ap.parse_args(argv)

    head = _read(HEAD_INCLUDE)
    faq = _read(FAQ)
    index = _read(INDEX_PAGE)
    llms = _read(LLMS)

    new_head = inject(head, SITE_BEGIN, SITE_END, render_site_block(), after_front_matter=False)
    faq_block = render_faq_block(faq)
    new_faq = inject(faq, FAQ_BEGIN, FAQ_END, faq_block, after_front_matter=True) if faq_block else faq
    new_index = append_block(index, BREADCRUMB_BEGIN, BREADCRUMB_END, render_breadcrumb_block())
    # llms.txt "What's new": inject the recency block from the marketing feed after the H1,
    # touching only the marked span (the hand-written body is preserved). When the feed is
    # absent/empty the block is "" and any existing marked span is left as-is.
    whatsnew = render_whatsnew_block()
    new_llms = inject(llms, WHATSNEW_BEGIN, WHATSNEW_END, whatsnew, after_front_matter=True) if (llms and whatsnew) else llms

    changed = []
    if new_head != head:
        changed.append("docs/_includes/head-custom.html")
    if new_faq != faq:
        changed.append("docs/FAQ.md")
    if new_index != index:
        changed.append("docs/index.md")
    if new_llms != llms:
        changed.append("llms.txt")

    # Accuracy guard (independent of drift): the flattened FAQ answers must carry
    # no raw markdown markers — catches a _plain() regression even when the
    # committed output is byte-stable against the (buggy) generator.
    artifacts = faqpage_artifacts(faq)

    if args.check:
        rc = 0
        if changed:
            print("structured data OUT OF DATE; run: python tools/gen_structured_data.py")
            for c in changed:
                print(f"  - {c}")
            rc = 1
        if artifacts:
            print("FAQPage answers carry raw markdown artifacts (fix _plain()):")
            for a in artifacts:
                print(f"  - {a}")
            rc = 1
        if rc == 0:
            print("structured data up to date (no drift, no answer artifacts)")
        return rc

    if new_head != head:
        _write(HEAD_INCLUDE, new_head)
    if faq_block and new_faq != faq:
        _write(FAQ, new_faq)
    if new_index != index:
        _write(INDEX_PAGE, new_index)
    if new_llms != llms:
        _write(LLMS, new_llms)

    n_faq = len(build_faqpage(faq).get("mainEntity", [])) if faq_block else 0
    print(f"wrote site JSON-LD ({len(build_site_schemas())} schemas) -> docs/_includes/head-custom.html")
    print(f"wrote FAQPage JSON-LD ({n_faq} Q&A) -> docs/FAQ.md")
    print("wrote BreadcrumbList JSON-LD -> docs/index.md")
    if new_llms != llms:
        print("wrote What's-new block -> llms.txt")
    if not changed:
        print("(no changes — already up to date)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
