#!/usr/bin/env python3
"""Generate llms-full.txt from the curated llms.txt index.

`llms.txt` is the curated, link-rich map an LLM/answer-engine reads first.
`llms-full.txt` is its companion: the full text of every local document `llms.txt`
links to, inlined into one file so an answer engine can ingest the whole corpus in a
single fetch (per the https://llmstxt.org convention).

This keeps the two in sync: edit llms.txt, re-run this script. Read-only except for
writing llms-full.txt.

Run:  python tools/gen_llms_full.py           # write llms-full.txt
      python tools/gen_llms_full.py --check    # CI: exit 1 if out of date (#511)
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from urllib.parse import quote

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "llms.txt")
OUT = os.path.join(ROOT, "llms-full.txt")

LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
REPO_BLOB_BASE = "https://github.com/anthony-chaudhary/fak/blob/main/"
REPO_TREE_BASE = "https://github.com/anthony-chaudhary/fak/tree/main/"


def version() -> str:
    try:
        with open(os.path.join(ROOT, "VERSION"), encoding="utf-8") as f:
            return f.read().strip()
    except OSError:
        return "unknown"


def collect_targets(index_text: str):
    """Ordered, de-duplicated list of (title, relpath) for local .md links."""
    seen = set()
    out = []
    for title, target in LINK_RE.findall(index_text):
        # Skip external links and pure anchors.
        if target.startswith(("http://", "https://", "#", "mailto:")):
            continue
        relpath = target.split("#", 1)[0]
        if not relpath.endswith(".md"):
            continue
        abspath = os.path.normpath(os.path.join(ROOT, relpath))
        if not os.path.isfile(abspath):
            sys.stderr.write(f"warn: linked file not found, skipping: {relpath}\n")
            continue
        if relpath in seen:
            continue
        seen.add(relpath)
        out.append((title.strip(), relpath.replace("\\", "/")))
    return out


def _split_link_target(target: str) -> tuple[str, str]:
    """Return (path, suffix) for a markdown link target, preserving ?query/#anchor."""
    cut = len(target)
    for marker in ("#", "?"):
        i = target.find(marker)
        if i != -1:
            cut = min(cut, i)
    return target[:cut], target[cut:]


def _repo_url(rel: str, *, is_dir: bool = False) -> str:
    base = REPO_TREE_BASE if is_dir else REPO_BLOB_BASE
    return base + quote(rel.replace("\\", "/"), safe="/:@")


def absolutize_local_links(text: str, source_relpath: str) -> str:
    """Rewrite local links in an inlined document to repo-absolute URLs.

    `llms-full.txt` is a flat one-fetch corpus. Once `docs/foo/bar.md` is inlined,
    a link like `[x](baz.md)` no longer has `docs/foo/` as its base, so an answer
    engine following the flat file sees a dangling citation. Resolve local targets
    against the source document's original directory and emit GitHub blob/tree URLs.
    External URLs and pure page anchors stay untouched.
    """
    source_dir = os.path.dirname(source_relpath)

    def repl(m: re.Match[str]) -> str:
        label, target = m.group(1), m.group(2).strip()
        if target.startswith(("http://", "https://", "mailto:", "tel:", "#")):
            return m.group(0)
        path_part, suffix = _split_link_target(target)
        if not path_part:
            return m.group(0)
        if path_part.startswith("/"):
            rel = os.path.normpath(path_part.lstrip("/"))
        else:
            rel = os.path.normpath(os.path.join(source_dir, path_part))
        if rel.startswith(".."):
            return m.group(0)
        abs_target = os.path.join(ROOT, rel)
        if os.path.isdir(abs_target):
            return f"[{label}]({_repo_url(rel, is_dir=True)}{suffix})"
        if os.path.isfile(abs_target):
            return f"[{label}]({_repo_url(rel)}{suffix})"
        return m.group(0)

    return LINK_RE.sub(repl, text)


def build_corpus():
    """Build the llms-full.txt text from llms.txt. Returns (text, targets)."""
    with open(INDEX, encoding="utf-8") as f:
        index_text = f.read()
    targets = collect_targets(index_text)

    parts = []
    parts.append("# fak — the agent kernel: full documentation corpus")
    parts.append("")
    parts.append(
        "> This file inlines the full text of every document the curated `llms.txt` "
        "links to, for one-fetch ingestion by LLMs and answer engines. Generated by "
        "`tools/gen_llms_full.py` from `llms.txt` (the source of truth). "
        f"Project version: {version()}."
    )
    parts.append("")
    parts.append("## Index (start with the curated map)")
    parts.append("")
    parts.append(index_text.strip())
    parts.append("")
    parts.append("---")
    parts.append("")

    for title, relpath in targets:
        with open(os.path.join(ROOT, relpath), encoding="utf-8", errors="replace") as f:
            body = absolutize_local_links(f.read().strip(), relpath)
        parts.append(f"# {title}")
        parts.append("")
        parts.append(f"> Source: `{relpath}`")
        parts.append("")
        parts.append(body)
        parts.append("")
        parts.append("---")
        parts.append("")

    text = "\n".join(parts).rstrip() + "\n"
    return text, targets


def main() -> int:
    global ROOT, INDEX, OUT
    ap = argparse.ArgumentParser(description="Generate llms-full.txt from the llms.txt index.")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if llms-full.txt is missing or out of date (CI drift gate, #511)")
    ap.add_argument("--root", default=ROOT,
                    help="repo root holding llms.txt / llms-full.txt (default: the repo root)")
    args = ap.parse_args()

    # Honor --root by repointing the module paths (so the build reads the requested
    # tree and --check compares against its llms-full.txt; enables isolated tests).
    ROOT = args.root
    INDEX = os.path.join(args.root, "llms.txt")
    OUT = os.path.join(args.root, "llms-full.txt")

    text, targets = build_corpus()

    if args.check:
        try:
            with open(OUT, encoding="utf-8") as f:
                current = f.read()
        except OSError:
            print("llms-full.txt OUT OF DATE (missing); run: python tools/gen_llms_full.py")
            return 1
        # Normalize CRLF->LF so the check is byte-stable across Windows/POSIX: the
        # write path forces LF, but this tolerates a CRLF copy an older run left.
        if current.replace("\r\n", "\n") != text:
            print("llms-full.txt OUT OF DATE; run: python tools/gen_llms_full.py")
            return 1
        print(f"llms-full.txt up to date ({len(targets)} documents, {len(text):,} bytes)")
        return 0

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)

    print(f"wrote {OUT}: {len(targets)} documents, {len(text):,} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
