#!/usr/bin/env python3
"""Single source of truth for the cloud-notebook quickstarts under notebooks/.

The notebooks are GENERATED ARTIFACTS — do not hand-edit the .ipynb files. Edit the
shared cell builders here, then regenerate:

    python tools/gen_notebooks.py            # (re)write notebooks/*.ipynb
    python tools/gen_notebooks.py --check    # CI: fail on drift OR a stale repo reference

Why a generator instead of two hand-kept notebooks:
  - DRY: the setup + get-the-binary cells are IDENTICAL across notebooks; they live once,
    here, so a change (a new flag, a pinned version, a clone tweak) updates every notebook.
  - Anti-rot: --check re-renders in memory and diffs against the committed files (a
    "generated, do not edit" guard, like a gofmt check), AND verifies every repo path the
    cells reference still exists — so deleting examples/…json or scripts/fetch-model.sh
    fails CI here instead of failing a user mid-notebook.

Modular update path in one line: edit a builder -> run this -> commit; CI runs --check.
"""
from __future__ import annotations
import json
import sys
import pathlib
import difflib

ROOT = pathlib.Path(__file__).resolve().parents[1]
NB = ROOT / "notebooks"

GEN_MARKER = ("> _Generated by `tools/gen_notebooks.py` — edit the generator, not this "
              "`.ipynb`. CI guards drift + stale references via `--check`._")

# --- repo references the cells depend on (the anti-rot allow-list) -----------------
# (path-relative-to-repo-root, why it's referenced). --check fails if any is missing.
REQUIRED_PATHS = [
    ("cmd/fak", "the binary the notebooks build (go build ./cmd/fak)"),
    ("examples/customer-support-readonly-policy.json", "Tier-0 preflight DENY/ALLOW demo"),
    ("testdata/tau2/tau2-smoke.json", "quickstart offline transport/value benchmark"),
    ("testdata/turntax/turntax-airline.json", "quickstart turn-tax value benchmark"),
    ("scripts/fetch-model.sh", "Notebook B real-weights export (Tier 2b)"),
]
# fak verbs the cells invoke — must still be wired in cmd/fak.
REQUIRED_VERBS = [
    "preflight", "serve", "agent", "policy", "attest", "benchmarks", "bench",
    "turntax", "version",
]


# --- shared cell builders ----------------------------------------------------------
def setup_cell(gpu_note_expr: str) -> str:
    return (r'''# --- setup: work dir, repo coords, GPU ---
import os, shutil, subprocess, sys, time, json, urllib.request

WORK = os.environ.get("FAK_WORK") or ("/content" if os.path.isdir("/content")
        else "/kaggle/working" if os.path.isdir("/kaggle/working") else "/tmp/fak-demo")
os.makedirs(WORK, exist_ok=True); os.chdir(WORK)

REPO   = os.environ.get("FAK_REPO", "anthony-chaudhary/fak")
BRANCH = os.environ.get("FAK_BRANCH", "main")  # pin a release tag here, e.g. v0.30.0

HAS_GPU = shutil.which("nvidia-smi") is not None and \
          subprocess.run(["nvidia-smi"], capture_output=True).returncode == 0
print("work dir :", WORK)
print(f"repo     : {REPO}@{BRANCH}")
print("GPU      :", __GPU_NOTE__)''').replace("__GPU_NOTE__", gpu_note_expr)


GET_BINARY_CELL = r'''# --- get a fresh `fak` binary plus the examples/testdata the demos use.
#     The Go module is the repository ROOT (go.mod), so the clone dir *is* the build dir.
#     By default an existing clone is refreshed to FAK_BRANCH. Set FAK_REFRESH=0 to reuse it.
import urllib.request, tarfile, platform, re

def sh(cmd, timeout=900):
    print("$", cmd)
    subprocess.run(cmd, shell=True, check=True, timeout=timeout)

def go_ok():
    try:
        out = subprocess.run(["go","version"], capture_output=True, text=True, check=True).stdout
        m = re.search(r"go(\d+)\.(\d+)", out)
        return bool(m) and (int(m.group(1)), int(m.group(2))) >= (1, 26)
    except Exception:
        return False

def latest_go_archive():
    arch = platform.machine().lower()
    goarch = {"x86_64":"amd64", "amd64":"amd64", "aarch64":"arm64", "arm64":"arm64"}.get(arch)
    if sys.platform.startswith("linux") and goarch:
        rels = json.load(urllib.request.urlopen("https://go.dev/dl/?mode=json", timeout=30))
        for rel in rels:
            m = re.match(r"go(\d+)\.(\d+)", rel.get("version", ""))
            if not m or (int(m.group(1)), int(m.group(2))) < (1, 26):
                continue
            for f in rel.get("files", []):
                if f.get("kind") == "archive" and f.get("os") == "linux" and f.get("arch") == goarch:
                    return rel["version"], f["filename"]
    return "go1.26.3", "go1.26.3.linux-amd64.tar.gz"

if not go_ok():
    GOV, GO = latest_go_archive()
    print("installing", GOV, "...")
    urllib.request.urlretrieve("https://go.dev/dl/" + GO, "/tmp/" + GO)
    shutil.rmtree("/usr/local/go", ignore_errors=True)
    with tarfile.open("/tmp/" + GO) as t: t.extractall("/usr/local")
os.environ["PATH"] = "/usr/local/go/bin:" + os.environ["PATH"]
print(subprocess.run(["go","version"], capture_output=True, text=True).stdout.strip())

# clone the public repo (anonymous; no token needed), then refresh to the requested ref
FAK_DIR = os.path.join(WORK, "fak")
if not os.path.isdir(os.path.join(FAK_DIR, ".git")):
    print(f"$ git clone --depth 1 -b {BRANCH} https://github.com/{REPO}.git  ->  {FAK_DIR}")
    subprocess.run(["git","clone","--depth","1","-b",BRANCH,
                    f"https://github.com/{REPO}.git", FAK_DIR], check=True)
else:
    print("clone exists:", FAK_DIR)
    if os.environ.get("FAK_REFRESH", "1") != "0":
        sh(f'git -C "{FAK_DIR}" fetch --depth 1 origin "{BRANCH}"')
        sh(f'git -C "{FAK_DIR}" checkout -q --detach FETCH_HEAD')
    else:
        print("FAK_REFRESH=0, reusing the existing checkout without fetch")

stamp = subprocess.run(["git","-C",FAK_DIR,"log","-1","--format=%h %cI %s"],
                       capture_output=True, text=True, check=True).stdout.strip()
print("source  :", stamp)

# the module is the repo root, so build right here
FAK_EXE = "fak.exe" if os.name == "nt" else "fak"
FAK = os.path.join(FAK_DIR, FAK_EXE)
sh(f'cd "{FAK_DIR}" && go build -o "{FAK_EXE}" ./cmd/fak')
print("\nfak ->", FAK)
print(subprocess.run([FAK,"version"], capture_output=True, text=True).stdout.strip() or "built ok")'''


def md(s):   return {"cell_type": "markdown", "metadata": {}, "source": s}
def code(s): return {"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [], "source": s}


# --- Notebook A: quickstart (Tier 0 + Tier 1) --------------------------------------
def quickstart_cells():
    return [
        md(r'''# fak quickstart - fresh value demos

Build the current `fak` once, then run the case that matches what you are trying to prove.
The notebook defaults to `FAK_BRANCH=main`, refreshes an existing clone unless
`FAK_REFRESH=0`, and prints the exact commit and binary version it is about to run.

| Case | Use this when... | What it proves | Needs |
|---|---|---|---|
| **A. Policy floor** | you need a reviewable allow/deny boundary | `preflight --json` explains the winning rung; `attest` proves the manifest | CPU |
| **B. App/API drop-in** | you have a Python app, MCP adapter, or tool runner | `/v1/fak/adjudicate` gives a verdict before your code executes a tool | CPU |
| **C. Value measurement** | you want a number before wiring a model | offline benchmark catalog, vDSO transport A/B, and turn-tax report | CPU |
| **D. Real model gateway** | you want `fak` in front of a chat model | OpenAI-compatible client -> `fak serve` -> Ollama | GPU recommended |

No API key is needed for cases A-C. Case D uses a free Colab/Kaggle GPU and a small Ollama
model by default.

''' + GEN_MARKER),
        code(setup_cell('"yes — Tier 1 ready" if HAS_GPU '
                        'else "no — Tier 0 only (Runtime -> T4 for Tier 1)"')),
        code(GET_BINARY_CELL),
        code(r'''# --- small helpers used by the cases below ---
POL = "examples/customer-support-readonly-policy.json"

def cmd(argv, cwd=FAK_DIR, check=True, timeout=180):
    p = subprocess.run(argv, cwd=cwd, capture_output=True, text=True, timeout=timeout)
    if check and p.returncode != 0:
        raise RuntimeError("command failed: " + " ".join(argv) + "\n" + p.stdout + p.stderr)
    return p

def fak(*args, check=True, timeout=180):
    return cmd([FAK, *args], check=check, timeout=timeout)

def fak_json(*args, timeout=180):
    p = fak(*args, timeout=timeout)
    return json.loads(p.stdout)

def clip(s, n=2400):
    s = s.strip()
    return s if len(s) <= n else s[:n] + "\n... clipped ..."

def post_json(base, path, payload, timeout=30):
    req = urllib.request.Request(base + path, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.load(r)

def stop_process(name):
    p = globals().get(name)
    if p and p.poll() is None:
        p.terminate()
        try:
            p.wait(timeout=5)
        except subprocess.TimeoutExpired:
            p.kill()

print("source :", cmd(["git","log","-1","--format=%h %cI %s"]).stdout.strip())
print("binary :")
print(fak("version").stdout.strip())'''),
        md(r'''## Expected state for a CPU run

Run-all on a CPU-only runtime should finish Cases A-C and print these success signals:

- Case A: `refund_payment` is `DENY/POLICY_BLOCK`, `search_kb` is `ALLOW`, and the policy attestation passes with zero failed probes.
- Case B: local `fak serve` reports healthy, and `/v1/fak/adjudicate` denies `refund_payment` before your app executes it.
- Case C: `benchmarks list --offline` prints the zero-asset benchmark catalog, `bench` reports `PRIMARY GATE : pass`, and `turntax` reports 9 turns saved on the fixture.
- Case D: skipped on CPU-only runtimes; on a GPU runtime it should serve `qwen2.5:1.5b` through the OpenAI SDK.

The cells below include assertions for the stable CPU expectations, so a stale policy,
missing verb, or broken HTTP adjudication path fails where it happens.'''),
        md(r'''## Case A - policy floor you can ship

This is the no-model proof. `preflight` runs the same adjudication fold a served call uses,
and `attest` turns the policy file into a re-checkable proof obligation.'''),
        code(r'''# A1. Three structural calls: explicit deny, prefix allow, fail-closed unknown.
cases = [
    ("explicit deny", "refund_payment", {}, "DENY", "POLICY_BLOCK"),
    ("prefix allow", "search_kb", {"query": "refund policy"}, "ALLOW", ""),
    ("fail-closed unknown", "__not_in_policy__", {}, "DENY", "DEFAULT_DENY"),
]
for label, tool, args, want_kind, want_reason in cases:
    d0 = fak_json("preflight", "--policy", POL, "--tool", tool, "--args", json.dumps(args),
                  "--json")
    got = (d0["verdict"], d0.get("reason", ""))
    assert d0["verdict"] == want_kind, (label, got, want_kind)
    if want_reason:
        assert d0.get("reason") == want_reason, (label, got, want_reason)
    print(f"{label:<20} {tool:<22} -> {d0['verdict']} {d0.get('reason','')}")

# A2. Explain the exact winning rung without logging raw args.
d = fak_json("preflight", "--policy", POL, "--tool", "refund_payment", "--args", "{}",
             "--json")
print("\nwinning verdict:", d["verdict"], d.get("reason", ""), "by", d.get("by", ""))
print("explanation    :", d["explanation"])
print("\nrung trace:")
for r in d["rungs"]:
    mark = "WIN" if r.get("winner") else "   "
    print(f"{mark} [{r['index']}] {r['rung']:<26} {r.get('kind','ELIDED'):<9} {r.get('reason','')}")'''),
        code(r'''# A3. Prove the whole manifest, not just one cherry-picked call.
att = fak_json("attest", "--policy", POL, "--quiet")
assert att["summary"]["pass"] is True, att["summary"]
assert att["summary"]["failed"] == 0, att["summary"]
print("attestation schema:", att["schema"])
print("policy sha256     :", att["policy"]["sha256"][:16] + "...")
print("probes            :", att["summary"]["probes"])
print("passed / failed   :", att["summary"]["passed"], "/", att["summary"]["failed"])
print("floor proven      :", att["summary"]["pass"])'''),
        md(r'''## Case B - app/API drop-in

Use this path when your own application executes tools. The application asks `fak` for a
verdict first, then executes only the calls that survive. No chat model or GPU is involved.'''),
        code(r'''# Start a local fak HTTP gateway for adjudication-only calls.
stop_process("fak_api_proc")
API_ADDR = os.environ.get("FAK_API_ADDR", "127.0.0.1:8765")
API = "http://" + API_ADDR
fak_api_proc = subprocess.Popen(
    [FAK, "serve", "--addr", API_ADDR, "--policy", POL, "--model", "quickstart"],
    cwd=FAK_DIR, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

for _ in range(60):
    try:
        with urllib.request.urlopen(API + "/healthz", timeout=2) as r:
            print("gateway:", r.read().decode().strip())
            break
    except Exception:
        time.sleep(1)
else:
    raise RuntimeError("fak serve did not become healthy on " + API)'''),
        code(r'''# The same endpoint accepts JSON objects and OpenAI-style JSON-string arguments.
api_cases = [
    ("read-only app action", {"tool": "search_kb", "arguments": {"query": "refund policy"},
                              "read_only": True}),
    ("blocked business action", {"tool": "refund_payment", "arguments": {"amount": 100}}),
    ("OpenAI function args", {"tool": "refund_payment",
                              "arguments": json.dumps({"amount": 100})}),
]
for label, payload in api_cases:
    r = post_json(API, "/v1/fak/adjudicate", payload)
    v = r["verdict"]
    if payload["tool"] == "refund_payment":
        assert v["kind"] == "DENY" and v.get("reason") == "POLICY_BLOCK", v
    if payload["tool"] == "search_kb":
        assert v["kind"] == "ALLOW", v
    print(f"{label:<24} -> {v['kind']:<5} {v.get('reason','')} {v.get('disposition','')}")

print("\nThis was adjudicate-only: your application still owns execution of allowed tools.")'''),
        md(r'''## Case C - value measurement without a model

Before you spend GPU time, ask what can be measured offline. The catalog names the benchmark
surfaces, then two small runs show the transport/value axes on committed fixtures.'''),
        code(r'''# Discover the zero-asset benchmark surfaces.
print(clip(fak("benchmarks", "list", "--offline").stdout, 3600))'''),
        code(r'''# Run the short transport benchmark and a turn-tax report on frozen fixtures.
print("== transport A/B ==")
bench_out = fak("bench", "--suite", "tau2-smoke", "--baseline-n", "5",
                "--out", "quickstart-bench.json", timeout=240).stdout
assert "PRIMARY GATE" in bench_out and "pass" in bench_out, bench_out
print(clip(bench_out, 2200))

print("\n== turn-tax A/B ==")
turntax_out = fak("turntax", "--suite", "turntax-airline",
                  "--out", "quickstart-turntax.json", timeout=240).stdout
assert "turns saved" in turntax_out and ": 9" in turntax_out, turntax_out
print(clip(turntax_out, 2600))'''),
        md(r'''## Case D - real model gateway

If the runtime has a GPU, this starts Ollama with a small model and puts `fak serve` in front
of it. The client is the standard OpenAI Python SDK pointed at `http://127.0.0.1:8080/v1`.'''),
        code(r'''# D1. Start Ollama and pull a small model that fits a free T4.
MODEL = os.environ.get("FAK_MODEL", "qwen2.5:1.5b")

if not HAS_GPU:
    print("no GPU - skipping Case D. Switch Runtime -> Change runtime type -> T4 and run again.")
else:
    if shutil.which("ollama") is None:
        subprocess.run("curl -fsSL https://ollama.com/install.sh | sh", shell=True, check=True)
    if not globals().get("ollama_proc") or ollama_proc.poll() is not None:
        ollama_proc = subprocess.Popen(["ollama", "serve"],
                                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    for _ in range(60):
        try:
            urllib.request.urlopen("http://127.0.0.1:11434/api/tags", timeout=2)
            break
        except Exception:
            time.sleep(1)
    print("ollama up; pulling", MODEL, "(one-time, cached) ...")
    subprocess.run(["ollama", "pull", MODEL], check=True)
    print("model ready:", MODEL)'''),
        code(r'''# D2. Start fak in front of Ollama.
if HAS_GPU:
    stop_process("fak_model_proc")
    fak_model_proc = subprocess.Popen(
        [FAK, "serve", "--addr", "127.0.0.1:8080",
         "--base-url", "http://127.0.0.1:11434/v1",
         "--model", MODEL, "--policy", POL],
        cwd=FAK_DIR, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    for _ in range(60):
        try:
            with urllib.request.urlopen("http://127.0.0.1:8080/healthz", timeout=2) as r:
                print("fak serve:", r.read().decode().strip())
                break
        except Exception:
            time.sleep(1)
    else:
        raise RuntimeError("fak serve did not become healthy on :8080")'''),
        code(r'''# D3. Drive it with the OpenAI SDK.
if HAS_GPU:
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "openai"], check=True)
    from openai import OpenAI
    client = OpenAI(base_url="http://127.0.0.1:8080/v1", api_key="not-needed")
    resp = client.chat.completions.create(
        model=MODEL,
        temperature=0.2,
        messages=[{"role": "user", "content": "In one sentence, what is a syscall?"}],
    )
    print("model through fak:", resp.choices[0].message.content)
    models = json.load(urllib.request.urlopen("http://127.0.0.1:8080/v1/models", timeout=10))
    print("\n/v1/models:", json.dumps(models, indent=2)[:900])'''),
        md(r'''## Where to go next

- **Tier 2 - the fused in-kernel model** (`fak serve --engine inkernel`, real SmolLM2 via
  `scripts/fetch-model.sh`): see **`fak-inkernel.ipynb`** in this folder, or
  `GETTING-STARTED.md` section 4.
- **Policy authoring:** `POLICY.md` · **Architecture:** `ARCHITECTURE.md`
- **What's real vs. simulated vs. stub:** `CLAIMS.md` (every claim machine-tagged)

*Cleanup* - background servers die when the notebook runtime recycles. To stop them now:
`for p in [fak_api_proc, fak_model_proc, ollama_proc]: p.terminate()`'''),
    ]


# --- Notebook B: fused in-kernel (Tier 2) ------------------------------------------
def inkernel_cells():
    return [
        md(r'''# fak — Tier 2: the fused in-kernel model (neocloud notebook)

This is **Notebook B** — the GPU-deep companion to `fak-quickstart.ipynb`. It runs the
deepest fusion: the model runs **inside the kernel's address space**, decoding over a
kernel-owned KV cache, reachable via `/v1/fak/syscall`. It then fronts a **bigger** model
and exposes a **stable endpoint** an external client can reach — the two things a free,
no-ingress Colab can't do.

Host it on a neocloud Jupyter with a real terminal and port ingress — **Lightning AI Studio**
or a **RunPod / Vast** GPU pod (the `[VERIFIED]` single-GPU rows in
`PLAN-cloud-neocloud-rightsizing-2026-06-20.md`).

| Section | What it shows | Needs |
|---|---|---|
| **2a — synthetic in-kernel** | the real prefill+decode loop over a kernel-owned KV cache | **CPU ok** |
| **2b — real SmolLM2-135M** | the same path on weights exported from HuggingFace | **CPU ok** (Python/torch) |
| **bigger model + endpoint** | `qwen2.5:14b` behind `fak serve` on a 24 GB card, exposed publicly | **GPU** (24 GB) |

> Honest scope (matches `CLAIMS.md`): the in-kernel paths are proven correct at the
> tensor layer against a HuggingFace oracle — they make model state first-class kernel-owned
> state; they are **not** a production chat-quality serving engine. For practical chat, the
> bigger-model section uses Tier 1 (front Ollama).

''' + GEN_MARKER),
        code(setup_cell('"yes" if HAS_GPU else '
                        '"no — Tier 2 in-kernel still runs on CPU; the bigger-model section is skipped"')),
        code(GET_BINARY_CELL),
        code(r'''# --- helpers: (re)start a fak serve on a port, and call the in-kernel syscall ---
def serve(args, port=8137, env=None):
    subprocess.run('pkill -f "fak serve" 2>/dev/null; sleep 1', shell=True)
    e = dict(os.environ)
    if env: e.update(env)
    p = subprocess.Popen([FAK,"serve","--addr",f"127.0.0.1:{port}",*args],
                         cwd=FAK_DIR, env=e, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    for _ in range(90):
        try:
            with urllib.request.urlopen(f"http://127.0.0.1:{port}/healthz", timeout=2) as r:
                print("fak serve up:", r.read().decode()); return p
        except Exception: time.sleep(1)
    print("did not bind on", port); return p

def syscall(tool, arguments, port=8137):
    # NB: the fak-native wire key is "arguments" (NOT "args" — unknown keys are dropped)
    req = urllib.request.Request(f"http://127.0.0.1:{port}/v1/fak/syscall",
        data=json.dumps({"tool":tool,"arguments":arguments}).encode(),
        headers={"Content-Type":"application/json"})
    return json.load(urllib.request.urlopen(req, timeout=120))

print("helpers ready")'''),
        md(r'''## 2a — synthetic in-kernel checkpoint (instant, CPU ok)

`--engine inkernel` with no weights runs a small deterministic synthetic checkpoint. The
tokens are meaningless (random-init weights) — what it proves is the **real prefill+decode
loop over the kernel-owned KV cache**, dispatched through the adjudicator.'''),
        code(r'''serve(["--engine","inkernel","--model","smollm2-inkernel"], port=8137)
out = syscall("read_file", {"path":"notes.txt"}, port=8137)
print("verdict :", out.get("verdict"))
print("meta    :", out.get("result", {}).get("meta"))
print("content :", out.get("result", {}).get("content", "")[:200])'''),
        md(r'''## 2b — real SmolLM2-135M weights (CPU torch is enough)

`scripts/fetch-model.sh` makes a Python venv, installs torch/transformers (CPU is fine),
downloads `HuggingFaceTB/SmolLM2-135M-Instruct`, and exports it into
`internal/model/.cache/smollm2-135m`. First run needs network to HuggingFace; it takes a
few minutes. `FAK_MODEL_DIR` is what selects the real weights.'''),
        code(r'''try:
    print("exporting real weights (one-time, ~mins) ...")
    subprocess.run(f'cd "{FAK_DIR}" && ./scripts/fetch-model.sh', shell=True, check=True)
    MODEL_DIR = os.path.join(FAK_DIR, "internal/model/.cache/smollm2-135m")
    serve(["--engine","inkernel","--model","smollm2-135m"], port=8137,
          env={"FAK_MODEL_DIR": MODEL_DIR})
    out = syscall("read_file", {"path":"notes.txt"}, port=8137)
    print("verdict :", out.get("verdict"))
    print("meta    :", out.get("result", {}).get("meta"))
except subprocess.CalledProcessError as e:
    print("fetch-model failed (needs Python 3.10+ and network to HuggingFace):", e)
    print("the synthetic path in 2a already exercised the in-kernel decode loop.")'''),
        md(r'''## Bigger model + a stable endpoint (needs a 24 GB GPU)

A free Colab T4 (16 GB) tops out around a 7B model and has **no inbound port**. On a
neocloud 24 GB card you can front `qwen2.5:14b` (~9 GB) through the kernel — the same shape
as the live GCP demo, but reader-owned — and expose it so an external client (or Claude
Code) can point at it.'''),
        code(r'''if not HAS_GPU:
    print("no GPU — skipping. (Tier 2 in-kernel above ran on CPU.)")
else:
    MODEL = os.environ.get("FAK_MODEL", "qwen2.5:14b")  # ~9 GB, fits a 24 GB card
    if shutil.which("ollama") is None:
        subprocess.run("curl -fsSL https://ollama.com/install.sh | sh", shell=True, check=True)
    subprocess.Popen(["ollama","serve"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    for _ in range(60):
        try: urllib.request.urlopen("http://127.0.0.1:11434/api/tags", timeout=2); break
        except Exception: time.sleep(1)
    print("pulling", MODEL, "(one-time, cached) ...")
    subprocess.run(["ollama","pull",MODEL], check=True)
    serve(["--base-url","http://127.0.0.1:11434/v1","--model",MODEL], port=8080)

    subprocess.run([sys.executable,"-m","pip","install","-q","openai"], check=True)
    from openai import OpenAI
    client = OpenAI(base_url="http://127.0.0.1:8080/v1", api_key="not-needed")
    r = client.chat.completions.create(model=MODEL, temperature=0.3,
        messages=[{"role":"user","content":"In one sentence, what is a syscall?"}])
    print("\nmodel (through the kernel):", r.choices[0].message.content)'''),
        code(r'''# Expose :8080 publicly. On Lightning AI: use the Studio "expose port" control.
# On RunPod: the pod's proxy URL is https://<POD_ID>-8080.proxy.runpod.net .
# Portable fallback (no signup) — a cloudflared quick tunnel; watch for the trycloudflare URL:
if HAS_GPU:
    try:
        subprocess.run(
            "wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/"
            "cloudflared-linux-amd64 -O /usr/local/bin/cloudflared && chmod +x /usr/local/bin/cloudflared",
            shell=True, check=True)
        print("starting cloudflared quick tunnel to :8080 — the https://*.trycloudflare.com")
        print("URL will print below; point any OpenAI client at  <that-url>/v1")
        subprocess.Popen(["cloudflared","tunnel","--url","http://localhost:8080"])
        time.sleep(8)
    except Exception as e:
        print("tunnel optional — on Lightning/RunPod use the platform's port-expose instead:", e)'''),
        md(r'''## Where to go next

- **Why this is the deep fusion:** `docs/explainers/addressable-kv-cache.md` (mid-run causal
  span eviction, bit-exact `max|Δ| = 0`).
- **The expert smoke** — Qwen3.6-27B through fak's own GGUF→Q8 path (`cmd/fakchat`):
  `GETTING-STARTED.md` §4c–4d.
- **The cost/hardware tiers** behind this notebook: `PLAN-cloud-neocloud-rightsizing-2026-06-20.md`.
- **What's real vs. simulated vs. stub:** `CLAIMS.md`.

*Cleanup:* `!pkill -f "fak serve"; pkill -f ollama; pkill -f cloudflared`'''),
    ]


def notebook(cells):
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
            "colab": {"provenance": []},
        },
        "nbformat": 4, "nbformat_minor": 5,
    }


TARGETS = {
    "fak-quickstart.ipynb": quickstart_cells,
    "fak-inkernel.ipynb": inkernel_cells,
}


def render(name):
    return json.dumps(notebook(TARGETS[name]()), indent=1, ensure_ascii=True) + "\n"


def verify_refs():
    """Fail if a repo path/verb the cells depend on has gone away."""
    problems = []
    for rel, why in REQUIRED_PATHS:
        if not (ROOT / rel).exists():
            problems.append(f"missing {rel}  ({why})")
    # cmd/fak must still register the verbs the notebooks invoke
    src = "\n".join(p.read_text(encoding="utf-8", errors="ignore")
                    for p in (ROOT / "cmd" / "fak").glob("*.go")) if (ROOT/"cmd"/"fak").is_dir() else ""
    for verb in REQUIRED_VERBS:
        if f'"{verb}"' not in src:
            problems.append(f"verb '{verb}' not found in cmd/fak/*.go (notebook invokes it)")
    return problems


def main(argv):
    check = "--check" in argv
    drift, missing = [], verify_refs()
    for name in TARGETS:
        want = render(name)
        path = NB / name
        if check:
            have = path.read_text(encoding="utf-8") if path.exists() else ""
            if have != want:
                drift.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(want, encoding="utf-8")
            print(f"wrote notebooks/{name}  ({len(TARGETS[name]())} cells)")

    if check:
        for name in drift:
            print(f"DRIFT: notebooks/{name} differs from the generator — run "
                  f"`python tools/gen_notebooks.py`", file=sys.stderr)
            have = (NB / name).read_text(encoding="utf-8").splitlines() if (NB/name).exists() else []
            for line in list(difflib.unified_diff(
                    have, render(name).splitlines(), name, name+" (generated)", lineterm=""))[:20]:
                print("  " + line, file=sys.stderr)
        for p in missing:
            print(f"STALE REF: {p}", file=sys.stderr)
        if drift or missing:
            return 1
        print("notebooks in sync with the generator; all referenced repo paths/verbs present.")
    elif missing:
        for p in missing:
            print(f"WARNING stale ref: {p}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
