#!/usr/bin/env python3
"""
hero_video_gen.py — assemble the fak README hero video from the project's best
existing lab-grade visuals, with real chart animation.

The video is a calm, frontier-lab "model card reveal": a montage of the headline
hero charts with motion that *builds the chart in front of you* — the turn-tax
curves sweep left-to-right and their big multipliers count up; the dense
receipt cards (stat-card, sweep, capability matrix) wipe in from a steady raster.
It is silent, 2560x1440 by default, autoplay-loop friendly.

Pipeline (fully deterministic, no AI footage — the charts ARE the content):
  1. the load-bearing HERO scene (turn-tax) is drawn frame-by-frame in Pillow
     straight from its source-of-truth data file (tools/hero_turntax.data.json):
     axes are steady, the baseline/fak polylines trace L->R, the gap shades in,
     and the per-panel multiplier (20,480x / 9.7x / 4.1x) counts up. No number
     can drift from the data — the animation reads the same JSON the SVG does.
  2. the dense receipt scenes (stat-card, sweep, capability matrix, spectrum,
     hardware matrix) render each storyboard SVG -> high-res PNG @3x via headless
     Chrome (falls back to an existing visuals/<name>.png), then BUILD IN with a
     left-to-right reveal wipe + a settle, so they feel composed, not pasted.
  3. raw RGB frames are piped to ffmpeg (imageio-ffmpeg) -> H.264 mp4 at a rich
     bitrate (CRF 19), plus a poster PNG and a compact looping GIF teaser.

Usage:
  python tools/hero_video_gen.py                 # build mp4 + poster + gif (2560x1440)
  python tools/hero_video_gen.py --fast          # 15fps draft, quick preview
  python tools/hero_video_gen.py --no-gif        # skip the gif
  python tools/hero_video_gen.py --crf 19        # x264 quality (lower=better/bigger)

Storyboard:  visuals/hero-video.storyboard.json  (generated by the design panel)
Outputs:     visuals/hero-video.mp4 · hero-video-poster.png · hero-video.gif
"""
from __future__ import annotations

import argparse
import json
import math
import os
import subprocess
import sys
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageFont

LANCZOS = Image.Resampling.LANCZOS

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO = Path(__file__).resolve().parents[1]
VISUALS = REPO / "visuals"
TOOLS = REPO / "tools"
STORYBOARD = VISUALS / "hero-video.storyboard.json"
BUILD = Path(os.environ.get("HEROVID_BUILD", Path.home() / "AppData/Local/Temp/herovid"))
BUILD.mkdir(parents=True, exist_ok=True)

OUT_MP4 = VISUALS / "hero-video.mp4"
OUT_POSTER = VISUALS / "hero-video-poster.png"
OUT_GIF = VISUALS / "hero-video.gif"

# ---------------------------------------------------------------------------
# House palette (sampled from the hero SVGs)
# ---------------------------------------------------------------------------
INK = (20, 32, 43)        # #14202b  near-black
INK2 = (40, 54, 68)
GREEN = (46, 139, 87)     # #2e8b57  sea green accent
GREEN_D = (31, 107, 70)   # #1f6b46
BLUE = (59, 74, 122)      # #3b4a7a  baseline curve
GREY = (91, 106, 122)     # #5b6a7a
GREY_L = (154, 166, 178)  # #9aa6b2
CARD_BG = (250, 251, 252)
HAIRLINE = (205, 213, 221)  # #cdd5dd
GRID = (224, 230, 236)

FONTS = Path("C:/Windows/Fonts")


def font(name: str, size: int) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(str(FONTS / name), size)


# lazily-built font cache
_FC: dict[tuple[str, int], ImageFont.FreeTypeFont] = {}


def F(name: str, size: int) -> ImageFont.FreeTypeFont:
    key = (name, size)
    if key not in _FC:
        _FC[key] = font(name, size)
    return _FC[key]


SEMIBOLD = "seguisb.ttf"
BOLD = "segoeuib.ttf"
REG = "segoeui.ttf"
LIGHT = "segoeuil.ttf"
MONO = "consola.ttf"
MONO_B = "consolab.ttf"

# Canvas — overridden from the storyboard's `resolution`. SX is the linear scale
# vs the original 1920x1080 design grid, so every hardcoded size below tracks it.
W, H = 2560, 1440
SX = W / 1920.0


def S(v: float) -> int:
    """scale a 1920-grid dimension to the current canvas."""
    return round(v * SX)


# ---------------------------------------------------------------------------
# Asset rendering (raster scenes)
# ---------------------------------------------------------------------------
def find_chrome() -> str | None:
    for c in [
        os.environ.get("CHROME"),
        "C:/Program Files/Google/Chrome/Application/chrome.exe",
        "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    ]:
        if c and Path(c).exists():
            return c
    return None


def render_svg(name: str, scale: int = 3) -> Path:
    """Obtain a high-res raster for visuals/<name>.

    Hand-authored cards carry a numeric root width (e.g. width="1200") and
    rasterize crisply through headless Chrome. Mermaid decks instead emit
    width="100%" + a max-width style, which headless Chrome sizes unreliably
    (it can collapse to a tiny strip) — for those the committed visuals/<name>.png
    IS the canonical "always-visible" render (text baked in), so we use it
    directly. See visuals/RENDERING-NOTE.md."""
    out = BUILD / f"{name}@{scale}.png"
    if out.exists():
        return out
    svg = VISUALS / f"{name}.svg"
    fallback = VISUALS / f"{name}.png"
    txt = svg.read_text(encoding="utf-8", errors="ignore") if svg.exists() else ""
    import re
    root = re.search(r"<svg[^>]*>", txt)
    # numeric only if the root width is digits closed by a quote (width="1200"),
    # NOT a percentage (width="100%") — the "1" in "100%" must not count.
    numeric_root = bool(root and re.search(r'\bwidth="\d[\d.]*"', root.group(0)))

    # Mermaid (width="100%") -> prefer the canonical committed PNG.
    if not numeric_root and fallback.exists():
        return fallback

    chrome = find_chrome()
    if chrome and numeric_root:
        wm = re.search(r'\bwidth="(\d+(?:\.\d+)?)"', root.group(0))
        hm = re.search(r'\bheight="(\d+(?:\.\d+)?)"', root.group(0))
        w = round(float(wm.group(1))) if wm else None
        h = round(float(hm.group(1))) if hm else None
        if not (w and h):
            vb = re.search(r'viewBox="\s*[-\d.]+\s+[-\d.]+\s+([\d.]+)\s+([\d.]+)', txt)
            if vb:
                w, h = round(float(vb.group(1))), round(float(vb.group(2)))
        if w and h:
            cmd = [
                chrome, "--headless", "--disable-gpu", "--hide-scrollbars",
                f"--force-device-scale-factor={scale}",
                "--default-background-color=ffffffff",
                f"--window-size={w},{h}",
                f"--screenshot={out}", str(svg),
            ]
            subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            if out.exists():
                return out
    # last resort: committed raster, else a Chrome render of whatever we have
    if fallback.exists():
        return fallback
    raise FileNotFoundError(f"cannot obtain raster for {name} (no Chrome render, no {fallback})")


def load_visual(name: str, scale: int = 3) -> Image.Image:
    return Image.open(render_svg(name, scale)).convert("RGB")


def corner_bg(im: Image.Image) -> tuple[int, int, int]:
    w, h = im.size
    pts = [(3, 3), (w - 4, 3), (3, h - 4), (w - 4, h - 4)]
    cols = [im.getpixel(p) for p in pts]
    # pick the lightest corner (visuals sit on near-white)
    return max(cols, key=lambda c: sum(c))


def autotrim(im: Image.Image, bg: tuple[int, int, int], tol: int = 12,
             pad_frac: float = 0.012) -> Image.Image:
    """Crop the uniform outer margin (within `tol` of `bg`) so the chart fills the
    frame instead of floating inside the SVG's generous canvas padding."""
    bgimg = Image.new("RGB", im.size, bg)
    diff = ImageChops.difference(im, bgimg).convert("L")
    mask = diff.point(lambda p: 255 if p > tol else 0)
    bbox = mask.getbbox()
    if not bbox:
        return im
    x0, y0, x1, y1 = bbox
    pw = round((x1 - x0) * pad_frac)
    ph = round((y1 - y0) * pad_frac)
    return im.crop((max(0, x0 - pw), max(0, y0 - ph),
                    min(im.width, x1 + pw), min(im.height, y1 + ph)))


# ---------------------------------------------------------------------------
# Easing / motion
# ---------------------------------------------------------------------------
def smoothstep(x: float) -> float:
    x = max(0.0, min(1.0, x))
    return x * x * (3 - 2 * x)


def ease_out_cubic(x: float) -> float:
    x = max(0.0, min(1.0, x))
    return 1 - (1 - x) ** 3


def contain(im: Image.Image, bw: int, bh: int) -> Image.Image:
    w, h = im.size
    s = min(bw / w, bh / h)
    return im.resize((max(1, round(w * s)), max(1, round(h * s))), LANCZOS)


def ken_burns(base: Image.Image, bw: int, bh: int, frac: float, motion: str,
              intensity: float, bg: tuple[int, int, int]) -> Image.Image:
    """Return a (bw x bh) frame of `base` (already contained to <= box) with a
    subtle motion applied. `frac` is 0..1 progress within the scene."""
    box = Image.new("RGB", (bw, bh), bg)
    e = smoothstep(frac)
    zoom_amp = 0.16 * intensity      # max scale delta
    pan_amp = 0.10 * intensity       # max translate as frac of box

    s = 1.0
    dx = dy = 0.0
    if motion == "zoom_in":
        s = 1.0 + zoom_amp * e
    elif motion == "zoom_out":
        s = 1.0 + zoom_amp * (1 - e)
    elif motion == "reveal":
        s = 1.0 + zoom_amp * (1 - e) * 1.4
    elif motion == "pan_lr":
        s = 1.0 + zoom_amp * 0.5
        dx = (-pan_amp / 2 + pan_amp * e) * bw
    elif motion == "pan_rl":
        s = 1.0 + zoom_amp * 0.5
        dx = (pan_amp / 2 - pan_amp * e) * bw
    elif motion == "pan_down":
        s = 1.0 + zoom_amp * 0.5
        dy = (-pan_amp / 2 + pan_amp * e) * bh
    elif motion == "pan_up":
        s = 1.0 + zoom_amp * 0.5
        dy = (pan_amp / 2 - pan_amp * e) * bh
    else:  # static — a barely-there breath so it is not dead-still
        s = 1.0 + 0.01 * intensity * e

    cw, ch = base.size
    nw, nh = max(1, round(cw * s)), max(1, round(ch * s))
    cur = base.resize((nw, nh), LANCZOS) if (nw, nh) != (cw, ch) else base
    ox = round((bw - nw) / 2 + dx)
    oy = round((bh - nh) / 2 + dy)
    box.paste(cur, (ox, oy))
    return box


def reveal_wipe(base: Image.Image, bw: int, bh: int, frac: float,
                bg: tuple[int, int, int], settle: float = 0.62) -> Image.Image:
    """Build a steady raster IN: a soft left-to-right reveal of the chart over the
    first `settle` of the scene, then a gentle settle-zoom. Makes a dense card feel
    composed rather than pasted, without re-drawing its layout."""
    box = Image.new("RGB", (bw, bh), bg)
    # late-scene settle: a tiny zoom so it is alive after the wipe completes
    e_settle = smoothstep(max(0.0, (frac - settle) / max(1e-6, 1 - settle)))
    s = 1.0 + 0.05 * e_settle
    cw, ch = base.size
    nw, nh = max(1, round(cw * s)), max(1, round(ch * s))
    cur = base.resize((nw, nh), LANCZOS) if (nw, nh) != (cw, ch) else base
    ox = round((bw - nw) / 2)
    oy = round((bh - nh) / 2)

    # reveal fraction with a soft feathered leading edge
    rp = ease_out_cubic(min(1.0, frac / settle)) if settle > 0 else 1.0
    if rp >= 0.999:
        box.paste(cur, (ox, oy))
        return box
    reveal_x = int(nw * rp)
    feather = max(2, int(nw * 0.05))
    # paste the revealed portion fully
    if reveal_x > 0:
        crop = cur.crop((0, 0, min(nw, reveal_x), nh))
        box.paste(crop, (ox, oy))
    # feathered edge: blend a narrow band so the wipe edge is soft, not a hard line
    fx0 = max(0, reveal_x - feather)
    if reveal_x < nw and fx0 < nw:
        band = cur.crop((fx0, 0, min(nw, reveal_x + feather), nh))
        bandbox = Image.new("RGB", band.size, bg)
        # linear alpha across the band, 1 at the left, 0 at the right
        bw2 = band.size[0]
        alpha = Image.new("L", band.size, 0)
        adraw = ImageDraw.Draw(alpha)
        for i in range(bw2):
            a = int(255 * max(0.0, 1.0 - i / max(1, bw2)))
            adraw.line([(i, 0), (i, band.size[1])], fill=a)
        merged = Image.composite(band, bandbox, alpha)
        box.paste(merged, (ox + fx0, oy))
    return box


def scroll_progress(frac: float, hold: float) -> float:
    """0..1 scroll position with a static hold at each end so the viewer can read
    the top of the diagram before the pan starts and the bottom after it lands."""
    if frac <= hold:
        return 0.0
    if frac >= 1 - hold:
        return 1.0
    return smoothstep((frac - hold) / max(1e-6, 1 - 2 * hold))


def reveal_scroll(base: Image.Image, bw: int, bh: int, frac: float,
                  bg: tuple[int, int, int], axis: str, hold: float = 0.13) -> Image.Image:
    """Scale a tall (axis='v') or wide (axis='h') diagram to FILL the box on its
    short axis, then pan it fully along its long axis — a steady scroll that reads
    the whole diagram top-to-bottom (or left-to-right) instead of letterboxing it
    into a thin strip. Holds at both ends so the start and end frames are legible."""
    box = Image.new("RGB", (bw, bh), bg)
    iw, ih = base.size
    p = scroll_progress(frac, hold)
    if axis == "v":
        s = bw / iw
        nw, nh = bw, max(1, round(ih * s))
        cur = base.resize((nw, nh), LANCZOS)
        travel = max(0, nh - bh)
        box.paste(cur, (0, -round(travel * p)))
    else:  # 'h'
        s = bh / ih
        nw, nh = max(1, round(iw * s)), bh
        cur = base.resize((nw, nh), LANCZOS)
        travel = max(0, nw - bw)
        box.paste(cur, (-round(travel * p), 0))
    return box


# ---------------------------------------------------------------------------
# Text helpers
# ---------------------------------------------------------------------------
def measure(draw, text, fnt):
    b = draw.textbbox((0, 0), text, font=fnt)
    return b[2] - b[0], b[3] - b[1]


def wrap(draw, text, fnt, max_w):
    words = text.split()
    lines, cur = [], ""
    for w_ in words:
        trial = (cur + " " + w_).strip()
        if measure(draw, trial, fnt)[0] <= max_w or not cur:
            cur = trial
        else:
            lines.append(cur)
            cur = w_
    if cur:
        lines.append(cur)
    return lines


def draw_center(draw, cx, y, text, fnt, fill, max_w=None):
    lines = wrap(draw, text, fnt, max_w) if max_w else [text]
    asc, desc = fnt.getmetrics()
    lh = asc + desc + S(8)
    for i, ln in enumerate(lines):
        tw = measure(draw, ln, fnt)[0]
        draw.text((cx - tw / 2, y + i * lh), ln, font=fnt, fill=fill)
    return y + len(lines) * lh


# ---------------------------------------------------------------------------
# Plates  (static caption layer per scene)
# ---------------------------------------------------------------------------
# Content box for a chart on a visual/anim scene, on the 1920 grid; scaled by S().
# The "full" box is for self-contained cards that carry their own title/caption —
# they get nearly the whole frame and no headline plate stacked on top.
CONTENT_1920 = (96, 206, 1824, 1002)
FULL_CONTENT_1920 = (60, 58, 1860, 1014)


def content_box(full: bool = False):
    x0, y0, x1, y1 = FULL_CONTENT_1920 if full else CONTENT_1920
    return (S(x0), S(y0), S(x1), S(y1))


def _lum(c: tuple[int, int, int]) -> float:
    return 0.299 * c[0] + 0.587 * c[1] + 0.114 * c[2]


def is_dark(bg: tuple[int, int, int]) -> bool:
    return _lum(bg) < 128


def plate_full(scene, chart_bg) -> Image.Image:
    """A bare frame the colour of the card's own background, so a self-contained
    card (which already carries its title + caption + caveat) fills the frame
    edge-to-edge with matching letterbox and no duplicated headline."""
    return Image.new("RGB", (W, H), chart_bg)


def wordmark(draw, cx, y, size):
    """draw 'fak' + a green block cursor, centered on cx, top at y. returns bottom y."""
    fnt = F(MONO_B, size)
    txt = "fak"
    tw, th = measure(draw, txt, fnt)
    cur_w = round(size * 0.16)
    gap = round(size * 0.14)
    total = tw + gap + cur_w
    x0 = cx - total / 2
    draw.text((x0, y), txt, font=fnt, fill=INK)
    asc, desc = fnt.getmetrics()
    cy0 = y + round(size * 0.14)
    cy1 = y + round(size * 0.86)
    cx0 = x0 + tw + gap
    draw.rectangle([cx0, cy0, cx0 + cur_w, cy1], fill=GREEN)
    return y + asc + desc


def plate_visual(scene, chart_bg) -> Image.Image:
    im = Image.new("RGB", (W, H), chart_bg)
    d = ImageDraw.Draw(im)
    cx = W / 2
    y = S(40)
    head = F(SEMIBOLD, S(50))
    y = draw_center(d, cx, y, scene["headline"], head, INK, max_w=S(1740))
    if scene.get("subcaption"):
        y += S(4)
        sub = F(REG, S(28))
        y = draw_center(d, cx, y, scene["subcaption"], sub, GREY, max_w=S(1720))
    d.rectangle([cx - S(34), y + S(10), cx + S(34), y + S(14)], fill=GREEN)
    if scene.get("footer"):
        ff = F(REG, S(22))
        fw = measure(d, scene["footer"], ff)[0]
        d.text((cx - fw / 2, S(1024)), scene["footer"], font=ff, fill=GREY_L)
    bm = F(MONO_B, S(25))
    d.text((S(50), S(1022)), "fak", font=bm, fill=INK)
    bw0 = measure(d, "fak", bm)[0]
    d.rectangle([S(50) + bw0 + S(7), S(1026), S(50) + bw0 + S(15), S(1044)], fill=GREEN)
    return im


def plate_title(scene) -> Image.Image:
    im = Image.new("RGB", (W, H), CARD_BG)
    d = ImageDraw.Draw(im)
    cx = W / 2
    by = wordmark(d, cx, S(300), S(200))
    sub_line = "the agent kernel"
    if "—" in scene["headline"]:
        sub_line = scene["headline"].split("—", 1)[1].strip()
    sf = F(LIGHT, S(58))
    swid = measure(d, sub_line, sf)[0]
    d.text((cx - swid / 2, by + S(6)), sub_line, font=sf, fill=INK2)
    yy = by + S(6) + S(80)
    d.rectangle([cx - S(60), yy + S(8), cx + S(60), yy + S(13)], fill=GREEN)
    if scene.get("subcaption"):
        tf = F(REG, S(34))
        draw_center(d, cx, yy + S(44), scene["subcaption"], tf, GREY, max_w=S(1280))
    if scene.get("footer"):
        ff = F(REG, S(24))
        fw = measure(d, scene["footer"], ff)[0]
        d.text((cx - fw / 2, S(1004)), scene["footer"], font=ff, fill=GREY_L)
    return im


def plate_closing(scene) -> Image.Image:
    im = Image.new("RGB", (W, H), CARD_BG)
    d = ImageDraw.Draw(im)
    cx = W / 2
    by = wordmark(d, cx, S(360), S(170))
    yy = by + S(18)
    d.rectangle([cx - S(60), yy, cx + S(60), yy + S(5)], fill=GREEN)
    if scene.get("subcaption"):
        tf = F(SEMIBOLD, S(40))
        draw_center(d, cx, yy + S(40), scene["subcaption"], tf, INK2, max_w=S(1300))
    if scene.get("footer"):
        ff = F(MONO, S(30))
        fw = measure(d, scene["footer"], ff)[0]
        d.text((cx - fw / 2, S(920)), scene["footer"], font=ff, fill=GREEN_D)
    return im


def plate_interstitial(scene) -> Image.Image:
    im = Image.new("RGB", (W, H), CARD_BG)
    d = ImageDraw.Draw(im)
    cx = W / 2
    head = F(SEMIBOLD, S(70))
    y = draw_center(d, cx, S(348), scene["headline"], head, INK, max_w=S(1500))
    d.rectangle([cx - S(60), y + S(18), cx + S(60), y + S(23)], fill=GREEN)
    sub = scene.get("subcaption") or ""
    parts = [p.strip() for p in sub.split("  ") if p.strip()]
    bf = F(REG, S(38))
    yy = y + S(70)
    for p in parts:
        yy = draw_center(d, cx, yy, p, bf, INK2, max_w=S(1500)) + S(14)
    if scene.get("footer"):
        ff = F(LIGHT, S(30))
        draw_center(d, cx, yy + S(10), scene["footer"], ff, GREY, max_w=S(1400))
    return im


# ---------------------------------------------------------------------------
# Animated turn-tax renderer — drawn frame-by-frame from the data file.
# This is the HERO: axes steady, curves sweep L->R, gap shades, multiplier counts up.
# ---------------------------------------------------------------------------
def _fmt_mult(target_str: str, frac: float) -> str:
    """Count a multiplier string up to its target over `frac` (0..1).
    Preserves the trailing unit ('×' / '%') and thousands separators."""
    t = target_str.strip()
    unit = ""
    if t.endswith("×") or t.endswith("x"):
        unit = "×"
        t = t[:-1]
    elif t.endswith("%"):
        unit = "%"
        t = t[:-1]
    num = float(t.replace(",", ""))
    cur = num * ease_out_cubic(frac)
    if num >= 1000:
        return f"{cur:,.0f}{unit}"
    if num >= 100:
        return f"{cur:,.0f}{unit}"
    # one decimal for the small multipliers (9.7×, 4.1×)
    return f"{cur:,.1f}{unit}"


class TurnTaxAnim:
    """Holds the parsed turn-tax data and renders the chart layer at a reveal frac."""

    def __init__(self):
        data = json.loads((TOOLS / "hero_turntax.data.json").read_text(encoding="utf-8"))
        self.panels = data["panels"]
        self.legend = data["legend"]

    def render(self, bw: int, bh: int, frac: float, bg) -> Image.Image:
        im = Image.new("RGB", (bw, bh), bg)
        d = ImageDraw.Draw(im)
        n = len(self.panels)
        gap = S(34)
        pw = (bw - gap * (n - 1)) // n
        # reveal is global; each panel sweeps with a small stagger so it reads as a build
        for i, p in enumerate(self.panels):
            px = i * (pw + gap)
            stagger = 0.10 * i
            pf = max(0.0, min(1.0, (frac - stagger) / max(1e-6, 1 - 0.10 * (n - 1))))
            self._panel(d, im, px, 0, pw, bh, p, pf)
        return im

    def _panel(self, d, im, x, y, pw, ph, p, pf):
        # panel chrome
        title = F(SEMIBOLD, S(30))
        subt = F(REG, S(18))
        d.text((x, y + S(2)), p["title"], font=title, fill=INK)
        d.text((x, y + S(40)), p["subtitle"], font=subt, fill=GREY)

        # plot rect inside the panel
        plot_x0 = x + S(14)
        plot_x1 = x + pw - S(10)
        plot_y0 = y + S(96)
        plot_y1 = y + ph - S(74)
        pw2 = plot_x1 - plot_x0
        ph2 = plot_y1 - plot_y0

        x_vals = p["x_vals"]
        xmin, xmax = min(x_vals), max(x_vals)
        y_max = float(p["y_max"])

        def sx(v):
            return plot_x0 + (v - xmin) / (xmax - xmin) * pw2

        def sy(v):
            return plot_y1 - (v / y_max) * ph2

        # gridlines + y ticks (steady)
        gf = F(REG, S(16))
        for yt in p["y_ticks"]:
            yy = sy(yt["v"])
            d.line([(plot_x0, yy), (plot_x1, yy)], fill=GRID, width=max(1, S(1)))
            d.text((plot_x0 + S(2), yy - S(20)), yt["t"], font=gf, fill=GREY_L)
        # x axis
        d.line([(plot_x0, plot_y1), (plot_x1, plot_y1)], fill=HAIRLINE, width=max(1, S(2)))
        for xt, xv in zip(p["x_ticks"], x_vals):
            xx = sx(xv)
            tw = measure(d, xt, gf)[0]
            d.text((xx - tw / 2, plot_y1 + S(8)), xt, font=gf, fill=GREY_L)

        # build the two polylines, revealed up to `pf` along the x extent
        base = p["baseline"]
        fak = p["fak"]
        # reveal as a continuous x position so the line grows smoothly, not point-by-point
        reveal_v = xmin + (xmax - xmin) * ease_out_cubic(pf)

        def clipped_line(vals, reveal):
            pts = []
            for xv, yv in zip(x_vals, vals):
                if xv <= reveal:
                    pts.append((sx(xv), sy(yv)))
                else:
                    # interpolate the partial segment to the reveal x
                    # find the segment this reveal falls in
                    prev_i = max(0, [j for j, xx in enumerate(x_vals) if xx <= reveal][-1]
                                 if any(xx <= reveal for xx in x_vals) else 0)
                    if prev_i < len(x_vals) - 1:
                        x0v, x1v = x_vals[prev_i], x_vals[prev_i + 1]
                        y0v, y1v = vals[prev_i], vals[prev_i + 1]
                        if x1v != x0v and x0v <= reveal <= x1v:
                            t = (reveal - x0v) / (x1v - x0v)
                            yy = y0v + (y1v - y0v) * t
                            pts.append((sx(reveal), sy(yy)))
                    break
            return pts

        base_pts = clipped_line(base, reveal_v)
        fak_pts = clipped_line(fak, reveal_v)

        # shade the gap between baseline and fak up to the reveal
        if len(base_pts) >= 2 and len(fak_pts) >= 2:
            poly = base_pts + list(reversed(fak_pts))
            shade = Image.new("RGBA", im.size, (0, 0, 0, 0))
            sd = ImageDraw.Draw(shade)
            sd.polygon(poly, fill=(46, 139, 87, 34))
            im.paste(Image.alpha_composite(im.convert("RGBA"), shade).convert("RGB"), (0, 0))
            d2 = ImageDraw.Draw(im)
        else:
            d2 = d

        lw = max(2, S(4))
        if len(base_pts) >= 2:
            d2.line(base_pts, fill=BLUE, width=lw, joint="curve")
        if len(fak_pts) >= 2:
            d2.line(fak_pts, fill=GREEN, width=lw, joint="curve")
        # endpoint dots once fully revealed
        if pf > 0.985:
            r = max(2, S(5))
            bx, by = sx(x_vals[-1]), sy(base[-1])
            fx, fy = sx(x_vals[-1]), sy(fak[-1])
            d2.ellipse([bx - r, by - r, bx + r, by + r], fill=BLUE)
            d2.ellipse([fx - r, fy - r, fx + r, fy + r], fill=GREEN)

        # the big multiplier, counting up. Sits in the empty lower-centre wedge
        # (below the steep baseline, above the flat fak line) with a soft halo in
        # the card background so it stays legible wherever a curve passes near.
        mult_f = F(MONO_B, S(58))
        mtxt = _fmt_mult(p["mult"], pf)
        mtw, mth = measure(d2, mtxt, mult_f)
        mcx = plot_x0 + pw2 * 0.5
        mcy = plot_y1 - ph2 * 0.30
        subf = F(SEMIBOLD, S(20))
        stw = measure(d2, p["mult_sub"], subf)[0]
        sub_x = mcx - stw / 2
        sub_y = mcy + mth / 2 + S(6)

        def halo(cx_, top_, txt_, fnt_, w_):
            r = max(2, S(4))
            for ox in (-r, 0, r):
                for oy in (-r, 0, r):
                    d2.text((cx_ - w_ / 2 + ox, top_ + oy), txt_, font=fnt_, fill=CARD_BG)

        halo(mcx, mcy - mth / 2, mtxt, mult_f, mtw)
        d2.text((mcx - mtw / 2, mcy - mth / 2), mtxt, font=mult_f, fill=GREEN_D)
        if pf > 0.55:
            halo(mcx, sub_y, p["mult_sub"], subf, stw)
            d2.text((sub_x, sub_y), p["mult_sub"], font=subf, fill=INK2)
        # panel footnote — one line, ellipsised, kept clear of the x tick labels
        if pf > 0.85:
            footf = F(REG, S(15))
            ftxt = wrap(d2, p["mult_foot"], footf, pw2)
            line = ftxt[0] if ftxt else ""
            if len(ftxt) > 1:
                line = line.rstrip(" .,—-") + " …"
            d2.text((plot_x0, plot_y1 + S(40)), line, font=footf, fill=GREY_L)


# ---------------------------------------------------------------------------
# Scene model
# ---------------------------------------------------------------------------
class Scene:
    def __init__(self, spec):
        self.spec = spec
        self.kind = spec["kind"]
        self.dur = float(spec["duration_s"])
        self.tin = float(spec["transition_dur_s"])  # cross-dissolve duration
        self.motion = spec["motion"]
        self.intensity = float(spec["motion_intensity"])
        self.render_mode = spec.get("render", "kenburns")  # kenburns | wipe | anim
        self.chart_bg = CARD_BG
        self.base = None
        self.box = None
        self.plate = None
        self.anim = None
        self._build()

    def _build(self):
        s = self.spec
        if self.kind == "visual":
            self.full = bool(s.get("full"))
            x0, y0, x1, y1 = content_box(self.full)
            bw, bh = x1 - x0, y1 - y0
            self.box = (x0, y0, bw, bh)
            if self.render_mode == "anim" and s.get("visual") == "60-hero-turntax-curves":
                self.anim = TurnTaxAnim()
                self.chart_bg = CARD_BG
                self.plate = plate_visual(s, self.chart_bg)
            else:
                chart = load_visual(s["visual"])
                self.chart_bg = corner_bg(chart)
                # self-contained cards are designed edge-to-edge — don't trim them.
                if not self.full:
                    chart = autotrim(chart, self.chart_bg)
                if self.render_mode == "scroll":
                    # keep full-res; reveal_scroll scales + pans the long axis.
                    iw, ih = chart.size
                    self.scroll_axis = s.get("scroll_axis") or (
                        "v" if (ih / iw) > (bh / bw) else "h")
                    self.base = chart
                else:
                    self.base = contain(chart, round(bw * 0.998), round(bh * 0.998))
                self.plate = plate_full(s, self.chart_bg) if self.full else \
                    plate_visual(s, self.chart_bg)
        elif self.kind == "title":
            self.plate = plate_title(s)
        elif self.kind == "closing":
            self.plate = plate_closing(s)
        else:
            self.plate = plate_interstitial(s)

    def frame(self, local_t: float) -> Image.Image:
        frac = min(1.0, local_t / self.dur) if self.dur > 0 else 1.0
        if self.kind == "visual":
            im = self.plate.copy()
            x0, y0, bw, bh = self.box
            if self.anim is not None:
                chart = self.anim.render(bw, bh, frac, self.chart_bg)
            elif self.render_mode == "wipe":
                chart = reveal_wipe(self.base, bw, bh, frac, self.chart_bg)
            elif self.render_mode == "scroll":
                chart = reveal_scroll(self.base, bw, bh, frac, self.chart_bg, self.scroll_axis)
            else:
                chart = ken_burns(self.base, bw, bh, frac, self.motion, self.intensity, self.chart_bg)
            im.paste(chart, (x0, y0))
            return im
        else:
            return ken_burns(self.plate, W, H, frac, self.motion, self.intensity, CARD_BG)


# ---------------------------------------------------------------------------
# Timeline
# ---------------------------------------------------------------------------
def build_timeline(scenes):
    starts = [0.0]
    for i in range(1, len(scenes)):
        starts.append(starts[i - 1] + scenes[i - 1].dur - scenes[i].tin)
    ends = [starts[i] + scenes[i].dur for i in range(len(scenes))]
    return starts, ends


def render(scenes, fps, frange=None):
    starts, ends = build_timeline(scenes)
    total = ends[-1]
    total_frames = math.ceil(total * fps)
    bg0 = Image.new("RGB", (W, H), CARD_BG)

    f_lo, f_hi = 0, total_frames
    if frange:
        f_lo, f_hi = frange

    for f in range(f_lo, f_hi):
        t = f / fps
        cur = 0
        for i in range(len(scenes)):
            if starts[i] <= t < ends[i] and starts[i] >= starts[cur]:
                cur = i
        if t >= ends[-1]:
            cur = len(scenes) - 1
        s = scenes[cur]
        over = s.frame(min(t - starts[cur], s.dur))
        if cur == 0 and t < s.tin and s.tin > 0:
            a = smoothstep(t / s.tin)
            frame = Image.blend(bg0, over, a)
        elif cur > 0 and t < starts[cur] + s.tin and s.tin > 0:
            prev = scenes[cur - 1]
            under = prev.frame(min(t - starts[cur - 1], prev.dur))
            a = smoothstep((t - starts[cur]) / s.tin)
            frame = Image.blend(under, over, a)
        else:
            frame = over
        frame = draw_progress(frame, t / total)
        yield f, frame


def draw_progress(im, frac):
    d = ImageDraw.Draw(im)
    bw = round(W * max(0.0, min(1.0, frac)))
    h = max(4, S(5))
    d.rectangle([0, H - h, W, H], fill=HAIRLINE)
    d.rectangle([0, H - h, bw, H], fill=GREEN)
    return im


# ---------------------------------------------------------------------------
# Encode
# ---------------------------------------------------------------------------
def ffmpeg_exe():
    import imageio_ffmpeg
    return imageio_ffmpeg.get_ffmpeg_exe()


def write_mp4(scenes, fps, out: Path, want_poster=False, crf=19, poster: Path = OUT_POSTER):
    ff = ffmpeg_exe()
    cmd = [
        ff, "-y", "-f", "rawvideo", "-pix_fmt", "rgb24",
        "-s", f"{W}x{H}", "-r", str(fps), "-i", "-",
        "-an", "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-crf", str(crf), "-preset", "slow", "-profile:v", "high",
        "-movflags", "+faststart", str(out),
    ]
    proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.DEVNULL,
                            stderr=subprocess.DEVNULL)
    n = 0
    poster_frame = None
    starts, ends = build_timeline(scenes)
    poster_idx = None
    if want_poster:
        # prefer a scene flagged "poster": true; else the turn-tax count-up beat.
        cands = ([i for i, s in enumerate(scenes) if s.spec.get("poster")] or
                 [i for i, s in enumerate(scenes)
                  if s.spec.get("visual") == "60-hero-turntax-curves"])
        if cands:
            i = cands[0]
            s = scenes[i]
            # land on the scene's final readable beat, but BEFORE the cross-dissolve
            # into the next scene starts (so no ghost bleed-through)
            nxt_tin = scenes[i + 1].tin if i + 1 < len(scenes) else 0.0
            poster_t = starts[i] + s.dur - nxt_tin - 0.15
            poster_idx = round(poster_t * fps)
    for f, frame in render(scenes, fps):
        proc.stdin.write(frame.tobytes())
        if poster_idx is not None and f == poster_idx:
            poster_frame = frame.copy()
        n += 1
        if n % 60 == 0:
            print(f"  ...{n} frames", file=sys.stderr)
    proc.stdin.close()
    proc.wait()
    print(f"wrote {out}  ({n} frames @ {fps}fps = {n/fps:.1f}s)")
    if want_poster:
        if poster_frame is None:
            poster_frame = next(fr for _, fr in render(scenes, fps, frange=(poster_idx or 0, (poster_idx or 0) + 1)))
        poster_frame.save(poster)
        print(f"wrote {poster}")


# A condensed highlight reel for the README GIF: the load-bearing beats only,
# shortened, so the GIF stays small (GitHub markdown can't autoplay an mp4).
GIF_BEATS = {
    "s1_title": 1.8,
    "s2_turntax": 3.4,      # the HERO — measured 9.7x sweep + count-up
    "s5_capability": 2.4,   # owns the whole boundary
    "s6_statcard": 2.4,     # three pillars + honest fence
    "s9_closing": 1.8,
}


def condense(scene_specs):
    # A storyboard can mark its own GIF beats with "gif": true (+ optional
    # "gif_dur"); otherwise fall back to the hero deck's hardcoded beat list.
    flagged = [sp for sp in scene_specs if sp.get("gif")]
    out = []
    if flagged:
        for sp in flagged:
            c = dict(sp)
            c["duration_s"] = float(sp.get("gif_dur", 2.4))
            c["transition_dur_s"] = 0.5
            out.append(c)
        return out
    for sp in scene_specs:
        if sp["id"] in GIF_BEATS:
            c = dict(sp)
            c["duration_s"] = GIF_BEATS[sp["id"]]
            c["transition_dur_s"] = 0.55
            out.append(c)
    return out


def build_gif(scene_specs, out_gif: Path, fps=24, fps_gif=12, width=820):
    """Render the condensed highlight reel to a temp mp4, then a compact looping GIF."""
    scenes = [Scene(s) for s in condense(scene_specs)]
    tmp = BUILD / "hero-gif-src.mp4"
    write_mp4(scenes, fps, tmp, want_poster=False)
    ff = ffmpeg_exe()
    vf = (f"fps={fps_gif},scale={width}:-1:flags=lanczos,"
          f"split[s0][s1];[s0]palettegen=max_colors=96[p];[s1][p]paletteuse=dither=bayer:bayer_scale=5")
    subprocess.run([ff, "-y", "-i", str(tmp), "-vf", vf, "-loop", "0", str(out_gif)],
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    if out_gif.exists():
        print(f"wrote {out_gif}  ({out_gif.stat().st_size/1e6:.1f} MB)")


# ---------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fast", action="store_true", help="15fps draft")
    ap.add_argument("--no-gif", action="store_true")
    ap.add_argument("--crf", type=int, default=19,
                    help="x264 quality (lower=better/bigger); 19 is a rich 1440p bitrate")
    ap.add_argument("--storyboard", default=str(STORYBOARD))
    ap.add_argument("--out", default=str(OUT_MP4))
    ap.add_argument("--poster", default=None, help="poster png path (default: <out>-poster.png)")
    ap.add_argument("--gif", default=None, help="gif path (default: <out>.gif)")
    args = ap.parse_args()

    spec = json.loads(Path(args.storyboard).read_text(encoding="utf-8"))
    global W, H, SX
    W = spec.get("resolution", {}).get("w", W)
    H = spec.get("resolution", {}).get("h", H)
    SX = W / 1920.0
    fps = 15 if args.fast else spec.get("fps", 30)

    # poster/gif default to the out stem so a second storyboard never clobbers
    # the hero video's hero-video-poster.png / hero-video.gif.
    out = Path(args.out)
    poster = Path(args.poster) if args.poster else out.with_name(out.stem + "-poster.png")
    gif = Path(args.gif) if args.gif else out.with_suffix(".gif")

    print(f"building {len(spec['scenes'])} scenes -> {out}  ({W}x{H} @{fps}fps, crf {args.crf})")
    scenes = [Scene(s) for s in spec["scenes"]]
    write_mp4(scenes, fps, out, want_poster=True, crf=args.crf, poster=poster)
    if not args.no_gif:
        build_gif(spec["scenes"], gif)


if __name__ == "__main__":
    main()
