#!/usr/bin/env python3
"""
hero_video_gen.py — assemble the fak README hero video from the project's best
existing lab-grade visuals.

The video is a calm, frontier-lab "model card reveal": a montage of the four
headline hero charts (plus the performance spectrum + hardware matrix) with
subtle Ken-Burns motion, gentle cross-dissolves, and house-style title/closing
cards. It is silent, 1920x1080, autoplay-loop friendly.

Pipeline (fully deterministic, no AI footage — the charts ARE the content):
  1. render each storyboard visual SVG -> high-res PNG @2x via headless Chrome
     (falls back to an existing visuals/<name>.png if Chrome is unavailable),
  2. composite the full frame sequence in Pillow (motion on the chart layer only;
     captions stay rock-steady; letterbox is filled with each chart's own
     background colour so it is seamless),
  3. pipe raw RGB frames to the bundled ffmpeg (imageio-ffmpeg) -> H.264 mp4,
     plus a poster PNG and a compact looping GIF preview for README embedding.

Usage:
  python tools/hero_video_gen.py                 # build mp4 + poster + gif
  python tools/hero_video_gen.py --fast          # 15fps draft, quick preview
  python tools/hero_video_gen.py --no-gif        # skip the gif
  python tools/hero_video_gen.py --frames 0,300  # render only a frame range (debug)

Storyboard:  visuals/hero-video.storyboard.json  (generated by the design panel)
Outputs:     visuals/hero-video.mp4 · hero-video-poster.png · hero-video.gif
"""
from __future__ import annotations

import argparse
import json
import math
import os
import subprocess
import sys
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageFont

LANCZOS = Image.Resampling.LANCZOS

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO = Path(__file__).resolve().parents[1]
VISUALS = REPO / "visuals"
STORYBOARD = VISUALS / "hero-video.storyboard.json"
BUILD = Path(os.environ.get("HEROVID_BUILD", Path.home() / "AppData/Local/Temp/herovid"))
BUILD.mkdir(parents=True, exist_ok=True)

OUT_MP4 = VISUALS / "hero-video.mp4"
OUT_POSTER = VISUALS / "hero-video-poster.png"
OUT_GIF = VISUALS / "hero-video.gif"

# ---------------------------------------------------------------------------
# House palette (sampled from the hero SVGs)
# ---------------------------------------------------------------------------
INK = (20, 32, 43)        # #14202b  near-black
INK2 = (40, 54, 68)
GREEN = (46, 139, 87)     # #2e8b57  sea green accent
GREEN_D = (31, 107, 70)   # #1f6b46
GREY = (91, 106, 122)     # #5b6a7a
GREY_L = (154, 166, 178)  # #9aa6b2
CARD_BG = (250, 251, 252)
HAIRLINE = (205, 213, 221)  # #cdd5dd

FONTS = Path("C:/Windows/Fonts")


def font(name: str, size: int) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(str(FONTS / name), size)


# lazily-built font cache
_FC: dict[tuple[str, int], ImageFont.FreeTypeFont] = {}


def F(name: str, size: int) -> ImageFont.FreeTypeFont:
    key = (name, size)
    if key not in _FC:
        _FC[key] = font(name, size)
    return _FC[key]


SEMIBOLD = "seguisb.ttf"
BOLD = "segoeuib.ttf"
REG = "segoeui.ttf"
LIGHT = "segoeuil.ttf"
MONO = "consola.ttf"
MONO_B = "consolab.ttf"

W, H = 1920, 1080


# ---------------------------------------------------------------------------
# Asset rendering
# ---------------------------------------------------------------------------
def find_chrome() -> str | None:
    for c in [
        os.environ.get("CHROME"),
        "C:/Program Files/Google/Chrome/Application/chrome.exe",
        "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    ]:
        if c and Path(c).exists():
            return c
    return None


def render_svg(name: str, scale: int = 2) -> Path:
    """Render visuals/<name>.svg -> BUILD/<name>.png at `scale`x via headless Chrome.
    Falls back to an existing visuals/<name>.png if Chrome is missing/fails."""
    out = BUILD / f"{name}.png"
    svg = VISUALS / f"{name}.svg"
    chrome = find_chrome()
    if chrome and svg.exists():
        txt = svg.read_text(encoding="utf-8", errors="ignore")
        import re
        wm = re.search(r'width="(\d+)"', txt)
        hm = re.search(r'height="(\d+)"', txt)
        if wm and hm:
            w, h = int(wm.group(1)), int(hm.group(1))
            cmd = [
                chrome, "--headless", "--disable-gpu", "--hide-scrollbars",
                f"--force-device-scale-factor={scale}",
                "--default-background-color=ffffffff",
                f"--window-size={w},{h}",
                f"--screenshot={out}", str(svg),
            ]
            subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            if out.exists():
                return out
    # fallback: committed raster
    fallback = VISUALS / f"{name}.png"
    if fallback.exists():
        return fallback
    raise FileNotFoundError(f"cannot obtain raster for {name} (no Chrome render, no {fallback})")


def load_visual(name: str) -> Image.Image:
    return Image.open(render_svg(name)).convert("RGB")


def corner_bg(im: Image.Image) -> tuple[int, int, int]:
    w, h = im.size
    pts = [(3, 3), (w - 4, 3), (3, h - 4), (w - 4, h - 4)]
    cols = [im.getpixel(p) for p in pts]
    # pick the lightest corner (visuals sit on near-white)
    return max(cols, key=lambda c: sum(c))


def autotrim(im: Image.Image, bg: tuple[int, int, int], tol: int = 12,
             pad_frac: float = 0.012) -> Image.Image:
    """Crop the uniform outer margin (within `tol` of `bg`) so the chart fills the
    frame instead of floating inside the SVG's generous canvas padding."""
    bgimg = Image.new("RGB", im.size, bg)
    diff = ImageChops.difference(im, bgimg).convert("L")
    mask = diff.point(lambda p: 255 if p > tol else 0)
    bbox = mask.getbbox()
    if not bbox:
        return im
    x0, y0, x1, y1 = bbox
    pw = round((x1 - x0) * pad_frac)
    ph = round((y1 - y0) * pad_frac)
    return im.crop((max(0, x0 - pw), max(0, y0 - ph),
                    min(im.width, x1 + pw), min(im.height, y1 + ph)))


# ---------------------------------------------------------------------------
# Easing / motion
# ---------------------------------------------------------------------------
def smoothstep(x: float) -> float:
    x = max(0.0, min(1.0, x))
    return x * x * (3 - 2 * x)


def contain(im: Image.Image, bw: int, bh: int) -> Image.Image:
    w, h = im.size
    s = min(bw / w, bh / h)
    return im.resize((max(1, round(w * s)), max(1, round(h * s))), LANCZOS)


def ken_burns(base: Image.Image, bw: int, bh: int, frac: float, motion: str,
              intensity: float, bg: tuple[int, int, int]) -> Image.Image:
    """Return a (bw x bh) frame of `base` (already contained to <= box) with a
    subtle motion applied. `frac` is 0..1 progress within the scene. Any reveal
    is filled with `bg`, which matches the chart's own background, so it is
    seamless."""
    box = Image.new("RGB", (bw, bh), bg)
    e = smoothstep(frac)
    zoom_amp = 0.18 * intensity      # max scale delta
    pan_amp = 0.12 * intensity       # max translate as frac of box

    s = 1.0
    dx = dy = 0.0
    if motion == "zoom_in":
        s = 1.0 + zoom_amp * e
    elif motion == "zoom_out":
        s = 1.0 + zoom_amp * (1 - e)
    elif motion == "reveal":
        s = 1.0 + zoom_amp * (1 - e) * 1.4
    elif motion == "pan_lr":
        s = 1.0 + zoom_amp * 0.5
        dx = (-pan_amp / 2 + pan_amp * e) * bw
    elif motion == "pan_rl":
        s = 1.0 + zoom_amp * 0.5
        dx = (pan_amp / 2 - pan_amp * e) * bw
    elif motion == "pan_down":
        s = 1.0 + zoom_amp * 0.5
        dy = (-pan_amp / 2 + pan_amp * e) * bh
    elif motion == "pan_up":
        s = 1.0 + zoom_amp * 0.5
        dy = (pan_amp / 2 - pan_amp * e) * bh
    else:  # static — a barely-there breath so it is not dead-still
        s = 1.0 + 0.01 * intensity * e

    cw, ch = base.size
    nw, nh = max(1, round(cw * s)), max(1, round(ch * s))
    cur = base.resize((nw, nh), LANCZOS) if (nw, nh) != (cw, ch) else base
    ox = round((bw - nw) / 2 + dx)
    oy = round((bh - nh) / 2 + dy)
    box.paste(cur, (ox, oy))
    return box


# ---------------------------------------------------------------------------
# Text helpers
# ---------------------------------------------------------------------------
def measure(draw, text, fnt):
    b = draw.textbbox((0, 0), text, font=fnt)
    return b[2] - b[0], b[3] - b[1]


def wrap(draw, text, fnt, max_w):
    words = text.split()
    lines, cur = [], ""
    for w_ in words:
        trial = (cur + " " + w_).strip()
        if measure(draw, trial, fnt)[0] <= max_w or not cur:
            cur = trial
        else:
            lines.append(cur)
            cur = w_
    if cur:
        lines.append(cur)
    return lines


def draw_center(draw, cx, y, text, fnt, fill, max_w=None):
    if max_w:
        lines = wrap(draw, text, fnt, max_w)
    else:
        lines = [text]
    asc, desc = fnt.getmetrics()
    lh = asc + desc + 8
    for i, ln in enumerate(lines):
        tw = measure(draw, ln, fnt)[0]
        draw.text((cx - tw / 2, y + i * lh), ln, font=fnt, fill=fill)
    return y + len(lines) * lh


def draw_left(draw, x, y, text, fnt, fill, max_w=None):
    lines = wrap(draw, text, fnt, max_w) if max_w else [text]
    asc, desc = fnt.getmetrics()
    lh = asc + desc + 8
    for i, ln in enumerate(lines):
        draw.text((x, y + i * lh), ln, font=fnt, fill=fill)
    return y + len(lines) * lh


# ---------------------------------------------------------------------------
# Plates  (static layer per scene)
# ---------------------------------------------------------------------------
CONTENT = (96, 206, 1824, 1002)  # x0,y0,x1,y1 for the chart on visual scenes


def wordmark(draw, cx, y, size):
    """draw 'fak' + a green block cursor, centered on cx, top at y. returns bottom y."""
    fnt = F(MONO_B, size)
    txt = "fak"
    tw, th = measure(draw, txt, fnt)
    cur_w = round(size * 0.16)
    gap = round(size * 0.14)
    total = tw + gap + cur_w
    x0 = cx - total / 2
    draw.text((x0, y), txt, font=fnt, fill=INK)
    asc, desc = fnt.getmetrics()
    # block cursor sits on the text baseline-ish
    cy0 = y + round(size * 0.14)
    cy1 = y + round(size * 0.86)
    cx0 = x0 + tw + gap
    draw.rectangle([cx0, cy0, cx0 + cur_w, cy1], fill=GREEN)
    return y + asc + desc


def plate_visual(scene, chart_bg) -> Image.Image:
    im = Image.new("RGB", (W, H), chart_bg)
    d = ImageDraw.Draw(im)
    cx = W / 2
    # top caption band
    y = 40
    head = F(SEMIBOLD, 50)
    y = draw_center(d, cx, y, scene["headline"], head, INK, max_w=1740)
    if scene.get("subcaption"):
        y += 4
        sub = F(REG, 28)
        y = draw_center(d, cx, y, scene["subcaption"], sub, GREY, max_w=1720)
    # short green accent rule under the caption
    d.rectangle([cx - 34, y + 10, cx + 34, y + 14], fill=GREEN)
    # footer
    if scene.get("footer"):
        ff = F(REG, 22)
        fw = measure(d, scene["footer"], ff)[0]
        d.text((cx - fw / 2, 1024), scene["footer"], font=ff, fill=GREY_L)
    # tiny brand mark, bottom-left
    bm = F(MONO_B, 25)
    d.text((50, 1022), "fak", font=bm, fill=INK)
    bw0 = measure(d, "fak", bm)[0]
    d.rectangle([50 + bw0 + 7, 1026, 50 + bw0 + 15, 1044], fill=GREEN)
    return im


def plate_title(scene) -> Image.Image:
    im = Image.new("RGB", (W, H), CARD_BG)
    d = ImageDraw.Draw(im)
    cx = W / 2
    # big wordmark
    wm_size = 200
    by = wordmark(d, cx, 300, wm_size)
    # subtitle "the agent kernel" (pull from headline after the em dash)
    sub_line = "the agent kernel"
    if "—" in scene["headline"]:
        sub_line = scene["headline"].split("—", 1)[1].strip()
    sf = F(LIGHT, 58)
    swid = measure(d, sub_line, sf)[0]
    d.text((cx - swid / 2, by + 6), sub_line, font=sf, fill=INK2)
    yy = by + 6 + 80
    # accent rule
    d.rectangle([cx - 60, yy + 8, cx + 60, yy + 13], fill=GREEN)
    # tagline (subcaption)
    if scene.get("subcaption"):
        tf = F(REG, 34)
        draw_center(d, cx, yy + 44, scene["subcaption"], tf, GREY, max_w=1280)
    # footer
    if scene.get("footer"):
        ff = F(REG, 24)
        fw = measure(d, scene["footer"], ff)[0]
        d.text((cx - fw / 2, 1004), scene["footer"], font=ff, fill=GREY_L)
    return im


def plate_closing(scene) -> Image.Image:
    im = Image.new("RGB", (W, H), CARD_BG)
    d = ImageDraw.Draw(im)
    cx = W / 2
    by = wordmark(d, cx, 360, 170)
    yy = by + 18
    d.rectangle([cx - 60, yy, cx + 60, yy + 5], fill=GREEN)
    if scene.get("subcaption"):
        tf = F(SEMIBOLD, 40)
        yy2 = draw_center(d, cx, yy + 40, scene["subcaption"], tf, INK2, max_w=1300)
    if scene.get("footer"):
        ff = F(MONO, 30)
        fw = measure(d, scene["footer"], ff)[0]
        d.text((cx - fw / 2, 920), scene["footer"], font=ff, fill=GREEN_D)
    return im


def plate_interstitial(scene) -> Image.Image:
    im = Image.new("RGB", (W, H), CARD_BG)
    d = ImageDraw.Draw(im)
    cx = W / 2
    head = F(SEMIBOLD, 70)
    y = draw_center(d, cx, 348, scene["headline"], head, INK, max_w=1500)
    d.rectangle([cx - 60, y + 18, cx + 60, y + 23], fill=GREEN)
    # the two flips: split the subcaption on the double space into two stacked lines
    sub = scene.get("subcaption") or ""
    parts = [p.strip() for p in sub.split("  ") if p.strip()]
    bf = F(REG, 38)
    yy = y + 70
    for p in parts:
        yy = draw_center(d, cx, yy, p, bf, INK2, max_w=1500) + 14
    if scene.get("footer"):
        ff = F(LIGHT, 30)
        draw_center(d, cx, yy + 10, scene["footer"], ff, GREY, max_w=1400)
    return im


# ---------------------------------------------------------------------------
# Scene model
# ---------------------------------------------------------------------------
class Scene:
    def __init__(self, spec):
        self.spec = spec
        self.kind = spec["kind"]
        self.dur = float(spec["duration_s"])
        self.tin = float(spec["transition_dur_s"])  # cross-dissolve duration
        self.motion = spec["motion"]
        self.intensity = float(spec["motion_intensity"])
        self.chart_bg = CARD_BG
        self.base = None    # contained chart (visual scenes)
        self.box = None     # (x0,y0,bw,bh)
        self.plate = None   # static layer
        self._build()

    def _build(self):
        s = self.spec
        if self.kind == "visual":
            chart = load_visual(s["visual"])
            self.chart_bg = corner_bg(chart)
            chart = autotrim(chart, self.chart_bg)
            x0, y0, x1, y1 = CONTENT
            bw, bh = x1 - x0, y1 - y0
            self.box = (x0, y0, bw, bh)
            self.base = contain(chart, round(bw * 0.998), round(bh * 0.998))
            self.plate = plate_visual(s, self.chart_bg)
        elif self.kind == "title":
            self.plate = plate_title(s)
        elif self.kind == "closing":
            self.plate = plate_closing(s)
        else:
            self.plate = plate_interstitial(s)

    def frame(self, local_t: float) -> Image.Image:
        frac = min(1.0, local_t / self.dur) if self.dur > 0 else 1.0
        if self.kind == "visual":
            im = self.plate.copy()
            x0, y0, bw, bh = self.box
            kb = ken_burns(self.base, bw, bh, frac, self.motion, self.intensity, self.chart_bg)
            im.paste(kb, (x0, y0))
            return im
        else:
            # whole-plate subtle motion for cards
            return ken_burns(self.plate, W, H, frac, self.motion, self.intensity, CARD_BG)


# ---------------------------------------------------------------------------
# Timeline
# ---------------------------------------------------------------------------
def build_timeline(scenes):
    starts = [0.0]
    for i in range(1, len(scenes)):
        starts.append(starts[i - 1] + scenes[i - 1].dur - scenes[i].tin)
    ends = [starts[i] + scenes[i].dur for i in range(len(scenes))]
    return starts, ends


def render(scenes, fps, frange=None):
    starts, ends = build_timeline(scenes)
    total = ends[-1]
    total_frames = math.ceil(total * fps)
    bg0 = Image.new("RGB", (W, H), CARD_BG)

    f_lo, f_hi = 0, total_frames
    if frange:
        f_lo, f_hi = frange

    for f in range(f_lo, f_hi):
        t = f / fps
        # topmost active scene = the one with the largest start <= t and t < end
        cur = 0
        for i in range(len(scenes)):
            if starts[i] <= t < ends[i] and starts[i] >= starts[cur]:
                cur = i
        # clamp to last if past the end
        if t >= ends[-1]:
            cur = len(scenes) - 1
        s = scenes[cur]
        over = s.frame(min(t - starts[cur], s.dur))
        # fade-in compositing
        if cur == 0 and t < s.tin and s.tin > 0:
            a = smoothstep(t / s.tin)
            frame = Image.blend(bg0, over, a)
        elif cur > 0 and t < starts[cur] + s.tin and s.tin > 0:
            prev = scenes[cur - 1]
            under = prev.frame(min(t - starts[cur - 1], prev.dur))
            a = smoothstep((t - starts[cur]) / s.tin)
            frame = Image.blend(under, over, a)
        else:
            frame = over
        frame = draw_progress(frame, t / total)
        yield f, frame


def draw_progress(im, frac):
    d = ImageDraw.Draw(im)
    bw = round(W * max(0.0, min(1.0, frac)))
    # subtle track + green progress along the very bottom edge
    d.rectangle([0, H - 5, W, H], fill=HAIRLINE)
    d.rectangle([0, H - 5, bw, H], fill=GREEN)
    return im


# ---------------------------------------------------------------------------
# Encode
# ---------------------------------------------------------------------------
def ffmpeg_exe():
    import imageio_ffmpeg
    return imageio_ffmpeg.get_ffmpeg_exe()


def write_mp4(scenes, fps, out: Path, want_poster=False, crf=26):
    ff = ffmpeg_exe()
    cmd = [
        ff, "-y", "-f", "rawvideo", "-pix_fmt", "rgb24",
        "-s", f"{W}x{H}", "-r", str(fps), "-i", "-",
        "-an", "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-crf", str(crf), "-preset", "slow", "-profile:v", "high",
        "-movflags", "+faststart", str(out),
    ]
    proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.DEVNULL,
                            stderr=subprocess.DEVNULL)
    n = 0
    poster_frame = None
    starts, ends = build_timeline(scenes)
    # poster = a readable beat inside the turn-tax scene (the measured 9.7x)
    poster_idx = None
    if want_poster:
        for i, s in enumerate(scenes):
            if s.spec.get("visual") == "60-hero-turntax-curves":
                poster_idx = round((starts[i] + s.dur * 0.55) * fps)
    for f, frame in render(scenes, fps):
        proc.stdin.write(frame.tobytes())
        if poster_idx is not None and f == poster_idx:
            poster_frame = frame.copy()
        n += 1
        if n % 60 == 0:
            print(f"  ...{n} frames", file=sys.stderr)
    proc.stdin.close()
    proc.wait()
    print(f"wrote {out}  ({n} frames @ {fps}fps = {n/fps:.1f}s)")
    if want_poster:
        if poster_frame is None:
            poster_frame = next(fr for _, fr in render(scenes, fps, frange=(poster_idx or 0, (poster_idx or 0) + 1)))
        poster_frame.save(OUT_POSTER)
        print(f"wrote {OUT_POSTER}")


# A condensed highlight reel for the README GIF: the 5 load-bearing beats only,
# shortened, so the GIF stays small (GitHub markdown can't autoplay an mp4).
GIF_BEATS = {
    "s1_title": 2.0,
    "s3_turntax": 3.0,      # the measured 9.7x
    "s5_capability": 2.6,   # owns the whole boundary
    "s6_statcard": 2.6,     # three pillars + honest fence
    "s9_closing": 2.0,
}


def condense(scene_specs):
    out = []
    for sp in scene_specs:
        if sp["id"] in GIF_BEATS:
            c = dict(sp)
            c["duration_s"] = GIF_BEATS[sp["id"]]
            c["transition_dur_s"] = 0.6
            out.append(c)
    return out


def build_gif(scene_specs, out_gif: Path, fps=24, fps_gif=11, width=760):
    """Render the condensed highlight reel to a temp mp4, then a compact looping GIF."""
    scenes = [Scene(s) for s in condense(scene_specs)]
    tmp = BUILD / "hero-gif-src.mp4"
    write_mp4(scenes, fps, tmp, want_poster=False)
    ff = ffmpeg_exe()
    vf = (f"fps={fps_gif},scale={width}:-1:flags=lanczos,"
          f"split[s0][s1];[s0]palettegen=max_colors=96[p];[s1][p]paletteuse=dither=bayer:bayer_scale=5")
    subprocess.run([ff, "-y", "-i", str(tmp), "-vf", vf, "-loop", "0", str(out_gif)],
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    if out_gif.exists():
        print(f"wrote {out_gif}  ({out_gif.stat().st_size/1e6:.1f} MB)")


# ---------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fast", action="store_true", help="15fps draft")
    ap.add_argument("--no-gif", action="store_true")
    ap.add_argument("--crf", type=int, default=26,
                    help="x264 quality (lower=better/bigger); 26 keeps the mp4 < 5MB")
    ap.add_argument("--storyboard", default=str(STORYBOARD))
    ap.add_argument("--out", default=str(OUT_MP4))
    args = ap.parse_args()

    spec = json.loads(Path(args.storyboard).read_text(encoding="utf-8"))
    global W, H
    W = spec.get("resolution", {}).get("w", W)
    H = spec.get("resolution", {}).get("h", H)
    fps = 15 if args.fast else spec.get("fps", 30)

    print(f"building {len(spec['scenes'])} scenes -> {args.out}  ({W}x{H} @{fps}fps)")
    scenes = [Scene(s) for s in spec["scenes"]]
    out = Path(args.out)
    write_mp4(scenes, fps, out, want_poster=True, crf=args.crf)
    if not args.no_gif:
        build_gif(spec["scenes"], OUT_GIF)


if __name__ == "__main__":
    main()
