#!/usr/bin/env python3
"""Install a durable fleet-agent command for the Claude account launcher.

This is intentionally smaller than Benchmark's installer: fleet is not packaged
as a Python project yet, so v1 writes thin wrappers that call the repo-local
``tools/claude_agent_chat.py`` launcher from any working directory.
"""
from __future__ import annotations

import argparse
import os
import stat
import sys
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parents[1]
DEFAULT_LAUNCHER = PROJECT_DIR / "tools" / "claude_agent_chat.py"
DEFAULT_NAME = "fleet-agent"
MARKER = "Generated by fleet install_agent_command.py"


def default_bin_dir(system: bool = False, platform: str | None = None) -> Path:
    platform = platform or sys.platform
    if system:
        if platform == "win32":
            return Path(os.environ.get("ProgramData", r"C:\ProgramData")) / "fleet" / "bin"
        return Path("/usr/local/bin")
    return Path.home() / ".local" / "bin"


def _quote_cmd(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def _quote_ps(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _quote_sh(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def wrapper_specs(
    *,
    name: str,
    bin_dir: Path,
    python_exe: str,
    launcher: Path,
    platform: str | None = None,
) -> list[tuple[Path, str, bool]]:
    platform = platform or sys.platform
    root = launcher.parents[1]
    if platform == "win32":
        cmd = "\r\n".join(
            [
                "@echo off",
                f"rem {MARKER}",
                f"set \"FLEET_ROOT={root}\"",
                f"{_quote_cmd(python_exe)} {_quote_cmd(str(launcher))} %*",
                "",
            ]
        )
        ps1 = "\n".join(
            [
                f"# {MARKER}",
                "$ErrorActionPreference = 'Stop'",
                f"$env:FLEET_ROOT = {_quote_ps(str(root))}",
                f"& {_quote_ps(python_exe)} {_quote_ps(str(launcher))} @args",
                "exit $LASTEXITCODE",
                "",
            ]
        )
        return [
            (bin_dir / f"{name}.cmd", cmd, False),
            (bin_dir / f"{name}.ps1", ps1, False),
        ]

    sh = "\n".join(
        [
            "#!/usr/bin/env sh",
            f"# {MARKER}",
            f"export FLEET_ROOT={_quote_sh(str(root))}",
            f"exec {_quote_sh(python_exe)} {_quote_sh(str(launcher))} \"$@\"",
            "",
        ]
    )
    return [(bin_dir / name, sh, True)]


def _owned(path: Path) -> bool:
    try:
        return MARKER in path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False


def install(
    *,
    name: str = DEFAULT_NAME,
    bin_dir: Path | None = None,
    python_exe: str | None = None,
    launcher: Path = DEFAULT_LAUNCHER,
    system: bool = False,
    force: bool = False,
    dry_run: bool = False,
    platform: str | None = None,
) -> dict:
    platform = platform or sys.platform
    bin_dir = (bin_dir or default_bin_dir(system, platform)).expanduser().resolve()
    launcher = launcher.expanduser().resolve()
    python_exe = python_exe or sys.executable
    specs = wrapper_specs(
        name=name,
        bin_dir=bin_dir,
        python_exe=python_exe,
        launcher=launcher,
        platform=platform,
    )

    if not launcher.is_file():
        return {"ok": False, "reason": f"launcher not found: {launcher}", "installed": []}

    installed = []
    if not dry_run:
        bin_dir.mkdir(parents=True, exist_ok=True)
    for path, content, executable in specs:
        if path.exists() and not _owned(path) and not force:
            return {
                "ok": False,
                "reason": f"refusing to overwrite non-fleet wrapper: {path}",
                "installed": installed,
            }
        action = "would-write" if dry_run else "installed"
        if not dry_run:
            path.write_text(content, encoding="utf-8", newline="")
            if executable:
                mode = path.stat().st_mode
                path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        installed.append({"path": str(path), "action": action})

    return {
        "ok": True,
        "name": name,
        "bin_dir": str(bin_dir),
        "launcher": str(launcher),
        "installed": installed,
        "on_path": _bin_dir_on_path(bin_dir),
    }


def uninstall(
    *,
    name: str = DEFAULT_NAME,
    bin_dir: Path | None = None,
    system: bool = False,
    force: bool = False,
    dry_run: bool = False,
    platform: str | None = None,
) -> dict:
    platform = platform or sys.platform
    bin_dir = (bin_dir or default_bin_dir(system, platform)).expanduser().resolve()
    specs = wrapper_specs(
        name=name,
        bin_dir=bin_dir,
        python_exe=sys.executable,
        launcher=DEFAULT_LAUNCHER,
        platform=platform,
    )
    removed = []
    for path, _content, _executable in specs:
        if not path.exists():
            continue
        if not force and not _owned(path):
            return {
                "ok": False,
                "reason": f"refusing to remove non-fleet wrapper: {path}",
                "removed": removed,
            }
        action = "would-remove" if dry_run else "removed"
        if not dry_run:
            path.unlink()
        removed.append({"path": str(path), "action": action})
    return {"ok": True, "name": name, "bin_dir": str(bin_dir), "removed": removed}


def _bin_dir_on_path(bin_dir: Path) -> bool:
    wanted = str(bin_dir.resolve()).lower() if sys.platform == "win32" else str(bin_dir.resolve())
    for raw in os.environ.get("PATH", "").split(os.pathsep):
        if not raw:
            continue
        try:
            got = str(Path(raw).expanduser().resolve())
        except OSError:
            got = str(Path(raw).expanduser())
        if sys.platform == "win32":
            got = got.lower()
        if got == wanted:
            return True
    return False


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Install the fleet-agent launcher command.")
    parser.add_argument("--name", default=DEFAULT_NAME, help="command basename to install")
    parser.add_argument("--bin-dir", type=Path, default=None, help="wrapper directory")
    parser.add_argument("--python", default=sys.executable, help="Python executable used by the wrapper")
    parser.add_argument("--launcher", type=Path, default=DEFAULT_LAUNCHER, help="launcher script to wrap")
    parser.add_argument("--system", action="store_true", help="use a system bin dir instead of ~/.local/bin")
    parser.add_argument("--force", action="store_true", help="overwrite/remove an existing non-fleet wrapper")
    parser.add_argument("--dry-run", action="store_true", help="show the action without writing")
    parser.add_argument("--uninstall", action="store_true", help="remove installed wrappers")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.uninstall:
        result = uninstall(
            name=args.name,
            bin_dir=args.bin_dir,
            system=args.system,
            force=args.force,
            dry_run=args.dry_run,
        )
    else:
        result = install(
            name=args.name,
            bin_dir=args.bin_dir,
            python_exe=args.python,
            launcher=args.launcher,
            system=args.system,
            force=args.force,
            dry_run=args.dry_run,
        )

    if not result.get("ok"):
        print(f"install_agent_command: {result.get('reason')}", file=sys.stderr)
        return 1

    rows = result.get("installed") or result.get("removed") or []
    for row in rows:
        print(f"{row['action']}: {row['path']}")
    if result.get("installed"):
        command = args.name
        if sys.platform == "win32":
            command = f"{args.name}.cmd"
        print(f"launch: {command} launch --goal \"...\"")
        print(f"tier:   {command} launch -t1 --goal \"...\"")
        if not result.get("on_path"):
            print(f"note: {result['bin_dir']} is not on PATH")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
