#!/usr/bin/env python3
"""Tests for the scrubber's CI leak-gate (`--audit-range`) and its self-ref exemption.

The pre-commit gate (`audit_staged`) only fires on an armed clone; `audit_range`
is the machine backstop that runs in CI over the pushed range. This proves it:
(1) catches a planted secret-tier needle in an added line, (2) passes a clean
range, (3) is line-oriented (only ADDED lines, not removed/context), and (4)
honors SELF_REFERENTIAL so editing the denylist itself does not cry wolf -- the
same exemption the post-export audit applies.

Run: `python tools/scrub_public_copy_test.py`  (exit 0 = all pass).
Pure stdlib; builds a throwaway git repo in a temp dir.
"""
from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
SCRUB = os.path.join(HERE, "scrub_public_copy.py")
sys.path.insert(0, HERE)
import scrub_public_copy as scrub  # noqa: E402
# A real secret-tier needle the gate must catch (the IP this change added).
# Assembled from parts so the literal never appears in THIS file -- this test is
# not SELF_REFERENTIAL, so a bare literal would (correctly) trip the leak gate on
# its own commit. We want the gate live on test code, not exempted.
NEEDLE = ".".join(["100", "95", "5", "23"])
# An identity-tier needle, assembled from parts for the SAME reason as NEEDLE
# (this test file is not SELF_REFERENTIAL, so a raw literal would trip the leak
# gate on its own commit). Used to prove DCO/co-author trailers are exempt while
# the same string in the body is still caught.
ORG = "".join(["netra", "systems"]) + ".ai"
# A derived lab-host alias that is not a real DNS hostname but still identifies
# private fleet topology. Assemble it so this non-self-referential test file does
# not trip the very gate it proves.
LAB_ALIAS = "lab-" + "dgx" + str(2)
BARE_GPU_ALIAS = "dgx" + str(2)

# --- #5405 generated-artifact exemption fixtures -----------------------------
# AFFIL is the AFFILIATION-class needle (an employer brand) the exemption is about.
# Assembled from parts for the SAME reason as NEEDLE/ORG above: this file is not
# SELF_REFERENTIAL, so a bare literal would trip the very gate it exercises.
AFFIL = "sam" + "sung"
# The declared class: one directory, one extension, one generator banner. The banner
# is the literal internal/egresslist.RenderArtifact writes as line 1.
ARTIFACT_DIR = "internal/egresslist/lists"
ARTIFACT_BANNER = ("! fak bundled egress filter list - GENERATED by "
                   "`fak egresslist refresh`; do not hand-edit.")


def _pin(text: str) -> str:
    """The sha256 a manifest pins for an artifact: LF-normalized, BOM-free.

    Computed here from hashlib directly rather than through the scrubber's own helper,
    so a bug in that helper cannot make these fixtures agree with it by construction.
    Mirrors internal/egresslist.Checksum.
    """
    return hashlib.sha256(text.replace("\r\n", "\n").encode("utf-8")).hexdigest()


def _artifact(rules, banner: str = ARTIFACT_BANNER, comments=()) -> str:
    """Render a bundled-list artifact the way `fak egresslist refresh` does."""
    lines = [banner, "! Name: feed"] + list(comments) + ["!"]
    lines += ["||%s^" % r for r in rules]
    return "\n".join(lines) + "\n"


def _artifact_manifest(name: str, text: str, sha: str | None = None) -> str:
    return json.dumps({
        "version": 1,
        "lists": [{
            "name": name, "url": "https://feed.invalid/hosts", "format": "hosts",
            "license": "MIT", "sha256": sha if sha is not None else _pin(text),
            "rules": 0, "last_refreshed": "", "description": "test fixture feed",
        }],
    }, indent=2) + "\n"


def _git(repo: str, *args: str) -> str:
    env = dict(os.environ)
    env.update(
        GIT_AUTHOR_NAME="t", GIT_AUTHOR_EMAIL="t@t",
        GIT_COMMITTER_NAME="t", GIT_COMMITTER_EMAIL="t@t",
        # Never let the repo-under-test inherit fleet's hooksPath.
        GIT_CONFIG_GLOBAL=os.devnull, GIT_CONFIG_SYSTEM=os.devnull,
    )
    out = subprocess.run(
        ["git", "-C", repo, *args],
        capture_output=True, text=True, encoding="utf-8", errors="replace", env=env,
    )
    if out.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {out.stderr}")
    return out.stdout.strip()


def _audit_range(repo: str, rng: str):
    """Return (exit_code, combined_output) of the scrubber's --audit-range."""
    out = subprocess.run(
        [sys.executable, SCRUB, "--audit-range", rng, "--root", repo],
        capture_output=True, text=True, encoding="utf-8", errors="replace",
    )
    return out.returncode, out.stdout + out.stderr


def _audit_tree(repo: str, as_json: bool = False):
    """Return (exit_code, combined_output) of the scrubber's --audit-tree."""
    cmd = [sys.executable, SCRUB, "--audit-tree", "--root", repo]
    if as_json:
        cmd.append("--json")
    out = subprocess.run(
        cmd, capture_output=True, text=True, encoding="utf-8", errors="replace",
    )
    return out.returncode, out.stdout + out.stderr


def _audit_message(repo: str, text: str):
    """Return (exit_code, combined_output) of the scrubber's --audit-message.

    Roots the scan at the throwaway repo so `_effective_audit_needles` reads the
    test-controlled private sidecar there. The message file is also written under
    the temp repo so nothing touches the real tree.
    """
    msg = os.path.join(repo, "_MSG")
    with open(msg, "w", encoding="utf-8") as f:
        f.write(text)
    out = subprocess.run(
        [sys.executable, SCRUB, "--audit-message", msg, "--root", repo],
        capture_output=True, text=True, encoding="utf-8", errors="replace",
    )
    return out.returncode, out.stdout + out.stderr


def _export(repo: str):
    out = subprocess.run(
        [sys.executable, SCRUB, "--export-dir", repo],
        capture_output=True, text=True, encoding="utf-8", errors="replace",
    )
    return out.returncode, out.stdout + out.stderr


def _write(repo: str, rel: str, text: str) -> None:
    path = os.path.join(repo, rel)
    os.makedirs(os.path.dirname(path) or repo, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def _check_commit_gate(check) -> None:
    """The pre-commit range gate: a clean range passes, a planted needle is
    named, removing one is not a hit, derived lab-host and bare node aliases
    are caught in prose/data/path, the denylist file itself is exempt, and an
    unreadable range exits 2."""
    with tempfile.TemporaryDirectory() as repo:
        _git(repo, "init", "-q")
        _git(repo, "config", "commit.gpgsign", "false")
        # Pull the private scan instructions into this throwaway repo. The public
        # AUDIT_NEEDLES are de-fanged, so under the hard cut the gate folds in the
        # REAL needle from a gitignored sidecar. Ignore the sidecar dir so it is
        # never tracked or scanned, exactly as in the real repos.
        _write(repo, ".gitignore", "tools/_registry/\n")
        _write(repo, "tools/_registry/scrub_needles.private.json",
               '{"schema":"fleet-scrub-needles/1","audit_needles":["%s"],'
               '"export_audit_needles":["%s"]}\n' % (NEEDLE, NEEDLE))
        # base commit: a clean file.
        _write(repo, "docs/notes.md", "hello world\nno secrets here\n")
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "base")
        base = _git(repo, "rev-parse", "HEAD")

        # 1) clean range -> exit 0
        _write(repo, "docs/notes.md", "hello world\nstill clean\nanother line\n")
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "clean change")
        rc, out = _audit_range(repo, f"{base}..HEAD")
        check("clean range exits 0", rc == 0, out)
        check("clean range reports clean", "clean" in out, out)

        clean_head = _git(repo, "rev-parse", "HEAD")

        # 2) added needle -> exit 1, names the file+needle
        _write(repo, "node.json", '{"ip": "%s"}\n' % NEEDLE)
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "leak")
        rc, out = _audit_range(repo, f"{clean_head}..HEAD")
        check("planted needle exits 1", rc == 1, out)
        check("planted needle is named", NEEDLE in out and "node.json" in out, out)

        leak_head = _git(repo, "rev-parse", "HEAD")

        # 3) REMOVING the needle is not a hit (only ADDED lines are scanned)
        _write(repo, "node.json", '{"ip": "0.0.0.0"}\n')
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "remove leak")
        rc, out = _audit_range(repo, f"{leak_head}..HEAD")
        check("removing a needle is not a hit", rc == 0, out)

        # 3b) A derived lab-host alias is a standing shape rule: it must be
        # caught in Markdown inline code AND structured/non-Markdown evidence,
        # without depending on the optional private-needle sidecar.
        alias_base = _git(repo, "rev-parse", "HEAD")
        _write(repo, "docs/alias.md", "ran on `%s`\n" % LAB_ALIAS)
        _write(repo, "alias.json", '{"host":"%s"}\n' % LAB_ALIAS)
        _write(repo, "docs/%s-report.md" % LAB_ALIAS, "clean body\n")
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "add derived lab aliases")
        rc, out = _audit_range(repo, f"{alias_base}..HEAD")
        check("derived lab alias exits 1", rc == 1, out)
        check("derived lab alias catches Markdown and JSON",
              "docs/alias.md" in out and "alias.json" in out, out)
        check("derived lab alias catches paths", LAB_ALIAS + "-report.md" in out, out)
        os.remove(os.path.join(repo, "docs", "alias.md"))
        os.remove(os.path.join(repo, "alias.json"))
        os.remove(os.path.join(repo, "docs", LAB_ALIAS + "-report.md"))
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "remove derived lab aliases")
        # 3c) A bare node label has the same private-host shape even without
        # the optional lab- prefix. Cover prose, data, and path.
        bare_base = _git(repo, "rev-parse", "HEAD")
        _write(repo, "docs/bare.md", "ran on `%s`\n" % BARE_GPU_ALIAS)
        _write(repo, "bare.json", '{"host":"%s"}\n' % BARE_GPU_ALIAS)
        _write(repo, "docs/%s-report.md" % BARE_GPU_ALIAS, "clean body\n")
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "add bare GPU aliases")
        rc, out = _audit_range(repo, f"{bare_base}..HEAD")
        check("bare GPU alias exits 1", rc == 1, out)
        check("bare GPU alias catches content and paths",
              "docs/bare.md" in out and "bare.json" in out and BARE_GPU_ALIAS + "-report.md" in out, out)
        os.remove(os.path.join(repo, "docs", "bare.md"))
        os.remove(os.path.join(repo, "bare.json"))
        os.remove(os.path.join(repo, "docs", BARE_GPU_ALIAS + "-report.md"))
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "remove bare GPU aliases")

        # 4) SELF_REFERENTIAL exemption: the same needle inside the denylist file
        #    itself must NOT trip the gate (it has to name needles to enforce them).
        safe_head = _git(repo, "rev-parse", "HEAD")
        _write(repo, "PUBLIC-SCRUB-POLICY.md", "| `%s` | redact | x |\n" % NEEDLE)
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "edit denylist")
        rc, out = _audit_range(repo, f"{safe_head}..HEAD")
        check("self-referential file is exempt", rc == 0, out)

        # 5) unreadable range -> exit 2 (mirrors dos review's grammar)
        rc, out = _audit_range(repo, "nope-no-such-ref..HEAD")
        check("unreadable range exits 2", rc == 2, out)


def _check_audit_tree(check) -> None:
    """The HARD-CUT full-tree backstop: shape-only mode without a pulled
    sidecar still catches live-token, GCP service-account and lab-alias shapes;
    full mode catches a pulled needle; --json emits the ok+mode contract."""
    # ---- audit-tree: the HARD-CUT full-tree backstop (its own repo) --------
    # Separate repo so the sidecar's presence/absence is controlled here and does
    # not interact with the commit-gate block above.
    with tempfile.TemporaryDirectory() as repo:
        _git(repo, "init", "-q")
        _git(repo, "config", "commit.gpgsign", "false")
        # Ignore the pulled-needle sidecar dir exactly like the real repos do, so
        # `git add -A` never tracks it (and audit-tree never self-hits on it).
        _write(repo, ".gitignore", "tools/_registry/\n")
        _write(repo, "docs/notes.md", "hello world\nno secrets here\n")
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "base")

        # 6) clean tree, no sidecar pulled -> exit 0, honest shape-only mode.
        rc, out = _audit_tree(repo)
        check("audit-tree clean (no sidecar) exits 0", rc == 0, out)
        check("audit-tree reports shape-only without sidecar", "shape-only" in out, out)

        # 7) a live-token SHAPE is caught even in shape-only mode (always sound).
        #    Assembled from parts so the literal token never appears in this file.
        token = "xoxb-" + "12345678" + "-" + "87654321" + "-" + "abcdefGHIJ0123456789"
        _write(repo, "cfg.txt", "slack_token=%s\n" % token)
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "add token")
        rc, out = _audit_tree(repo)
        check("audit-tree catches live-token shape (shape-only)", rc == 1, out)
        check("audit-tree names the offending file", "cfg.txt" in out, out)
        os.remove(os.path.join(repo, "cfg.txt"))
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "remove token")

        # 7b) a GCP service-account key renamed off the *.sa.json convention is still
        #     caught by its client_email shape (content, not the path rule). Assembled
        #     from parts so the literal email never appears in this (non-self-ref) file.
        sa_email = "fak-admin@example-proj" + ".iam.gserviceaccount" + ".com"
        _write(repo, "creds.json", '{"client_email":"%s","private_key":"x"}\n' % sa_email)
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "add renamed key")
        rc, out = _audit_tree(repo)
        check("audit-tree catches GCP SA-email shape", rc == 1, out)
        check("audit-tree names the renamed key file", "creds.json" in out, out)
        os.remove(os.path.join(repo, "creds.json"))
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "remove renamed key")

        # 7c) The derived lab-host alias is also an always-on tree shape. It
        # must fail closed even when no private sidecar has been pulled.
        _write(repo, "host.json", '{"host":"%s"}\n' % LAB_ALIAS)
        _write(repo, "%s-report.json" % LAB_ALIAS, '{"status":"clean"}\n')
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "add derived lab alias")
        rc, out = _audit_tree(repo)
        check("audit-tree catches derived lab alias in shape-only mode", rc == 1, out)
        check("audit-tree names derived lab alias file", "host.json" in out, out)
        check("audit-tree catches derived lab alias path", LAB_ALIAS + "-report.json" in out, out)
        os.remove(os.path.join(repo, "host.json"))
        os.remove(os.path.join(repo, LAB_ALIAS + "-report.json"))
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "remove derived lab alias")

        # 8) FULL mode: a pulled private needle in a tracked file is caught; the
        #    sidecar itself (ignored, untracked) is NOT scanned, so no self-hit.
        real = ".".join(["10", "11", "12", "13"])
        _write(repo, "tools/_registry/scrub_needles.private.json",
               '{"schema":"fleet-scrub-needles/1","audit_needles":[],'
               '"export_audit_needles":["%s"]}\n' % real)
        _write(repo, "node.json", '{"ip":"%s"}\n' % real)
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "leak with sidecar pulled")
        rc, out = _audit_tree(repo)
        check("audit-tree full mode catches pulled needle", rc == 1, out)
        check("audit-tree full mode names file + reports full",
              "node.json" in out and "full" in out, out)

        # 9) --json emits the ok + mode contract the control-pane loop reads.
        rc, jout = _audit_tree(repo, as_json=True)
        check("audit-tree --json emits ok+mode keys", '"ok"' in jout and '"mode"' in jout, jout)


def _check_scrub_transforms(check) -> None:
    """The two scrub TRANSFORMS: the root-hoisted catalog drops private-machine
    runs, and the export rewrites a derived lab alias in content AND in path."""
    # ---- root-hoisted DGX catalog/run scrub --------------------------------
    with tempfile.TemporaryDirectory() as repo:
        _write(repo, "experiments/benchmark/catalog.json", json.dumps({
            "machines": {"dgx": {"runs": 1}, "local": {"runs": 1}},
            "runs": [
                {"run_id": "dgx-run", "machine_id": "dgx"},
                {"run_id": "local-run", "machine_id": "local"},
            ],
            "index": {"by_machine": {"dgx": ["dgx-run"], "local": ["local-run"]}},
        }))
        dropped = scrub._strip_private_machines_from_catalog(repo)
        cat = json.loads(open(os.path.join(repo, "experiments/benchmark/catalog.json"), encoding="utf-8").read())
        check("root-hoisted catalog strips dgx runs", dropped == 1, str(cat))
        check("root-hoisted catalog keeps non-dgx runs",
              cat["runs"] == [{"run_id": "local-run", "machine_id": "local"}], str(cat))
        check("root-hoisted dgx run glob is declared",
              "experiments/benchmark/runs/by-machine/dgx*" in scrub.DELETE_GLOBS,
              str(scrub.DELETE_GLOBS))

    # ---- export transform: derived alias content + path -------------------
    with tempfile.TemporaryDirectory() as repo:
        _write(repo, "reports/%s.json" % LAB_ALIAS, '{"host":"%s"}\n' % LAB_ALIAS)
        rc, out = _export(repo)
        generic = os.path.join(repo, "reports", "gpu-server.json")
        check("export rewrites derived lab alias content and path", rc == 0 and os.path.isfile(generic), out)
        body = ""
        if os.path.isfile(generic):
            with open(generic, encoding="utf-8") as f:
                body = f.read()
        check("export leaves no derived lab alias in artifact", LAB_ALIAS not in body and "gpu-server" in body, body)


def _check_export_tier_and_message_gate(check) -> None:
    """The EXPORT/identity tier at commit time: ungated without a sidecar,
    gated with one; plus the commit-MESSAGE gate, where scissors lines, comment
    lines and DCO/co-author trailers are exempt but body prose is not."""
    # ---- §6 commit-gate EXPORT/identity-tier fold (its own repo) ------------
    # Under the hard cut the PUBLIC clone has no export step left to rewrite the
    # identity tier, so a provisioned clone (sidecar present) must catch an
    # EXPORT-tier needle AT COMMIT -- not just the secret tier. The private repo
    # (no sidecar) keeps its secret-tier-only gate, unchanged, so a module-org
    # identity string never cries wolf there. _audit_range routes through the same
    # _effective_audit_needles the pre-commit gate uses, so it is a faithful proxy.
    with tempfile.TemporaryDirectory() as repo:
        _git(repo, "init", "-q")
        _git(repo, "config", "commit.gpgsign", "false")
        _write(repo, ".gitignore", "tools/_registry/\n")
        _write(repo, "docs/notes.md", "hello world\n")
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "base")
        base = _git(repo, "rev-parse", "HEAD")

        # An EXPORT/identity-tier needle: present ONLY in export_audit_needles, not
        # in the committed secret-tier AUDIT_NEEDLES. Assembled from parts so the
        # literal never appears in this (non-self-referential) file.
        export_needle = "example" + "corp" + "-private"

        # 10) WITHOUT a sidecar, an identity-tier string is NOT gated -- the private
        #     repo's secret-tier-only gate is unchanged (no crying wolf on imports).
        _write(repo, "go.mod", "module %s/x\n" % export_needle)
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "import")
        rc, out = _audit_range(repo, f"{base}..HEAD")
        check("export-tier NOT gated without sidecar (private unchanged)", rc == 0, out)
        import_head = _git(repo, "rev-parse", "HEAD")

        # 11) WITH the sidecar (a provisioned public clone), the SAME identity-tier
        #     needle IS caught at commit -- the §6 hardening. The sidecar lists it
        #     only in export_audit_needles, so this proves the EXPORT tier folds in.
        _write(repo, "tools/_registry/scrub_needles.private.json",
               '{"schema":"fleet-scrub-needles/1","audit_needles":[],'
               '"export_audit_needles":["%s"]}\n' % export_needle)
        _write(repo, "leak.json", '{"org":"%s"}\n' % export_needle)
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "leak with sidecar")
        rc, out = _audit_range(repo, f"{import_head}..HEAD")
        check("export-tier gated WITH sidecar (PLAN §6)", rc == 1, out)
        check("export-tier hit names the file", "leak.json" in out, out)

        # The commit-message gate uses the same effective sidecar fold, so make
        # the message tests hermetic: no dependence on whether this checkout has
        # real private needles pulled.
        _write(repo, "tools/_registry/scrub_needles.private.json",
               '{"schema":"fleet-scrub-needles/1","audit_needles":["%s"],'
               '"export_audit_needles":["%s","%s"]}\n' % (NEEDLE, export_needle, ORG))

        # 7) commit MESSAGE gate (the gap: a leak in the subject/body, not a file)
        rc, out = _audit_message(repo, "fix(x): a clean subject (fak x)\n\nbody\n")
        check("clean message exits 0", rc == 0, out)
        rc, out = _audit_message(repo, "fix(x): debug node %s (fak x)\n" % NEEDLE)
        check("message with a needle exits 1", rc == 1, out)
        check("message hit is named", NEEDLE in out and "message:" in out, out)
        # a needle BELOW the scissors line (git strips it) must NOT count
        scissors = "# ------------------------ >8 ------------------------"
        rc, out = _audit_message(
            repo, "fix(x): clean (fak x)\n%s\ndiff has %s\n" % (scissors, NEEDLE)
        )
        check("needle below the scissors line is ignored", rc == 0, out)
        # a needle in a comment line (git strips it) must NOT count
        rc, out = _audit_message(repo, "fix(x): clean (fak x)\n# note: %s\n" % NEEDLE)
        check("needle in a comment line is ignored", rc == 0, out)
        # a DCO sign-off / co-author TRAILER carrying an identity needle is
        # exempt (it is structured metadata, not leakable prose) -- otherwise
        # every signed commit by an org member would be refused.
        signoff = "fix(x): clean subject (fak x)\n\nSigned-off-by: A B <a@%s>\n" % ORG
        rc, out = _audit_message(repo, signoff)
        check("DCO sign-off trailer is exempt", rc == 0, out)
        coauth = "fix(x): clean (fak x)\n\nCo-authored-by: X <x@%s>\n" % ORG
        rc, out = _audit_message(repo, coauth)
        check("co-author trailer is exempt", rc == 0, out)
        # but an identity needle in the BODY (not a trailer) is still caught
        body = "fix(x): clean (fak x)\n\nsee internal note at %s prod\n" % ORG
        rc, out = _audit_message(repo, body)
        check("identity needle in body is still caught", rc == 1, out)


def _check_pinned_artifact_commit_gate(check) -> None:
    """The generated, checksum-pinned third-party artifact exemption at commit
    time — one positive, and the negatives that bound it: hand-written prose
    beside it, a forged banner, a stale pin, a real IP, a credential shape,
    an affiliation claim in the artifact prose, and an undeclared directory."""
    # ---- #5405 GENERATED, CHECKSUM-PINNED THIRD-PARTY ARTIFACT --------------
    # The commit half. A community filter feed rendered by `fak egresslist refresh`
    # carries vendor ad/telemetry domains verbatim; an AFFILIATION needle inside one is
    # upstream DATA (a record of something being BLOCKED), not a claim this repo makes.
    # The exemption must clear that -- and must NOT clear the same needle anywhere it
    # could have been hand-written, which is what the four negatives below pin.
    with tempfile.TemporaryDirectory() as repo:
        _git(repo, "init", "-q")
        _git(repo, "config", "commit.gpgsign", "false")
        _write(repo, ".gitignore", "tools/_registry/\n")
        # The real-IP tier comes from the sidecar, exactly as the private gate loads it.
        _write(repo, "tools/_registry/scrub_needles.private.json",
               '{"schema":"fleet-scrub-needles/1","audit_needles":["%s"],'
               '"export_audit_needles":["%s"]}\n' % (NEEDLE, NEEDLE))
        _write(repo, "docs/notes.md", "base\n")
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "base")

        def _stage_commit(msg: str) -> str:
            prev = _git(repo, "rev-parse", "HEAD")
            _git(repo, "add", "-A")
            _git(repo, "commit", "-q", "-m", msg)
            return prev

        feed_rules = ["ads.%sads.com" % AFFIL, "log.%sacr.com" % AFFIL, "cdn.example.net"]
        feed = _artifact(feed_rules)

        # 12) POSITIVE: the pinned artifact commits with NO FLEET_ALLOW_LEAK.
        _write(repo, ARTIFACT_DIR + "/feed.txt", feed)
        _write(repo, ARTIFACT_DIR + "/manifest.json", _artifact_manifest("feed", feed))
        base = _stage_commit("ingest a community feed")
        rc, out = _audit_range(repo, f"{base}..HEAD")
        check("pinned generated artifact is exempt (no FLEET_ALLOW_LEAK)", rc == 0, out)

        # 13) NEGATIVE (the load-bearing one): a HAND-WRITTEN file, in the SAME
        #     directory and with the same extension, carrying the same needle is still
        #     REFUSED. This is what proves the exemption is bound to the generated
        #     artifact and cannot widen into prose that merely sits next to one.
        _write(repo, ARTIFACT_DIR + "/notes.txt", "our %s partnership notes\n" % AFFIL)
        base = _stage_commit("hand-written note beside the artifact")
        rc, out = _audit_range(repo, f"{base}..HEAD")
        check("hand-written file in the artifact dir is still refused", rc == 1, out)
        check("hand-written refusal names the file and needle",
              "notes.txt" in out and AFFIL in out, out)
        os.remove(os.path.join(repo, ARTIFACT_DIR, "notes.txt"))
        _stage_commit("drop the hand-written note")

        # 13b) NEGATIVE: FORGING the generator banner is not enough -- an unpinned file
        #      that merely copies the header stays refused, so "looks generated" can
        #      never substitute for "is the bytes the manifest pins".
        forged = _artifact(["tracker.%sads.com" % AFFIL])
        _write(repo, ARTIFACT_DIR + "/forged.txt", forged)  # no manifest entry
        base = _stage_commit("file that copies the generator banner")
        rc, out = _audit_range(repo, f"{base}..HEAD")
        check("forged generator banner without a pin is refused", rc == 1, out)
        os.remove(os.path.join(repo, ARTIFACT_DIR, "forged.txt"))
        _stage_commit("drop the forged artifact")

        # 14) NEGATIVE: an artifact whose bytes DO NOT match the pinned checksum loses
        #     the exemption -- a hand-edit to a generated file is exactly the smuggling
        #     path the pin exists to close.
        tampered = _artifact(feed_rules + ["extra.%sadhub.com" % AFFIL])
        _write(repo, ARTIFACT_DIR + "/feed.txt", tampered)  # manifest still pins `feed`
        base = _stage_commit("hand-edit the generated artifact")
        rc, out = _audit_range(repo, f"{base}..HEAD")
        check("artifact that fails its pinned checksum is refused", rc == 1, out)
        _write(repo, ARTIFACT_DIR + "/feed.txt", feed)
        _stage_commit("restore the pinned artifact")

        # 15) NEGATIVE: a real IP inside a CORRECTLY pinned artifact, on a line that is
        #     a well-formed rule, is STILL refused. Only the affiliation class is
        #     exemptible; an upstream feed may legitimately carry an IPv4 literal and
        #     that is still not something to normalise.
        ip_feed = _artifact(feed_rules + [NEEDLE])
        _write(repo, ARTIFACT_DIR + "/feed.txt", ip_feed)
        _write(repo, ARTIFACT_DIR + "/manifest.json", _artifact_manifest("feed", ip_feed))
        base = _stage_commit("feed carrying a real operator IP")
        rc, out = _audit_range(repo, f"{base}..HEAD")
        check("real IP inside a pinned artifact is still refused", rc == 1, out)
        check("real-IP refusal names the needle", NEEDLE in out, out)

        # 15b) NEGATIVE: a credential SHAPE inside a correctly pinned artifact is still
        #      refused -- AUDIT_REGEXES are never exempted.
        token = "xoxb-" + "12345678" + "-" + "87654321" + "-" + "abcdefGHIJ0123456789"
        cred_feed = _artifact(feed_rules, comments=["! contact token %s" % token])
        _write(repo, ARTIFACT_DIR + "/feed.txt", cred_feed)
        _write(repo, ARTIFACT_DIR + "/manifest.json", _artifact_manifest("feed", cred_feed))
        base = _stage_commit("feed carrying a credential shape")
        rc, out = _audit_range(repo, f"{base}..HEAD")
        check("credential shape inside a pinned artifact is still refused", rc == 1, out)

        # 16) NEGATIVE: the affiliation needle in the artifact's own PROSE (a comment
        #     line the generator never emits for upstream data) is refused even though
        #     the file is correctly pinned. The exemption is per-LINE, not per-file.
        prose_feed = _artifact(feed_rules, comments=["! Description: our %s deal" % AFFIL])
        _write(repo, ARTIFACT_DIR + "/feed.txt", prose_feed)
        _write(repo, ARTIFACT_DIR + "/manifest.json", _artifact_manifest("feed", prose_feed))
        base = _stage_commit("affiliation claim in the artifact header")
        rc, out = _audit_range(repo, f"{base}..HEAD")
        check("affiliation claim in artifact prose is refused", rc == 1, out)

        # 17) NEGATIVE: the same pinned bytes OUTSIDE the declared directory get no
        #     exemption -- the class is scoped by path as well as by shape.
        _write(repo, ARTIFACT_DIR + "/feed.txt", feed)
        _write(repo, ARTIFACT_DIR + "/manifest.json", _artifact_manifest("feed", feed))
        _write(repo, "docs/lists/feed.txt", feed)
        _write(repo, "docs/lists/manifest.json", _artifact_manifest("feed", feed))
        base = _stage_commit("same artifact under an undeclared directory")
        rc, out = _audit_range(repo, f"{base}..HEAD")
        check("pinned artifact outside the declared dir is refused", rc == 1, out)
        check("undeclared-dir refusal names that copy", "docs/lists/feed.txt" in out, out)


def _check_pinned_artifact_export_audit(check) -> None:
    """The same exemption on the EXPORT path — the half FLEET_ALLOW_LEAK cannot
    reach: a pinned artifact publishes clean, a stale pin and hand-written
    affiliation prose both stay a MISS."""
    # ---- #5405 EXPORT half: the post-scrub audit --------------------------
    # This is the half FLEET_ALLOW_LEAK=1 cannot reach. The affiliation needle is in
    # EXPORT_AUDIT_NEEDLES with NO REPLACEMENTS rewrite, so without the exemption here
    # the artifact fails the post-scrub audit on EVERY publish, not just one commit.
    export_feed = _artifact(["ads.%sads.com" % AFFIL, "log.%sacr.com" % AFFIL])
    with tempfile.TemporaryDirectory() as exp:
        _write(exp, ARTIFACT_DIR + "/feed.txt", export_feed)
        _write(exp, ARTIFACT_DIR + "/manifest.json", _artifact_manifest("feed", export_feed))
        rc, out = _export(exp)
        check("post-scrub export audit passes with a pinned artifact", rc == 0, out)
        check("post-scrub export audit reports clean", "(clean)" in out, out)

    with tempfile.TemporaryDirectory() as exp:
        # The same artifact with a STALE pin: the export half must lose the exemption
        # too, or a hand-edited security artifact would publish unexamined.
        _write(exp, ARTIFACT_DIR + "/feed.txt", export_feed)
        _write(exp, ARTIFACT_DIR + "/manifest.json",
               _artifact_manifest("feed", export_feed, sha="0" * 64))
        rc, out = _export(exp)
        check("post-scrub export audit refuses an unpinned artifact", rc == 1, out)
        check("post-scrub export audit names the affiliation needle",
              "MISS" in out and AFFIL in out, out)

    with tempfile.TemporaryDirectory() as exp:
        # Hand-written prose beside a genuinely pinned artifact is still a MISS on the
        # export path -- the negative half, proven on BOTH gates.
        _write(exp, ARTIFACT_DIR + "/feed.txt", export_feed)
        _write(exp, ARTIFACT_DIR + "/manifest.json", _artifact_manifest("feed", export_feed))
        _write(exp, ARTIFACT_DIR + "/notes.txt", "our %s partnership\n" % AFFIL)
        rc, out = _export(exp)
        check("post-scrub export audit refuses hand-written affiliation prose", rc == 1, out)
        check("export MISS names the hand-written file", "notes.txt" in out, out)


def _check_private_default_needles(check) -> None:
    """Canonical defaults catch private repository and identity text without
    carrying either contiguous private value in this non-exempt test file."""
    private_repo = "ca" + "ma"
    private_identity = "sar" + "onic"
    check("private repository is a canonical audit default",
          private_repo in scrub.AUDIT_NEEDLES)
    check("private identity is a canonical audit default",
          private_identity in scrub.AUDIT_NEEDLES)

    diff = (
        "diff --git a/docs/x.md b/docs/x.md\n"
        "new file mode 100644\n"
        "--- /dev/null\n"
        "+++ b/docs/%s.md\n"
        "@@ -0,0 +1 @@\n"
        "+private identity %s\n"
    ) % (private_repo.upper(), private_identity.upper())
    hits = scrub._scan_added_lines(diff, scrub.AUDIT_NEEDLES)
    hit_needles = {hit[2].lower() for hit in hits}
    check("private defaults match path and content case-insensitively",
          private_repo in hit_needles and private_identity in hit_needles,
          repr(hits))


def main() -> int:
    """Run every scrub-gate check group against throwaway repos and report.
    Returns 1 if any check failed, 0 otherwise."""
    failures = []

    def check(name: str, cond: bool, detail: str = "") -> None:
        status = "ok" if cond else "FAIL"
        print(f"  [{status}] {name}" + (f"  -- {detail}" if not cond and detail else ""))
        if not cond:
            failures.append(name)

    _check_commit_gate(check)
    _check_audit_tree(check)
    _check_scrub_transforms(check)
    _check_export_tier_and_message_gate(check)
    _check_private_default_needles(check)
    _check_pinned_artifact_commit_gate(check)
    _check_pinned_artifact_export_audit(check)

    print()

    if failures:
        print(f"FAILED: {len(failures)} check(s): {', '.join(failures)}")
        return 1
    print("scrub_public_copy_test: all checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
