#!/usr/bin/env python3
"""Hermetic tests for the canonical task-identity primitive (#618).

The acceptance for #618 is behavioral: two sessions with an IDENTICAL caveat +
`/effort` preamble but DIFFERENT `/goal` args must produce DISTINCT identities,
and a fleet of N distinct-goal crashed workers must dedup to N, not 1. These
tests pin that on ``task_identity`` directly, plus byte-for-byte parity with the
``fleet_sessions`` logic the primitive was extracted from, so routing the fleet
tools through this one primitive is a provably behavior-preserving change."""
from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import task_identity  # noqa: E402
import fleet_sessions  # noqa: E402  (parity oracle: the logic this primitive elevates)


# The REAL head a slash-command `/goal` session opens with: a <local-command-caveat>
# block, an /effort preamble, and a <local-command-stdout> echo that are all
# BYTE-IDENTICAL across every such session, with the actual /goal directive last.
def _slash_goal_head(goal: str):
    return [
        {"type": "user", "message": {"content":
            "<local-command-caveat>Caveat: The messages below were generated by the "
            "user while running local commands. DO NOT respond to these messages as if "
            "the user typed them.</local-command-caveat>"}},
        {"type": "user", "message": {"content":
            "<command-name>/effort</command-name> <command-message>effort</command-message> "
            "<command-args>ultracode</command-args>"}},
        {"type": "user", "message": {"content":
            "<local-command-stdout>Set effort level to ultracode (this session only): "
            "xhigh + dynamic workflow orchestration</local-command-stdout>"}},
        {"type": "user", "message": {"content":
            f"<command-name>/goal</command-name> <command-args>{goal}</command-args>"}},
    ]


class CanonicalDirectiveTest(unittest.TestCase):
    """The directive must come from the real /goal argument, never the boilerplate."""

    def test_directive_is_the_goal_argument_not_the_caveat(self) -> None:
        d = task_identity.canonical_directive(_slash_goal_head("model routing first class"))
        self.assertIn("model routing first class", d)
        self.assertNotIn("Caveat", d)
        self.assertNotIn("ultracode", d)            # the /effort config arg never leaks in

    def test_boilerplate_only_head_has_empty_directive(self) -> None:
        head = [
            {"type": "user", "message": {"content":
                "<local-command-caveat>Caveat: ...</local-command-caveat>"}},
            {"type": "user", "message": {"content":
                "<system-reminder>background context</system-reminder>"}},
            {"type": "user", "message": {"content": "Resume where you left off on the task."}},
        ]
        self.assertEqual(task_identity.canonical_directive(head), "")

    def test_config_command_args_alone_are_not_the_task(self) -> None:
        # an /effort-only head (config command, no task command) must NOT adopt
        # "ultracode" as its identity; the next genuine instruction wins.
        head = [
            {"type": "user", "message": {"content":
                "<command-name>/effort</command-name> <command-args>ultracode</command-args>"}},
            {"type": "user", "message": {"content": "actually do the real work here"}},
        ]
        self.assertEqual(task_identity.canonical_directive(head), "actually do the real work here")

    def test_future_local_command_wrapper_is_skipped(self) -> None:
        # robustness to a wrapper the harness has not added yet: any <local-command-*>
        # block is skipped by the whole-family match, so a future envelope can't
        # silently become the identity the way <local-command-caveat> once did.
        head = [
            {"type": "user", "message": {"content":
                "<local-command-future-thing>some brand new boilerplate"
                "</local-command-future-thing>"}},
            {"type": "user", "message": {"content":
                "<command-name>/goal</command-name> <command-args>ship the real work</command-args>"}},
        ]
        self.assertEqual(task_identity.canonical_directive(head), "ship the real work")


class SignatureTest(unittest.TestCase):
    def test_signature_is_deterministic(self) -> None:
        a = task_identity.signature("proj", "/cwd", "do the thing")
        b = task_identity.signature("proj", "/cwd", "do the thing")
        c = task_identity.signature("proj", "/cwd", "do a DIFFERENT thing")
        self.assertEqual(a, b)
        self.assertNotEqual(a, c)
        self.assertEqual(len(a), 16)

    def test_empty_directive_has_empty_signature(self) -> None:
        # an interactive / no-instruction row must never dedup against anything.
        self.assertEqual(task_identity.signature("proj", "/cwd", ""), "")


class AcceptanceTest(unittest.TestCase):
    """The two literal acceptance clauses of #618."""

    def test_distinct_goals_under_identical_preamble_get_distinct_identities(self) -> None:
        # identical caveat + /effort preamble, DIFFERENT /goal -> DISTINCT identities.
        da, sa = task_identity.task_identity("proj", "/cwd", _slash_goal_head("model routing first class"))
        db, sb = task_identity.task_identity("proj", "/cwd", _slash_goal_head("progress epic 595"))
        self.assertNotEqual(da, db)
        self.assertNotEqual(sa, sb)
        self.assertTrue(sa and sb)

    def test_fleet_of_n_distinct_goals_dedups_to_n_not_one(self) -> None:
        # the 2026-06-24 incident: 15 distinct /goal workers, 0 genuine repeats.
        goals = [
            "model routing first class", "progress epic 595", "GLM multi-GPU NCCL",
            "vllm comparisons", "generic account switcher", "context tape visuals",
            "dispatch loop watchdog", "hosted control plane", "industry scorecard",
            "persona readiness", "agent readiness", "seo aeo scorecard",
            "trajectory garden", "repo hygiene", "memory compaction",
        ]
        sigs = {task_identity.signature("proj", "/cwd",
                                        task_identity.canonical_directive(_slash_goal_head(g)))
                for g in goals}
        # N distinct goals -> N distinct signatures (pre-fix this set had size 1).
        self.assertEqual(len(sigs), len(goals))
        self.assertNotIn("", sigs)


class ParityWithFleetSessionsTest(unittest.TestCase):
    """The primitive is a faithful extraction: it must produce byte-for-byte the
    SAME directive and signature as the fleet_sessions logic it elevates, so a
    later wiring of fleet_sessions through it changes no behavior."""

    def test_directive_parity_on_real_slash_goal_head(self) -> None:
        for goal in ("model routing first class", "progress epic 595", "GLM multi-GPU NCCL"):
            head = _slash_goal_head(goal)
            self.assertEqual(
                task_identity.canonical_directive(head),
                fleet_sessions._first_instruction(head),
                f"directive drift for goal {goal!r}")

    def test_signature_parity(self) -> None:
        for goal in ("model routing first class", "progress epic 595"):
            head = _slash_goal_head(goal)
            directive = task_identity.canonical_directive(head)
            self.assertEqual(
                task_identity.signature("proj", "/cwd", directive),
                fleet_sessions._task_sig("proj", "/cwd", directive),
                f"signature drift for goal {goal!r}")

    def test_empty_and_wrapper_parity(self) -> None:
        head = [
            {"type": "user", "message": {"content":
                "<local-command-caveat>Caveat: ...</local-command-caveat>"}},
            {"type": "user", "message": {"content": "Resume where you left off."}},
        ]
        self.assertEqual(
            task_identity.canonical_directive(head),
            fleet_sessions._first_instruction(head))


if __name__ == "__main__":
    unittest.main()
