package agenttest

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/anthony-chaudhary/fak/internal/agent"
)

// Call is one scripted tool call: a tool name and the raw JSON arguments to emit.
type Call struct {
	Tool string
	Args string
}

// Turn is one scripted assistant turn. A turn with Calls emits those tool calls; a turn
// with no Calls emits Answer as a final answer (ending the session). A ScriptedPlanner
// emits one Turn per Complete call, in order.
type Turn struct {
	Calls  []Call
	Answer string
}

// CallTurn is a convenience constructor for a tool-calling turn.
func CallTurn(calls ...Call) Turn { return Turn{Calls: calls} }

// AnswerTurn is a convenience constructor for a final-answer turn.
func AnswerTurn(answer string) Turn { return Turn{Answer: answer} }

// ScriptedPlanner is a deterministic agent.Planner that emits a fixed sequence of turns,
// ignoring the running message context. It is the building block for a reproducible
// agent-workflow test: the tool-call pattern is authored, not sampled, so the run is a
// pure function of the script. Once exhausted it emits an empty final answer so the loop
// terminates deterministically rather than spinning to the turn cap.
type ScriptedPlanner struct {
	model string
	turns []Turn
	idx   int // next turn to emit
	seq   int // monotonic counter for deterministic tool_call ids
}

// NewScriptedPlanner builds a planner that emits the given turns in order.
func NewScriptedPlanner(turns ...Turn) *ScriptedPlanner {
	return &ScriptedPlanner{turns: turns}
}

// WithModel sets the reported model id (default "scripted").
func (p *ScriptedPlanner) WithModel(m string) *ScriptedPlanner { p.model = m; return p }

// Reset rewinds the planner to its first turn (and resets the id counter) so the SAME
// planner value reproduces an identical run — the determinism guarantee, in-place.
func (p *ScriptedPlanner) Reset() { p.idx, p.seq = 0, 0 }

// Model reports the planner's model id.
func (p *ScriptedPlanner) Model() string {
	if p.model == "" {
		return "scripted"
	}
	return p.model
}

// Complete emits the next scripted turn. It satisfies agent.Planner.
func (p *ScriptedPlanner) Complete(_ context.Context, _ []agent.Message, _ []agent.ToolDef, _ ...agent.SampleOpt) (*agent.Completion, error) {
	if p.idx >= len(p.turns) {
		return finalAnswer(""), nil
	}
	t := p.turns[p.idx]
	p.idx++
	if len(t.Calls) == 0 {
		return finalAnswer(t.Answer), nil
	}
	tcs := make([]agent.ToolCall, 0, len(t.Calls))
	for _, c := range t.Calls {
		p.seq++
		tcs = append(tcs, agent.ToolCall{
			ID:       fmt.Sprintf("call_%d", p.seq),
			Type:     "function",
			Function: agent.Func{Name: c.Tool, Arguments: c.Args},
		})
	}
	return &agent.Completion{
		Message:      agent.Message{Role: agent.RoleAssistant, ToolCalls: tcs},
		FinishReason: "tool_calls",
	}, nil
}

// ReplayPlanner is a deterministic agent.Planner that re-emits the assistant turns of a
// previously recorded transcript, in order — the reproduce-from-transcript primitive. A
// session driven by it reproduces the original run's exact tool-call pattern (the
// recorded tool_call ids and arguments are re-emitted verbatim), so a recorded production
// transcript becomes a regression fixture with no model in the loop. The tool RESULTS are
// regenerated by re-dispatching to the mock tools, which is what lets a replay test a
// changed tool implementation against an unchanged model trajectory.
type ReplayPlanner struct {
	model string
	turns []agent.Message // assistant messages from the transcript, in order
	idx   int
}

// NewReplayPlanner builds a replay planner from a full transcript by extracting its
// assistant messages (the model's turns) in order. Non-assistant messages are ignored —
// the harness regenerates the tool-result messages by re-dispatching to the mock tools.
func NewReplayPlanner(transcript []agent.Message) *ReplayPlanner {
	var turns []agent.Message
	for _, m := range transcript {
		if m.Role == agent.RoleAssistant {
			turns = append(turns, m)
		}
	}
	return &ReplayPlanner{turns: turns}
}

// WithModel sets the reported model id (default "replay").
func (p *ReplayPlanner) WithModel(m string) *ReplayPlanner { p.model = m; return p }

// Reset rewinds the planner to the first recorded turn.
func (p *ReplayPlanner) Reset() { p.idx = 0 }

// Model reports the planner's model id.
func (p *ReplayPlanner) Model() string {
	if p.model == "" {
		return "replay"
	}
	return p.model
}

// Complete re-emits the next recorded assistant turn. It satisfies agent.Planner.
func (p *ReplayPlanner) Complete(_ context.Context, _ []agent.Message, _ []agent.ToolDef, _ ...agent.SampleOpt) (*agent.Completion, error) {
	if p.idx >= len(p.turns) {
		return finalAnswer(""), nil
	}
	m := p.turns[p.idx]
	p.idx++
	m.Role = agent.RoleAssistant
	fr := "stop"
	if len(m.ToolCalls) > 0 {
		fr = "tool_calls"
	}
	return &agent.Completion{Message: m, FinishReason: fr}, nil
}

// finalAnswer wraps a final-answer assistant message as a completion.
func finalAnswer(s string) *agent.Completion {
	return &agent.Completion{
		Message:      agent.Message{Role: agent.RoleAssistant, Content: s},
		FinishReason: "stop",
	}
}

// LoadTranscriptJSONL parses a transcript recorded as JSON-lines (one agent.Message per
// line) — the shape examples/trajectory uses — into a message slice ready for
// NewReplayPlanner. Blank lines are skipped; a malformed line is a numbered error.
func LoadTranscriptJSONL(data []byte) ([]agent.Message, error) {
	var msgs []agent.Message
	for i, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		var m agent.Message
		if err := json.Unmarshal([]byte(line), &m); err != nil {
			return nil, fmt.Errorf("agenttest: transcript line %d: %w", i+1, err)
		}
		msgs = append(msgs, m)
	}
	return msgs, nil
}

// DumpTranscriptJSONL serializes a message transcript to JSON-lines, so a fresh run's
// transcript can be captured as a fixture and later replayed.
func DumpTranscriptJSONL(msgs []agent.Message) ([]byte, error) {
	var b strings.Builder
	for i, m := range msgs {
		raw, err := json.Marshal(m)
		if err != nil {
			return nil, fmt.Errorf("agenttest: marshal message %d: %w", i, err)
		}
		b.Write(raw)
		b.WriteByte('\n')
	}
	return []byte(b.String()), nil
}
