package mlpscore

// kernel.go is where this card rides the shared pkg/scorecard kernel instead of
// re-deriving the fold/grade/debt skeleton its siblings already share.
//
// The criterion rows stay this package's own domain model (they are what
// `fak milestone report` projects), but the fold that turns them into a control-pane
// payload -- the composite, the continuous value ratio, the A-F grade table, the
// unbounded pressure/slack layer, the debt integer, and the ok/verdict decision -- is
// scorecard.Fold's, so none of it can drift from the rest of the family. Grade() stamps
// its envelope FROM that payload rather than computing the same numbers a second way,
// and the payload is what --compare diffs against a prior --json run.

import (
	"fmt"
	"strings"

	"github.com/anthony-chaudhary/fak/pkg/scorecard"
)

// DebtKey is the headline HARD integer the control-pane folds (corpus.mlp_debt): the
// number of acceptance criteria still without a committed witness.
const DebtKey = "mlp_debt"

// VerdictLovable / VerdictNotYet are the closed mlp_verdict vocabulary.
const (
	VerdictLovable = "lovable"
	VerdictNotYet  = "not-yet"
)

// kpiGroup is the single KPI group: every criterion weighs the same in the composite.
const kpiGroup = "witness"

// fold turns the graded criterion rows into the shared control-pane payload.
//
// Exactly ONE defect is emitted per un-witnessed criterion -- never one per missing claim
// -- so the kernel's debt integer (Σ len(KPI.Defects)) stays the number mlp_debt has always
// meant: criteria still to witness. The individual missing claims ride inside that defect
// line (and in full on the criterion row) so nothing is lost.
func fold(rows []Criterion) scorecard.Payload {
	kpis := make([]scorecard.KPI, 0, len(rows))
	witnessed := 0
	for _, row := range rows {
		k := scorecard.KPI{
			Key:    row.Key,
			Group:  kpiGroup,
			Detail: fmt.Sprintf("[%s] %s -- witness %s", row.Workstream, row.Title, row.WitnessRef),
		}
		if row.Grade == GradeWitnessed {
			witnessed++
			k.Score = 100
		} else {
			why := strings.Join(row.Missing, "; ")
			if why == "" {
				why = "no committed witness"
			}
			k.Defects = []string{fmt.Sprintf("[%s] %s is not witnessed -- land %s: %s",
				row.Workstream, row.Title, row.WitnessRef, why)}
		}
		kpis = append(kpis, k)
	}

	total := len(rows)
	lovable := total > 0 && witnessed == total
	finding, verdict := "mlp_not_yet", VerdictNotYet
	reason := fmt.Sprintf("MLP first lovable cut: %d of %d criteria witnessed; %d remain", witnessed, total, total-witnessed)
	next := "land the next missing witness manifest and its linked test or captured run"
	if lovable {
		finding, verdict = "mlp_lovable", VerdictLovable
		reason = fmt.Sprintf("MLP first lovable cut: all %d criteria have committed witnesses", total)
		next = "keep every linked witness reproducible as the milestone evolves"
	}

	// Finding/NextAction are passed identically for both branches: this card's prose keys on
	// "all criteria witnessed", which is the same condition as the kernel's debt==0, so the
	// fold cannot pick a different sentence than the verdict above.
	return scorecard.Fold(Schema, kpis, DebtKey, nil, scorecard.Messages{
		Grade:           scorecard.GradeStd,
		Finding:         finding,
		FindingClean:    finding,
		NextAction:      next,
		NextActionClean: next,
		Reason:          reason,
		ExtraCorpus: map[string]any{
			"witnessed":   witnessed,
			"total":       total,
			"lovable":     lovable,
			"mlp_verdict": verdict,
		},
	})
}

// KernelPayload re-presents a graded Score as the shared control-pane payload: the same
// envelope every sibling card emits, and the shape --compare diffs. It reads the corpus and
// KPIs Grade already folded, so it can never disagree with the score it came from.
func KernelPayload(s Score) scorecard.Payload {
	return scorecard.Payload{
		Schema:     s.Schema,
		OK:         s.OK,
		Verdict:    s.Verdict,
		Finding:    s.Finding,
		Reason:     s.Reason,
		NextAction: s.NextAction,
		Workspace:  s.Workspace,
		Corpus:     s.Corpus,
		KPIs:       s.KPIs,
	}
}

// MarkdownDoc is the per-card prose for the kernel's committed-snapshot renderer, used by
// the shared --markdown surface when a caller wants the family-standard page body.
func MarkdownDoc(s Score) scorecard.MarkdownDoc {
	return scorecard.MarkdownDoc{
		Title: "fak MLP scorecard - the first lovable cut, witnessed",
		Description: "fak's deterministic MLP scorecard: the five acceptance criteria for the first lovable cut of " +
			"epic #3256, each graded only from a committed witness manifest that links a reproducible test or " +
			"captured run - folded into one mlp_debt integer.",
		Heading: "MLP first-lovable-cut scorecard",
		AutoGen: "Auto-generated by `fak mlp-score --markdown`. Do not hand-edit; re-run the tool.",
		Law: "The law: a criterion is witnessed only by evidence that is committed in HEAD - an untracked " +
			"working-tree file never counts, so the score cannot be moved by anything a reader could not re-run.",
		DebtKey:     DebtKey,
		HeaderExtra: fmt.Sprintf(" - %v/%v criteria witnessed", s.Witnessed, s.Total),
	}
}
