package devcmd

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/anthony-chaudhary/fak/internal/catchupscore"
	"github.com/anthony-chaudhary/fak/internal/devindex"
	"github.com/anthony-chaudhary/fak/internal/pathutil"
	"github.com/anthony-chaudhary/fak/pkg/scorecard"
)

// cmdCatchUpScore is `fak score catchup`: the single "how caught up is the dev
// system?" number + worst-first LEVEL worklist. It is the backlog/pace lens that
// complements `fak cadence` (which measures what HAPPENED over a window): this
// measures how far BEHIND the dev system is RIGHT NOW, at each level, and folds an
// unbounded catchup_backlog headline the ratchet reads.
//
// It auto-collects the ONE level with clean, deterministic, local evidence -- the
// dev self-index freshness (devindex.CheckFreshness over the tree, no network) --
// and takes the other levels from their existing sources: the portfolio
// self-measurement level from a captured scorecard control-pane payload
// (--scores-from), and intake / trunk / loops from --*-behind/--*-total flags (a
// level whose --*-behind is unset is EXCLUDED, never scored 0). Wiring each of
// those to its own live ledger is a thin follow-up; the fold already supports them.
//
// The control-pane --json this emits is exactly what `fak scoreboard post --from -
// --debt-key catchup_debt` ships to the scoreboard Slack workspace, so a caught-up
// read reaches the reporting sink in one pipe.
func RunCatchUpScore(stdout, stderr io.Writer, argv []string) int {
	fs := flag.NewFlagSet("fak score catchup", flag.ContinueOnError)
	fs.SetOutput(stderr)
	workspace := fs.String("workspace", "", "workspace root for the index level (default: repo root)")
	scoresFrom := fs.String("scores-from", "", "read a scorecard control-pane JSON payload (file, or '-' for stdin) for the measurement level")
	noIndex := fs.Bool("no-index", false, "skip the auto-collected dev self-index freshness level")
	intakeBehind := fs.Int("intake-behind", -1, "intake level: count of untriaged items (unset = level excluded)")
	intakeTotal := fs.Int("intake-total", -1, "intake level: total open items (default: --intake-behind)")
	trunkBehind := fs.Int("trunk-behind", -1, "trunk level: count of blocking build checks (unset = level excluded)")
	trunkTotal := fs.Int("trunk-total", -1, "trunk level: total build checks (default: --trunk-behind)")
	loopsBehind := fs.Int("loops-behind", -1, "loops level: count of overdue loops (unset = level excluded)")
	loopsTotal := fs.Int("loops-total", -1, "loops level: total loops (default: --loops-behind)")
	asJSON := fs.Bool("json", false, "emit control-pane JSON")
	asMarkdown := fs.Bool("markdown", false, "emit the committed snapshot body")
	comparePath := fs.String("compare", "", "compare against a prior --json payload")
	if !parseFlags(fs, argv) {
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "fak score catchup: unexpected argument %q\n", fs.Arg(0))
		return 2
	}

	root := *workspace
	if root == "" {
		root = repoRoot()
	}

	var f catchupscore.Facts
	if !*noIndex {
		f.Index = collectIndexLevel(root)
	}
	if *scoresFrom != "" {
		lvl, err := collectMeasurementLevel(*scoresFrom)
		if err != nil {
			fmt.Fprintf(stderr, "fak score catchup: --scores-from: %v\n", err)
			return 2
		}
		f.Measurement = lvl
	}
	f.Intake = flagLevel(*intakeBehind, *intakeTotal)
	f.Trunk = flagLevel(*trunkBehind, *trunkTotal)
	f.Loops = flagLevel(*loopsBehind, *loopsTotal)

	payload := catchupscore.Compose(f)

	return emitScorecard(stdout, stderr, "fak score catchup", catchupscore.DebtKey, payload,
		*comparePath, *asJSON, *asMarkdown, scorecard.MarkdownDoc{
			Title: "fak catch-up scorecard - how caught up is the dev system",
			Description: "fak's single 0..1 caught-up number across the dev-system levels -- issue-triage intake, " +
				"portfolio self-measurement, dev self-index freshness, trunk shippability, and gardening/RSI loop " +
				"cadence -- folded into one headline plus an UNBOUNDED catchup_backlog (total outstanding units) and " +
				"a worst-first level worklist a human reads at a glance and a gate ratchets on.",
			Heading: "Dev-system catch-up scorecard",
			AutoGen: "Auto-generated by `fak score catchup --markdown`. Do not hand-edit; re-run the tool.",
			Law: "The law: the levels fold into ONE 0..1 caught-up number with a worst-first worklist and an unbounded " +
				"backlog; a level below the pass line is debt, retired by discharging its REAL backlog (triage / measure " +
				"/ refresh the index / green the trunk / run the loops), never by weakening the floor.",
			DebtKey: catchupscore.DebtKey,
			HeaderExtra: fmt.Sprintf(" - %v/%v levels with evidence - catchup %v - backlog %v outstanding",
				payload.Corpus["levels_present"], payload.Corpus["levels_total"],
				payload.Corpus["catchup"], payload.Corpus[catchupscore.BacklogKey]),
		})
}

// collectIndexLevel folds the dev self-index freshness drift into the index level:
// behind == the count of drift findings (undeclared leaves, dead doc/llms links,
// uncataloged verbs, orphan notes), total == the declared index entities (leaves +
// docs) those drifts are drawn from. A workspace whose catalog cannot load (no
// dos.toml) yields nil -- the level is excluded, not scored 0.
func collectIndexLevel(root string) *catchupscore.Level {
	cat, err := devindex.Load(root)
	if err != nil {
		return nil
	}
	drifts := cat.CheckFreshness()
	behind := len(drifts)
	total := len(cat.Leaves) + len(cat.Docs)
	if total < behind {
		total = behind
	}
	lvl := &catchupscore.Level{Behind: behind, Total: total}
	if behind > 0 {
		lvl.Note = driftKindSummary(drifts)
	}
	return lvl
}

// driftKindSummary renders a short "kind xN, kind xM" tally of the freshness drifts
// for the worklist detail, in stable kind order.
func driftKindSummary(drifts []devindex.Drift) string {
	counts := map[devindex.DriftKind]int{}
	for _, d := range drifts {
		counts[d.Kind]++
	}
	kinds := make([]string, 0, len(counts))
	for k := range counts {
		kinds = append(kinds, string(k))
	}
	sort.Strings(kinds)
	parts := make([]string, 0, len(kinds))
	for _, k := range kinds {
		parts = append(parts, fmt.Sprintf("%s x%d", k, counts[devindex.DriftKind(k)]))
	}
	return strings.Join(parts, ", ")
}

// collectMeasurementLevel reads a scorecard control-pane JSON payload and folds its
// measured/errored/unmeasured counts into the measurement level: behind == cards that
// failed to score (errored + unmeasured), total == every card the pane tried. A
// payload with no cards at all (total 0) yields nil -- no evidence, level excluded.
func collectMeasurementLevel(from string) (*catchupscore.Level, error) {
	raw, err := pathutil.ReadFileOrStdin(from)
	if err != nil {
		return nil, err
	}
	var payload map[string]any
	if err := json.Unmarshal(raw, &payload); err != nil {
		return nil, fmt.Errorf("parse payload: %w", err)
	}
	measured := jsonInt(payload, "measured")
	behind := jsonInt(payload, "errored") + jsonInt(payload, "unmeasured")
	total := measured + behind
	if total == 0 {
		return nil, nil
	}
	return &catchupscore.Level{
		Behind: behind,
		Total:  total,
		Note:   fmt.Sprintf("%d errored/unmeasured of %d cards", behind, total),
	}, nil
}

// flagLevel builds a caller-supplied level from its --*-behind/--*-total flags. A
// behind below 0 means the flag was unset -> nil (level excluded). An unset total
// defaults to behind (a fully-behind level).
func flagLevel(behind, total int) *catchupscore.Level {
	if behind < 0 {
		return nil
	}
	if total < 0 {
		total = behind
	}
	return &catchupscore.Level{Behind: behind, Total: total}
}

func parseFlags(fs *flag.FlagSet, argv []string) bool {
	if err := fs.Parse(argv); err != nil {
		return false
	}
	return true
}

func repoRoot() string {
	wd, err := os.Getwd()
	if err != nil {
		return "."
	}
	for dir := wd; ; dir = filepath.Dir(dir) {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		if filepath.Dir(dir) == dir {
			return wd
		}
	}
}

func emitScorecard(stdout, stderr io.Writer, prefix, debtKey string, payload scorecard.Payload, comparePath string, asJSON, asMarkdown bool, doc scorecard.MarkdownDoc) int {
	if comparePath != "" {
		raw, err := os.ReadFile(comparePath)
		if err != nil {
			fmt.Fprintf(stderr, "%s: read --compare: %v\n", prefix, err)
			return 2
		}
		var base map[string]any
		if err := json.Unmarshal(raw, &base); err != nil {
			fmt.Fprintf(stderr, "%s: parse --compare: %v\n", prefix, err)
			return 2
		}
		fmt.Fprintln(stdout, scorecard.Compare(payload, base, debtKey))
		return boolExit(payload.OK)
	}
	if asJSON {
		if code := encodeJSONOrFail(stdout, stderr, payload, prefix); code != 0 {
			return code
		}
		return boolExit(payload.OK)
	}
	if asMarkdown {
		fmt.Fprint(stdout, scorecard.Markdown(payload, doc))
		return 0
	}
	fmt.Fprintln(stdout, scorecard.Render(payload, debtKey))
	return boolExit(payload.OK)
}

func boolExit(ok bool) int {
	if ok {
		return 0
	}
	return 1
}

func jsonInt(m map[string]any, key string) int {
	switch v := m[key].(type) {
	case float64:
		return int(v)
	case int:
		return v
	}
	return 0
}
