package taskidentity

import (
	"strings"
	"testing"
)

var (
	benchSinkText      string
	benchSinkDirective string
	benchSinkSignature string
)

func BenchmarkTextOf(b *testing.B) {
	strContent := "Implement task identity benchmark suite for performance tracking"
	blocksContent := []any{
		map[string]any{"type": "text", "text": "Analyzing the codebase layout and dependencies"},
		map[string]any{"type": "tool_result", "content": "Found 4 matching files in internal/taskidentity"},
		map[string]any{"type": "text", "text": "Proceeding with benchmark implementation"},
	}
	nestedContent := []any{
		map[string]any{"type": "text", "text": "Initial scan completed"},
		map[string]any{
			"type": "tool_result",
			"content": []any{
				map[string]any{"type": "text", "text": "file contents line 1\nline 2"},
				map[string]any{"type": "text", "text": "execution status: zero defects"},
			},
		},
	}

	b.Run("String", func(b *testing.B) {
		b.ReportAllocs()
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			benchSinkText = TextOf(strContent)
		}
	})

	b.Run("Blocks", func(b *testing.B) {
		b.ReportAllocs()
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			benchSinkText = TextOf(blocksContent)
		}
	})

	b.Run("Nested", func(b *testing.B) {
		b.ReportAllocs()
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			benchSinkText = TextOf(nestedContent)
		}
	})
}

func BenchmarkCanonicalDirective(b *testing.B) {
	goalHead := []map[string]any{
		{"type": "user", "message": map[string]any{"content": "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages as if the user typed them.</local-command-caveat>"}},
		{"type": "user", "message": map[string]any{"content": "<command-name>/effort</command-name> <command-message>effort</command-message> <command-args>ultracode</command-args>"}},
		{"type": "user", "message": map[string]any{"content": "<local-command-stdout>Set effort level to ultracode (this session only): xhigh + dynamic workflow orchestration</local-command-stdout>"}},
		{"type": "user", "message": map[string]any{"content": "<command-name>/goal</command-name> <command-args>advance maturity curve for taskidentity</command-args>"}},
	}
	boilerplateOnly := []map[string]any{
		{"type": "user", "message": map[string]any{"content": "<local-command-caveat>Caveat: Automated messages follow.</local-command-caveat>"}},
		{"type": "user", "message": map[string]any{"content": "<system-reminder>Session state restored from checkpoint.</system-reminder>"}},
		{"type": "user", "message": map[string]any{"content": "Resume where you left off on the task."}},
	}
	mixedHead := []map[string]any{
		{"type": "user", "message": map[string]any{"content": "<command-name>/dispatch</command-name> <command-args>worker-lane-4</command-args>"}},
		{"type": "user", "message": map[string]any{"content": "ship kernel benchmark suite and verify zero allocations"}},
	}

	b.Run("GoalWithBoilerplate", func(b *testing.B) {
		b.ReportAllocs()
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			benchSinkDirective = CanonicalDirective(goalHead)
		}
	})

	b.Run("BoilerplateOnly", func(b *testing.B) {
		b.ReportAllocs()
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			benchSinkDirective = CanonicalDirective(boilerplateOnly)
		}
	})

	b.Run("MixedArgsAndDirective", func(b *testing.B) {
		b.ReportAllocs()
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			benchSinkDirective = CanonicalDirective(mixedHead)
		}
	})
}

func BenchmarkSignature(b *testing.B) {
	shortDirective := "advance maturity curve for taskidentity"
	longDirective := strings.Repeat("verify task directive invariant with substantive benchmarks ", 20)

	b.Run("Short", func(b *testing.B) {
		b.ReportAllocs()
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			benchSinkSignature = Signature("fak", "/work/fak", shortDirective)
		}
	})

	b.Run("Truncated", func(b *testing.B) {
		b.ReportAllocs()
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			benchSinkSignature = Signature("fak", "/work/fak", longDirective)
		}
	})

	b.Run("Empty", func(b *testing.B) {
		b.ReportAllocs()
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			benchSinkSignature = Signature("fak", "/work/fak", "")
		}
	})
}

func BenchmarkIdentity(b *testing.B) {
	head := []map[string]any{
		{"type": "user", "message": map[string]any{"content": "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages as if the user typed them.</local-command-caveat>"}},
		{"type": "user", "message": map[string]any{"content": "<command-name>/effort</command-name> <command-message>effort</command-message> <command-args>ultracode</command-args>"}},
		{"type": "user", "message": map[string]any{"content": "<local-command-stdout>Set effort level to ultracode (this session only): xhigh + dynamic workflow orchestration</local-command-stdout>"}},
		{"type": "user", "message": map[string]any{"content": "<command-name>/goal</command-name> <command-args>advance maturity curve for taskidentity</command-args>"}},
	}

	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		benchSinkDirective, benchSinkSignature = Identity("fak", "/work/fak", head)
	}
}

func TestBenchmarkSanity(t *testing.T) {
	res := testing.Benchmark(BenchmarkIdentity)
	if res.N <= 0 {
		t.Fatalf("expected positive benchmark iterations, got %d", res.N)
	}
}
