package egresslist

// pinned_artifact.go — the machine-checkable definition of "this file is a GENERATED,
// checksum-pinned third-party artifact", so a leak gate can tell UPSTREAM DATA from a
// claim this repo makes (issue #5405).
//
// WHY THIS PREDICATE EXISTS AT ALL. The repo's PUBLIC_LEAK gate refuses any commit whose
// added lines contain an affiliation needle — an employer/brand token that must never
// leak into the public tree. That reading is exactly right for hand-written content and
// exactly wrong for the artifacts THIS package ships: a community ad/telemetry filter
// feed names vendor brands by construction, because naming a host is how you BLOCK it.
// Dropping the offending rules is not an option (the next `fak egresslist refresh` pulls
// them straight back, and determinism-across-refresh is the property the registry is
// built on), and rewriting them at export is worse still (the published fak would then
// block DIFFERENT hosts than the private one — silent divergence in a security artifact).
//
// WHAT MAKES AN EXEMPTION SAFE HERE, AND ONLY HERE. Not the path: a path allowlist would
// exempt anything anyone drops in the directory. The load-bearing condition is the PIN.
// An artifact qualifies only when its bytes hash to the sha256 lists/manifest.json
// records for its name — the same pin VerifyBundled and TestBundledListsMatchPinnedChecksum
// already enforce. A hand-smuggled line changes the hash, so a leak cannot ride in under
// the exemption without also re-pinning the manifest in the same reviewable diff.
// IsUpstreamRuleLine narrows it once more, to the single line SHAPE this package's own
// generator emits for feed data, so a brand name in the artifact's PROSE header — the one
// place a human could write a claim into a generated file — is still a leak.
//
// WHO CALLS IT. The scan definition lives in tools/scrub_public_copy.py (the canonical
// needle owner, which re-implements these three conditions for the Python gate and for
// the post-scrub EXPORT audit). This file is the Go-side twin, so the in-process gate can
// ask the package that OWNS the artifact rather than re-deriving its grammar: the shape
// of a bundled list is this leaf's business, not a leak scanner's. Keeping the predicate
// here is also what lets pinned_artifact_test.go red the trunk the day the generator
// starts emitting a line shape the exemption would not cover — a drift that would
// otherwise surface as a mysterious commit refusal months later.

import (
	"strings"
)

// ListsDir is the repo-relative directory holding the bundled artifacts and their
// manifest. It is the ONLY directory an artifact exemption may consider.
const ListsDir = "internal/egresslist/lists"

// ManifestFile is the provenance record's name, resolved BESIDE the artifact so the
// predicate works unchanged whether the tree is rooted at the repo or nested under a
// `fak/` prefix (the export layout does both).
const ManifestFile = "manifest.json"

// GeneratedHeader is the first line RenderArtifact writes: the do-not-hand-edit banner.
// TestGeneratedHeaderMatchesRenderArtifact keeps this in lockstep with the generator, so
// the constant can never drift into describing a banner nothing emits.
const GeneratedHeader = "! fak bundled egress filter list - GENERATED by `fak egresslist refresh`; do not hand-edit."

// ArtifactName returns the manifest list name for a repo-relative artifact path, and
// false for any path outside the declared class. Backslashes are normalized (a Windows
// caller passes native separators), a single leading `fak/` is tolerated (the nested
// export layout), and a name may not itself be path-shaped.
func ArtifactName(rel string) (string, bool) {
	p := strings.ReplaceAll(rel, "\\", "/")
	p = strings.TrimPrefix(p, "./")
	p = strings.TrimPrefix(p, "fak/")
	if !strings.HasPrefix(p, ListsDir+"/") || !strings.HasSuffix(p, ".txt") {
		return "", false
	}
	name := strings.TrimSuffix(strings.TrimPrefix(p, ListsDir+"/"), ".txt")
	if name == "" || strings.ContainsAny(name, "/\\.") {
		return "", false
	}
	return name, true
}

// IsPinnedArtifact reports whether `artifact` is the GENERATED rendering that `manifest`
// pins for the list named by `rel`. All three conditions must hold — declared path,
// generator banner, and a checksum that matches the manifest's pin — and every failure
// mode (unparseable manifest, missing entry, empty pin, mismatched bytes) returns false.
// Fail-closed is the only correct direction: a false negative costs one FLEET_ALLOW_LEAK
// override, a false positive silently publishes a leak.
func IsPinnedArtifact(rel string, artifact, manifest []byte) bool {
	name, ok := ArtifactName(rel)
	if !ok {
		return false
	}
	text := strings.TrimPrefix(string(artifact), "\xef\xbb\xbf") // UTF-8 BOM
	if !strings.HasPrefix(text, GeneratedHeader+"\n") && !strings.HasPrefix(text, GeneratedHeader+"\r\n") {
		return false
	}
	m, err := ParseManifest(manifest)
	if err != nil {
		return false
	}
	s, ok := m.Get(name)
	if !ok || strings.TrimSpace(s.SHA256) == "" {
		return false
	}
	return Checksum(text) == strings.ToLower(strings.TrimSpace(s.SHA256))
}

// IsUpstreamRuleLine reports whether one line of a bundled artifact is a rendered
// upstream rule — `||host^`, or `@@||host^` for an allow rule — which is the ONLY line
// shape RenderArtifact emits for feed data. Everything else in the artifact (the `!`
// provenance header, blank lines) is written by this repo, so a needle there is a claim
// this repo makes and must stay strict.
//
// The host is checked with the package's own isPlausibleHost — lower-case [a-z0-9.-] with
// at least one dot — so "a line the generator could have produced" is decided by the
// compiler's grammar rather than by a guess that could drift away from it. That predicate
// is also exactly what the Python twin's rule_re spells, which is what keeps the two
// enforcers from disagreeing about which lines an exemption covers.
func IsUpstreamRuleLine(line string) bool {
	s := strings.TrimPrefix(strings.TrimSpace(line), "@@")
	if !strings.HasPrefix(s, "||") || !strings.HasSuffix(s, "^") || len(s) < 3 {
		return false
	}
	return isPlausibleHost(s[2 : len(s)-1])
}
